### ISSUE TITLE
bundlesize not running on PR's

### ISSUE THREAD

**Issue by developit** [preactjs/preact#1013]
@siddharthkp - any idea why that might be happening?  Maybe we're on an old version?

**Comment by marvinhagemeister** [comment]
@developit Perhaps we are missing the github token?
 https://github.com/siddharthkp/bundlesize#2-build-status

**Comment by siddharthkp** [comment]
> Maybe we're on an old version?

Old but not too old

It seems to be running on `developit/preact` but not on forks, because the forks don't have the travis secrets 😢 

Not sure how other tools handle this, is there a tool I can take inspiration from?

**Comment by developit** [comment]
not sure! explanation makes sense though

**Comment by siddharthkp** [comment]
A quick and dirty workaround that I used was: Merge the pull request into a temporary branch first and then create another PR from that (all from GitHub website)

**Comment by ForsakenHarmony** [comment]
shouldn't it always take the secret from the repo being merged into?

**Comment by Kanaye** [comment]
Definitly not @ForsakenHarmony.
See the [Travis Docs on env vars](https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables)
> Encryption and decryption keys are tied to the repository. If you fork a project and add it to Travis CI, it will not have access to the encrypted variables.

If this weren't the case, you could leek the *private* keys stored within the env just by submitting a PR with malicious code executed from travis. 
For example I could modify the `npm run`-script to http post the secret keys to my own servers and do ... whatever those keys would allow me to do.

How are other projects handling this with bundlesize ?

**Comment by siddharthkp** [comment]
> How are other projects handling this with bundlesize ?

@Kanaye they are not

**Comment by ForsakenHarmony** [comment]
@siddharthkp I'm not sure I really see the problem, bundlesize should have the secret because it's being merged into this repo?

**Comment by siddharthkp** [comment]
@ForsakenHarmony nah, as @kanaye pointed out:

> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

(even if it is being merged back to the original)

> A quick and dirty workaround that I used was: Merge the pull request into a temporary branch first and then create another PR from that

**Comment by developit** [comment]
Update: we could just have our build job fail if the size is > 4kb. Ideally we'd run with a % delta from master, but that's hard to do in CI since its stateless.

**Comment by marvinhagemeister** [comment]
Closing, we switched to https://github.com/GoogleChromeLabs/travis-size-report
