### ISSUE TITLE
Make VNode generic type param optional

### ISSUE THREAD

**Issue by andrewiggins** [preactjs/preact#1081]
I suggest we make the VNode generic parameter optional by providing a default type for it.

Adding a generic parameter to the VNode interface breaks the types of many preact libraries that reference or extend VNode. Until many of these libraries update their types to provide a value for the VNode type parameter, I suggest we make it optional. Making it optional unblocks Preact TypeScript users to adopt 8.2.8+ without having to wait for all other libraries to catch up.

Below are some of the libraries that I've found that would need updating. I'll update this list with PRs to take advantage of the type parameter once they are opened. Post a comment here if you open one.

Libraries that need updating to provide a type param to `VNode`:
- [ ] [developit/preact-router](https://github.com/developit/preact-router)
- [ ] [developit/preact-render-to-string](https://github.com/developit/preact-render-to-string)
- [ ] [mzgoddard/preact-render-spy](https://github.com/mzgoddard/preact-render-spy)

**Comment by valotas** [comment]
@andrewiggins I believe it is a good suggestion

**Comment by developit** [comment]
LGTM - we can make the change here and then update the other libraries after, right?

**Comment by andrewiggins** [comment]
That's the plan
