### ISSUE TITLE
Enable the debug mode with React Developer tool will disable HRM

### ISSUE THREAD

**Issue by wen911119** [preactjs/preact#1261]
**Steps to reproduce**
1. preact create default bug-report-project 
2. cd bug-report-project && npm start
3. open localhost:8080 and enable React developer tools
4. modify the /routes/home/index.js

**What is expected?**
page changed without refresh

**What is actually happening?**
page refreshed

**Comment by marvinhagemeister** [comment]
Can't reproduce any HMR issues with the latest version of Preact, Preact Devtools and Prefresh. HMR works as expected :tada:
