### ISSUE TITLE
I created nano-preact-app: The quick boilerplate starter for preact apps

### ISSUE THREAD

**Issue by abhisheksoni27** [preactjs/preact#1303]
Just like we have a `create-react-app` for react, we now have `nano-preact-app` for preact.

There's not much bloatware. Just an index file that renders our App, an App component that showcases how we can create a Component and a couple of build scripts for developers.

I am also using Parcel to build the project.

PRs and issues welcome. Hope it helps everyone!

Here it is: [nano-preact-app](https://github.com/abhisheksoni27/nano-preact-app)

![template-tree](https://user-images.githubusercontent.com/4340071/53697896-0d8e6700-3dfc-11e9-9019-d0773ccfdfb0.png)

**Comment by developit** [comment]
Hi there - I think there's going to be a "getting started"  / setup area on the website soon, we can add this there once that happens.

**Comment by abhisheksoni27** [comment]
Thanks. I believe that would be great for incoming developers. Is anyone currently working on it?

**Comment by JoviDeCroock** [comment]
Feel free to PR this to https://github.com/preactjs/awesome-preact closing this issue
