### ISSUE TITLE
Strictly equal VNodes should short-circuit diffing

### ISSUE THREAD

**Issue by localvoid** [preactjs/preact#1322]
Libraries like react-redux are relying on this behavior for optimizations.

Preact X: https://codesandbox.io/s/4q307zk7o9
React: https://codesandbox.io/s/m3o2qy7398

**Comment by asilvas** [comment]
Surprised v10 is being rolled out without resolving this first as some apps will experience massive slowdowns by upgrading. More specifically the issue linked to this: https://github.com/preactjs/preact/pull/1538

**Comment by JoviDeCroock** [comment]
No apps should be faster by upgrading normally, are you experiencing something else @asilvas

**Comment by marvinhagemeister** [comment]
Yup we didn't have that optimization in 8.x either iirc.

**Comment by asilvas** [comment]
I see, wasn't aware this was a pre-existing issue. In my testing it resulted in significant slowness compared to React, and must have assumed it was related to v10.

**Comment by marvinhagemeister** [comment]
This was added earlier this year with #2386 :tada: Updating the codesandbox to the latest version of Preact resolves it :+1:
