### ISSUE TITLE
10.0.0-alpha.0: preact/debug doesn't automatically get removed in production

### ISSUE THREAD

**Issue by danieldiekmeier** [preactjs/preact#1355]
In Preact 8, the whole `preact/debug` was wrapped in a `process.env.NODE_ENV` conditional, so it got stripped out of production bundles by default: https://github.com/developit/preact/blob/8/debug/index.js#L3

But in Preact X, when using the `.mjs` bundle, it will always include the `import{checkPropTypes as n}from"prop-types";` line, which in turn will always import the `prop-types` package. This can be seen in the `preact/debug/dist/debug.mjs` file. For example here on unpkg: https://unpkg.com/preact@10.0.0-alpha.0/debug/dist/debug.mjs

So now I wrapped `preact/debug` in my app myself:

```
if (process.env.NODE_ENV === 'development') {
  require('preact/debug')
}
```

which is _okay_, I guess, but the previous behaviour was definitely nicer, and by upgrading to Preact X users could potentially start shipping the debug package to production.

**Comment by marvinhagemeister** [comment]
I'm curious why it doesn't work with the check we have in `master`:

**Comment by developit** [comment]
We may want to consider only shipping CommonJS and UMD versions of debug for this reason, and using inline requires:

```js
if (process.env.NODE_ENV==='development') {
  require('./debug').initDebug();
  require('./devtools').initDevTools();
}
```

**Comment by damianobarbati** [comment]
@developit I noticed I had to do the same to enable "prop-types" checking, is this the intended way?

**Comment by danieldiekmeier** [comment]
@damianobarbati If I understand correctly, then yes, this is intended: You have to import preact/debug if you want to use it. 

But you shouln‘t need an „if“ around it to have it stripped bundling for production (which is what my original issue is about.)

**Comment by JoviDeCroock** [comment]
This is documented [here](https://preactjs.com/guide/v10/debugging#strip-devtools-from-production) and is a side-effect of how ESM works, we can't really conditionally import in our bundle (async imports on your side however are an option but not in libraries).
