### ISSUE TITLE
Problem extending DOMAttributes type with new typescript typings.

### ISSUE THREAD

**Issue by mseddon** [preactjs/preact#1544]
I used to be able to attach new attribute types to preact by doing something like:

```typescript
declare namespace JSX {
	interface DOMAttributes {
		onSwipeStart?: (e: any) => void;
		onSwipeEnd?: (e: any) => void;
		onSwipeMove?: (e: any) => void;
	}
}
```

Since #1448, `JSX` has gone, but attempting:
```typescript
declare namespace preact.JSX {
	interface DOMAttributes {
		onSwipeStart?: (e: any) => void;
		onSwipeEnd?: (e: any) => void;
		onSwipeMove?: (e: any) => void;
	}
}
```

causes every jsx element to type error with:

`{ children: Element[] } has no properties in common with 'HTMLAttributes'`.

What is the correct way to add new events like this since the change? Thanks!

**Comment by maxpatiiuk** [comment]
This solved it for me:
https://github.com/preactjs/preact/issues/1180#issuecomment-643681851

**Comment by marvinhagemeister** [comment]
Closing as duplicate of https://github.com/preactjs/preact/issues/1180
