### ISSUE TITLE
Execution Stack on useState hook

### ISSUE THREAD

**Issue by fabiodcorreia** [preactjs/preact#1614]
I'm using the last version beta.1 and I'm seeing this behavior:

```
 
Render #1 - Start Render with message 'My Message' and state {"isVisible":true,"prevMessage":"My Message"}
Render #1 - End Render with message 'My Message' and state {"isVisible":true,"prevMessage":"My Message"}
Render #2 - Start Render with message '' and state {"isVisible":true,"prevMessage":"My Message"}
Render #2 - SetState with visible 'false' and prevMessage ''
Render #3 - Start Render with message '' and state {"isVisible":false,"prevMessage":""}
Render #3 - End Render with message '' and state {"isVisible":false,"prevMessage":""}
Render #2 - End Render with message '' and state {"isVisible":true,"prevMessage":"My Message"}
```
```
Start Render - Before checking the prevMessage agains props.message.
End Render - Just before the return for the render
```
So basically at the begin of the functional component I set the state to with isVisible to true because the prop message has a value and the prevMessage with the prop value.

As we can see from the render logs, Render # 1 is the first one and goes fine, then from the parent component I set the message to '' that fires Render # 2, since the props.message is different from state.prevMessage I update the state with isVisible to false and the prevMessage to '', that triggers Render # 3 and so far so good. The problem is as we can see after Render # 3 terminated the Render # 2 still executes the remaining instructions which is the return of the render but with wrong value as we can see on the log.

This is the expected behavior, my expectation is that last line of log never gets executed because it's deprecated.

**Comment by JoviDeCroock** [comment]
Reproduction: https://codesandbox.io/s/xpv213py2w?fontsize=14

**Comment by fabiodcorreia** [comment]
You are right I also upgrade the sandbox from the preview issue and that doesn't happen. The only thing different on my component is that instead of event on click the parent I just update the prop.message to ''. I'm using enzyme/preact to do the setProps on the component.

**Comment by JoviDeCroock** [comment]
Hmm, well problem is that I can't seem to reproduce it at this point in codesandbox (tried a bit). So you're only getting this in a testing env?

**Comment by fabiodcorreia** [comment]
Yes basically I have a test to start the component with a message and visible and then update the prop to ‘’ to make the component return null (no JSX returned) and it returns the JSX with empty message.

I also have a storyboard for it but storyboard far as I could find recreates the component when using dynamic props instead of just rerender it.
