### ISSUE TITLE
Using createPortal and Router causes route to be removed

### ISSUE THREAD

**Issue by pmkroeker** [preactjs/preact#1615]
Not too sure if this belongs more here or on `preact-router`. But I was investigating a strange behaviour in my app that I'm slowly moving from 8.4.2 to X.

I made a [codesandbox](https://codesandbox.io/embed/rwq55r7pj4) that illustrates the issue.

It seems as that when you call `createPortal` in a router path, it renders the contents of the portal, but removes everything else.

I would expect it to render into the defined element, either at the beginning or the end, but it seems to replace everything.

If this should be moved to `preact-router` I can move it there.

**Comment by JoviDeCroock** [comment]
This is because you are replacing your whole `div id="root"` with your portal. Most commonly you will refer to a div inside your component/route OR your body.

Try it out with `document.body` and you will notice the difference.

Feel free to comment again if you are experiencing more issues, if not I'll close this.

**Comment by pmkroeker** [comment]
Hmm, Ok I'll test it now. The strange part is that if not using router, it works as I expected. But using router it seems to replace the contents.

**Comment by JoviDeCroock** [comment]
Oh, never used it like that could be my understanding that's wrong then. Will fiddle around with it a bit

**Comment by pmkroeker** [comment]
Ok yes thanks @JoviDeCroock should just use `document.body`. I expected it to work like how `preact-portal` worked, where you could specify a selector and it would place the node there, but I guess the internal workings have changed a bit.

**Comment by pmkroeker** [comment]
I'll reopen this until there is as definite answer, `document.body` works but `document.querySelector(#root)`  does not when used with `preact-router`

**Comment by JoviDeCroock** [comment]
This is a bug, when using createPortal it overrides the full given node instead of inserting before already existing elements.

I have tested it with a minimal example and it is.

Most minimal example to test with:

```
const App = () => (
  <div>
    <p>hello</p>
    {createPortal(<div>Portalled</div>, document.getElementById("root"))}
  </div>
);

render(<App />, document.getElementById("root"));
```

This will effectively remove `<p>Hello</p>` from root
