### ISSUE TITLE
react-transition-group breaking with Preact X

### ISSUE THREAD

**Issue by piyushmahen** [preactjs/preact#1630]
Hi,
I am using react-transition-group, and have added alias in Webpack, as well as Babel.
Simple CssTransition works, but when using TransitionGroup, multiple DOM elements are created (i.e. old ones not removed after animation).
Also, I get this error in console: TypeError: Cannot read property 'cancelNextCallback' of undefined

FYI, its this line in the react transition library: https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js#L190

P.S. I tried running the same code with react (instead of preact X), and it worked like a charm, hence the assumption that it must be an issue in Preact X

Thanks in advance,
Piyush M

**Comment by JoviDeCroock** [comment]
Hey,

Thanks for the issue report, I do think this issue might be related to: https://github.com/developit/preact/pull/1627
So it might be fixed in the following beta release.

If you provide a reproduction we can follow this up and notify you wether it's fixed or not and if not follow it up further.

**Comment by robertknight** [comment]
The bug in #1627 would definitely cause this error. Once the next beta is released I'd suggest we close this issue as fixed unless there is a reproduction and it still fails for a different reason.

**Comment by robertknight** [comment]
I'm closing this issue as per the previous comment. If you can still reproduce with the latest beta then please provide steps / code to reproduce and I will re-open it.
