### ISSUE TITLE
Lifecycle methods not trigger correctly in safari.

### ISSUE THREAD

**Issue by oshell** [preactjs/preact#1643]
following scenario:
1) set state
2) change href
3) go back (browsers go back feature)

expected: component mounts again and state is back to initial
problem with preact in safari: state is same as when we left, and no life cycle methods such as componentDidMount trigger.

I can give 2 examples. 1) working fine with react. 2) showing the issue in safari with preact.

1) expected behaviour
https://gist.github.com/oshell/bb1b3eec49a98cf6d59cef44806f0fa6

2) preact behaviour 
https://gist.github.com/oshell/8c4fbb76657634d87cd4cdfa544aae63

**Comment by oshell** [comment]
I found out this problem is related to safari back-forward cache. A solution for the described problem would be to listen to pageshow event and than check if the page loaded is cached or not.

```
componentDidMount() {
  window.addEventListener('pageshow', (event) => {
    // fix for safari cached page
    if (event.persisted) {
      this.setState({
        isLoading: false
      });
    }
  });
}
```

**Comment by developit** [comment]
What would cause this to be different in Preact vs React? The only thing I could think of is that the preact example is below a size threshold that triggers bfcache. otherwise there's really nothing that could be done here. the page is restored to its previous state, and it's not observable to the library.

**Comment by marvinhagemeister** [comment]
Closing because there is nothing we can do about it in Preact. It's a browser bug and has to be fixed in webkit I'm afraid :S
