### ISSUE TITLE
10.0.0-beta.1 - Incorrect DOM ordering of elements

### ISSUE THREAD

**Issue by fjorgemota** [preactjs/preact#1652]
Hey.

This issue seems to be pretty similar to both #1635 and, I think, #1632, but either way it's an interesting testing scenario.

I found a difference in DOM ordering of elements between React and Preact X. I only tested with the latest beta of the Preact X available. 

This is the repository with the example: https://github.com/fjorgemota/preact-roses-example - it's the same example found on [Material Components Web for React](https://github.com/material-components/material-components-web-react), but with webpack configured to use `preact/compat` instead. To download and start the demo, you can clone the repository, run `npm install` and `npm start` and access https://127.0.0.1:8080/

Basically, on React, the elements are rendered like this:

![on React](https://user-images.githubusercontent.com/529864/58294677-d77cd580-7da1-11e9-8f6d-dc72eea5fc71.png)

Meanwhile, on Preact X the elements are rendered like this:

![On Preact X](https://user-images.githubusercontent.com/529864/58294727-1743bd00-7da2-11e9-8920-92e01a4e9aac.png)

In fact, if I change the state on any component Preact X observes the difference in rendering and adjust the DOM tree to have the correct DOM order:

![Preact X after any interaction with components](https://user-images.githubusercontent.com/529864/58332827-74775700-7e12-11e9-8bbd-a2d685785921.gif)

As you can see on the repository, the [main component of the example](https://github.com/fjorgemota/preact-roses-example/blob/master/Feedback.js) that calls MDC React is pretty simple...and at least for me the change in the ordering just doesn't make sense.

Anyway. I hope this bug report is useful for you guys. Thanks for this awesome project and keep the nice work on Preact X. ;)

Edit: Edited to have GIF with interaction on affected components.

**Comment by marvinhagemeister** [comment]
Awesome, thank you so much for the report it 👍 This looks to be related to an issue we're working on in #1700

**Comment by fjorgemota** [comment]
Hey!

First, thanks for the update and for the work on the project! :smile: 

I tested here and apparently this issue doesn't occur anymore with latest preact's master. :+1: 

I tried to test with a commit pushed before the commit that merges that PR and it also executed ok...So I think some update before that PR already fixed that problem. :thinking: 

So, now I have two questions:

- Should I try to bisect to find what specifically fixed this problem, just for the purpose of future documentation?
- Should I close the issue even before a new preact version with this fix is released?

**Comment by marvinhagemeister** [comment]
That's awesome! We'll very likely cut a new release this week :+1: :checkered_flag: 
There is no need to bisect master. @andrewiggins split the work in 2 separate PRs #1689 and #1700 in which he basically rethought how `Fragments` work internally and rewrote our implementation :raised_hands: 

We use the issue tracker as our current todo list, and because this is fixed in `master` it's safe to be closed :+1: :100:
