### ISSUE TITLE
Production build and Development server layout are differs

### ISSUE THREAD

**Issue by dalisoft** [preactjs/preact#1653]
Hello.

I migrated to Preact (`next` version because of Hooks) for my [first desktop app](https://github.com/dalisoft/websocket-client-app), but as title says, When using `preact dev`, everything looks great, but when trying `preact build`, layout is broken.

How i can fix this?

Thanks for great and small-sized library 😃

**Comment by JoviDeCroock** [comment]
Hey,

What exactly looks different? I'll have more time to dive into this tomorrow evening

**Comment by dalisoft** [comment]
Exactly layout is broken, some styles are not loaded. You can test yourself and compare just by serving `build` folder and `npm run dev` server. At first glance, you see what's differs

**Comment by JoviDeCroock** [comment]
Both production and dev look the same to me: https://gyazo.com/47d316154db49a41b85af1334394606b

**Comment by dalisoft** [comment]
Using `stable` instead of `next` fixed issue for me :)

Thanks for help
