### ISSUE TITLE
Object.prototype pollution / interfering with Backbone

### ISSUE THREAD

**Issue by cloakedninjas** [preactjs/preact#1655]
When aliasing preact & preact-compat into an existing React app (as part of a larger codebase) I've noticed it's polluting the global Object prototype

![Screenshot 2019-05-29 at 11 46 28](https://user-images.githubusercontent.com/1395013/58551239-7cb30600-8207-11e9-84d8-93be8840ea68.png)

And this is causing issues with some Backbone views we have in a separate part of the app

![Screenshot 2019-05-29 at 11 19 31](https://user-images.githubusercontent.com/1395013/58549840-5475d800-8204-11e9-8ef9-d9ef468ba322.png)

The `$$typeof` is causing things to choke - is this desired behaviour?

This is with `"preact": "^10.0.0-beta.1"` and `"preact-compat": "^3.18.5"`

**Comment by JoviDeCroock** [comment]
You should use `preact/compat` when using preact v10. Could you check if this issue still happens when not using `preact-compat` and replacing it with `preact/compat`?

**Comment by cloakedninjas** [comment]
I've changed my webpack config to be this

```
resolve: {
  alias: {
    react: 'preact/compat',
    'react-dom': 'preact/compat'
  }
}
```

but the error persists

**Comment by JoviDeCroock** [comment]
That would imply that one of your vnodes being passed to preact is effectively the global Object, I'll try and reproduce this without backbone

**Comment by cloakedninjas** [comment]
If you can tell me where these props are applied I can debug my code and trace through what might have caused this

**Comment by JoviDeCroock** [comment]
Every time a vnode gets passed to createElement these properties are applied.

**Comment by marvinhagemeister** [comment]
There is probably still an import to `preact-compat` somewhere in your code. Maybe there is a transient dependency somewhere?

**Comment by cloakedninjas** [comment]
That's exactly what it was. Just about to post. For me it was https://github.com/algolia/instantsearch.js
