### ISSUE TITLE
Reconciliation needlessly removes/readds nodes compared to React

### ISSUE THREAD

**Issue by ivaynberg** [preactjs/preact#1668]
It seems Preact unnecessary reparents nodes if leading siblings are removed. Given the following example ([fiddle](https://jsfiddle.net/ket5j2g8/2/)):
```
const { Component, h, render, createRef } = preact

class App extends Component {
   inputRef;
   
   constructor(props) {
  	super(props);
        this.setState({values:["item1","item2"]});
        this.inputRef=createRef();
        this.remove=this.remove.bind(this);
  }
  
  render(props, state) {
  	return <div>
 	    {state.values.map((v,i)=><div key={i}>{v}</div>)}
            <button onclick={this.remove}>remove items</button>
            <input type="text" ref={this.inputRef}/>
  	</div>
  }
  
  remove() {
     this.setState({values:[]});
     this.inputRef.current.focus();
  }
}

render(<App />, document.querySelector("#app"))
```

When remove  button is clicked the search field does not get focus as expected because it is yanked and readded into its parent. If we move the input field to be the first child of the root div it will get focus as expected.

This appears to work correctly in this React [fiddle](https://jsfiddle.net/Lvpshzqm/)

**Comment by ForsakenHarmony** [comment]
This is fixed in preact x it seems

(add https://unpkg.com/preact@10.0.0-beta.2/dist/preact.umd.js)
