### ISSUE TITLE
preact.memo or preact.PureComponent?

### ISSUE THREAD

**Issue by alshdavid** [preactjs/preact#1669]
I am using `preact@next` and can't seem to find the `memo` function or the `PureComponent` class.
are they included in Preact? If not, what's the best way to use a "memo" functional component?

**Comment by pmkroeker** [comment]
Both of those reside within `preact/compat`, not within the base.

**Comment by marvinhagemeister** [comment]
As @pmkroeker said: These functions are part of the `preact/compat` export.

```js
import { memo, PureComponent } from "Preact/compat"
```
