### ISSUE TITLE
VSCode/TypeScript: JSX element type 'Component<{}, {}>' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by IngwiePhoenix** [preactjs/preact#1671]
![image](https://user-images.githubusercontent.com/2893716/58785129-35e95580-85e5-11e9-9d0c-6de45dd17e03.png)

I am new to TypeScript and basically moved to it due to a much more stable support for decorators, some frameworks and since I am generally more into typed languages like C/C++. 

So when I began to put together a basic example with 10.0.0-beta.2, I got the error seen in the screenshot above.

Is that something I need to worry about - or rather, something that I can do anything about? Thanks!

**Comment by ForsakenHarmony** [comment]
I think that might be a conflict between react and preact types

**Comment by Silic0nS0ldier** [comment]
I've hit another type incompatibility issue myself.

```
src/app.tsx:6:2 - error TS2605: JSX element type 'PrimaryButton' is not a constructor function for JSX elements.
  Types of property 'componentDidCatch' are incompatible.
    Type '(error: Error, errorInfo: ErrorInfo) => void' is not assignable to type '(error: any) => void'.

6  <PrimaryButton>I am a button.</PrimaryButton>
```

Would it be at all possible to expand the preact type definitions to use the existing widely used definitions distributed via `@types/react`?

**Comment by pmkroeker** [comment]
Both if these problems should be resolved with #1703

**Comment by KashubaK** [comment]
Running into this problem on `10.0.0-rc.0`. I have a typescript project that requires me to render preact components inside a react project, and whenever I do this I get the same error as OP.

**Comment by JoviDeCroock** [comment]
Closing thanks to https://github.com/preactjs/preact/pull/1703 and a docs update about Preact/React typings. In case anyone runs into issues, re-open an issue with a reproduction please.
