### ISSUE TITLE
Preact SSR (render-to-string): Adding the DOCTYPE "element"

### ISSUE THREAD

**Issue by IngwiePhoenix** [preactjs/preact#1672]
Something that I found missing in general, was how Preact users are supposed to add `<!DOCTYPE html>` to server-side rendered pages.

In my case, I am pre-rendering a layout using Preact's `render-to-string` module. However, so far, the only way I could figure out how to do so would be to just prepend that string. But... this feels a little bit off, honestly.

Is there a more streamlined method? Thanks! :)

**Comment by ForsakenHarmony** [comment]
You generally have a string template and only render into the body

**Comment by marvinhagemeister** [comment]
Yup, the current solution is to create the doctype outside of any virtual-dom based frameworks and insert the rendered content into the body. There is nothing wrong with concatenating just the `doctype`. Any server renderer for that matter will concatenate strings under the hood, with the only difference that they escape attribute values and tag names to prevent any XSS Attacks :+1:

**Comment by sant123** [comment]
I can do this using `hono/jsx`. Would be awesome in someway be supported in Preact:

```tsx
export async function Layout({ title, children }: Props) {
  const template = (<>{children}</>).toString();
  const { css } = await uno.generate(template, { minify: true });

  return (
    <>
      {raw("<!DOCTYPE html>")}
      <html lang="en">
        <head>
          <meta charset="utf-8" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
          <title>{title}</title>
          <style id="unocss-reset">{raw(unoResetCSS)}</style>
          <style id="unocss-default">{css}</style>
        </head>
        <body>{children}</body>
      </html>
    </>
  );
}
```
