### ISSUE TITLE
Test utils `act()` disables normal deferred rendering

### ISSUE THREAD

**Issue by robertknight** [preactjs/preact#1681]
When the act function is called for the first time, it [installs a debounceRendering hook](https://github.com/preactjs/preact/blob/896e77d8c11a36ea642fe3999ac7087ac5110961/test-utils/src/index.js#L19) in order to be able to flush effects and state updates synchronously.

It does not restore the hook before it returns. As a result, any subsequent effects or `setState` calls which get executed outside the `act()` call will no longer trigger deferred rendering, which is a pretty confusing experience to debug.

Is there any reason not to restore any `options` hooks before `act` returns?

**Comment by JoviDeCroock** [comment]
Good point, I'll fix this when I get home :D thanks for noticing it I'll probably try and dive into the other issue as well.

**Comment by robertknight** [comment]
Thanks @JoviDeCroock. If there is any way I can help, please let me know!
