### ISSUE TITLE
npm README field is blank

### ISSUE THREAD

**Issue by FredKSchott** [preactjs/preact#1684]
### To reproduce:

1. `curl https://registry.npmjs.org/preact | pbcopy` ([link](https://registry.npmjs.org/preact))
2. Open you favorite JSON formatter (ex: https://codebeautify.org/jsonviewer)
3. See that the top-level "readme" property is empty string
4. See that there is no "readme" property on the latest version (or any versions <10)
5. See that a "readme" property does exist on the "next" version (and all versions 10+)

This is the only package I've seen this for in all of my npm traveling. I can't tell why this is (README does exist in the installed package) but just wanted to bring it to your attention since package README-viewers may be failing for your package.

**Comment by gilbert** [comment]
AFAIK it's because the readme file is not included in [the list of files to publish to npm](https://github.com/preactjs/preact/blob/master/package.json#L55-L70).

**Comment by JoviDeCroock** [comment]
It is included in the files to publish, can be seen here: https://unpkg.com/preact@10.0.0-beta.2/

**Comment by developit** [comment]
[README.md is always included](https://docs.npmjs.com/files/package.json#files) when npm creates tarballs:

<img width="455" alt="Screen Shot 2019-06-06 at 11 06 16 AM" src="https://user-images.githubusercontent.com/105127/59043928-24a18280-884b-11e9-9756-0ae047e09a21.png">

This seems like something more sinister - the registry includes a readme for both [8.4.2](https://registry.npmjs.org/preact/8.4.2) and [10.0.0-beta.2](https://registry.npmjs.org/preact/10.0.0-beta.2).

I recall there was a mixup with dist-tags when publishing recently. Maybe 8.4.2 or 10.0.0-beta.2 was re-tagged and that doesn't update the top-level readme field?

**Comment by Haroenv** [comment]
I've seen this bug happening on random packages as well  and can't find a pattern for it. I know that the npm website actually unpacks the tarball of the package backend to find the readme, which is why it's different to something you could make with the API. In Yarn's indexing process I added a GitHub fallback to find the readme's file name for this reason. I don't think preact can do anything about this

**Comment by marvinhagemeister** [comment]
Looks like this issue has been fixed. The `readme` field properly displays the content of our README.

**Comment by Haroenv** [comment]
The root readme yes, but interestingly the individual versions only have a readme for alpha versions

**Comment by marvinhagemeister** [comment]
Oh ok, just checked and our package contains the right version of the readme. Not sure why the registry points to something else. Like Jason said, it seems to be an issue with the registry when multiple tags are used. I don't think there is anything we can do to resolve that in Preact.

**Comment by Haroenv** [comment]
I contacted npm support with that insight, hopefully I can find the root cause now!

**Comment by jdnichollsc** [comment]
@marvinhagemeister what do you think about multiple tags are used? @Haroenv did you find a fix for that?
