### ISSUE TITLE
[10.0.0-beta.2] TS7026 error when using module alias between react and preact/compat on tsconfig.json

### ISSUE THREAD

**Issue by babie** [preactjs/preact#1693]
Hi, committers!

When I set this module alias between `react` and `preact/compat` on `tsconfig.json`,
```json
    ...
    "baseUrl": "./",
    "paths": {
      "react": ["node_modules/preact/compat"],
      "react-dom": ["node_modules/preact/compat"]
    },
    ...
```

I see `tsc` has TS7026 errors ("JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.").
```
$ yarn tsc
yarn run v1.16.0
$ /Users/babie/src/github.com/babie/preact-cli-template/template/node_modules/.bin/tsc
src/App.tsx:5:5 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

5     <h1 className="title">Hello, Preact!</h1>
      ~~~~~~~~~~~~~~~~~~~~~~
...
```

And when I write this patch,
```patch
diff --git a/node_modules/preact/compat/src/index.d.ts b/node_modules/preact/compat/src/index.d.ts
index bdc044f..6314d96 100644
--- a/node_modules/preact/compat/src/index.d.ts
+++ b/node_modules/preact/compat/src/index.d.ts
@@ -11,6 +11,7 @@ export import createRef = preact.createRef;
 export import Fragment = preact.Fragment;
 export import createElement = preact.createElement
 export import cloneElement = preact.cloneElement
+export import JSX = preact.JSX
 
 export declare const version: string;
 
```

Then `tsc` has no error.
```
$ yarn tsc
yarn run v1.16.0
$ /Users/babie/src/github.com/babie/preact-cli-template/template/node_modules/.bin/tsc
✨  Done in 1.72s.
```

Probably, TypeScript needs a global(top level) `JSX` type. 

Here is a sample repository:
- found problem: https://github.com/babie/preact-cli-template/tree/b87af42e002e00e3e77febd9531319eabd628660
- fix problem: https://github.com/babie/preact-cli-template/tree/a57e2ea1276cac7c18bcefecf26e326064b428e6
- diff: https://github.com/babie/preact-cli-template/commit/a57e2ea1276cac7c18bcefecf26e326064b428e6

**Comment by pmkroeker** [comment]
Does it give you the same message if you use `import * as React from 'preact/compat'`?

**Comment by babie** [comment]
Sorry, I forgot to write it.
It needs both of them(`export import JSX = preact.JSX` and `import * as React from 'react'`).
I'm done checking the difference.

**Comment by babie** [comment]
1. `export import JSX = preact.JSX`
2. `import * as React from 'react'`
3. `import * as React from 'preact/compat'`

When there is 1, both of them(2 and 3) have no error.
When there is not 1, both of thme(2 and 3) have errors.

**Comment by pmkroeker** [comment]
Made a [codesandbox repro](https://codesandbox.io/s/1693-repro-n4suc) of this issue. My only concern with exporting the types is they may clash with the react types.

**Comment by babie** [comment]
I made your codesandbox closer to my example, then there are same TS7026 errors.
https://codesandbox.io/embed/1693-repro-nguc9
(Please click the `Open in Editor` button, then type errors appears on the code inline)

diffs:
- Remove `"jsxFactory": "h"` on tsconfig.json because of `"jsx": "react"`.
```diff
      ...
-     "jsx": "react",
-     "jsxFactory": "h"
+     "jsx": "react"
      ...
```

- Change imports on index.tsx.
```diff
  import "./style";
- import { render, Component, h } from "preact";
+ import * as React from "react";
+ import { render } from "react-dom";

- export class App extends Component {
+ export class App extends React.Component {
    render() {
      return <div>This is a test, Second Part</div>;
    }
  }

  if (typeof window !== "undefined") {
    render(<App />, document.getElementById("root") as Element);
  }
```

**Comment by babie** [comment]
I removed `baseUrl` and `paths` on tsconfig.json from your repro, but it has type errors and does not run.
I think my way is not the cause and it needs `eslint-plugin-react` setting.
And `@typescript-eslint` does not support TypeScript v3.5.1 yet.

**Comment by pmkroeker** [comment]
Sorry I was messing around with it after I posted the link. I'll fix it when I get the chance.

**Comment by babie** [comment]
Alright. I hope to hear from you.

**Comment by pmkroeker** [comment]
So after some investigation, adding `export import JSX = preact.JSX` does solve the issue when using the import like `import * as React from 'preact/compat'`, but unfortunately does not if using `import React from 'preact/compat`. Currently working on a solution to hopefully allow both methods to work equally.
