### ISSUE TITLE
[10.0.0-beta.2] controlled text input does not perform like React

### ISSUE THREAD

**Issue by MichaelRando** [preactjs/preact#1694]
I mentioned in the Slack I saw possible issues on <input> with PreactX vs react & preact8. Maybe it's a performance regression; since adding shouldComponentUpdate to input wrapper resolves the bug. For the benefit of those who asked, I've put a smallish repro test case in a github repository, namely: https://github.com/MichaelRando/preact-text-problem

**Comment by marvinhagemeister** [comment]
Currently looking into it and it seems like the `SignUpForm` is constantly remounted. Need to dig deeper as to why that's the case.

**Comment by marvinhagemeister** [comment]
Was able to narrow the described issue down to something fishy going on with the `createPortal` in `Modal.js`. When I remove that, the text input won't be re-created on every render. One step closer :tada:

**Comment by marvinhagemeister** [comment]
Note: That I had to patch the import statements. There is a mix of `react-redux/src` vs `react-redux` and `redux` vs `redux/es/redux` going on. @JoviDeCroock spotted that earlier today and this needs to be corrected regardless :slightly_smiling_face:

**Comment by MichaelRando** [comment]
pull requests welcome.? 
Haha, my apologies, I'll sort it out in a future rev (unless I get to discard all this after preactx ships)
In my defense, the real project uses preact-redux, and my IDE set those paths on autocomplete because preact-redux is known incompatible with preactx.

**Comment by marvinhagemeister** [comment]
Just checked against the code in `master` and this issue is resolved :tada: It was fixed by #1691 which will be included in the next release :+1: :100:
