### ISSUE TITLE
How can I extend HTMLAttributes in 10.0.0.beta ?

### ISSUE THREAD

**Issue by jerry153fish** [preactjs/preact#1714]
In `8.4.6` I can simply extend HTML attributes in a Triple-Slash project

```
declare namespace JSX
{
    // Our extensions
    export interface HTMLAttributes
    {
        test?: boolean
    }
}
```

JSX become internal namescript which is exported. According the typescript doc, you can not merge and exported module. So is it still possible to add self-defined attributes ?

**Comment by pmkroeker** [comment]
You likely came across [this SO](https://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules) answer in your travels.

I did find a workaround(?)! You can extend using:
```typescript
// global.d.ts
declare namespace preact.JSX {
  interface HTMLAttributes {
    test?: boolean;
  }
}
```
Don't use triple slash in any of my projects, but this works if you add `global.d.ts` to your includes in `tsconfig.json`.
![Extending HTML Attributes](https://user-images.githubusercontent.com/10147685/59520686-56d06700-8e7f-11e9-826b-24b911b16daa.png)

**Comment by jerry153fish** [comment]
Thanks I am using react types now.
