### ISSUE TITLE
componentWillUnmount not called

### ISSUE THREAD

**Issue by ivaynberg** [preactjs/preact#1722]
Given the following

```
class MyComponent extends Component {
  componentDidMount() {
    console.log("Component mounted.");
  }
  componentWillUnmount() {
    console.log("Component unmounted");
  }
  render() {
    return <div>My Component</div>;
  }
}

var container=document.createElement("div");
document.body.appendChild(container);
render(<MyComponent />, document.body, container);
render(<div>Not my component</div>, document.body, container);
```

I expect componentWillUnmount() to be called, and it has been in X alphas and beta0, but in beta1 and beta2 it no longer is.

Sandbox: https://codesandbox.io/s/1288-5mfm5

**Comment by pmkroeker** [comment]
Which browser are you using? I just opened your Sandbox and I'm getting `Component unmounted` in the console. On Chrome.

**Comment by JoviDeCroock** [comment]
Same here, it logs the unmount for me.

**Comment by ivaynberg** [comment]
using Chrome

**Comment by JoviDeCroock** [comment]
Your reproduction was not inline with your issue statement, I corrected it. Is there a reason as to why you are using replaceNode? I'll look into the issue though, as far as I can see you can avoid using replaceNode

**Comment by ivaynberg** [comment]
i am using preact to enhance existing select components, so i need to render a preact component after a specific dom node. i do this by inserting the placeholder div into the right place in the dom and rendering a preact component into it.

since an existing select component does not have to be a last child of a container i cannot use the two arg variant of render()

**Comment by JoviDeCroock** [comment]
All right, looking into it as we speak, I have an inclination as to what is causing this
