### ISSUE TITLE
[Question] Main Preact advantages

### ISSUE THREAD

**Issue by rafaellages-hotmart** [preactjs/preact#1726]
Hi guys, I've been using Preact(and loving) for some time in my project with the argument that it is a 3kb alternative to React. But a coworker showed me that recent versions of React are way smaller than before (the latest is just 2.6kb https://bundlephobia.com/result?p=react@16.8.6)
So what are the main advantages Preact has now over React?

Thanks

**Comment by marvinhagemeister** [comment]
The thing with react is that it cannot be used without an adapter like `react-dom` or `react-native`. That's where the size increase comes from:

| package | minified | gzip |
|---|--:|--:|
| react + react-dom | 6.5kB + 103kB = 109.5kB | 1.7kB + 32.9kB = 34.6kB |
| preact | **8.7kB** | **3.5kB** |

So yeah that's quite the difference and our strongest argument about the size remains. No worries, you and your coworker are not the first to make that mistake 😉
