### ISSUE TITLE
Not replacing the elements inside render container at first rendering

### ISSUE THREAD

**Issue by kaioduarte** [preactjs/preact#1727]
[React documentation](https://reactjs.org/docs/react-dom.html#render) says that:

> ReactDOM.render() controls the contents of the container node you pass in. Any existing DOM elements inside are replaced when first called.

But in preact the content is not replaced, here is a running example:

https://codesandbox.io/s/replace-content-of-container-fcrf4

**Comment by MichaelRando** [comment]
same conversation as #1718; preact is not constrained to the ReactDOM.render() api definition and can operate differently. Is that good? in my opinion "no", but but clearly there's a history why it's never been the same

**Comment by kaioduarte** [comment]
Oops, my bad, thanks for link the conversation :wink:

I'll close to keep just one issue for that =)

**Comment by marvinhagemeister** [comment]
Awesome, thanks for posting 👍 We could destroy the DOM just in compat, that sounds easy enough 💯
