### ISSUE TITLE
The url of preact-render-to-string in release note is wrong

### ISSUE THREAD

**Issue by 38elements** [preactjs/preact#1730]
The url of `preact-render-to-string ` in release note is wrong.

https://github.com/preactjs/preact/releases/tag/10.0.0-beta.3

Currently, The link is `https://github.com/preactjs/preact/blob/10.0.0-beta.3/preact-render-to-string` in `Important` section, not `https://github.com/preactjs/preact-render-to-string`.

**Comment by marvinhagemeister** [comment]
Oh shoot, I messed up the markdown syntax for links by putting the label and the url in the wrong order. Thank's a bunch for reporting it, just updated the notes :+1: :100:
