### ISSUE TITLE
Preact + TypeScript won't allow me to directly call the h function instead of using JSX

### ISSUE THREAD

**Issue by rockmandash** [preactjs/preact#1732]
I'm using create-react-app for project setup.

I found that I can't directly use `h` function in TypeScript.

Please see this minimum example code:

```tsx
import { FunctionalComponent, h } from 'preact';

const Text: FunctionalComponent = () => {
    const tag = 'div'
    const props = {}
    const children = 'I am children'

    return (
        h(tag, props, children)
    )
}
```
![](https://i.stack.imgur.com/eYrsL.png)

It says: `Cannot invoke an expression whose type lacks a call signature. Type 'typeof h' has no compatible call signatures.`

If I directly use JSX, it will be fine:

![](https://i.stack.imgur.com/2TkVu.png)

How can I directly use the `h` function in TypeScript?

[related issue](https://stackoverflow.com/questions/56731453/preact-typescript-wont-allow-me-to-directly-call-the-h-function-instead-of-us)

**Comment by JoviDeCroock** [comment]
What version of preact are you using?

**Comment by rockmandash** [comment]
@JoviDeCroock I'm using `^10.0.0-beta.2` version (latest beta version)

**Comment by JoviDeCroock** [comment]
@rockmandash `10.0.0-beta.3` should be the latest and the issue should be fixed there, could try upgrading and tell me if that solves your pbolem?

**Comment by rockmandash** [comment]
I worked!
