### ISSUE TITLE
lazy/Suspense behavior different with react

### ISSUE THREAD

**Issue by whitetrefoil** [preactjs/preact#1738]
```tsx
// index.tsx
import { h, render }      from 'preact';
import { lazy, Suspense } from 'preact/compat';

const Outer = lazy(() => import('./Outer'));

render(
  <Suspense fallback={<div>loading outer...</div>}>
    <App/>
  </Suspense>,
  document.getElementById('app')!,
);
```

```tsx
// Outer.tsx
import { FunctionComponent, h } from 'preact';
import { lazy, Suspense }       from 'preact/compat';

export const Outer: FunctionComponent = () => {

  const Inner = lazy(() => import('./Inner'));

  return (
    <div>
      <div>Outer</div>
      {/*<Suspense fallback={<div>loading inner...</div>}>*/}
        <Inner/>
      {/*</Suspense>*/}
    </div>
  );
};

export default Outer;
```

```tsx
// Inner.tsx
import { FunctionComponent, h } from 'preact';

export const Inner: FunctionComponent = () => <div>Inner</div>;

export default Inner;
```

With react, I don't need that `<Suspense>` in `Outer.tsx` to make the code work. But with `preact/compat`, if I comment the `<Suspense>` in `Outer.tsx` like above, the top-level (in `index.tsx`) `<Suspense>` won't disappear after the `Inner.tsx` loaded, and sometimes the page will crash.

I'm not sure if this difference is by design or not since I can't found related info in changelog.

**Comment by JoviDeCroock** [comment]
So if Suspense is the first child of render it doesn't work correctly, am I making an invalid assumption here or?

**Comment by marvinhagemeister** [comment]
It could also be related to `Suspense` not setting the `_children` pointer correctly. It's something I came across in #1549 . See this commit: https://github.com/preactjs/preact/pull/1549/commits/b0fe5e748543b0be163c641769f632fc65f06df6

**Comment by andrewiggins** [comment]
I made this codesandbox to try and replicate the issue: https://codesandbox.io/s/1738-dzq9w

However I had to make two changes to get it to work:
1. Define an App component: `const App = () => <Outer />;`
2. Move the definition of `Inner = lazy(...)` outside of `Outer`'s render method, else we ended up in an infinite loop.

@whitetrefoil Does moving the definition of `Inner = lazy(..)` outside of the Outer's render method fix the problem for you? Or is that unrelated? If you are still seeing the issue, would it be possible to modify the codesandbox to repro the issue?

FWIW it does seem React's supports using lazy, inside of a render method: https://codesandbox.io/s/1738-react-koirg

**Comment by marvinhagemeister** [comment]
I don't know about supporting creating `lazy` inside `render`. My gut feeling says that this should be treated as an error.

**Comment by whitetrefoil** [comment]
@andrewiggins It seems I made some mistake during cleaning unrelated code.  I checked my local code, `lazy()` are located outside of render functions.

Let me paste some my original code:

```tsx
// src/index.tsx (Entry, root of everything)
import { h, render }      from 'preact';
import { lazy, Suspense } from 'preact/compat';
import { PageLoading }    from './components/shared/PageLoading';
import { getLogger }      from './services/log';


const { debug } = getLogger(`/src/${__filename.split('?')[0]}`);


async function bootstrap() {
  import('./styles/global.scss');

  const App = lazy(() => import(/*webpackChunkName:"|c|App"*/'./components/App'));

  render(
    <Suspense fallback={<PageLoading/>}>
      <App/>
    </Suspense>,
    document.getElementById('app')!,
  );
}


bootstrap()
  .then(() => {
    debug('Bootstrapped!');

    const loadingErrorDiv = document.getElementById('loading-error');
    if (loadingErrorDiv != null) {
      loadingErrorDiv.remove();
    }
  }, e => {
    console.error(e);
  });
```

```tsx
// src/components/App.tsx
import { FunctionComponent, h } from 'preact';
import { lazy }                 from 'preact/compat';
import { BrowserRouter, Route } from 'react-router-dom';
import './App.scss';


const Hello = lazy(() => import(/*webpackChunkName:"|c|Hello"*/'./Hello'));


export const App: FunctionComponent = () =>
  <div id="app" className="container">
    <h1 className="h1">[Component] MyApp</h1>

    <BrowserRouter>
      <Route path="/" component={Hello}/>
    </BrowserRouter>
  </div>
;

export default App;
```

```tsx
// src/components/Hello/index.tsx
import { FunctionComponent, h } from 'preact';
import { lazy }                 from 'preact/compat';
import { Route }                from 'react-router-dom';
import * as css                 from './index.scss';


const Shared = lazy(() => import(/*webpackChunkName:"|c|s|Shared"*/'../shared/Shared'));
const Nested = lazy(() => import(/*webpackChunkName:"|c|Nested"*/'./Nested'));


interface Props {}


const Hello: FunctionComponent<Props> = () => {

  // init();
  return (
    <div className={`hello ${css.hello}`}>
      <h1 className="h1">[component] HelloPage</h1>

      <h3 className="h3">Hello!!!</h3>

      {/*<p>{this.props.greeting}</p>*/}

      <p>
        <button
          type="button"
          className="btn btn-danger"
          // onClick={this.props.change}
        >Another receptionist!
        </button>
      </p>

      <section>
        <Route
          render={p => (
            <Shared name={p.location.pathname}/>
          )}
        />
      </section>

      <section>
        <Nested name="hello"/>
      </section>

      <section>
        <h3 className="h3">url-loader test</h3>
        <div className={`image ${css.image}`}/>
      </section>
    </div>
  );
};

export default Hello;
```

Both `src/components/shared/Shared.tsx` and `src/components/Hello/Nested` are very simple almost static function.

It's a WIP test project to research about using preact with react stuff, so please ignore those wired naming and structure, and some other errors like typing compatibility with react-router.

In this project, `Entry` lazy loads `App`, while `App` lazy loads `Hello`, and `Hello` lazy loads `Nested`&`Shared`.

Currently only `Entry` has a `<Suspense>`, the result when using React is everything work, while with Preact is that `PageLoading` keep showing after inner modules loaded.

If I added `<Suspense>` in `App.tsx`, it works, even there's still no `<Suspense>` in `Hello.tsx`.

**Comment by sventschui** [comment]
@whitetrefoil would it be possible to share a minimal runnable reproduction case? Maybe a codesandbox? You mentioned it's a codebase to do some experiments, can you share the git repo?

**Comment by whitetrefoil** [comment]
@sventschui https://github.com/whitetrefoil/Preact_MobX_TS_Arch I've uploaded that expr. code, but it's not very "minimal".  Let me know if it has to be cleaner (or anything else I can do).

**Comment by sventschui** [comment]
Had a first look at your project. What happens is that some Parts of the App get rendered twice. Something seems to be broken with the vdom parking. I'll try to dig deeper later

**Comment by sventschui** [comment]
Might be related to #1859, did not verify yet though

**Comment by intrnl** [comment]
It seems that the behavior has gotten worse after I upgraded from rc1 to rc3, the fallback component is successfully unmounted but nothing shows up, not even the components that aren't lazily loaded.

**Comment by adrian2x** [comment]
Currently broken @10.0.3 this looks like it was working for me at some point but I upgraded and now all my lazy routes are broken.

I will have to downgrade now which means rolling back my hooks :roll_eyes: : 

suspense.js:60 Uncaught (in promise) TypeError: Cannot read property 'push' of null
    at k.u (suspense.js:60)
    at Object._preact.options.__e (suspense.js:19)
    at $ (index.js:158)
    at children.js:85
    at x (children.js:194)
    at x (children.js:190)
    at b (children.js:52)
    at $ (index.js:131)
    at children.js:85
    at x (children.js:194)

**Comment by marvinhagemeister** [comment]
@adrian2x FYI: There is no `10.0.3` version yet. We're at `10.0.1` currently.

**Comment by andrewiggins** [comment]
Hey @whitetrefoil - I just tried running your Preact_Mobx_TS_Arch repo with the fix from #2025 and it appeared to work for me. I didn't modify any of the source and the Loading icon disappeared after the App loaded and I didn't see any console errors. Hope it fixes this for you!

**Comment by whitetrefoil** [comment]
What a good news!🥳
So I believe this can be closed once your PR get merged?

**Comment by andrewiggins** [comment]
Yup!
