### ISSUE TITLE
Typescript: types incompatible with react-router

### ISSUE THREAD

**Issue by whitetrefoil** [preactjs/preact#1739]
Direct dependencies:
* typescript@3.5.2
* preact@10.0.0-beta.3
* react-router@5.0.1
* react-router-dom@5.0.1
* @types/react-router-dom@4.3.4
* @types/react-router@5.0.2

Indirect dependencies:
* @types/react@16.8.22

```ts
import { FunctionComponent, h } from 'preact';
import { BrowserRouter, Route } from 'react-router-dom';

const Hello: FunctionComponent = //...

const App: FunctionComponent = () =>
  <div>
    <BrowserRouter>
      <Route path="/" component={Hello}/> // Here shows error
    </BrowserRouter>
  </div>
```

```
Error:(xx, xx) TS2322: Type 'FunctionComponent<Props>' is not assignable to type 'ComponentClass<RouteComponentProps<any, StaticContext, any>, any> | FunctionComponent<RouteComponentProps<any, StaticContext, any>> | ComponentClass<any, any> | FunctionComponent<...> | undefined'.
  Type 'FunctionComponent<Props>' is not assignable to type 'FunctionComponent<RouteComponentProps<any, StaticContext, any>>'.
    Type 'VNode<any> | null' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null'.
      Type 'VNode<any>' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.
        Types of property 'type' are incompatible.
          Type 'string | ComponentClass<any, {}> | FunctionComponent<any> | null' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
            Type 'null' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.

**Comment by pmkroeker** [comment]
Where are you aliasing react to `preact/compat`? The preact types are not directly compatible with react, but if you're aliasing react to compat in webpack then you should
`import { createElement as h, FunctionComponent } from 'react';` and the typings should work fine. Mixing both preact and react types in the same file will cause issues, and there is no nice way around it.

**Comment by whitetrefoil** [comment]
Umm... In preact-router's README file, it says "React Router 4 even works directly with Preact, no compatibility layer needed!".

**Comment by pmkroeker** [comment]
The docs are for preact 8. And it doesn't mention types. Mixing types in one file will lead to inconsistencies.

**Comment by whitetrefoil** [comment]
OK... So in order to use TypeScript, the additional size & configuration of compat package is required...
Maybe some `as any` will be a better solution if the JS actually works. 😂

**Comment by pmkroeker** [comment]
I think I slightly misunderstood. You shouldn't need compat if it works directly with (as the docs say it does, IDK if they have been updated for preact X, but we'll assume they do).

The real issue here is that you are trying to mix the types of `React` and `Preact`, and the typings **are not** compatible when mixed into the same file. You can intermix React and Preact in the same TS project as long as they are split in different files (though this is a bit awkward).

Is there a reason you are using `react-router` over `preact-router`?

**Comment by whitetrefoil** [comment]
Actually no, personally I usually use preact+preact-router+unistore(rare case).

I'm currently working on some tech. research & scaffolding for my team.  Till now my team uses preact (no router, no state mgr.) for very small traditional non-single-page application (for size), and Vue family for larger projects.

Recently we are researching React family, and since I'm a little bit concern about the huge size of `react-dom`, I want to make a try about using preact-x instead of react and see what's the difference between the two scaffold.  This issue came from that testing project.

Your suggestion to use a stealth replacement during building process is just right for my project since we use some others from React family (e.g. MobX).  But now I'm just personally interested in the fact that when using preact + react-router I have to include an additional compat package just for typing, that feels odd 😂

**Comment by hinst** [comment]
I ran into this 5-year old problem as soon as I started working on a project using Preact. The error happens out of the box after creating an app using `create-preact` command without any changes to the dependencies of the project

**Comment by rschristian** [comment]
@hinst That has no relation to this issue.

I'm going to close this on out, `react-router-dom`'s types seem to work well with Preact now.
