### ISSUE TITLE
TypeScript error when functional component return undefined

### ISSUE THREAD

**Issue by weijarz** [preactjs/preact#1753]
```typescript

interface HelloProps {
  name?: string
}
const Hello: FunctionComponent<HelloProps> = props => {
  if (props.name) {
    return <h1>Hello, {props.name}</h1>
  }
}
```

Type '(props: Readonly<HelloProps & Attributes & { children?: ComponentChildren; ref?: RefObject<any> | RefCallback<any> | undefined; }>) => Element | undefined' is not assignable to type 'FunctionComponent<HelloProps>'.
  Type 'Element | undefined' is not assignable to type 'VNode<any> | null'.
    Type 'undefined' is not assignable to type 'VNode<any> | null'.ts(2322)

**Comment by JoviDeCroock** [comment]
As far as I know your component shouldn’t return undefined, the case without return should be null. In React this throws an error when undefined is returned
