### ISSUE TITLE
<Switch> from react-router-dom not working with preact X <Fragment>

### ISSUE THREAD

**Issue by mdierolf** [preactjs/preact#1754]
The ``<Switch>`` module from react-router-dom does not appear to be compatible with ``<Fragment>``
```
<Switch>
 <Fragment>
  <Route .../>
  <Route .../>
 </Fragment>
</Switch>
```
When rendering the above code, all the routes are rendered, i.e. the Switch component does not see the individual routes underneath the fragment, and thus does not render them exclusively.

Looking at the code for the Switch component, it appears that they use React.Children.forEach to loop through each child in the VDOM - which is presenting the fragment and not the children of the fragment - is it expected behavior for that function to present the fragment instead of the children of the fragment?

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js

I'm not sure if this is a bug with preact or not, but it prevents ``<Fragment>`` from being used underneath components that have certain expectations of what the VDOM should look like.

**Comment by marvinhagemeister** [comment]
Can you share a [codesandbox](https://codesandbox.io) where the issue can be reproduced? It helps us tremendously in narrowing issues down.

**Comment by marvinhagemeister** [comment]
Ok, Ai just [checked their docs](https://reacttraining.com/react-router/web/api/Switch/children-node) and they explicitly mention that the `<Switch>` component has a hard parent to child relationship. This means that any child of the Switch component **must** be a `<Route>` component for it to work correctly.
