### ISSUE TITLE
Preact X - The Last Mile

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact#1756]
As we're getting really close to a release I thought it'd be good to make a list of remaining tasks to be done. Sort of like a release checklist like we had back in the `ceviche` repo before we went public. I think it helped us a lot in the final weeks.

I compiled a list of PRs that I think are a _must_ have for the final release. We should be careful here not to fail victim of feature creep. It's not like will stop publishing releases after that. Instead we'll continue cutting new ones in our usual 2-3 weeks cycle.

Releasing X will ease our maintenance burden quiet a bit as we can finally deprecate `preact-compat` (it has moved to core at `preact/compat`) and allow the ecosystem to adapt.

**PRs:**
- [x] Bypass props in `hydration` #1697
- [ ] ~~`Suspense` for SSR https://github.com/preactjs/preact-render-to-string/pull/92~~
- [x] Evaluate approach to fix portals used in https://github.com/preactjs/preact/pull/1749

**Docs:**
- [x] Write migration guide. We can reuse our release notes here, we just need to combine that into a single doc. - _@marvinhagemeister Just checked, the initial X alpha.0 release notes are very complete. Can't find anything to add_
- [x] Update [differences to React](https://preactjs.com/guide/differences-to-react) page

**Release:**

- [ ] Publish `preact-router@next` as latest
- [ ] Publish `preact-render-to-string@next` as latest
- [ ] Publish `preact-jsx-chai` for X https://github.com/developit/preact-jsx-chai/pull/70

cc @andrewiggins @JoviDeCroock @developit @ForsakenHarmony @cristianbote

**Comment by marvinhagemeister** [comment]
Forgot to add: PRs like the new devtools adapter can easily land in a point/patch release. My thinking here is that even the extension itself is still marked as experimental so we could release it under the "preview" umbrella. I still need to write more tests for it though.

**Comment by JoviDeCroock** [comment]
I'd say this is a good issue to point to for our docs: https://github.com/developit/preact-www/issues/286

**Comment by marvinhagemeister** [comment]
@pmkroeker Anything on the TS side you'd want to add?

**Comment by pmkroeker** [comment]
Not that I can think of off hand. The biggest thing is to remind library authors that JSX will now need to be imported if it is used in their typings.

**Comment by marvinhagemeister** [comment]
Closing, Preact X was released a while back :tada:
