### ISSUE TITLE
Issue using Hooks with exported component

### ISSUE THREAD

**Issue by oliverdunk** [preactjs/preact#1757]
### Bug
When I render an imported component which uses the `useContext` hook, I get the following error:
```
Uncaught TypeError: Cannot read property 'context' of undefined
    at Module.useContext (index.js:173)
    at d../src/example.tsx.exports.Example [as constructor] (example.tsx:7)
```
It appears that `currentComponent` is undefined, but I'm not sure what that means or how to fix it.

I think the issue is related to my build process, so have created a repository which demonstrates the problem.

### Steps to reproduce
1. Clone https://github.com/oliverdunk/preact-bug
2. Run `npm install`
3. Run `npm run-script run`

### Expected behaviour
The number 5 is rendered on the page, inside of a H1.

### Actual behaviour
When the `Example` component is rendered, the previously mentioned error is thrown.

**Comment by marvinhagemeister** [comment]
The issue is caused by a wrong import. `preact/hooks` will import the minified distribution files whereas `preact/hooks/src` will import the original source files. We use variable mangling for the distribution files and because of different namings the `currentComponent` variable will not be set correctly.

```diff
- import { useContext } from "preact/hooks/src";
+ import { useContext } from "preact/hooks";
```

**Comment by oliverdunk** [comment]
Thanks for the quick response, that fix worked perfectly! I went with the detailed issue because I had no idea what bit of my setup was relevant 😅

IIRC, VSCode did offer the import to me - I wonder if there's a way to prevent that? No big deal though.

**Comment by OngeUK** [comment]
FWIW - I had the same issue where VSCode's auto importing used `preact/hooks/src`...

**Comment by developit** [comment]
@marvinhagemeister I wonder if this could be fixed if we excluded `preact/hooks/src` from the npm package via `pkg.files`?

**Comment by marvinhagemeister** [comment]
@developit That would work too :+1: I don't think anybody uses that anyway since it's not referenced in `main` or `module` :100:

**Comment by kossnocorp** [comment]
I've encountered the same issue with the VS Code and `10.0.0-rc.3`.

**Comment by artalar** [comment]
`10.0.0-rc.3` - same bug.

([reproduce](https://codesandbox.io/s/hello-world-i5m8g), see `Header.tsx`)

I try to `import { useContext } from "preact/hooks";` and `import { useContext } from "preact/compat";`, but every time get the same error: `TypeError: Cannot read property 'context' of undefined`.

By the way, all works fine if I firstly start the server with code without hooks, and after that try to add code with hooks (hot reload -> all works fine). May be the problem related to SSR (next.js)?

**Comment by artalar** [comment]
@developit @marvinhagemeister 
`10.0.0-rc.3` - same bug.

([reproduce](https://codesandbox.io/s/hello-world-i5m8g), see `Header.tsx`)

I try to `import { useContext } from "preact/hooks";` and `import { useContext } from "preact/compat";`, but every time get the same error: `TypeError: Cannot read property 'context' of undefined`.

By the way, all works fine if I firstly start the server with code without hooks, and after that try to add code with hooks (hot reload -> all works fine). May be the problem related to SSR (next.js)?

**Comment by cristianbote** [comment]
Hey @artalar when using aliasing of `react` to `preact/compat` you should use `react` imports rather than `preact`. In other words, you should use `import { useContext } from "react"`.

Check out the amended version https://codesandbox.io/s/hello-world-1xs58

**Comment by artalar** [comment]
@cristianbote it works! Thanks a lot!

**Comment by marvinhagemeister** [comment]
I'm wondering why this leads to errors though, because `preact/compat` just re-exports `preact/hooks`. Maybe we need to check out bundler config and make sure that it isn't inlined into `preact/compat`
