### ISSUE TITLE
X cannot work with material-ui TextField

### ISSUE THREAD

**Issue by yuqianma** [preactjs/preact#1759]
I create a codesandbox to show the problem:
https://codesandbox.io/s/goofy-davinci-nnwgo?fontsize=14

I first guess it's related to this [PR](https://github.com/preactjs/preact/pull/1548/files) in [10.0.0-beta.1](https://github.com/preactjs/preact/releases/tag/10.0.0-beta.1). But I tried to install `beta.0`. It's also broken.
Other possible is `ref`?

Have no time to dig in the problem. Open a ticket there for whom may also encounter the issue.

**Comment by JoviDeCroock** [comment]
Hey @yuqianma thanks for taking time out of your day to reproduce the issue and bring it to our attention. This is highly appreciated, I'll update this comment as I go through it.

So I have foudn that it got introduced in the `alpha.3` version

**Comment by yuqianma** [comment]
@JoviDeCroock You are so actively reply the issue every time! It's joyful to code in the preact community!

**Comment by JoviDeCroock** [comment]
@yuqianma hey I found the fix, it was due to https://github.com/preactjs/preact/pull/1438 implicitly removing support for uncontrolled inputs. Thank you so much for bringing it to our attention and the awesome reproduction!

**Comment by yuqianma** [comment]
@JoviDeCroock Sooooo quick!!! Thanks!
