### ISSUE TITLE
Preact/React hooks difference in behaviour

### ISSUE THREAD

**Issue by pmkroeker** [preactjs/preact#1767]
I've been slowly working into moving some of my class based components over to hooks with `beta.3` and noticed some differences to how react handles hooks vs preact. Below are 2 sandboxes with the same code, one in React and the other in preact-X. The React one seems to properly load the image, and when the image is clicked, will update the counter, but the preact one does not seem to even show the image.

I have added console logs into sections to show when `useEffect` is run in the `useFetch` hook, and what the response from the hook is.

The React Example logs
```
Object > { response: null, error: null }
'running effect'
Object > { response: Object, error: null }
```
as expected.

The Preact examples logs only
```
Object > { response: null, error: null }
```

[React Hooks](https://codesandbox.io/s/react-hooks-example-711pp)
[Preact Hooks](https://codesandbox.io/s/preact-hooks-example-juome)

**Comment by JoviDeCroock** [comment]
For some reason in Preact it throws to: 

```
index.js? [sm]:9 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (index.js? [sm]:9)
    at Object.eval [as i] (index.js? [sm]:9)
    at l (hooks.js:1)
    at Array.forEach (<anonymous>)
    at x (hooks.js:1)
    at eval (hooks.js:1)
    at Array.some (<anonymous>)
    at p (hooks.js:1)
```

**Comment by pmkroeker** [comment]
Hmm, that looks like a babel error (and why I opted for TS over babel for transpiling JSX). I tested the same code snippet from the examples above on my work TS+webpack setup and it seems to be working correctly. Will close for now unless I find something else may be causing the inconsistencies.
