### ISSUE TITLE
React typings not found in 3rd party package with peerDependency

### ISSUE THREAD

**Issue by ondratra** [preactjs/preact#1771]
Hello,
I am trying to get working library [`react-sortable-hoc`](https://github.com/clauderic/react-sortable-hoc) with `preact` and `browserify` in Typescript.  
I tried to alias the `react` package with [`aliasify`](https://github.com/benbria/aliasify) as described in [`preact-compat`](https://github.com/developit/preact-compat) package's readme. 
Unfortunately `react-sortable-hoc` has peerDependency on `react` and even when aliasing for `.ts` files works fine I've encountered an error in typescript definition of the package (in `.d.ts` file) :
```
TypeScript error: node_modules/react-sortable-hoc/types/index.d.ts(1,24): Error TS2307: Cannot find module 'react'.
```
I've been trying different approaches to solve this but none of them were successfull. So I would like to know if there is anything I can do to get that working? Also could `preact-compat` somehow provide react typings that would solve the problems with preact + peer dependency in 3rd party react packages?

**Comment by JoviDeCroock** [comment]
Hey what version of preact are you using?

**Comment by ondratra** [comment]
Preact 10.0.0-rc.0

**Comment by JoviDeCroock** [comment]
Then you shouldn't use `preact-compat` but `preact/compat`

**Comment by ForsakenHarmony** [comment]
Also think you might have to install `@types/react`

**Comment by ondratra** [comment]
Sorry for confusion I made: I tried both current stable `preact` version with `preact-compat` and `preact X` with `preact/compat` as documentation suggested. Plus i don't think you can include both `preact` and `@types/react` to the same project. I tried that for 8.x.x version and it conflicts ([known issue](https://github.com/preactjs/preact/issues/639#issuecomment-385146125)) - I haven't tried that with Preact X.

After some more digging into the problem I found that when running 
```
browserify src/index.tsx  -t [aliasify] --global-transform=aliasify -p [tsify -p tsconfig.json] -o dist/bundle.js
```
command `aliasify` transform get's ignored. As stated [here](https://github.com/TypeStrong/tsify/issues/113#issuecomment-193908514) `tsify` plugin can't use other tranforms. 

`tsify` also [doesn't support](https://github.com/TypeStrong/tsify/issues/91) Typescript's `path` directive, while browserify doesn't support ES6 imports in it's `b.require('x', {expose: 'y'})`; another dead end.

Is there anybody that got components originally created for `react` working in stack Typescript + Browserify + Preact? At this point I think this is more like `tsify`'s issue than `preact`'s, but I would be glad if anybody can give me hint.

**Comment by ondratra** [comment]
Alias can be done via `pathmodify` plugin for `browserify` see how to do that in [this](https://github.com/TypeStrong/tsify/issues/255) ticket. 

Thanks everyone for help.
