### ISSUE TITLE
[preact/10.0.0-rc.0] Jest doesn't seem to work with preact/compat

### ISSUE THREAD

**Issue by thiagoabreu** [preactjs/preact#1775]
Hi. I'm trying to update a project to Preact X, and found that my Jest ("jest": "^24.8.0") tests do not run.

I set up the jest config with the following module mapper:

```json
"jest": {
    "preset": "ts-jest/presets/js-with-ts",
    "transform": {
      "^.+\\.ts$": "ts-jest",
      "^.+\\.svg$": "jest-svg-transformer"
    },
    "testRegex": "\\.test\\.(t|j)s",
    "moduleNameMapper": {
      "react": "preact-compat"
    }
}
```

And here's the output:

```
FAIL  src/reduxStore/actions.test.js
  ● Test suite failed to run

    TypeError: Cannot read property '__e' of undefined

      at Object.<anonymous> (node_modules/preact/compat/src/suspense.js:89:8)
      at Object.<anonymous> (node_modules/pretty-format/build/plugins/ReactElement.js:8:39)
      at Object.<anonymous> (node_modules/pretty-format/build/index.js:19:44)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.099s
Ran all test suites.
```

Is any additional config needed?

UPDATE: added full jest config

**Comment by marvinhagemeister** [comment]
The jest config maps `react` to `preact-compat` which only works with Preact 8. For Preact X we moved compat into core. If that's actually not a typo in this issue, replacing `preact-compat` with `preact/compat` should do the job.

**Comment by thiagoabreu** [comment]
Found the error.

Apparently the `react-is` module was been mapped to preact/compat too.

Fixed:

```
"moduleNameMapper": {
      "^react$": "preact/compat"
    },
```

Thanks!

**Comment by marvinhagemeister** [comment]
Oh that's good to know :+1: Awesome that you found it :100:
