### ISSUE TITLE
(TypeScript) Why can't I setState with an object containing the keys of my state type

### ISSUE THREAD

**Issue by Hubro** [preactjs/preact#1778]
Why doesn't this work:

```typescript
export interface IState {
    username: string;
    password: string;
}

// ...

private onInputChange(e: Event, field: keyof IState) {
    const target = e.target as HTMLInputElement;
    this.setState({ [field]: target.value });
}
```

![image](https://user-images.githubusercontent.com/597206/61289605-fa3bd100-a7c9-11e9-85cd-12c6d8043d2d.png)

Am I incorrect in thinking this should work? `field` is by definition one of the keys of `IState`, so defining an object containing only `field` as keys should be a valid `IState` object. Is there an issue with the preact type declarations, or have I misunderstood something?

**Comment by marvinhagemeister** [comment]
That is an issue with TypeScript itself and not our typings. You can reproduce that issue in the official TypeScript playground: http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQGUZNU4BvAKDhrgFcBnNJTAW2AC44GYpkBzANzVaYTAwYB3aABMuPPkiGUAvpUro6SbDAQQkcffiRg6MAMIALTEuAAKTnACiAN2AoANHHQJgAGzk4AGtgAE8IdAJiUmAASgoRGmx9HjgSKH5geABeOGAAOnTM+HE4AAkAFQBZABljUxgnP2B2FGFabizo1DtyOABtH38ZAF0uIqz8l0w-OjwVWOE1DS0dPQMmGG77HhiuIhJUeKoOgHpTuCQICDBVIA

**Comment by Hubro** [comment]
@marvinhagemeister Ok thanks. Do you have any suggestions for how to implement such a function? Basically my state object has multiple text properties, and I don't want to have to add a mostly identical function for every event handler. Do I basically have to hack around it with `as any`?

**Comment by cecilemuller** [comment]
@Hubro maybe you could use `Partial<IState>` in setState ?

````ts
export interface IState {
    username: string;
    password: string;
}

function onInputChange(e: Event, field: keyof IState) {
    const target = e.target as HTMLInputElement;
    setState({ [field]: target.value });
}

function setState(state: Partial<IState>) {
    //
}
````

**Comment by marvinhagemeister** [comment]
After having a closer look I had an error in my sample snippet. Looks like we're indeed missing a `Partial` declaration in our types.

cc @pmkroeker 

This is the updated sample: http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQGUZNU4BvAKDhrgFcBnNJTAW2AC44GYpkBzANzVaYTAwYB3aABMuPPkiGUAvpUro6SbDAQQkcffiRg6MAMIALTEuAAKTnACiAN2AoANHHQJgAGzk4AGtgAE8IdAJiUmAASgoRGmx9HjgSKH5geABeOGAAOnTM+HE4AAkAFQBZABljUxgnP2B2FGFabizo1DtyOABtH38ZAF0uIqz8l0w-OjwVWOE1DS0dPQMmGG77HhiuAAVMWAQZgB4iElQAPniqDoB6e7gkCAgwVSA

**Comment by Hubro** [comment]
@marvinhagemeister Does that mean my original example should work after modifying preact's types?

**Comment by pmkroeker** [comment]
Interesting. I think I played around with using `Partial` and it had some other side effects that I didn't like, also, the React typings don't use `Partial` for setState but `Pick` like ours do. Will investigate.

**Comment by pmkroeker** [comment]
This seems to be cause as it did not match `Pick<State, keyof State>`, so it was trying to match explicitly with `State`, when it should have been `Partial<State>`.
