### ISSUE TITLE
can't build Preact X + Typescript

### ISSUE THREAD

**Issue by moebiusmania** [preactjs/preact#1782]
hi everybody, I wanted to play a little bit with Preact X before official release, but I'm finding stuck with basic building of a Typescript template project.

steps to reproduce:
```bash
$ npm i -g preact-cli@next
$ preact create typescript x-test
$ cd x-test
$ npm i -D preact-cli@next @types/react
$ npm i preact@next preact-router@next
$ npm run build
```

and I get the following errors (at 95% of build 😭):
```
✖ ERROR ./node_modules/preact-router/index.d.ts
ERROR in ./node_modules/preact-router/index.d.ts(65,62):
TS2694: Namespace 'global.JSX' has no exported member 'HTMLAttributes'.
✖ ERROR ./node_modules/preact-router/match.d.ts
ERROR in ./node_modules/preact-router/match.d.ts(9,40):
TS2694: Namespace 'global.JSX' has no exported member 'HTMLAttributes'.
✖ ERROR ./src/components/header/index.tsx
ERROR in ./src/components/header/index.tsx(11,22):
TS2322: Type '{ children: string; activeClassName: string; href: string; }' is not assignable to type 'LinkProps'.
  Property 'children' does not exist on type 'LinkProps'.
✖ ERROR ./src/components/header/index.tsx
ERROR in ./src/components/header/index.tsx(14,22):
TS2322: Type '{ children: string; activeClassName: string; href: string; }' is not assignable to type 'LinkProps'.
  Property 'children' does not exist on type 'LinkProps'.
✖ ERROR ./src/components/header/index.tsx
ERROR in ./src/components/header/index.tsx(17,22):
TS2322: Type '{ children: string; activeClassName: string; href: string; }' is not assignable to type 'LinkProps'.
  Property 'children' does not exist on type 'LinkProps'.
✖ ERROR undefined
```

running `npm start` is fine, the project is built and can be opened in the browser, is only the build command that it's breaking.

I've figured out reading other issues how to "upgrade" to Preact X, I didn't found any documentation or note about it in repo or website, so maybe I'm missing something.

Any feedback is appreciated, thanks

**Comment by pmkroeker** [comment]
These have all been fixed in the master branch of preact router, but there has not been a new release since I believe.

**Comment by pmkroeker** [comment]
Is there a reason your are installing the types for react?

**Comment by marvinhagemeister** [comment]
FYI: we cut a new release for `preact-router`

**Comment by moebiusmania** [comment]
@pmkroeker read it in a previous issue and solved some of typings errors. If you say that this isn't necessary I will try again by removing it. But once again, I didn't found any clear documentation on how to upgrade for X so I had to figure out things by reading different issues.

**Comment by moebiusmania** [comment]
@pmkroeker I've update `preact-router` to the latest next release (v3.0.1) and build is fine, I've tried to remove the `@types/react` package and when I run the build command I'm getting these errors.

```
✖ ERROR ./node_modules/preact-render-spy/index.d.ts
ERROR in ./node_modules/preact-render-spy/index.d.ts(98,23):
TS2503: Cannot find namespace 'JSX'.
✖ ERROR ./node_modules/preact-render-spy/index.d.ts
ERROR in ./node_modules/preact-render-spy/index.d.ts(121,18):
TS2503: Cannot find namespace 'JSX'.
✖ ERROR ./node_modules/preact-render-spy/index.d.ts
ERROR in ./node_modules/preact-render-spy/index.d.ts(127,18):
TS2503: Cannot find namespace 'JSX'.
✖ ERROR undefined
```

Now that I have a working build I can start to figure out the migration to X, thanks to both @pmkroeker  and @marvinhagemeister . 
Looking forward for the official release 😎
