### ISSUE TITLE
Render bug with replaceNode parameter after update from 10.0.0-beta.3 to 10.0.0-rc.0

### ISSUE THREAD

**Issue by jasson2788** [preactjs/preact#1783]
Hello guys. After upgrading preact to its newest version the styles are no longer applied when using a replaceNode parameter in the render function.

Here's an example: 

```
import { h, render, Component, JSX } from 'preact';

const parent = document.getElementById('parent') as HTMLElement;
const child = document.createElement('div') as HTMLDivElement;
parent.appendChild(child);

class Comp extends Component {
    public render = (): JSX.Element => {
        return <div style={{ height: '100px' }}>Preact</div>;
    }
}
	
render(<Comp />, parent, child);
```

When you call the render function without the replaceNode parameter the styles are applied correctly:

`render(<Comp />, parent);`

Have a great day everyone.

**Comment by cristianbote** [comment]
Hi @jasson2788, thanks for opening this issue.

So what's happening here, is that the `third` param for the `render` method is used as a starting point for kicking in the hydration process. Since `-rc.0` we're ignoring the props during hydration.
