### ISSUE TITLE
Preact 8 - How to create a reverse constructor?

### ISSUE THREAD

**Issue by thadeu** [preactjs/preact#1791]
Its is possible create reverse constructor?

example:

```
class Simple extends Component {
  constructor(props) {
    super(props)
  }
  
  disconstructor(props) {
    super(props)
  }
}
```

in this case, called after the complete disassembly of the component

**Comment by pmkroeker** [comment]
Are you trying to run something when the component is unmounted? The closest is `componentWillUnmount`, which fires right before the component is unmounted.

**Comment by thadeu** [comment]
@pmkroeker so, `componentWillUnmount` is fired based on diff, in my case, I'd like fire always unmounted once

**Comment by marvinhagemeister** [comment]
@thadeu The instance will be discarded right after `componentWillUnmount` is called once the next GC sweep takes place. The only thing we do before that is detaching any `dom` nodes that belong to that `Component` from the document. It's basically the same thing as you're suggesting with "reverse constructor".
