### ISSUE TITLE
Stand-alone, cross-component functions?

### ISSUE THREAD

**Issue by heymartinadams** [preactjs/preact#1792]
Newbie to Preact here ✨  Love how fast it is.

Is it possible to share stand-alone functions across various components? Several components in my preact app share functions that are unrelated to any particular components.

For example (I custom-built my own router):

**routes/index.js**
```js
export const testForUrlRedirect = ({ url, props }) => {
  ...
  return newUrl
}
export const getPageDataFromPageIdOrUrl = ({ pageId, url }) => {
  ...
  return pageData
}
```

**MyComponent.js**
```js
import { testForUrlRedirect, getPageDataFromPageIdOrUrl } from '../routes'
```

In `MyComponent`, neither functions work as expected.

I did notice #722, yet that issue refers to functions that are part of other components. Is it possible to have stand-alone functions and share them across various components?

**Comment by JoviDeCroock** [comment]
Yes it's possible. 

Example: https://codesandbox.io/s/hidden-https-04wf2

I can't derive much from this issue statement as to what is going wrong since these are code fragments and what is going wrong is not really told

**Comment by heymartinadams** [comment]
Sorry, I should have included the error logs:
```console
⚠ WARN ./components/App.js 64:45-71
"export 'getPageDataFromPageIdOrUrl' was not found in '../routes'
 @ ./index.js
 @ /Users/martinadams/.config/yarn/global/node_modules/preact-cli/lib/lib/entry.js
 @ multi /Users/martinadams/.config/yarn/global/node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

When I manually log the function `console.log(getPageDataFromPageIdOrUrl)` in the component, it shows up as `undefined`, even though the path to the function is correct.

**Comment by JoviDeCroock** [comment]
This is not an issue related to preact, this is an issue related to your project.

Let's say you have this folder structure

components
  App.js
routes
    index.js

With your import you will look at that routes/index.js for those two exports

**Comment by heymartinadams** [comment]
That’ correct, what I did, no? Using the file structure you mentioned:

**components/App.js**
```js
import { getPageDataFromPageIdOrUrl } from '../routes'
```

**routes/index.js**
```js
export const getPageDataFromPageIdOrUrl = ({ pageId, url }) => {
  ...
}
```

Wondered if somehow Webpack might have disabled stand-alone function exporting.

**Comment by JoviDeCroock** [comment]
Do you have a repository I could look at or something, it's quite vague to talk about code on this level

**Comment by heymartinadams** [comment]
Thanks, @JoviDeCroock 🙏  https://github.com/EcstaticLife/preact/blob/master/src/components/Application.js

**Comment by JoviDeCroock** [comment]
In preact-cli `/routes` is used as a code-splitting point that's why this is happening. Renaming it solves your issue

**Comment by heymartinadams** [comment]
Thanks @JoviDeCroock 👌

**Comment by JoviDeCroock** [comment]
```
in general, routes/*.js and routes/*/index.js must export single components, since they get auto-wrapped by the CLI for lazy loading

if you have helper functions you'll need to move them so they don't match those patterns
```
