### ISSUE TITLE
componentWillUnmount() fires too late when use with preact-router route()

### ISSUE THREAD

**Issue by thadeu** [preactjs/preact#1793]
I have two components where I need to call something exactly in the constructor and in the unmount. But it seems that taking unmount fire before the constructor.

<img width="1516" alt="Screen Shot 2019-07-22 at 19 31 32" src="https://user-images.githubusercontent.com/77889/61669697-582f5380-acb7-11e9-8210-a18df68b57dd.png">

Maybe its same problem as [#349](https://github.com/preactjs/preact/issues/349)

Is there a quick fix for this?

thanks

**Comment by JoviDeCroock** [comment]
When checking your screenshot everything feels right to me, could you give a reproduction? I'll double check to ensure

**Comment by thadeu** [comment]
@JoviDeCroock https://jsfiddle.net/tadeuu/3j1r6ckq/1/

**Comment by thadeu** [comment]
@JoviDeCroock when used componentDidMount and componentWillUnmount its ok!

https://jsfiddle.net/tadeuu/3j1r6ckq/7/

**Comment by thadeu** [comment]
But it dont solve my problem!

**Comment by JoviDeCroock** [comment]
As far as I see it's behaving as expected, it constructs the prior and unmounts the latter.

This is correct according to me:

```
in Home
mount home
in Profile
out Home
mount profile
```

**Comment by ForsakenHarmony** [comment]
@thadeu what are you looking to achieve with doing something in the constructor instead of `componentDidMount`?

**Comment by thadeu** [comment]
@ForsakenHarmony I'll keep componentDidMount for now.
