### ISSUE TITLE
Declaring form attribute on button element result in error (Preact X)

### ISSUE THREAD

**Issue by Saartje87** [preactjs/preact#1801]
Hey,

I'm trying out Preact 10.0.0-rc.0 and preact/compat and came across an issue with buttons referencing a form `<button form="target">`.

The following example result in "Cannot assign to read only property 'form' of object '#\<HTMLButtonElement>'"

```jsx
render(
  <div>
    <form id="testForm">
      <input type="text" name="foo" />
    </form>
    <button form="testForm">
      Hi
    </button>
  </div>,
  mountNode,
);
```

**Comment by marvinhagemeister** [comment]
Thanks for your report :+1: Just pasted the snippet in a sandbox and it works without any errors: https://codesandbox.io/s/button-form-80lv3 Both Firefox and Chrome don't print any errors for me (don't have more browsers to test right now).

Which browsers are you using?

**Comment by Saartje87** [comment]
Browsers: Chrome 75, Safari 12.

My setup webpack / babel / typescript (trying to port a react project). 
Created a test with preact-cli and no error occurs 😱Not sure what could be triggering this issue in my setup..

Thanks for the snippet, side note there, the form tag is not applied, so the button won't submit the form.

setAttribute seems to work fine, dom.form = 'target' not.

I am a bit confused about this attribute, it is a read only attribute(?) see the second link.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement
https://www.w3schools.com/tags/att_button_form.asp

<img width="888" alt="Screenshot 2019-07-25 at 16 15 40" src="https://user-images.githubusercontent.com/346697/61882475-eb0b0080-aef8-11e9-83d8-5b8931085a01.png">

**Comment by sventschui** [comment]
> it is a read only attribute(?)
Yes the `.form` attribute on the `HTMLButtonElement` is read-only in JS.

This is why setting the prop doesn't work but a `setAttribute` will, as it modifies the button element (DOM).

I'm not sure how we handle such cases in preact but I think we should add another `!==` here: https://github.com/preactjs/preact/blob/master/src/diff/props.js#L90
