### ISSUE TITLE
version X: Context HOC - Uncaught TypeError: n.children is not a function

### ISSUE THREAD

**Issue by oste** [preactjs/preact#1803]
I am trying to create a HOC using Context and I am getting `Uncaught TypeError: n.children is not a function`

Here is the basic code

index.js:

```
import { render } from 'preact';
import MyProvider from 'context';
import Button from 'button';

render(
     <MyProvider color="red">
         <Button/>
    </MyProvider>,
    target
);
```

context.js

```
import { Component, createContext } from 'preact';

const context = createContext();

export default class MyProvider extends Component {
	render() {
		const { children, ...value } = this.props;
		return (
			<context.Provider value={value}>{children}</context.Provider>
		);
	}
}

// this is the part that is faling
export const withContext = (WrappedComponent) => {
    return class ContextConsumer extends Component {
      render() {
        return (<context.Consumer><WrappedComponent /></context.Consumer>);
      }
    }
}
```

button.js

```
import { Component } from 'preact';
import { withContext } from 'context';

class Button extends Component {
    render() {
        return (
            <button>test</button>
        );
    }
}

export default withContext(Buttonn);
```

**Comment by oste** [comment]
I also tried `withContext` like this

```
export const withContext = (WrappedComponent) => {
	return class ContextConsumer extends Component {
		render() {
			return (<context.Consumer><WrappedComponent /></context.Consumer>);
		}
	}
}
```

**Comment by JoviDeCroock** [comment]
Consumer is a render prop so your component should look like:

<Consumer>{(ctx) => <Component ctx=ctx />}</Consumer>

**Comment by oste** [comment]
Hi @JoviDeCroock, 

Thanks for getting back. This was actually one of the first things I tried.

```
export const withContext = (WrappedComponent) => {
 	return <context.Consumer>{(ctx) => <WrappedComponent ctx={ctx} {...this.props} />}</context.Consumer>
}
```
but this gave `preact.js?10a9:1 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.`

This does however seem to work.
```
export const withContext = (WrappedComponent) => {
	return class ContextConsumer extends Component {
		render() {
			return <context.Consumer>{(ctx) => <WrappedComponent ctx={ctx} {...this.props} />}</context.Consumer>
		}
	}
}
```

**Comment by oste** [comment]
This also used to work in v8 with `preact-context`

```
export const withContext = OriginalComponent => props => (
  <context.Consumer render={ctx => <OriginalComponent {...ctx} {...props} />} />
);
```

**Comment by JoviDeCroock** [comment]
Works for me with Preact X, has to be something else on your side: https://codesandbox.io/s/hidden-https-04wf2

**Comment by oste** [comment]
ok will look into it.

Are these not equivalent? I was trying the former so wasn't getting success as a render prop.

`return <context.Consumer render={(ctx) => <WrappedComponent ctx={ctx} {...this.props} />}></context.Consumer>`

`return <context.Consumer>{(ctx) => <WrappedComponent ctx={ctx} {...this.props} />}</context.Consumer>`

**Comment by JoviDeCroock** [comment]
These are not equivalent, in the former you are relying on the render function of Consumer to be this:

```
render() {
  return this.props.render(context)
} 
```

while in the latter you are relying on this implementation:


```
render() {
  return this.props.children(context)
} 
```

**Comment by oste** [comment]
oh, your codesandbox works for me as well. What I was saying above is that this does not work

```
export const withContext = (WrappedComponent) => {
 	return <context.Consumer>{(ctx) => <WrappedComponent ctx={ctx} {...this.props} />}</context.Consumer>
}
```

It seems that just a simple function like this should work, no?

**Comment by JoviDeCroock** [comment]
Because that is not a HOC, that's a regular function for your case you'd need to do this:

```
export const wrapWithContext = (WrappedComponent) => {
  return (props) => <context.Consumer>{(ctx) => <WrappedComponent ctx={ctx} {...props} />}</context.Consumer>
}
```

**Comment by oste** [comment]
ok great, it was my use of `render={` causing issues. Like I [mentioned](https://github.com/preactjs/preact/issues/1803#issuecomment-515175333) this worked in Preact 8 using `preact-context`

Thanks for the help looking into this, hopefully this can help others making the transition.
