### ISSUE TITLE
10.0.0-rc.0 portal render differs from React when portal container element has existing children

### ISSUE THREAD

**Issue by rmales** [preactjs/preact#1806]
Hi,

I noticed that when using a portal in Preact the portal content is mounted in a different order compared to React when the portal container has existing child nodes. In Preact its prepended while in React its appended.
Example: https://codesandbox.io/s/patient-dream-0b83r

I also noticed that on rerender the existing child nodes are removed in Preact, but maybe that issue is fixed by https://github.com/preactjs/preact/pull/1781 (is there a way to test that commit in CodeSandbox)?

Thanks,
Richard

**Comment by JoviDeCroock** [comment]
Oh, that would be my mistake then, thought React prepended as well. Will fix that later thanks for the issue report!
