### ISSUE TITLE
Source Code is shown in Prodcution Build

### ISSUE THREAD

**Issue by chattes** [preactjs/preact#1809]
Maybe this is my mistake somewhere, but I have built and deployed to my server using preact-cli

```
yarn build

```

But in my production app if I open up the dev tools , I can find the actual source code under webpack, is there a way not to show that ?

![Screenshot_2019-07-27_00-53-08](https://user-images.githubusercontent.com/11190834/61976264-f1889d80-b008-11e9-8696-386f92daa2ba.png)

**Comment by marvinhagemeister** [comment]
This feature is called "Source Maps" and it remaps the minified code to the actual source. Without it debugging basically becomes impossible.

If you don't want to generate them you can disable them in your `preact.config.js` by modifying the webpack configuration.

```js
export default function(config) {
  config.devtool = 'none';
  return config;
};
```

**Comment by chattes** [comment]
Thanks for the info.
I need sourcemaps enabled when I am in dev not when I am in production.
let me try this hint.

Thanks
