### ISSUE TITLE
JSX type definition in Preact 8 is moved into preact namespace or JSX type definition is added to global for compatibility 

### ISSUE THREAD

**Issue by 38elements** [preactjs/preact#1811]
The namespace of JSX was changed.
This is breaking change.
I think that it is better to specify in the release notes.

https://github.com/preactjs/preact/blob/b4e059ad00ff2d4dc71b0d69d4a148a204da6d5f/src/index.d.ts#L6-L8

https://github.com/preactjs/preact/blob/3aaa578270c0c6cd1fb7f5cf992737eec2934433/src/preact.d.ts#L168-L170

To solve the following issue, I think that it is better to add JSX type definition to global.

https://github.com/developit/unistore/pull/158

I think it is better that JSX type definition in global  be deprecated.

**Comment by ForsakenHarmony** [comment]
> To solve the following issue, I think that it is better to add JSX type definition to global.

> I think it is better that JSX type definition in global be deprecated.

So uhh which one are you asking for?

global was removed because it conflicted with react

**Comment by 38elements** [comment]
> So uhh which one are you asking for?

JSX is added to global.
And JSX exists global until Preact 8 support is terminated.

**Comment by 38elements** [comment]
I think it is better that JSX type definition in Preact 8 is moved into preact namespace.

**Comment by ForsakenHarmony** [comment]
Release in v8.5.0

**Comment by aMarCruz** [comment]
Great, now prting my 8.x preact app to 10 breaks my toolchain because "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists".

![image](https://user-images.githubusercontent.com/6636980/63655883-2c3e3c80-c753-11e9-9b99-13b848cd8e97.png)

Using @types/react fixes this issue but breaks other things, I'm not using preact/compat.

**Comment by 38elements** [comment]
In 8.4.x, JSX exists in global namespace.
In 8.5+, JSX exists in global namespace and preact namespace.
In 10, JSX exists in preact namespace.
