### ISSUE TITLE
[10.0.0-rc.0] Suspense's fallback not being unmounted when it should

### ISSUE THREAD

**Issue by fjorgemota** [preactjs/preact#1813]
Hey.

I found a pretty weird issue on Suspense's fallback implementation of Preact X. Here's a [small codesandbox](https://codesandbox.io/s/preact-suspense-lazy-issue-euz15) with the issue (please navigate using the links on the demo to see the issue ocurring).

It's pretty simple, actually: Basically, when using a Component as a fallback, the content rendered by that Component isn't unmounted **after** Switch rendered the new page of the router.

Now, curiously, the issue is basically resolved when I use the content rendered by the Component directly as the fallback, OR when I use `() => <Loading />` with the fallback. I assume there's some flag on the component object that is making Preact to ignore it instead of just unmounting it, but as I don't know many of the Preact internals I'll post this issue here and hope for a solution.

Hope this helps to discover the cause of the issue. And keep the great work! :+1:

**Comment by fjorgemota** [comment]
Okay, apparently the suggested workaround (using `() => <Loading />` as fallback)  bugs with `preact/debug`, causing an exception "TypeError: Invalid value used as weak map key" to be throw. At least that's a very specific `preact/debug` issue.

:thinking:

**Comment by marvinhagemeister** [comment]
@fjorgemota `preact/debug` errors because `() => <Loading />` is not a valid component instance. You're passing the raw function instead.

```jsx
// This is invalid
<div>{() => <Loading />}</div>
```

To pass Components around they need to be wrapped in `h/createElement`:

```jsx
<div>{h(() => <Loading />)}</div>

// ... or via native jsx
const MyComponent = () => <Loading />;
<div><MyComponent /></div>
```

**Comment by fjorgemota** [comment]
Oh, okay, this makes sense.

Unfortunately, with that behavior the issue originally reported just...happens again. But okay, I'll let the issue open anyway, and I'll ignore the `preact/debug` issue for now.

Thanks for the reply anyway =)

**Comment by sventschui** [comment]
Sorry for the late reply. Was quite busy the past days. I guess I found the cause and a a fix (see #1859). Unfortunately I did not yet manage to reproduce this issue outside the codesandbox

**Comment by aduh95** [comment]
I have the same issue on my [app](https://github.com/aduh95/newsletter-template), so I tried to clone your PR's branch, I ran `yarn install && yarn build`, then I moved the `dist` folder to my `node_modules` in my app project. I am still able to reproduce the issue, the "Loading..." DOM nodes are still there..

**Comment by sventschui** [comment]
Thanks for the heads up. My attempt to fix this is still untested as I can‘t come up with a repro in preact‘s demo space. I‘ll try to create a unit test today :)

**Comment by oscartbeaumont** [comment]
Is there a fix as I am encountering this issue with one of my projects?

**Comment by marvinhagemeister** [comment]
@oscartbeaumont We're marking issues as `closed` when we have a fix ready. When an issue is unresolved and still open like this one, it means that there is no fix available.

**Comment by sventschui** [comment]
Unfortunately it is not easy to fix this issue. As mentioned in https://github.com/preactjs/preact/pull/1859 I managed to fix parts of it and we might want to release these fixes as it might help in some cases. 

I think two pass rendering won‘t arrive too soon as we want to get a stable v10 out as soon as possible.

**Comment by aduh95** [comment]
Shall we add a note about this issue on the [Differences to React page](https://preactjs.com/guide/differences-to-react)? Maybe in the `What's Missing` section? I feel that this issue may impact the code splitting in a project and devs should be aware of this as there is no fix or workaround at the moment.

**Comment by andrewiggins** [comment]
Just opened #2025 to fix the (this) fallback issue. Ideally we could support code-splitting without needing a two-phase render.
