### ISSUE TITLE
Bundle size is 143kb?

### ISSUE THREAD

**Issue by ko06** [preactjs/preact#1814]
Hi! really thanks for making such a library. I have doubt with a bundle size.

I just followed the steps as per documents everything working fine.

`$ preact create default my-project`

then,

`$ preact build`

but it produced 143kb !!!

`  "dependencies": {
    "preact": "^8.2.6",
    "preact-compat": "^3.17.0",
    "preact-render-to-string": "^4.1.0",
    "preact-router": "^2.5.7"
  },`

This is only on my package.json file. As of we know `Preact` is 3kb and `Preact-compact` is 4kb, however, the whole size must be less than 30kb probably. but it creates 143 kb unbelievable for me.

![Screenshot 2019-07-28 at 1 53 10 PM](https://user-images.githubusercontent.com/24521034/62004264-6f02f980-b140-11e9-88bf-1d981ca5b3bf.png)

![Screenshot 2019-07-28 at 2 16 16 PM](https://user-images.githubusercontent.com/24521034/62004406-598ecf00-b142-11e9-9a5b-ce6e6a6745a0.png)

@FYI,

`Preact-mini` [https://github.com/aganglada/preact-minimal](url) only give 30kb as expected without `"preact-render-to-string`.

So am I missing something regarding bundle size?
- Because of a test-case
- preact-render-to-string

 Just need a bit clarification regarding bundle size!

Thanks.

**Comment by marvinhagemeister** [comment]
If you look at all files webpack generated than you can see where the 143kb is coming from. Here is a list of all files it generated for me sorted by hteir size. Note that all measurements are done without gzip.

```
51.5 kB  /build/assets/icons/android-chrome-512x512.png
19.0 kB  /build/bundle.14732.js
15.1 kB  /build/assets/favicon.ico
15.1 kB  /build/favicon.ico
14.1 kB  /build/assets/icons/android-chrome-192x192.png
12.7 kB  /build/assets/icons/apple-touch-icon.png
9.05 kB  /build/assets/icons/mstile-150x150.png
1.68 kB  /build/route-profile.chunk.1e466.js
1.49 kB  /build/assets/icons/favicon-32x32.png
1.14 kB  /build/style.b9a15.css
888 B    /build/index.html
626 B    /build/assets/icons/favicon-16x16.png
451 B    /build/manifest.json
407 B    /build/route-home.chunk.d18d1.js
```

As you can see most of the size come from the various app icons. Browsers only pick one of them to display in the tab bar. If you're installing it on your home screen the larger ones will typically be used.

So I can see why you got confused there. For the next version of `preact-cli` (which is in RC by the way) we've changed the output significantly to avoid confusion. It does look something like this:

![size-output](https://user-images.githubusercontent.com/1062408/62005154-49b9bf80-b12f-11e9-881f-e42ea0a807c1.png)

**Comment by ko06** [comment]
Looks awesome. When it will be available..!?

**Comment by marvinhagemeister** [comment]
It will probably released the same time as X goes stable. Should be sometime soon, hard to give an exact date right now.

**Comment by ForsakenHarmony** [comment]
@ko06 you can try it right now by installing `preact-cli@rc`
