### ISSUE TITLE
Remove IE11 ponyfills?

### ISSUE THREAD

**Issue by joseprio** [preactjs/preact#1815]
The `utils.js` file has two functions: `assign` (for `Object.assign`) and `removeNode` (for `Element.prototype.remove`); those functions can be handled by Babel, or a polyfill. Perhaps they should be removed? IMHO, this would be beneficial for mobile browsers, as the native functions should be quicker, and resource-constrained systems are probably the most benefited from Preact.

**Comment by JoviDeCroock** [comment]
The problem with that is that most people don't transpile their node_modules, this effectively would lead to us making a breaking change. What we could do is adding a modern bundle, this work is being done in the microbundle repository.

**Comment by joseprio** [comment]
@JoviDeCroock thanks for the information; a modern bundle would definitely solve that inefficiency.
