### ISSUE TITLE
3.0.0-rc.3 → 3.0.0-rc.4 causes socket error

### ISSUE THREAD

**Issue by heymartinadams** [preactjs/preact#1817]
When upgrading from rc.3 to rc.4, I get the following error:

```javascript
Uncaught TypeError: Cannot read property 'replace' of null at createSocketUrl (createSocketUrl.js?2ef6:20)
```

It appears that `var getCurrentScriptSource = require('./getCurrentScriptSource');` (line 8) doesn’t get the current script source, which then causes `scriptHost.replace` to misfire (line 18-20):

```javascript
var scriptHost = getCurrentScriptSource(); // eslint-disable-next-line no-useless-escape

scriptHost = scriptHost.replace(/\/[^\/]+$/, '');
```

**Comment by JoviDeCroock** [comment]
I think this is meant for the preact-cli repository, preact itself is at rc.0

**Comment by heymartinadams** [comment]
Sorry about that — I did open the `preact-cli` repo, but then forgot to post it there :)
