### ISSUE TITLE
[10.0.0-rc.0] binding events from custom elements does not work

### ISSUE THREAD

**Issue by gregorym** [preactjs/preact#1820]
Hi!

Preact X has a regression in regards to registering events from custom elements.
I am unable to bind events from JSX anymore. I have to create the event listener manually in `componentDidMount`.

Here is an example below:
```javascript
import { h, Component } from 'preact';
import style from './style';

class Home extends Component {

	componentDidMount() {
		// This works
		this.checkbox.addEventListener('ionChange', console.log);
	}

	render() {
		return (
			<div class={style.home}>
				<script type="module" src="https://unpkg.com/@ionic/core@latest/dist/ionic/ionic.esm.js" />
				<link href="https://unpkg.com/@ionic/core@4.7.0/css/ionic.bundle.css" rel="stylesheet" />
			
				<h1>Home</h1>
				<ion-checkbox
					ref={checkbox => this.checkbox = checkbox}
					onIonChange={console.log} // This line does not work
				/>
			</div>);
	}
}

export default Home;
```

Codesandbox link: https://codesandbox.io/s/vigilant-spence-clqfo?fontsize=14
*You expect to see 2 console logs when toggling the checkbox.*

Let me know if you need more details.

**Comment by JoviDeCroock** [comment]
The reproduction isn't working for me

**Comment by gregorym** [comment]
It works now, you were seeing the previous revision for some reason.

**Comment by gregorym** [comment]
Ok i'm dumb. Here is the solution: `onionChange={console.log}`.

Preact 8 does lowercase the event name while Preact X does not.
https://custom-elements-everywhere.com/

**Comment by marvinhagemeister** [comment]
Let's reopen this. We're currently talking about ways to make this more obvious. One such idea would be to lowercase the first char `onIonChange -> ionChange` but we need to think about it some more 👍

**Comment by gregorym** [comment]
If anyone is curious, here is the logic to determine if the event name needs to be lowercased or not.
https://github.com/preactjs/preact/blob/9d46573e7a648f0edc965d63b7e2779c0e9cbb5c/src/diff/props.js#L79-L80

**Comment by marvinhagemeister** [comment]
Okay, so I had a look into this, but there is no way to know which events are available on a custom element. Native DOM events are available as property on the dom node itself, which we check for in the above snippet. For custom elements we can't check that and assume that the name part in `on + name` maps directly to a custom event. We can't make any assumptions about casing here because it's up the element to decide if it uses `ionChange` or `IonChange`.

I'll add a section about this to the docs.
