### ISSUE TITLE
[10.0.0-rc.1] preact/compat recreates DOM tree on every render call

### ISSUE THREAD

**Issue by alebastr** [preactjs/preact#1828]
Codepen: <https://codepen.io/alebastr/pen/RXLRRN?editors=0010>

There's a simple example that updates external state and calls `ReactDOM.render` on input field change. 
Every time you type something into input field, it loses focus. From the Chrome's DOM inspector it seems like the whole tree under '#root' is recreated or remounted on every `ReactDOM.render` call.

The issue is limited to `preact/compat` and everything works fine when I use `preact`. Last working release is 10.0.0-beta.3.

**Comment by ForsakenHarmony** [comment]
Why are you not using the built in update mechanism, i.e. `setState` in the class?

**Comment by alebastr** [comment]
Because that's something I used to do since react 0.9: call ReactDOM.render in an onChange callback of external state manager to update the presentation of an application.

[ReactDOM.render](https://reactjs.org/docs/react-dom.html#render) documentation promises that all the calls after initial render "use React’s DOM diffing algorithm for efficient updates". Seems like #1729 intentionally broke that for `preact/compat` and this deserves some big red warning text in changelog.

**Comment by marvinhagemeister** [comment]
Nah, it deserves a fix, not a red warning :wink:
