### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by zavr-1** [preactjs/preact#1834]
Hello 
would you mind keeping a changelog please? say I have a fork of preact 8, now it's been bumped to 8.5 from 8.4 and how am i supposed to know what the changes are? a simple

- `feature` add fragment
- `fix` don't evaluate on destroy 

would be nice... thanks
like i get it, on 8, it was a simple JSX namespace typedefs change, because I can see in commits, but on master with thousands of commits, it would be harder... anyway it's up to you it's just nicer for other developers to see what's really new

**Comment by JoviDeCroock** [comment]
Hey,

Changes can normally be found under https://github.com/preactjs/preact/releases. Every release will state the PR's that got merged and the things that have changed between releases. This is our way of not adding yet another file to the repository but having it inside the repo itself.

**Comment by marvinhagemeister** [comment]
Yup, the changelog is always available on the releases tab here on GitHub like @JoviDeCroock said :+1:

**Comment by zavr-1** [comment]
@JoviDeCroock @marvinhagemeister alright thanks folks didn't think of that tab! 🙇‍♂️
