### ISSUE TITLE
Preact removes draggable={false} from attributes

### ISSUE THREAD

**Issue by laino** [preactjs/preact#1849]
Same issue as https://github.com/preactjs/preact/issues/651

**Comment by laino** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

**Comment by laino** [comment]
There should probably be an internal list of enumerated properties, instead of hardcoding all of these in if/else paths.

**Comment by laino** [comment]
According to https://github.com/preactjs/preact/issues/663#issuecomment-482980069 this was fixed on the master branch. Are there any plans of backporting the fix to the current release version?

**Comment by JoviDeCroock** [comment]
Are you using Preact 8? Was testing in Preact X and this works fine. If there's more info on that from your side I can see what I can do to fix it

**Comment by laino** [comment]
I'm on Preact 8.5.1. I'd submit a PR with a simple fix, but since there's allegedly already a fix floating around I'm holding my horses for now. I wonder what the commit that fixed the issue was though.

**Comment by JoviDeCroock** [comment]
The commit that fixed the issue is located in X

**Comment by laino** [comment]
I realize that, but there's 1,988 commits on the master branch that aren't in version 8 and there's a good chance it just got fixed during some refactoring, instead of with a specific commit (especially since none specifically mentions draggable).

**Comment by marvinhagemeister** [comment]
Just checked and I can't reproduce the described issue in the latest version of Preact :tada:
