### ISSUE TITLE
Material UI example not working as in react

### ISSUE THREAD

**Issue by bb** [preactjs/preact#1850]
Hi, I just tried using the Material UI demo "Hide app bar" with preact 10 rc1 (using preact/compat in an alias configuration).

Using React, it can be observed, that the App Bar moves out when scrolling down (passing 100px) and in again when scrolling in again (above 100px or when last scroll direction was up).

Using preact, after hiding the App Bar, it never comes back. Assuming the goal of compatibility with React, I think it should work exactly the same.

Documentation: https://material-ui.com/components/app-bar/#hide-app-bar
Code Sandbox using React: https://codesandbox.io/s/h8ls7

Reproduction Code Sandbox using preact/compat: https://codesandbox.io/s/material-demo-7v6qq ... well, that's not working yet and I'm running out of time for today.
I don't know how to configure the alias (tried in package config as guessed from what I saw in https://github.com/codesandbox/codesandbox-client/pull/853). Changing the imports in the two files isn't enough because material-ui imports react as well. Can somebody help?

**Comment by marvinhagemeister** [comment]
Awesome, thanks a bunch for the sandbox! With it I was able to pinpoint the issue down to browsers not resetting styles when the value is `undefined`.

```js
// noop, doesn't work
dom.style.visibility = undefined;

// works
dom.style.visibility = null;
```
PR is ready and the fix should be included in the next release 🙂

**Comment by bb** [comment]
Wow, that's great... and again, on a weekend. Sorry for the timing. I'd be totally fine with fixes Mo-Fr.

The sandbox isn't even working as-is -- if anybody knows how to configure the alias there, that would help me with future reproduction cases (even though you can obviously fix issues without working sandboxes).
