### ISSUE TITLE
Preact 8: forwardRef is not a function

### ISSUE THREAD

**Issue by jmarroyave** [preactjs/preact#1872]
Hi, i'm migrating an app from react to preact. I setted up the preact-compat in the webpack.config and it builds with no errors, but when i see the app in the browser throws this error

**Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_2__.default.forwardRef is not a function**

Aparently is in the material-ui package, this is the stacktrace

    at Module../node_modules/@material-ui/core/esm/SvgIcon/SvgIcon.js (vendor.js:24641)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at Module../node_modules/@material-ui/core/esm/SvgIcon/index.js (vendor.js:24744)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at Object../node_modules/@material-ui/icons/utils/createSvgIcon.js (vendor.js:32744)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at Object../node_modules/@material-ui/icons/Send.js (vendor.js:32684)

and this is the code from the debugger 

```javascript
var SvgIcon = react__WEBPACK_IMPORTED_MODULE_2__["default"].forwardRef(function SvgIcon(props, ref) {
  var children = props.children,
      classes = props.classes,
      className = props.className,
      _props$color = props.color,
      color = _props$color === void 0 ? 'inherit' : _props$color,
      _props$component = props.component,
      Component = _props$component === void 0 ? 'svg' : _props$component,
      _props$fontSize = props.fontSize,
      fontSize = _props$fontSize === void 0 ? 'default' : _props$fontSize,
      htmlColor = props.htmlColor,
      titleAccess = props.titleAccess,
      _props$viewBox = props.viewBox,
      viewBox = _props$viewBox === void 0 ? '0 0 24 24' : _props$viewBox,
      other = Object(_babel_runtime_helpers_esm_objectWithoutProperties__WEBPACK_IMPORTED_MODULE_1__["default"])(props, ["children", "classes", "className", "color", "component", "fontSize", "htmlColor", "titleAccess", "viewBox"]);
```

what can i do?

**Comment by JoviDeCroock** [comment]
If you are using Preact X your alias should be preact/compat not preact-compat.

**Comment by jmarroyave** [comment]
no, i'm currently using 

    "preact": "^8.5.1",
    "preact-compat": "^3.19.0",

but after you mentioned Preact X (10.0.0-rc.1), i installed it and changed the webpack.config and throw this error

react-hot-loader.development.js:1567 TypeError: Cannot read property 'getChildContext' of undefined
    at Provider (preact.module.js:1)
    at y.ProxyFacade [as constructor] (react-hot-loader.development.js:805)
    at y.A [as render] (preact.module.js:1)
    at N (preact.module.js:1)
    at k (preact.module.js:1)
    at N (preact.module.js:1)
    at k (preact.module.js:1)
    at N (preact.module.js:1)
    at k (preact.module.js:1)
    at N (preact.module.js:1)

i'm using react-hot-loader: 4.12.5

**Comment by JoviDeCroock** [comment]
Well the material-ui one is normal, forwardRef is not available in the earlier preact afaik. The getChildContext feels weird since that’s deprecates in React... right?

**Comment by marvinhagemeister** [comment]
FYI: `forwardRef` is not supported in the 8.x release line.

**Comment by jmarroyave** [comment]
Hi Marvin, Is it not supported and it will not be? Is it because the version or because the feature?

What would be the next step that someone like me (a newbie in Preact, who wants to reduce the  React app bundle size and increase performance ) should take to migrate a React app to Preact?

**Comment by marvinhagemeister** [comment]
@jmarroyave It's in our upcoming Preact version titled X. It has loads of new features and many fixes to improve compatibility with react apps. We're currently in the release candidate phase (close before a final release) and you can try it out today via `npm install preact@next`. The remaining blocker for a release is getting the new devtools to work again.

**Comment by jmarroyave** [comment]
@marvinhagemeister will not be a version 9? 

By the way, i tried version 10 and got another issue that i report above about a "getChildContext from undefined" in the preact.module, should i open a new thread?

**Comment by marvinhagemeister** [comment]
We originally planned to do a 9 version with just the breaking changes to the internal `vnode` shape to make migration to 10 easier. But everybody jumped straight to 10 and so there doesn't seem to be any interest on putting effort into a release nobody will use :)

Yup, please open a new issue for that. It's a lot easier for us to keep track when one issue is about one issue only :+1:

**Comment by jmarroyave** [comment]
ok, thanks
