### ISSUE TITLE
Devtools error after release of new React DevTools

### ISSUE THREAD

**Issue by raulmmdev** [preactjs/preact#1873]
Yesterday React released a new React DevTools, https://reactjs.org/blog/2019/08/15/new-react-devtools.html
So now running my preact project with the new tools, i'm getting this error:
I'm  still using "preact": "^8.5.1",

`backend.js:9 Uncaught (in promise) TypeError: e.getPublicInstance is not a function
    at h (backend.js:9)
    at Object.receiveComponent (backend.js:9)
    at Object.e.<computed> [as receiveComponent] (backend.js:9)
    at Object.componentUpdated (devtools.js:262)
    at Object.preact.options.afterUpdate (devtools.js:380)
    at renderComponent (preact.umd.js:619)
    at rerender (preact.umd.js:104)`

Let me know if you need more information. Thanks

**Comment by JoviDeCroock** [comment]
This PR adds support for the new devtools in Preact X: https://github.com/preactjs/preact/pull/1549

For Preact 8 we haven't decided yet on how we'll tackle the issue yet but we are actively working on it.

**Comment by raulmmdev** [comment]
oh yes !!! my mistake i searched on issues but not on PR, everything under control

**Comment by JoviDeCroock** [comment]
No problem, let's keep this issue open so it's more clear on our radar. Since we still have to decide for Preact 8

**Comment by JoviDeCroock** [comment]
@raulmmdev you can use the devtools with Preact 8 like this for now: https://reactjs.org/blog/2019/08/15/new-react-devtools.html#how-do-i-get-the-old-version-back

**Comment by marvinhagemeister** [comment]
FYI: I'm currently working on bringing them into the 8.x release line :tada:

**Comment by marvinhagemeister** [comment]
We just released Preact 8.5.2 which fixes this :tada:
