### ISSUE TITLE
TypeError: e.getPublicInstance is not a function

### ISSUE THREAD

**Issue by r3wt** [preactjs/preact#1877]
As soon as the dev tools are open the preact app blows up. 
```js
backend.js:9 Uncaught TypeError: e.getPublicInstance is not a function
    at h (backend.js:9)
    at m (backend.js:9)
    at N (backend.js:9)
    at Object.flushInitialOperations (backend.js:9)
    at backend.js:9
    at <anonymous>:1:225
    at Array.map (<anonymous>)
    at Object.emit (<anonymous>:1:202)
    at i (backend.js:9)
    at backend.js:9
    at Map.forEach (<anonymous>)
    at g (backend.js:9)
    at e (backend.js:1)
```
I'm hoping someone can help me make sense of it. FWIW, dev tools stopped working with it as well. I haven't changed anything in my project since i initially got it working. project is using `preact`, `preact-compat`, `mobx-preact`,`preact/devtools`, `mobx`, `mobx-persist`, and `react-router-dom`.

**Comment by GeeLi** [comment]
This problem also bothers me

**Comment by GeeLi** [comment]
> This problem also bothers me

It seems like the problem of chrome extension ”React Developer Tools“

**Comment by marvinhagemeister** [comment]
We just released Preact 8.5.2 which fixes this :tada:

**Comment by r3wt** [comment]
@marvinhagemeister thank you for swift action. i know it must be difficult having to "react" to what arbitrary changes they make in react/react-devtools.

**Comment by timsco** [comment]
In case it happens to you, I had to turn off the extension and turn it back on after the update before the error went away. Thanks for the fix!
