### ISSUE TITLE
Many incorrect setState inside the constructor warnings being logged in latest git

### ISSUE THREAD

**Issue by mzealey** [preactjs/preact#1878]
Due to https://github.com/preactjs/preact/pull/1857 , latest git build is spewing out lots of warnings about "Calling "this.setState" inside the constructor of a component is a no-op and might be a bug in your application" in spite of me **not** using setState in the constructor. Many of these seem to happen when I call from `componentDidMount` but `render()` previously returned null.

**Comment by mzealey** [comment]
looking at the code this probably an issue whenever `render()` returns `null`.

**Comment by marvinhagemeister** [comment]
I can't reproduce the behavior you described. It works perfectly fine here with this snippet:

```js
class Foo extends Component {
	componentDidUpdate() {
		this.setState({});
	}
	render() {
		return null;
	}
}

const root = document.getElementById("root");
render(<Foo />, root);
// Render a second time to trigger componentDidUpdate
render(<Foo />, root);
```

Can you share the component that's causing the warning for you?

**Comment by mzealey** [comment]
Even that is enough to trigger the warning for me with a build from the latest git - perhaps related to merge of #1871 ??

**Comment by marvinhagemeister** [comment]
no

**Comment by sventschui** [comment]
I can not reproduce the behaviour you mentioned. Are you able to ship a reproduction case as a PR? I guess you could extend the demo for this.

**Comment by developit** [comment]
This could happen if using a minified version of Preact, but the unminified debug extension, since the hook names will not match. When using Preact from source, make sure to use all of the pieces from source (`preact` + `preact/debug`).

**Comment by mzealey** [comment]
ok this seems to have been resolved in the rc2 build at least thanks.
