### ISSUE TITLE
[10.0.0-rc1]  devtools error

### ISSUE THREAD

**Issue by Friph** [preactjs/preact#1885]
Hi there,

I upgraded my preact v8 project which i create with preact-boilerplate to Preact X.
If I import in index.js:
`if (process.env.NODE_ENV === 'development') {
  require('preact/debug');
}`

I tried to use the new upgrade docs, but I got this error:

![image](https://user-images.githubusercontent.com/31510303/63251054-3b158280-c26d-11e9-96ad-899f2b7c337d.png)

In Firefox devtools I got this error: 

![image](https://user-images.githubusercontent.com/31510303/63253126-89c51b80-c271-11e9-8850-24586734ebc6.png)

The devtools in chrome for react don't start.

Is this a bug ?

Best regards.

**Comment by marvinhagemeister** [comment]
Yup, the new devtools for Preact X are a work in progress. See #1549 .

**Comment by marvinhagemeister** [comment]
Let's leave this open until it's resolved (so that we don't get duplicate issues inn the future) :)

**Comment by marvinhagemeister** [comment]
Closing, as we have #1882 already, which is the same issue.
