### ISSUE TITLE
Compatibility issues with antd-mobile

### ISSUE THREAD

**Issue by sycreece** [preactjs/preact#1890]
When the Picker component in antd-mobile is used in preact, the picker container disappears when the picker sub-element is scrolled. 
There is no problem with React cooperation.
Prect version: 8.4.2

**Comment by cristianbote** [comment]
Hey @sycreece do you have a codesandbox with that issue? It'll be way quicker to help with your issue. Also, did you tries with preact x as well?

**Comment by 99414041** [comment]
[sand_box.zip](https://github.com/preactjs/preact/files/3526111/sand_box.zip)

**Comment by 99414041** [comment]
preact x no problem

**Comment by cristianbote** [comment]
Ok, so that basically means preact x will solve your issues. You should use that instead.
