### ISSUE TITLE
Scoped css with pure css string 

### ISSUE THREAD

**Issue by dntzhang** [preactjs/preact#1898]
I tried to add scoped CSS plug-in to preact. But I have a problem.  Can i get the component instance in  "vnode hook"  function?

```js
import { options } from 'preact'

options.vnode = (vnode, component) =>{
  //generate scoped attr by component

  //add attr to vnode
}
```

Thanks!
-dntzhang

**Comment by marvinhagemeister** [comment]
The `options.vnode` hook is executed as part of `h/createElement` and that runs way before any component instances are created.

There is `options.diffed(vnode)` which runs after the component is diffed and rendered. If that's too late for you we have a private hook that isn't made public yet as `__r` (=`_render`) which is called right before render.

Let me know if that's the one you were looking for. We're a bit conservative with making more public until there's a valid use case, because it increases maintenance area. That's why we love to know about yours :)

We haven't made that hook public yet, but you could use th

**Comment by dntzhang** [comment]
`h` runs in the render function, it's after any component instances are created in preact 8. I'm going to write the scoped CSS plug-in for preact 8 first.

**Comment by dntzhang** [comment]
I'll try options. _r of preact x right now. Thank you. I'll give you a conclusion later.

**Comment by dntzhang** [comment]
I need the hook. My plan:

```js
//to string loader
import cssString from './_xx.css'

let scopedAttr

options.__r = (vnode, component) => {

  //set scopedAttr

  // set css string to component.css
}

options.afterMount = (component) => {
  //get css string 

  //add scoped style to the head
}
```

**Comment by developit** [comment]
@dntzhang what if you used a Component instead of a vnode plugin? Then you could install the component:

```js
import { options } from 'preact';

const old = options.vnode;
options.vnode = vnode => {
  // <style scoped>css</style> ➡ <Style>css</Style>
  if (vnode.nodeName==='style' && vnode.attributes.scoped) {
    vnode.nodeName = Style;
  }
  if (old) old(vnode);
};

class Style extends Component {
  componentDidMount() {
    this.style = document.createElement('style');
    this.style.textContent = [].concat(props.children).join('\n');
    document.head.appendChild(this.style);
  }
  render() {
    return null;
  }
}
```

**Comment by dntzhang** [comment]
But how to add scoped attr to the dom.

Usage:

```jsx
<>
  <h1>I am red color</h1>
  <style scoped>
    {`h1 {
      color: red;
    }`}
  </style>
</>
```

Rendered:

```html
<head>
h1[_ss1]{
  color: red;
}
</head>

<h1 _ss1>I am red color</h1>
```

**Comment by dntzhang** [comment]
Pure css string is very useful. For example:

```js
function rpx(css) {
  return css.replace(/([1-9]\d*|0)(\.\d*)*rpx/g, (a, b) => {
    return (window.innerWidth * Number(b)) / 750 + 'px'
  })
}

<>
  <h1>I am red color</h1>
  <style scoped>
    {rpx(`h1 {
      color: 20rpx;
    }`)}
  </style>
</>
```

**Comment by developit** [comment]
@dntzhang technically there is a reference to the component instance associated with a given VNode, as a `._component` property (compressed in production as `.__c`). However, VNodes are created long before they can be associated with a component, so this is not a reliable method of associating vnodes and components during the `options.vnode` hook. The workaround is to store the component's associated VNode, then reference it dynamically in your `options.vnode` hook:

```js
import { options } from 'preact';

let componentNode;

// store a reference to the "current component" vnode
let oldDiff = options._diff || options.__b;
options._diff = options.__b = vnode => {
  componentNode = vnode;
  if (oldDiff) oldDiff(vnode);
};

// reset component reference at end of diffing:
let oldDiffed = options.diffed;
options.diffed = vnode => {
  if (componentNode === vnode) componentNode = null;
  if (oldDiffed) oldDiffed(vnode);
};

// our vnode hook looks up the associated component
let old = options.vnode;
options.vnode = vnode => {
  const component = componentNode && (componentNode._component || componentNode.__c);
  if (component) {
    // component is the component instance
    component.css;
    // example: assign component's unique CSS ID:
    (vnode.props || (vnode.props = {}))[component._styleId] = '';
  }
  if (old) old(vnode);
};
```

**Comment by marvinhagemeister** [comment]
@developit I wonder if we should make the `options.diff` hook public

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/tree/master/packages/preact-css

Done. Many thanks to @developit and @marvinhagemeister .
