### ISSUE TITLE
Trying to build 10.0.0-rc1

### ISSUE THREAD

**Issue by drewlesueur** [preactjs/preact#1902]
I am trying to build from tag `10.0.0-rc1` and I am getting what look like errors.
Here is the command I am running:
```
npm run build
```
And here are the last few lines of the output:
```
Using named and default exports together. Consumers of your bundle will have to use preactCompat['default'] to access the default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
Circular dependency: src/diff/index.js -> src/component.js -> src/diff/index.js
Circular dependency: src/diff/index.js -> src/diff/children.js -> src/diff/index.js
```

Should I expect a `dist` directory to be generated?

My end goal is to get a `preact.js` or `preact.min.js` file that I can use in a `<script>` tag.

```
/preact # node --version
v10.16.3
/preact # npm --version
6.9.0
```

Thank you!

**Comment by drewlesueur** [comment]
Looks like those are just warnings and should't affect the build.
https://github.com/preactjs/preact/issues/1507

Maybe I just don't know where to look for the build artifacts?

**Comment by marvinhagemeister** [comment]
The generated bundles reside in `dist/` for core, `hooks/dist/` for the hooks add-on, etc.

The files you are looking for are:
- `dist/preact.module.js` (esm bundle)
- `dist/preact.js`

The warnings you are seeing are just that: warnings. They can be ignored since rollup already figures out the right way to inline circular exports.

**Comment by drewlesueur** [comment]
Thank you. I looked for `dist` after building but didn't see it. I was running in alpine linux as root and didn't see any other error messages/warning. Maybe I am missing something else. I can try not as root.

For now I'll just `npm install preact@next` and try to get the builds out of there.

Thank you.
