### ISSUE TITLE
10.0.0-rc1 - Hook useEffect re-rendering with cloned nodes

### ISSUE THREAD

**Issue by bastienrobert** [preactjs/preact#1905]
I was using [Splitting](https://github.com/shshaw/Splitting/) in the useEffect hook, everything is working as expected on the first render. 

But when a state is updated on the parent component, the children is re-rendered and the node is cloned. It's a bit weird to explain, an example is better than a thousand words:

- Preact: https://codesandbox.io/s/green-silence-7h2ie
- React: https://codesandbox.io/s/blazing-hooks-i5uyi

As you can see, when you click on the "Trigger second" button, it updates a state and another "hello!" text is appearing under the first. This second text is a TextNode. Splitting doesn't seems to be the problem here: using React it's working and with `splitting.html` (so without useEffect) it's working using both Preact and React.

**Comment by sventschui** [comment]
The problem here is that splitting is manipulating the DOM. You are not supposed to manipulate the DOM when using React or preact.

Preacts diff algo can not handle changes you do to the DOM. You are best of using dangerouslySetInnerHTML as you do in your second example.
