### ISSUE TITLE
New DevTools doesn't work with `8.5.2`

### ISSUE THREAD

**Issue by flexdinesh** [preactjs/preact#1907]
Just upgraded the project to `8.5.2` and the new Dev Tools still doesn't work.

Dropping be to see if this is something missing on my side. I am receiving this error in the console.

```js
Uncaught (in promise) TypeError: Cannot read property '_topLevelWrapper' of undefined
```

**Comment by marvinhagemeister** [comment]
Duplicate of #1882.
