### ISSUE TITLE
Improve documentation of class vs className

### ISSUE THREAD

**Issue by ByteEater-pl** [preactjs/preact#1914]
from [Differences to React](https://preactjs.com/guide/v10/differences-to-react):
> With Preact we follow more closely the DOM specification supported by all major browsers.

The paradigm is that properties from VDOM are passed as DOM attributes, not content attributes. So, for example, you have value on select and textarea elements – those exist only in DOM, not in (X)HTML. Having class and for as special cases in addition to className and htmlFor may be a convenience feature (based on the assumption that no relevant standard will actually add class or for to DOM) but advertising it as closer to DOM specs is plainly confusing.

**Comment by marvinhagemeister** [comment]
Works fine for me in every browser:

```js
const div = document.createElement("div");
div.setAttribute("class", "foo");
console.log(div);
// Logs: <div class="foo" />

const label = document.createElement("label");
label.setAttribute("for", "some-input");
console.log(label);
// Logs: <label for="some-input" />
```

**Comment by ByteEater-pl** [comment]
try this:
`const textarea = document.createElement("textarea")
textarea.setAttribute("value", "foo")
console.log(textarea.value)`

**Comment by marvinhagemeister** [comment]
The `value` attribute is indeed weird for `textarea` elements, but it's there:

```js
const textarea = document.createElement("textarea")
textarea.value = "foo";
console.log(textarea.value)
```

If the element is appended to the DOM you can see the content changing. See [the spec](https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element) for a description of that behavior.
