### ISSUE TITLE
Hooks may fail when using in libraries if npm/yarn didn't dedupe properly

### ISSUE THREAD

**Issue by whitetrefoil** [preactjs/preact#1918]
For example I have a custom hook:
```tsx
import { useContext } from 'preact/hooks';
export function useStore() {
    return useContext(UnistoreContext);
}
```
Now I publish it as a npm package, say `my-use-store`.
Then I `npm install` it & require it from my main project.
For whatever reason, npm/yarn didn't dedupe `preact`, now there are 2 different `preact` in `node_modules`:
1. `node_modules/preact`
2. `node_modules/my-use-store/node_modules/preact`

Then...
```tsx
import { useStore } from 'my-use-store';
export default () => {
    const store = useStore(); // Error!!!
};
```

Did some trace and found that's because only `currentComponent = vnode._component` in `node_modules/preact/hooks` has been executed, but `useStore` called `node_modules/my-use-store/node_modules/preact/hooks#useContext`, while `currentComponent` there was `undefined`.

**Comment by JoviDeCroock** [comment]
The safest way to avoid that is to make sure you add Preact as a peerDependency and not as a Dependency. Like this: https://github.com/preactjs/preact-router/blob/master/package.json#L48

**Comment by marvinhagemeister** [comment]
@JoviDeCroock is correct. The use cases described in the original post is the exact reason `peerDependencies` were invented and added to npm/yarn👍
