### ISSUE TITLE
Typings: in PureComponent, generic types of state and props aren't passed to Component

### ISSUE THREAD

**Issue by amelekhin** [preactjs/preact#1919]
In compat typings, generic types for state and props aren't passed from `PureComponent` to the `Component` class it extends. It makes impossible to use `PureComponent` from `preact/compat` directly in the code because it's impossible to define interfaces for props and state and TS compiler cannot resolve types.

According to the typings in `@types/react`, `P` and `S` are passed down to `Component`:

```js
class PureComponent<P = {}, S = {}, SS = any> extends Component<P, S, SS> { }
```

Perhaps, we should pass them down as well?

**Comment by JoviDeCroock** [comment]
Fixed by https://github.com/preactjs/preact/pull/1920
