### ISSUE TITLE
audio tag not support volume attribute in typescripts

### ISSUE THREAD

**Issue by CarmeloXue** [preactjs/preact#1934]
I use 10.0.0-rc.1, and I want to use <audio {...someProps} volume={0.1}></audio>.
But in ts, I got an error :
Property 'volume' does not exist on type 'HTMLAttributes'.
Then I found in index.d.ts file where HTMLAttributes just don't include this attribute.
Is there any chance to add this?

**Comment by jessicabyrne** [comment]
I'll tackle this beginner-friendly one.
