### ISSUE TITLE
preact@10.0.0-rc.3: Radium.StyleRoot throws an error

### ISSUE THREAD

**Issue by christianpv** [preactjs/preact#1936]
Hi, I'm looking to replace react by using preact with compat mode but facing an issue due to Radium.StyleRoot throwing an error when using preact. Initially, I thought it was an issue with preact-render-to-string but I removed all dependencies and the problem persist when using preact to render in the browser.

You can reproduce by running the following commands:
1. `git clone https://github.com/christianpv/preact-radium-styleroot-bug`
2. `cd ./preact-radium-styleroot-bug && npm install && npm run dev:preact`.
3. `open http://localhost:8080` and check the console.

The error that I see is `
Uncaught TypeError: Cannot read property '_radiumConfig' of undefined
    at _getStyleKeeper (style-root.js:22)
    at RadiumEnhancer.StyleRoot (style-root.js:37)
    at RadiumEnhancer.ComposedComponent (enhancer.js:151)
    at new RadiumEnhancer (enhancer.js:164)
    at $ (preact.module.js:1)
    at preact.module.js:1
    at x (preact.module.js:1)
    at b (preact.module.js:1)
    at $ (preact.module.js:1)
    at preact.module.js:1
`

You can run `npm run dev:react` to see that it works correctly with react dependencies.

I was trying to look into a possible solution but it might be possible that someone is already working on it. Please let me know if I can help somehow or point me in the right direction so that I can try to create a PR to fix it.

**Comment by JoviDeCroock** [comment]
It's quite odd. I've tried to reproduce this with exactly your code and this works out of the box https://codesandbox.io/s/reach-router-preact-nw6su

Is there a way to make the sandbox fail? Else I would blame it on a radium version that's failing

**Comment by marvinhagemeister** [comment]
Updating it to the latest version of `radium` (0.26.0) fixes this issue :tada:
