### ISSUE TITLE
preact@10.0.0-rc.3 PureComponent doesnt skip rerendering, depending on the repl

### ISSUE THREAD

**Issue by katywings** [preactjs/preact#1949]
IS: The `Random` component rerenders on every parent render even tough no props have changed.
SHOULD: It should only rerender when the props actually change.

Component:
```jsx
class Random extends PureComponent {
  render() {
    return <span>{Math.random()}</span>;
  }
}
```

Edit: Now this is getting weird, if I copy the same code from Demo 1 to https://preactjs.com/repl there the PureComponent works o.O. Any ideas why?

Demo 1 (Ticks with hooks): https://codesandbox.io/s/loving-tree-l9t99
Demo 2 (Ticks with setState): https://codesandbox.io/s/busy-sky-6lw6j

**Comment by JoviDeCroock** [comment]
Hey, 

Thanks for the nice issue report with reproductions, these have helped tremendously in identifying this issue.
The issue is due to `babel-plugin-jsx-sourcemaps` the PR will fix that issue.

**Comment by katywings** [comment]
Thanks a lot for fixing this so quickly 😃
