### ISSUE TITLE
preact@10.0.0-rc.3 + emotion/styled rendering issue

### ISSUE THREAD

**Issue by animecyc** [preactjs/preact#1952]
I'm testing a few internal libraries Preact X with Emotion styled-components and am running into an issue where the emotion styled components are not re-rendering as expected. Here is a code-sandbox replicating the issue: https://codesandbox.io/s/preact-x-emotion-lydz8?fontsize=14

**Comment by JoviDeCroock** [comment]
Hey, that should be resolved with the next release, this should work in rc.1 and we have fixed that in master

**Comment by animecyc** [comment]
Thats great to hear. Was that fixed recently? Can you link me to the commit, curious as to what the issue/regression was.

**Comment by JoviDeCroock** [comment]
Here you go: https://github.com/preactjs/preact/pull/1931

**Comment by animecyc** [comment]
Much appreciated! I'll close this down.
