### ISSUE TITLE
styled-components ref type

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact#1953]
Got this bug report via email, so I'm pasting it here:

> (...)I've just got a quick question regarding the index.d.ts file of Preact, more exactly this line. Is there any reason why it's not ref?: Ref<any> | null; instead? I'm asking this since I'm having some troubles with setting up some styled components libraries with Typescript and the latest Preact rc, and adding the ? to this line fixed it. (...)

**Comment by 38elements** [comment]
> (...)I've just got a quick question regarding the index.d.ts file of Preact, more exactly this line. Is there any reason why it's not ref?: Ref | null; instead? I'm asking this since I'm having some troubles with setting up some styled components libraries with Typescript and the latest Preact rc, and adding the ? to this line fixed it. (...)

I think the sender of the email should show the detailed content of "some troubles".

**Comment by xiel** [comment]
I'm also getting a similar error from the same type of ref when I want to use `react-spring` with preact.

`<animated.div style={animatedStyles} />`

**Property 'ref' is missing in type 'ReactElement'**
```
    Error:Error:line (117)TS2605: JSX element type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>' is not a constructor function for JSX elements.
  Property 'ref' is missing in type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>' but required in type 'Element'.
```

when I manually change (preact/src/index.d.ts)

```
interface VNode<P = {}> {
  ...
  ref: Ref<any> | null;
  ...
}
```

to be
`ref?: Ref<any> | null;`
the errors go away.

From what I see in the React.Element types, ref should be defined optional.

**Comment by xiel** [comment]
Was broken with this PR it seems: https://github.com/preactjs/preact/pull/1447

**Comment by victordidenko** [comment]
Still not working with many libraries: [react-spring](https://www.react-spring.io/), [astroturf](https://github.com/4Catalyzer/astroturf), [react-fontawesome](https://github.com/FortAwesome/react-fontawesome)

<img width="853" alt="Screenshot 2019-11-20 at 11 57 07" src="https://user-images.githubusercontent.com/15016227/69224364-75086480-0b8d-11ea-8388-7693e5a27649.png">

**Comment by zaninime** [comment]
I still have this issue with `urql` and more libraries.
