### ISSUE TITLE
render differs from react

### ISSUE THREAD

**Issue by dy** [preactjs/preact#1954]
Question/bug report.
There's discrepancy of preact and react `render`.
If we have simple example ([see codesandbox](https://codesandbox.io/s/dazzling-bas-umm5p?fontsize=14))
```js
import { render } from "preact";

let el = document.getElementById("root");
el.innerHTML = "<a>x</a>";

render(<div>y</div>, root);
```
Preact appends `<div>y</div>` to `root` (unexpected!), whereas react mutates it.

Maybe related to https://github.com/preactjs/preact/pull/1781 - same issue is with portals - is that expected that preact keeps existing html?

**Comment by JoviDeCroock** [comment]
It's not related to that, for full react compat you should do the following: https://codesandbox.io/s/gifted-pike-ktv4t

Here we import form compat, a layer meant to ensure compatability with React.

**Comment by marvinhagemeister** [comment]
This is resolved in the upcoming version that should come out really soon. Preact 8 works differently, because it has a third argument for the `render` function that gives you the behavior of React.

```jsx
render(<div>y</div>, root, root.firstChild);
```
