### ISSUE TITLE
Element props in preact X

### ISSUE THREAD

**Issue by dy** [preactjs/preact#1956]
```js
import { render } from "preact";

let root = document.createElement("div");

render(<div x={1} />, root);
root.firstChild.x = undefined
console.log(root.firstChild.x);

render(<div x={2} />, root);
console.log(root.firstChild.x);

// preact 8: undefined, undefined
// preact X: undefined, 2
// react: undefined, undefined
```

Is that intended side-effect of preact X? Can that be relied on?

**Comment by marvinhagemeister** [comment]
Yes, but this is meant mainly to be able to support custom elements where we one can't really detect if the property exists or not. And due to our size constraints we don't ship with any whitelist or blacklist for various properties and trust that users know which ones to set.
