### ISSUE TITLE
preact X type error

### ISSUE THREAD

**Issue by Gregorein** [preactjs/preact#1959]
I'm getting `undefined is not an object (evaluating 'h.__H')` after building with rc3, 

```[Error] TypeError: undefined is not an object (evaluating 'h.__H')
	o (bundle.269f6.js:1:8826)
	i (bundle.269f6.js:1:8957)
	O (bundle.269f6.js:1:8604)
	O (bundle.269f6.js:1:16581)
	w (bundle.269f6.js:1:16048)
	k (bundle.269f6.js:1:17676)
	_ (bundle.269f6.js:1:13235)
	u (bundle.269f6.js:1:19075)
	pwNi (bundle.269f6.js:1:19106)
	e (bundle.269f6.js:1:106)
	(anonymous function) (bundle.269f6.js:1:1351)
	Global Code (bundle.269f6.js:1:1364)
```

what am I overlooking?

**Comment by JoviDeCroock** [comment]
We’ll need some narrowed down details since this could have several causes

**Comment by Gregorein** [comment]
I built a site with `preact build --no-prerender --template src/template.html`, using project structure similar to one `preact-cli`  ejects.

used dependecies are :
```  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "classnames": "^2.2.5",
    "eslint": "^5.8.0",
    "identity-obj-proxy": "^3.0.0",
    "if-env": "^1.0.0",
    "node-sass": "^4.12.0",
    "preact-cli": "^2.1.0",
    "preact-render-spy": "^1.2.1",
    "sass-loader": "^6.0.7"
  },
  "dependencies": {
    "preact": "^10.0.0-rc.3",
    "preact-router": "^3.0.1",
    "smooth-scroll": "^12.1.5"
  }
```

the error above occurs in `o` function of `hooks.module.js`

**Comment by JoviDeCroock** [comment]
Could you try updating preact-cli to the latest version 3.0.0-rc.5

**Comment by maltium** [comment]
Having the same or a similar issue ```Uncaught (in promise) TypeError: Cannot read property '__H' of undefined```.

Not using preact-cli, but instead a custom webpack config with TypeScript.

```
import { h } from 'preact';
import { useState } from 'preact/hooks';

export function TestComponent(props) {
  const [num, setNum] = useState(0);  // commenting this fixes the error
  return <div/>;
}
```

If the line containing the ```useState``` call is removed, the error won't occur. Other than hooks, the rest of Preact is behaving normally.

**Comment by developit** [comment]
The error is caused by using `preact-cli` version 2. Update to 3.0 to fix:

```sh
npm i -D preact-cli@rc
```

**Comment by maltium** [comment]
@developit I checked an there definitely are no copies of Preact 8 in node_modules.

I've created a repo that reproduces the issue https://github.com/maltium/repro-preact-hook

**Comment by JoviDeCroock** [comment]
When I look at the output of your bundle it's pointing to different bundles of Preact (Preact seems to be bundled in multiple times)

Adding: ```  resolve: {
    // Add `.ts` and `.tsx` as a resolvable extension.
    extensions: [".ts", ".js"],
    alias: {
      preact: path.resolve(__dirname, 'node_modules', 'preact'),
      'preact/hooks': path.resolve(__dirname, 'node_modules', 'preact', 'hooks'),
    }
  },```

To your webpack.config.js does not only reduce bundle size it also removes the error, note that a setup like this would fail with any framework.
