### ISSUE TITLE
upload preact/hooks to cdnjs

### ISSUE THREAD

**Issue by dvorakroth** [preactjs/preact#1962]
hi! i couldn't find preact/hooks on cdnjs for some reason?

was i doing something wrong and i just couldn't find it, or is it really missing?

thanks :3

**Comment by MaxMilton** [comment]
Looks like `preact/hooks` and the other addons (`preact/compat`, `preact/test-utils`, and `preact/debug`) are not on cdnjs: <https://cdnjs.com/libraries/preact/10.0.0-rc.3>. Additionally, cdnjs is missing Preact version `10.0.0-rc4` and the freshly released `10.0.0`.

That said, [in the docs](https://preactjs.com/guide/getting-started) the officially recommended CDN is jsdelivr. jsDelivr fetches the packages direct from the NPM registry and so is always up to date. It also includes all the files distrubuted in the NPM package (including all add ons).

Personally I find jsDelivr to have better overall performance too, so I recommend switching to it instead.

**Comment by dvorakroth** [comment]
ok but can this be fixed tho

**Comment by JoviDeCroock** [comment]
Then you'll have to wait until cdnjs decides to update their records. For now unpkg and jsdelivr are more reliable since these update with every request.

**Comment by JoviDeCroock** [comment]
You can use `unpkg` for now, the usage can be found here: https://github.com/JoviDeCroock/Vanilla-Preact-Application/blob/master/src/modules/home/index.js
