### ISSUE TITLE
preact/compat 10: style doesn't get updated.

### ISSUE THREAD

**Issue by ritz078** [preactjs/preact#1975]
Hi, 

Great work on preact X. Congratulations on the release.

I am facing an issue where the style doesn't get updated even when the corresponding variable gets changed.

My code looks like

```js
const dimensions = useWindowResize(visualizerRef, {
    width: 1100,
    height: 400
  });

const {width, height} = dimensions;
console.log(dimensions)

return <canvas
      width={width}
      height={height}
      style={dimensions}
      ref={canvasRef}
/>
```

Here's the log:

<img width="338" alt="Screenshot 2019-10-04 at 3 13 02 AM" src="https://user-images.githubusercontent.com/5389035/66166426-ed09e200-e654-11e9-8dbb-14648b8490f0.png">

Since `dimensions` has updated, the canvas' style should also update but even after this my HTML looks like:

<img width="1073" alt="Screenshot 2019-10-04 at 3 05 57 AM" src="https://user-images.githubusercontent.com/5389035/66166466-0b6fdd80-e655-11e9-950a-57ad82aadc83.png">

The `height` and `width` attribute have updated but style hasn't.

You can test this on this PR: https://github.com/ritz078/raaga/pull/75

**Comment by JoviDeCroock** [comment]
Very odd but when I do a test like this:

```
		it.only('should work with statefull styles', () => {
			class App extends Component {
				constructor(props) {
					super(props);
					this.state = { width: 1, height: 1 };
				}

				componentDidUpdate() {
					if (this.state.width !== this.props.dimensions.width)
						// eslint-disable-next-line
						this.setState(this.props.dimensions);
				}

				render() {
					return (
						<canvas style={this.state} />
					);
				}
			}

			render(<App />, scratch);
			console.log(scratch.firstChild.style.width);

			render(<App dimensions={{ width: 2, height: 2 }} />, scratch);
			rerender();
			console.log(scratch.firstChild.style.width);
		});
```

It seems to work correctly

**Comment by ritz078** [comment]
In case it helps, the whole code can be found [here](https://github.com/ritz078/raaga/blob/68c9149f35b214fde6c1c8aa95a6c62fb4fbc054/components/Visualizer/Visualizer.tsx). It's using custom hooks.

One more issue I found was that there are times when I see 2 `canvas` elements after rerender

**Comment by marvinhagemeister** [comment]
@ritz078 I just cloned the repo, but I'm unable to run the app due to the following error:

```txt
ModuleNotFoundError: Module not found: Error: Can't resolve '../../midi.json' in '/home/marvinh/dev/test/raaga/components/TrackList'
```

**Comment by ritz078** [comment]
@marvinhagemeister 

Run the below commands in that order:
```
yarn build:midi
yarn build:icons
yarn dev
```

Will improve this later. This should get you going.

**Comment by marvinhagemeister** [comment]
@ritz078 Thanks for the instruction. With these I was able to start the app.

I wasted a good 10 min on figuring out how to start it correctly as by default the app is using `react` in `master` (which is fine, but took me way too long to figure out) :/

After getting to that point I can't confirm the issue. I checked with both Firefox and Chrome and the `style` attribute is correctly updated. To test this I resized the browser window and checked if the console logs match the values in the `style` attribute.

So I guess there is nothing to do for us here :tada:

**Comment by ritz078** [comment]
Hey @marvinhagemeister ,
I am really sorry that your time was wasted. It's still in development and readme isn't upto the mark. 
I had mentioned in the description that you should test in on this PR: https://github.com/ritz078/raaga/pull/75

There itself in the description of that PR I had mentioned the steps to run the server. Did you test that PR or the `master`? only the PR uses preact-compat. In case you were not able to find the issue, I will create a video and post it here.

Again, sorry for your time. I will make sure I update the main readme too and post my findings here. Thanks for the help. :)

**Comment by marvinhagemeister** [comment]
@ritz078 No worries, it's also a bit on me as I should've checked the branch the link lead to. Even when building the `preact` branch, I'm still not able to reproduce the described issue. The style attribute is correctly updated for me.
