### ISSUE TITLE
10.0.0 break context update with mobx.toJs usage

### ISSUE THREAD

**Issue by Nuzsk** [preactjs/preact#1983]
After updating 10.0.0 child components can't observe store passed by context when mobx.toJs used in their parent.

explanation of example:
1. MobX store passed into Context.Provider value in App component
2. contenxt.store.count serialized & printed in Test component
3. contenxt.store.count printed in Counter component
4. user click button and compare clicks/raw value on your screen
5. the values are the same for 10.0.0-rc.1 and differ for 10.0.0 release

error reproduction (cache cleaning may be required):
rc1: https://nuzsk.github.io/preact-x-consumer-bug/10.0.0-rc.1/dist/index.html
rel: https://nuzsk.github.io/preact-x-consumer-bug/10.0.0/dist/index.html
source:
https://github.com/Nuzsk/preact-x-consumer-bug

note: removing toJs allows the child component to update

**Comment by marvinhagemeister** [comment]
Awesome, thanks a bunch for the repro cases and the source :+1: With it I was able to narrow down what's causing it and got a fix nearly ready :tada:
