### ISSUE TITLE
Consider exporting shallowDiffers in compat

### ISSUE THREAD

**Issue by katywings** [preactjs/preact#1985]
I wanted to ask you what you think about exporting the shallowDiffers function from compat: 
https://github.com/preactjs/preact/blob/master/compat/src/index.js#L305

My usecase is a component that is very similar to PureComponent but has some extra sideeffect logic in addition to the props/state shallowDiffers. Because of the sideEffects I dont think its optimal to directly extend on PureComponent, so a shallowDiffers export would be super handy :).

Thanks for the consideration and your feedback in advance.

**Comment by katywings** [comment]
P.S. currently I solve it with a very nasty trick:
```js
MyComponent.prototype._shallowDiffers = PureComponent.prototype.shouldComponentUpdate
```
😅

**Comment by marvinhagemeister** [comment]
Currently going through some older issues. In the end we settled on not exporting it to keep the public API surface small. If we expose `shallowDiffers` we'll need to keep maintaining it, regardless of future updates. The workaround described above is fantastic and if that isn't an option one can copy the code over 👍
