### ISSUE TITLE
Reused html nodes retain attributes

### ISSUE THREAD

**Issue by kkurola** [preactjs/preact#1986]
It seems that the issue fixed in #677 is back in Preact 10.0.0. When reusing a node already in DOM, Preact doesn't remove the original attributes. This becomes apparent for example when your server returned placeholder html has classes that are missing from what Preact rendered and those classes aren't removed when some of those nodes are reused.

Here's a simple pen to demonstrate: https://codepen.io/kurola/pen/YzzPNEp

## Expected behaviour
Diff should remove attributes when reusing nodes that weren't generated by h.

## Actual behaviour
It preserves removed attributes when the merged node comes from the DOM.

**Comment by JoviDeCroock** [comment]
This is fixed in master and will be in the next release, thank you so much for the accurate reproduction!
