### ISSUE TITLE
Material UI 4.0.0 PopOver and Selects not working. lastFocus.current is null

### ISSUE THREAD

**Issue by pinkfloydsito** [preactjs/preact#1993]
> 
> "Material UI": 4.0.0,
>     "preact": "^10.0.0",
>     "preact-compat": "^3.19.0",
>     "react": "^16.8.5"
> 

Currently whenever I use the Popover from material UI or its selects trapfocus throws an exception when the modal is closed. Is there any workaround for this?
```
TypeError: "lastFocus.current is null"
    TrapFocus TrapFocus.js:98
    Preact 13
    safeSetState Transition.js:318
    performExit Transition.js:297
    nextCallback Transition.js:330
    setTimeout handler*addEndListener Grow.js:116
    onTransitionEnd Transition.js:351
    performExit Transition.js:296
    nextCallback Transition.js:330
    Preact 5
    update SelectInput.js:114
    handleItemClick SelectInput.js:131
    Preact 31
index.js:1446
    e index.js:1446
    componentDidCatch ErrorBoundary.js:10
    Preact 9
    safeSetState Transition.js:318
    performExit Transition.js:297
    nextCallback Transition.js:330
    addEndListener Grow.js:116
    onTransitionEnd Transition.js:351
    performExit Transition.js:296
    nextCallback Transition.js:330
    Preact 5
    update SelectInput.js:114
    handleItemClick SelectInput.js:131
    Preact 31
```

![image](https://user-images.githubusercontent.com/8844096/66506447-f8b13a80-ea92-11e9-93f1-c914e00fc978.png)
After I lose focus from the Select the exception is thrown.

**Comment by JoviDeCroock** [comment]
Hey,

Are you using that `preact-compat` dependency? You should be reffing to `preact/compat` now. I'll look into how that component works and report back.

**Comment by PinkFLoyd92** [comment]
Yes, I am using it.

![image](https://user-images.githubusercontent.com/8844096/66507254-77f33e00-ea94-11e9-8b59-fdb12069519b.png)

**Comment by JoviDeCroock** [comment]
After testing this it looks like it works in latest Preact, if this is causing issues for you please reopen this issue with a reproduction.
