### ISSUE TITLE
input tag in preact is not accepting the normal input functions like oninvalid and oninput which are generally accepted in react

### ISSUE THREAD

**Issue by jayaramasaipavanmanda** [preactjs/preact#2000]
<input className={style.input} type="text" required name={key} oninvalid="setCustomValidity('Cusotm Alert 1');"/> giving me an error

(property) JSX.IntrinsicElements.input: JSX.HTMLAttributes
Type '{ className: any; type: string; required: true; name: string; oninvalid: string; }' is not assignable to type 'HTMLAttributes'.
  Property 'oninvalid' does not exist on type 'HTMLAttributes'.

where as in react it shows like this

JSX.IntrinsicElements.input: React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>

**Comment by JoviDeCroock** [comment]
It should be onInvalid and onInput, also like React. We document the listeners we attach through React now how they are named on the dom-element itself.

**Comment by marvinhagemeister** [comment]
I think original post is just running into a type issue with our definitions. Shouldn't be too hard to fix.

**Comment by jayaramasaipavanmanda** [comment]
When can I expect this fix, since I need a solution urgent. Could you please let me know if there is any alternative or this?

**Comment by jayaramasaipavanmanda** [comment]
When can we expect these fixes? Could you please let me know is there any alternative for this.

**Comment by JoviDeCroock** [comment]
Well onInvalid is present so that should work, no? It should just be adding something to the type definitions in `jsx.d.ts` you can try if you want.

**Comment by jayaramasaipavanmanda** [comment]
Yeah used onInvalid but while running tests using jest it is giving an error `Property 'onInvalid' does not exist on type 'HTMLAttributes'.` let me know if you have any solution for this. Thanks.

**Comment by JoviDeCroock** [comment]
It's present in the [`jsx`](https://github.com/preactjs/preact/blob/master/src/jsx.d.ts#L337) typings so maybe there's something wrong in your jest config if it works while normally devving on your app?

**Comment by jayaramasaipavanmanda** [comment]
how can I add onInvalid to HTMLAttributes in preact.d.ts , since the error refers to it actually.

**Comment by JoviDeCroock** [comment]
that's just exporting jsx.d.ts

**Comment by jayaramasaipavanmanda** [comment]
I couldn't find any file naming jsx.d.ts

**Comment by JoviDeCroock** [comment]
Yea but that's compiled... Look into source code

**Comment by JoviDeCroock** [comment]
These events should be available https://www.runpkg.com/?preact@10.2.1/src/jsx.d.ts#438

Feel free to reopen if it's not the case for you, maybe something goofs up in TS
