### ISSUE TITLE
Render documentation incorrectly mentions return value

### ISSUE THREAD

**Issue by richardhinkamp** [preactjs/preact#2002]
The documentation for [render()](https://preactjs.com/guide/v10/api-reference#render) says:

>  Render a Preact component into the containerNode DOM node. Returns a reference to the rendered DOM node.

In Preact X `render()` does not return anything anymore?

**Comment by JoviDeCroock** [comment]
Yes

**Comment by richardhinkamp** [comment]
Second issue with the docs is the `replaceNode`. 
The docs state `<div>foo</div>` will be inside `<div id="target">`, but it will replace the div (and keep the id?), see https://codepen.io/rhinkamp/pen/MWWaMVQ
So should it read?
```
// After render:
// <div id="container">
//   <div>bar</div>
//   <div id="target">foo</div>
// </div>
```
