### ISSUE TITLE
SSR doc, error page

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [preactjs/preact#2007]
Hi, I have error page title, https://preactjs.com/guide/v10/server-side-rendering/#app
'Yikes, looks like that page vanished.'
Or this old page for SSR? 

![изображение](https://user-images.githubusercontent.com/29048318/66703079-50f86e80-ed17-11e9-948a-3047bea32992.png)

**Comment by Kanaye** [comment]
Hi @TchernyavskyDaniil.
For me the page works fine, might be a service worker issue.
Can you force reload the page (`[ctrl] + [shift] + [r]`) or try an other browser ?

**Comment by TchernyavskyDaniil** [comment]
> Hi @TchernyavskyDaniil.
> For me the page works fine, might be a service worker issue.
> Can you force reload the page (`[ctrl] + [shift] + [r]`) or try an other browser ?

Yep, i tried
So, I fixed this problem with VPN, funny.
