### ISSUE TITLE
root attributes are not merged (10.0.1)

### ISSUE THREAD

**Issue by shirotech** [preactjs/preact#2022]
I've upgraded from 10.0.0 -> 10.0.1 and noticed a slight difference in the behaviour of re-using the existing root element.

i.e.

```html
<div id="root" style="display: block !important"></div>
```

When I mount this with:

```jsx
render(<div style={{opacity: 1}}/>, document.body, document.getElementById('root'));
```

The expected behaviour is it should output:

```html
<div id="root" style="display: block !important; opacity: 1"></div>
```

Now the existing styles are not inherited.

```html
<div id="root" style="opacity: 1"></div>
```

Was wondering if this is now the new behaviour? Or might be a regression?

**Comment by marvinhagemeister** [comment]
Thanks for reporting it. This was indeed a bug that was fixed with #1970 . The `replaceNode` argument should replace nodes and not keep old attributes or anything around. The same is true for nodes that are somewhere down the tree. But for that the PR is still in progress (#1965).
