### ISSUE TITLE
Preact 10.0.0 and vulnerabilities with react-modules

### ISSUE THREAD

**Issue by mweissen** [preactjs/preact#2027]
I want to learn more about how to use react-modules in preact  and I have uses these instructions: [react-google-authorize](https://www.npmjs.com/package/react-google-authorize). But I always get messages like "found 43 vulnerabilies. That is very disturbing.
These are the steps:
```
preact create default pwa5
cd pwa5
npm i react-google-authorize
```
And I get:
```
C:\pwa2b\pwa5>npm i react-google-authorize
npm WARN jest-preset-preact@1.0.0 requires a peer of jest@24.x but none is installed. You must install peer dependencies yourself.
npm WARN react-google-authorize@1.0.4 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-authorize@1.0.4 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ react-google-authorize@1.0.4
added 4 packages from 24 contributors and audited 34333 packages in 18.078s
found 43 vulnerabilities (40 low, 2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
`npm audit fix --force` does not solve the problem. I have tried it with some other react modules - same result. 

I have added react and react-dom, but I think a `preact build` includes react and creates a very big app. (I am not sure.)

What is wrong? Can I ignore all _WARN_-messages? And what's about the 
_vulnerabilities_ ?

**Comment by marvinhagemeister** [comment]
The `default` template saw some updates this morning. Those should be resolved. The warnings can be ignored as npm is not aware of how packages are aliased at build time.
