### ISSUE TITLE
If shouldComponentUpdate return false, the callback in setState(..., callback) will not be executed.

### ISSUE THREAD

**Issue by sanmaopep** [preactjs/preact#2051]
If shouldComponentUpdate return false, the callback in setState(..., callback) will not be executed until next shouldComponentUpdate return true.
```js

state = false;

shouldComponentUpdate(nextProps, nextState){
    return this.state !== nextState;
}

someFunctionInComponent(){
    setState(false, ()=> {console.log('callback 1')}); // nothing happened
    setTimeOut(()=>{
        // after 2 seconds, log callback1 and callback2 in the same time
        setState(true, ()=> {console.log('callback 2')});
    }, 2000);
}

```
It seems that the callback will be run after the render function is called, but what if the render function is not called since shouldComponentUpdate return false?

**Comment by andrewiggins** [comment]
Hi @sanmaopep! Thanks for the bug report! Just wanted to ack that I saw this and am thinking about what we can do to resolve it... Just need some time to explore :)

**Comment by andrewiggins** [comment]
And thinking out loud, what is the expectation for a functional component that uses `const [state, setState] = useState({})` and calls `setState` but is wrapped in `preact.memo`? I assume that the component would still rerender even though it is wrapped in `preact.memo` cuz `preact.memo` only looks at `props` and not `state`...
