### ISSUE TITLE
Functional refs behave different from React

### ISSUE THREAD

**Issue by mindplay-dk** [preactjs/preact#2052]
I may have discovered a subtle deviation from React's behavior regarding the dispatch of functional refs.

That is, something like `<p ref={ p => doSomething(p) }>` seems to behave different during updates.

I've created an sandbox that prints out the sequence of events:

https://codesandbox.io/s/happy-morning-jyu67

You can toggle between `react` and `preact` by un/commenting the imports at the top of the script.

If I copy the console output from `react` and `preact` and put them side-by-side (and some empty lines to show the missing events) it looks like this:

![image](https://user-images.githubusercontent.com/103348/67670685-bc2b7d00-f974-11e9-8e12-9ba02428b9d4.png)

The big question for me here is, why is `react` dispatching the `ref` callbacks with `null` for elements that *weren't* removed during the update?

Even if I add `key` attributes to these elements, I get the `null` events.

Now, according to the [React docs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs), it seems to me maybe `preact` is actually right on this point:

> React will call the ref callback with the DOM element when the component mounts, and call it with `null` when it unmounts.

Of course, this doesn't say it *won't* call the ref callback with `null` between updates, but it certainly seems to imply so?

I went back as far as `react` `16.8.0`, and it behaves like this in every release - unfortunately, older versions than that refuse to load in CodeSandbox, so I can't say if the behavior was always like this.

I've tested with `preact` and `preact/compat`, both of which behave the same.

Anyhow, bottom line is, if people rely on callbacks with `null` as a means of cleaning up side-effects, this could definitely lead to problems, right? (I suspect it might account for some of the reported incompatibilities with various libraries intended for React, but I haven't looked at those reports/libraries in-depth to see if they use functional refs.)

**Comment by marvinhagemeister** [comment]
That's very interesting! I'm with you, that this looks like a bug in `react`. The elements aren't unmounted so it seems wrong to call `ref` with `null`.

cc @sebmarkbage @gaearon @acdlite

**Comment by sebmarkbage** [comment]
It’s intensional because it’s a new function identity we don’t know if it’s a different ref all together.

```
<p ref={
  c ? n => doSomething(n)
  : n => doSomethingElse(n)
} />
```

If it’s the same referential identity it’s not called.

Seems like Preact wouldn’t handle changes to the ref callback without doing this?

**Comment by JoviDeCroock** [comment]
Hey @sebmarkbage 

I've double-checked this with our test-suite

```
	it('should not call stale refs', () => {
		let ref = spy('ref');
		let ref2 = spy('ref2');
		let bool = true;
		const App = () => <div ref={bool ? ref : ref2} />;

		render(<App />, scratch);
		expect(ref).to.have.been.calledOnce.and.calledWith(scratch.firstChild);

		bool = false;
		render(<App />, scratch);
		expect(ref2).to.have.been.calledOnce.and.calledWith(scratch.firstChild);
	});
```

This results in a correct case or am I misunderstanding this?

**Comment by sebmarkbage** [comment]
@JoviDeCroock 

After the second render, you should probably assert that `ref` has been called again with `null`.

Imagine patterns like this 

```
let ref = useRef(null);
useEffect(() => {
  if (ref.current) doSomething(ref.current);
});
return <div ref={bool ? n => { ref.current = n; } : () => {}} />;
```

You want to ensure that the current state of the mutable storage doesn't leave the DOM node in there forever.

**Comment by marvinhagemeister** [comment]
@sebmarkbage thank you so much for chiming in :+1: That makes sense, I hadn't thought of referential equality :+1: 

@JoviDeCroock Yeah it works for us, but in `react` it will call the previous `ref` function with `null` to signal that it's reached the "end of life".

**Comment by mindplay-dk** [comment]
Yeah, React's behavior makes sense to me now - thanks everyone for looking into this 🙂👍
