### ISSUE TITLE
Preact debug over-stating `Can't call "this.setState" on an unmounted component. `

### ISSUE THREAD

**Issue by pmkroeker** [preactjs/preact#2056]
I'm not sure if this is actually and issue of if its an implementation error on my part. I have a functional component that has an open state trigger.

```tsx
interface AccordianProps {
  class?: string;
  label: string;
  children: ComponentChildren;
}

interface AccordianState {
  isOpen: boolean;
}

export class Accordian extends Component<AccordianProps, AccordianState> {
  public state = {
    isOpen: false,
  }

  public render ({ label, children, ...props }: AccordianProps,
    { isOpen }: AccordianState): VNode {
    return (
      <div class={`${style.accordian} ${props.class ? props.class : ''}`}>
        <div class={style.header} onClick={() => this.setState({ isOpen: !isOpen })}>
          {label}
          <span style={{ transform: `rotate(${isOpen ? '-' : ''}90deg)` }}>&#10095;</span>
        </div>
        { isOpen && children }
      </div>
    );
  }
}
```

When I click the component header to toggle the open state I get the following error.
>Can't call "this.setState" on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

The component is appearing properly on the screen and behaves as expected.

I threw a console log in the header click handler to see what `this._parentDom` was at that point and it is undefined, which is causing the warning. But I'm not sure why it would not be defined at this point.

**Comment by jonbo** [comment]
I am running into this same exact warning message, for seemingly no reason, on a mounted component. Everything else seems to be working fine. I just upgraded from 10beta.3 to 10.0.2 on a project.

**Comment by marvinhagemeister** [comment]
That's strange! Had a quick look into it and without importing `preact/debug` the property is correctly set. But as soon as I import `preact/debug` `component._vnode` is always null for me.

**Comment by marvinhagemeister** [comment]
I'll publish a new release shortly

**Comment by marvinhagemeister** [comment]
Published as `10.0.3` :tada:

**Comment by jliebrand** [comment]
I'm seeing this on 10.4.4. The component is mounted, but it still throws the error as if it is not?

**Comment by marvinhagemeister** [comment]
@jliebrand Can you file a new issue for that? If we have a repro case (repo or codesandbox) we can get to the bottom of it pretty quickly.
