### ISSUE TITLE
Suspense/Lazy and debug

### ISSUE THREAD

**Issue by pmkroeker** [preactjs/preact#2062]
Found an issue with using Suspense/Lazy and debug.

I'm getting the following error in the console when debug is being used:
>Uncaught Error: Missing Suspense. The throwing component was: Lazy

If I remove debug the app works correctly.

All of my Lazy routes are nested in a Suspense.

**Comment by andrewiggins** [comment]
FYI, I think I've gotten to the bottom of this. PR with fix should be out soon (couple days).

**Comment by ohmlnz** [comment]
Hi @andrewiggins, any updates on the above? I'm also experiencing the issue when using `require('preact/debug')`. Thanks!

**Comment by pmkroeker** [comment]
It would be great if this could get resolved. Having some issues with the latest release and was hoping debug might help.

**Comment by marvinhagemeister** [comment]
@pmkroeker I'd love to help out here! Do you happen to have a codesandbox or a scenario where the error occurs? Tried to reproduce it on my own but I'm unable to.

**Comment by pmkroeker** [comment]
@marvinhagemeister I'll put something together!

**Comment by pmkroeker** [comment]
Here is a [CodeSandBox](https://codesandbox.io/s/preact-suspenselazy-with-debug-jfozy) that demonstrates the issue.

If you remove the wrapping `Suspense` it throws with the same error.

The biggest problem is that it crashes the app.

**Comment by MattAndDev** [comment]
Also just hit this exact same issue!
Will try to take a deeper look into it.

**Comment by andrewiggins** [comment]
Hi! Sorry this slipped through the cracks. I had to take a break from Preact for a lil bit due to some work stuff that came up. But I have some time to come back now :smile:

@marvinhagemeister I think [this commit](https://github.com/preactjs/preact/commit/1757778ca9eaf7b9ef1f1f242a0842b60a93e84e) from my branch where I run tests against minified builds fixes this issue. (tl;dr: `_childDidSuspend` is missing from the mangle.json)

**Comment by marvinhagemeister** [comment]
@andrewiggins Ohh that could very much be it! I copied the code into our demo app and couldn't reproduce the error. That's presumably because we don't use the minified bundles in our demo app and build straight from source.
