### ISSUE TITLE
inquire about jsx.d.ts type definition

### ISSUE THREAD

**Issue by js87zz** [preactjs/preact#2067]
I have a question about `style` type definition in `HTMLAttributes` of `jsx.d.ts`.
Currently type is defined as below.
```js
interface HTMLAttributes extends preact.ClassAttributes<any>, DOMAttributes  {
  // ...
  style?: string | {[key: string]: string | number};
  // ...
}
```
I have used style attributes that could have `null` or `undefined` property for applying style attributes to DOM element on specific condition. I think it's one of the advantages of using `jsx`.
```js
// example
const { padding, valign } = this.props; //  padding or valign can be `undefined` or `null`
const styles = { padding };

return (
   // caused type error(`padding` or `valign` cannot be `undefined` or `null`)
   <div style={style}>
     {//...}
   </div>
```
But attribute in `style` cannot have `undefined`, `null`, I have to fixed the code to solve this issue.
How about modifyng the `style` type definition as below?
```js
style?: string | {[key: string]: string | number | null | undefined};
```

**Comment by jeremy-coleman** [comment]
I have an open pull request fixing this

the concern is that csstype type definitions cause a dependency, although i would argue it doesnt since its only a dts with no runtime overhead

You can manually add csstype and do import * as CSS from csstype and then let mystyles:CSS.Properties = {...styles}, this will behave the same as react’s css type defs

**Comment by jeremy-coleman** [comment]
I also think for your case here, you need to type the styles variable ,  ts defs with a ? Are already nullable . React behaves the same way as this btw

**Comment by js87zz** [comment]
@jeremy-coleman 
I confirmed this [PR](https://github.com/preactjs/preact/pull/1797) you commented. 
CSS.properties type allows the optional type. So, my case could be solved when i tested using it. Do you have any plan to merge the PR?
Thank you for your replying :)

**Comment by marvinhagemeister** [comment]
Closing, since the type of `style` has changed quite a bit and is now defined as:

```ts
type AllCSSProperties = {
  [key: string]: string | number | null | undefined;
};
```
