### ISSUE TITLE
TypeError: Cannot read property 'getChildContext' of undefined when trying to switch to Preact existing project (with redux)

### ISSUE THREAD

**Issue by adam4leos** [preactjs/preact#2069]
Ahoy.

I am currently trying to switch existing project (react v16.8 + react-redux  v7.1) to preact (trying v10) by using `preact` & `preact/compat` aliases in webpack config.
 And encountering next problem on application start -> 
```JavaScript
TypeError: Cannot read property 'getChildContext' of undefined
``` 
caused by usage of `Provider` component (from `react-redux`). 
<img width="785" alt="Screenshot 2019-10-30 at 17 01 21" src="https://user-images.githubusercontent.com/18248739/67870116-09574c80-fb37-11e9-9796-d5ae8161ecd5.png">

Code itself -> 
```JavaScript
import React from 'react';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';


export const createEntrypoint = (ApplicationComponent, { store, persistor, playerInstance }) => (
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <ApplicationComponent playerInstance={playerInstance} />
    </PersistGate>
  </Provider>
);
```

Following to the `preact-module` code it says that `Provider` has an 'undefined' value as 'this' (`create-context` file, https://github.com/preactjs/preact/blob/master/src/create-context.js#L14).

Same code works well without Provider so can't figure out what is wrong. Demo from this repo, with redux `Provider` usage works as well. 

Any information will be much appreciated.

**Comment by marvinhagemeister** [comment]
iirc there was an issue with `react-hot-loader` rewriting things weirdly which broke context. Just a shot in the dark.

**Comment by ppozniak** [comment]
I can only add up that I am getting the same error without Redux. It's just freezing my tab.

**Comment by andrewiggins** [comment]
@ppozniak are you using react-hot-loader too?

**Comment by ppozniak** [comment]
> @ppozniak are you using react-hot-loader too?

Yes I do.

**Comment by andrewiggins** [comment]
Hmm seems like `react-hot-loader` is the commonality here and cause of the issue.

**Comment by adam4leos** [comment]
@andrewiggins  @ppozniak @marvinhagemeister   hmm, very interesting. I'll investigate this one further. Appreciate your answers here.

**Comment by adam4leos** [comment]
I can confirm that issue caused because of conflicts with `react-hot-loader`. Disabling `react-hot-loader` removes the problem.

**Comment by adam4leos** [comment]
Meanwhile, it looks like if you want to use hotloader alias for `react-dom` (https://github.com/gaearon/react-hot-loader#hot-loaderreact-dom), you'd run into conflict with preact, where we want to set `"react-dom": "preact/compat"` alias. Anything I'm missing here, how this could be done better?

**Comment by LinusCenterstrom** [comment]
Having the same problem here, is there any workaround to get react-hot-loader to work with Preact?

**Comment by labeldock** [comment]
https://github.com/preactjs/preact/blob/master/src/create-context.js#L15

I am shy to speak English ...
Anyway, the problem I found is that `this.getChildContext` "this" is undefined at runtime.

**Comment by dangreen** [comment]
@marvinhagemeister https://github.com/gaearon/react-hot-loader/issues/1445#issuecomment-618726809

**Comment by marvinhagemeister** [comment]
FYI: We're close to getting an official fast-refresh plugin for Preact out. It supports not just component HMR but also hooks. We'll announce it sometime in the coming weeks and need a bit of time to resolve remaining issues. This is doable without extending options like proposed in the react-hot-loader repo above.
