### ISSUE TITLE
Can't import `preact/devtools` after upgrading from v8 to v10

### ISSUE THREAD

**Issue by peterswallow** [preactjs/preact#2077]
Previously we were using Preact v8 and doing `require('preact/devtools')` into our component which worked fine.

We just upgraded to Preact v10 but I can no longer `require('preact/devtools')` and have to `require('preact/debug')` instead.

We only want the DevTools feature and not the full debug feature.

Is this correct or am I missing something? The [documentation](https://www.npmjs.com/package/preact#developer-tools) suggests I should be able to just do `require('preact/devtools')`.

Thanks :)

**Comment by JoviDeCroock** [comment]
The documentation you linked to refers to using /debug

**Comment by peterswallow** [comment]
but its says you can use preact/devtools only if needed.

If you only want to include devtool integration, without runtime error
checking, you can replace preact/debug in the above example with
preact/devtools.

**Comment by peterswallow** [comment]
I'm using v10.0.4. It feels like the documentation needs updating.

**Comment by targumon** [comment]
That section entered the docs a long time ago https://www.npmjs.com/package/preact/v/6.4.0

**Comment by marvinhagemeister** [comment]
Yeah it's true, we haven't updated our Readme in a while. The `preact/devtools` import is gone and replaced by `preact/debug`. The latter includes the debug warnings, too. There is currently not a way to just import devtools.

Nonetheless I'd love to hear more about your use case. Is it for something outside of development?

**Comment by peterswallow** [comment]
@marvinhagemeister Ah that's cool. If it's definitely gone, then i'll just go with `preact/debug` instead. I just wanted to double check as the documentation suggested otherwise.
I guess the documentation just needs a "only for V8 or earlier" adding.
