### ISSUE TITLE
Functional refs still behave slightly different from React

### ISSUE THREAD

**Issue by mindplay-dk** [preactjs/preact#2112]
This is a follow-up issue to #2052, which was fixed by #2055.

While re-testing the [sandbox from that issue](https://codesandbox.io/s/happy-morning-jyu67), I found that there is still a subtle deviation from the order of events in React - here's the console output for comparison:

![image](https://user-images.githubusercontent.com/103348/68668171-e15ce580-0547-11ea-9d67-427bc437a577.png)

As you can see, React cleans up all refs before creating new ones - whereas Preact seems to create and clean up refs in the order they were created?

This could be important and *might* create problems for components that use several functional refs to manipulate the same component or global state.

(Refs are sometimes used as a way to create side-effects that depend on the life-cycle of *elements* - as opposed to `useEffect` or life-cycle methods, which depend on the life-cycle of *components*.)

**Comment by JoviDeCroock** [comment]
This is a deviation that was outlined in the PR and probably won't be fixed since it does not cause any severe issues

**Comment by marvinhagemeister** [comment]
Looking at the difference in behavior I guess it comes down to different diffing strategies used under the hood. React has a 2-pass rendering algorithm and for that it makes sense to flush all pending refs in one go. We currently do have a single-pass algo and update elements as we go. We offload some effects into queues to ensure that effects are called independent of that. In the long run we'll likely switch to a 2-pass renderer, but it will take time.

**Comment by 132yse** [comment]
I don't think it matters here. As long as we can assert `null` before ref is executed, react has to traverse the linked list twice. I don't think it's better. There's no need to keep it completely consistent.

**Comment by mindplay-dk** [comment]
After thinking more about this, I'm leaning towards agreeing with you guys here.

The thing is, React does not *prescribe* a specific order of events - what it does prescribe is the guarantee that callback refs will be called with nulls to clean them up, but I don't believe anything is formally prescribed regarding the notification order among *individual* refs.

So I think we can safely regard this as an implementation detail - the sort of thing that might even be subject to change in React itself, were the engine to change in some way or other.

If you'd prefer to close this issue, I won't object. 🙂

**Comment by robertknight** [comment]
Thanks for looking into this. It seems there is consensus that we can leave this behaviour as-is for the moment and subject to change in future.
