### ISSUE TITLE
Not possible to use css !important in style={} tag

### ISSUE THREAD

**Issue by hinst** [preactjs/preact#2133]
<span style={{backgroundColor: 'red !important'}}>a</span>
Expected result: it is red
Actual result: it as long as !important is present in the string, the value is not set at all.

**Comment by JoviDeCroock** [comment]
Is this the case in React?

**Comment by hinst** [comment]
It appears that !important was fine in older versions of React. 
But now it is no longer allowed in React version 15+

**Comment by JoviDeCroock** [comment]
It's pretty hard for me to see a valid case for `!important` in inline styles

**Comment by hinst** [comment]
I'm using a 3rd party stylesheet w3.css and it defines colors with "!important". When I want to override the color for only one of my buttons, I have to use !important in inline as well, otherwise its not effective. But oh well I guess I can't ask for this to be supported if the current version of React doesn't support it (i didn't know that React doesn't support it anymore at the time when i filed the issue)

**Comment by JoviDeCroock** [comment]
I'm going to look deeper into the reasoning behind this and report back

**Comment by robertknight** [comment]
Relevant discussion in React repo: https://github.com/facebook/react/issues/1881. In summary, it seems as though they are not opposed to the idea of supporting `!important` in inline styles, but they are being cautious about the implementation. There is also a note in that issue about the suggested workaround using refs.

I'm inclined to keep this limitation in Preact for the time being as long as we don't need it for React compatibility, as it makes it easier to keep the implementation simple and fast.
