### ISSUE TITLE
Continue publishing preact/compat as standalone node module also?

### ISSUE THREAD

**Issue by maranomynet** [preactjs/preact#2149]
I'd like to suggest you continue publishing the npm package `preact-compat` as alternative method of installing/using `preact/compat`.

This would make it possible to use npm and yarn's native package.json dependency renaming syntax and skip installing 3rd party aliasing-plugins and/or relying on bundler config tricks.

Like so...

```
npm install react@npm:preact-compat@^10 react-dom@npm:preact-compat@^10
```

resulting in these depdendency lines in package.json

```json
	"react": "npm:preact-compat@^10",
	"react-dom": "npm:preact-compat@^10",
```

The only thing that might make this unfeasible, is if this would result in large amounts of code being imported twice - once from `node_modules/react` and then again from `node_modules/react-dom`.
I'm not familiar enough with the preact codebase to judge how tight the coupling is between the "react"y and "react-dom"y bits of Preact.

**Comment by sventschui** [comment]
Not super familiar with the dependency renaming but if it results in two copies of preact-compat being located at `node_modules/react` and `node_modules/react-dom` (I think this is what your last paragraph mentions) then this doesn't work in terms of simply shipping the `preact/compat` folder as a separate npm package.

What might work tough is to publish a `preact-compat` that is a single file doing `module.exports = require('preact/compat')` as this would be de-duplicated later.

One thing that needs to be mentioned tough is that if one of your bundles uses an incompatible version range of react (note all "regular" react versions will be incompatible) then it will result in installing react to `node_modules/fancy-react-library/node_modules/react`. Again here I'm only 90% sure this is the case as I did not try this out.

If you want to give it a try you could experiment with different cases (fully blown preact-compat, simple re-export, ...) using `"react": "file:.../local-preact-compat"`.

**Comment by cristianbote** [comment]
Unfortunately installing a package like that `npm install react@npm:preact-compat@^10 react-dom@npm:preact-compat@^10` ends up with `preact` being duplicated(basically drop-in replacement) of both, `react` and `react-dom`.
![Screenshot 2019-11-29 at 08 53 34](https://user-images.githubusercontent.com/3405161/69849659-078fbe80-1286-11ea-8c87-919cafdfb98c.png)

So I don't see how this would work. What do you think @maranomynet?

**Comment by ForsakenHarmony** [comment]
does that cause it to resolve dependencies in a non flattened tree? Otherwise you could just have a tiny wrapper that imports preact

**Comment by andrewiggins** [comment]
Does npm aliases work for compat? At least when they were first introduced, it only aliased the package for yourself, not for any libraries you add (e.g. when your code imported `react` you would get `preact-compat` but if you used `react-router`, it's `react` import would still be `react`, not compat). That's my understanding of the [relevant section in the RFC](https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md#rationale-and-alternatives) (see the paragraph about problems this RFC does not address). Has npm changed the behavior of aliases since this RFC was released?

**Comment by jeremy-coleman** [comment]
I think it depends on how the sub package defines its dependencies. For ex if react router were to have react as a peer dep, the npm alias should work, but an exact dep would cause a nested node_modules folder. Lerna hoist and postinstall scripts can fix anything tho if u really need to get something working

**Comment by caub** [comment]
I've struggled so much with this!

I thought 

    "preact": "^10.5.12",
    "preact-compat": "file:node_modules/preact/compat",
    "react": "npm:preact-compat@^some.version",

would have done the trick, but I kept having weird issues when `npm i` or with `npx react-scripts build`

in the end, what worked for me is hacky:

      "preact": "^10.5.12",
      "react": "file:node_modules/preact/compat",

along with those npm scripts:

    "preinstall": "npm r react",
    "postinstall": "sed -i '/\"preact-.*/a \\ \\ \\ \\ \"react\": \"file:node_modules/preact/compat\",' package.json && npm i --ignore-scripts",

I also tried a custom build script

```js
process.env.NODE_ENV = 'production';

const config = require('react-scripts/config/webpack.config.js')('production');

config.resolve.alias['react'] = 'preact/compat';
config.resolve.alias['react-dom'] = 'preact/compat';

require('react-scripts/scripts/build');
```

but `npm i` was failing anyway, so I had to move the compat thing to package.json

**Comment by marvinhagemeister** [comment]
FYI: `preact-compat` is for Preact <= 8.x and won't work with Preact 10. Starting with Preact 10.x it is available as an entry of the `preact` package: `preact/compat`.

**Comment by caub** [comment]
@marvinhagemeister Thanks, I did notice that, no worry. I'm just posting my solution for the record, and comparing with what others are doing

**Comment by popuguytheparrot** [comment]
https://github.com/DocSpring/craco-preact one else alternative way
