### ISSUE TITLE
preact with rollup

### ISSUE THREAD

**Issue by Kulak** [preactjs/preact#2163]
Hi,

I have attempted to follow Getting started by doing things from scratch here and run into a problem:

https://github.com/Kulak/preactWithRollup

My Preact code above seems to render just fine example from getting started:

```
import { h, Component, render } from 'https://unpkg.com/preact?module';

// Create your app
const app = h('div', null, 'Hello World!');

// Inject your application into the an element with the id `app`.
// Make sure that such an element exists in the dom ;)
render(app, document.getElementById('app'));
```

but the moment I go to Class form it fails to call render method in App class.  That's the state I have left the code in my example repository.

I have even removed JSX from the solution to simplify things and I still have problems.  I think the issue might be around my incorrect invocation here:

```
render(h('div', null, [new App]), document.getElementById('container'))
```

My apologies, but there is no support forum and twitter does not seem like a good format.

Thank you

**Comment by Kulak** [comment]
I managed to get it to work with `htm` package, which was my original goal.

**Comment by AxelRHD** [comment]
@Kulak could you share a minimum example of your app with rollup? I can't get it work with preact. Even your rollup.config.js might help. Thank you.

**Comment by marvinhagemeister** [comment]
@AxelRHD What kind of error are you getting? Preact should work out of the box with Rollup.

**Comment by AxelRHD** [comment]
@marvinhagemeister, I am very new to the concepts op React/Preact and wanted to give the JSX-Alternative [HTM](https://preactjs.com/guide/v10/getting-started/#alternatives-to-jsx) a try. I got the following warning: `(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
src/main.js
27:   }
28:
29: render(h(App, {__self: this, __source: {fileName: _jsxFileName, lineNumber: 29}} ), document.body)`

My rollup.config:
import resolve from '@rollup/plugin-node-resolve';
import sucrase from '@rollup/plugin-sucrase';
// import commonjs from '@rollup/plugin-commonjs';
import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import preact from 'rollup-plugin-preact';

const production = !process.env.ROLLUP_WATCH;

export default {
  input: 'src/main.js',
  output: {
    file: 'public/dist/bundle.js',
    format: 'umd',
    globals: [preact]
  },
  // external: ["preact", "preact-compat", "preact-compat2"],
  plugins: [
    resolve(),
    sucrase({
      exclude: ['node_modules/**'],
      transforms: ['jsx'],
      jsxPragma: "h",
      jsxFragmentPragma: "Fragment"
    }),
    // commonjs(),
    // preact({
    //   usePreactX: false, // usePreactX is auto resolvePreactCompat: true.
    //   noPropTypes: false,
    //   noReactIs: false,
    //   noEnv: false,
    //   resolvePreactCompat: false,
    //   aliasModules: {
    //     "react-css-styler": "preact-css-styler",
    //   },
    // }),

    // In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve({
      contentBase: 'public',
      host: '0.0.0.0',
      port: 3000
    }),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
  ]
}

And the main.js:
import { render, Component } from 'preact';

class App extends Component {
    // Add `name` to the initial state
    state = { value: '', name: 'world' }
  
    onInput = ev => {
      this.setState({ value: ev.target.value });
    }
  
    // Add a submit handler that updates the `name` with the latest input value
    onSubmit = () => {
      this.setState({ name: this.state.value });
    }
  
    render() {
      return (
        <div>
          <h1>Hello, {this.state.name}!</h1>
          <form onSubmit={this.onSubmit}>
            <input type="text" value={this.state.value} onInput={this.onInput} />
            <button type="submit">Update</button>
          </form>
        </div>
      );
    }
  }

render(<App />, document.body)


Obviously I ended up in a mix of the to concepts but all attempts to fix it ended in different errors. So I would be very thankfull for maybe two little examples using rollup and preact with HTM or JSX.

**Comment by JoviDeCroock** [comment]
This one works: https://github.com/JoviDeCroock/Vanilla-Preact-Application/blob/master/rollup.config.js this is a production one so you'll need to fine-tune the config stuff, (no terser during dev, ...)

**Comment by AxelRHD** [comment]
@JoviDeCroock thank you. I checked the example code. But one thing I don't understand. Why do you set these global variabels:

`window.html = htm.bind(h);`
`window.h = h;`
`window.Component = Component;`

I can't find something about that in the documentation. Even for HTM.

**Comment by JoviDeCroock** [comment]
Oh I just do it to simplify my life to be honest

**Comment by AxelRHD** [comment]
Okay, I see... I have a lot to lern the concepts yet.
