### ISSUE TITLE
Untyped "this" parameter in the type declarations.

### ISSUE THREAD

**Issue by Artikash** [preactjs/preact#2164]
Here's some TSX
```
const App = {
	processData(data: string) {},
	forwardEvent(this: { processData(data: string): void }, data: Event) {
		this.processData(event?.type || "");
	}
}

render(<input
	type="text"
	onChange={App.forwardEvent} // NOOOOOO!!!!
/>, document.body);
```

Expected behavior: compile error due to incompatible `this` types.
Actual behavior: compiles fine with the undeclared `this` parameter in `jsx.d.ts`, runtime error as soon as the event fires 😢 .

In Preact version 10.0.5.

**Comment by marvinhagemeister** [comment]
Awesome, thanks a bunch for the bug report :tada: I was able to reproduce the issue and the fix turned out to be a one-liner. It's already merged into `master` and will be included in our next release :+1: :100:
