### ISSUE TITLE
No way to set unknown properties to the `style` attribute

### ISSUE THREAD

**Issue by akdor1154** [preactjs/preact#2174]
Preact uses `element.style.cssText = "..."` to set inline styles from strings.

I have a kind of annoying usecase where this approach does not work: I am rendering a table that users are going to be frequently copy/pasting into Microsoft Excel. In order to control how certain cells are formatted, they need an inline style that looks something like:
```html
<td style='mso-number-format: "\@"'>1234</td>
```

Unfortunately, `element.style.cssText` ignores any unknown properties (`mso-number-format` is invalid in everything except Excel) so the resulting `style` attribute actually becomes blank.

`element.setAttribute('style', "random text")` would work for me, but it looks like it's inferior for every other use case to mine, and Preact has sensibly chosen that method. This is fine, but is there any way I can hook in and directly set the `style` attribute as text on my `td`s? (Preferably not by doing `ref.current.querySelector('td').forEach((td) => td.setAttribute(...))`after every render...)

**Comment by cristianbote** [comment]
Hey @akdor1154 , thanks for taking the time to open this issue. Really appreciate it.

Indeed, `cssText` wipes away any form of illegal css. Your use-case though seems valid, but it's not part of the CSSOM specs, I presume. So, there needs to be some sort of a proprietary code that would take care of that.

Indeed, waking the DOM tree might be not that great, and this is what I was thinking. You could hook into the `options.diffed` and basically set the `style` again to the `dom` element.

```js
options.diffed = vnode => {
  if  (vnode.type === 'td') {
    // This could change so be weary of relying on it
    const el = vnode. _dom || vnode.__e;
    el.setAttribute('style', vnode.props.style);
  }
}
```

This hook should be defined just once, thinking top-level app and you could filter out the `vnode.type`s that you don't wanna target.

Let me know if this works for you.

**Comment by marvinhagemeister** [comment]
Closing as Microsoft Excel is not one of our official supported browsers and a workaround is available as mentioned above :+1:
