### ISSUE TITLE
Error with undefined __hooks property

### ISSUE THREAD

**Issue by apfelbox** [preactjs/preact#2175]
Hi,

sorry for this confusing issue, but I haven't found anything so far:

I have the issue that `__hooks` is suddenly undefined:
![2019-12-10 at 17 19](https://user-images.githubusercontent.com/1032411/70547519-4f112700-1b71-11ea-9198-ecef24dd3581.png)

Both of the `forEach` before succeed, but here `__hooks` is suddenly undefined (ie it must be through a side effect of one the `invokeEffect` calls):

Error in console:
![2019-12-10 at 17 20](https://user-images.githubusercontent.com/1032411/70547602-75cf5d80-1b71-11ea-9bb4-e3853e5a5e8b.png)

My `hooks.module.js` (extended by some `console.log()` calls):
![2019-12-10 at 17 20](https://user-images.githubusercontent.com/1032411/70547649-8a135a80-1b71-11ea-8012-91f51651a86c.png)

I highlighted the one that is right before the error.

The component that is triggering this error seems innocent enough (it is not yet finished 😉):
<details>
<summary>Show screenshot</summary>

![2019-12-10 at 17 23](https://user-images.githubusercontent.com/1032411/70547847-e5454d00-1b71-11ea-8302-df016b5a06fe.png)

</details>

Happy to provide any additional info, if you could give me some pointers on where to look.

**Comment by JoviDeCroock** [comment]
I tried reproducing your issue here but can't seem to figure out as to why it's failing https://codesandbox.io/s/brave-panini-i3iho

**Comment by apfelbox** [comment]
Hi @JoviDeCroock,

thank you for taking a look!

I narrowed it down to this case: if I call `fetch.request()` in my effect it errors out, if I don't call it it works.

So, works:
![2019-12-10 at 19 00](https://user-images.githubusercontent.com/1032411/70555499-6bb45b80-1b7f-11ea-8be6-a9868cc9b967.png)

Doesn't work:
![2019-12-10 at 19 00](https://user-images.githubusercontent.com/1032411/70555476-5d663f80-1b7f-11ea-8b1e-2e53ad92710c.png)

I have no idea on how the hooks are implemented in preact, but do you know of anything that might lead to issues in combination with hooks – even if my callback doesn't even return anything (so just some side effects)?

**Comment by marvinhagemeister** [comment]
I'm unable to create a reproducible scenario. Is there any way you can narrow it down further to a specific component? We'd love to help but without access to the quote we're shooting in the dark :S

**Comment by apfelbox** [comment]
Yeah, sorry about being so unspecific, the issue occurs in my app which is spread across ~5 private projects. I am currently trying to reproduce this issue in sandbox.

What I have so far:
My `fetch.request()` method is internally calling a global service, that renders a global loader overlay. That global loader overlay is a JS class that internally calls `render()` (from preact) and as soon as it is calling that it fails with the error.
It doesn't matter *what* it renders, or *where*, just that it renders at all.

I am still trying to create a minimal reproducible example, so that you can take a look at it more closely.

**Comment by apfelbox** [comment]
Still trying to reproduce it, but I at least can tell you what happens:

So somehow the component shifts, I added some logging to the `_render` in `hooks/index`:
![2019-12-10 at 20 20](https://user-images.githubusercontent.com/1032411/70561338-8c35e300-1b8a-11ea-903d-20b2ff061382.png)

And somehow the component changes!
![2019-12-10 at 20 21](https://user-images.githubusercontent.com/1032411/70561462-c7d0ad00-1b8a-11ea-8285-6158abaab612.png)

**Comment by apfelbox** [comment]
Ok wow, so I finally got it reproducible. (I don't want to admit that finding this just took me around 4.5 hours 😬)

Please, before investing time into "fixing this": if my code / architecture is 💩 (ie that is a "won't fix"), please tell me beforehand so that I can clean it up on my side and you don't have to support super obscure use cases. 😬 

Here is the reproducer: https://codesandbox.io/s/mystifying-frost-u6b7v

1. pass a state hook setter into a nested prop
2. immediately call this setter synchronously
3. in the inner element render something (somewhere else using `render()`) in an effect.

I have absolutely no idea what is happening here, but what I can tell you is:

* if move the `render()` code outside of the `useEffect` it works.
* if I remove the state hook setter call it works

I guess step 2 is not supposed to be done like this, but I actually have no idea anymore now 😄

**Comment by JoviDeCroock** [comment]
Generally calling a parent setter in a child is not encouraged most of the time you pass a callback to achieve such a thing.

This means that instead of doing

```
<MyChild set={mySetState}
```

You can do

```
<MyChild set={(val) => mySetState(val)}
```

The difference is small but this means that your `set` will always be executed in the context of that particular component. At this point in time it will work.

I forked your repro but it just works for me: https://codesandbox.io/s/competent-joliot-h082q

**Comment by apfelbox** [comment]
It works, but it throws in a promise:
![2019-12-11 at 12 33](https://user-images.githubusercontent.com/1032411/70618188-84218600-1c12-11ea-9199-a7e0930d2958.png)

So... it isn't breaking, but it access a (possibly) undefined property and throws (even if that doesn't have any influence on the rest of the app).

The error still occurs if I wrap the state setter in a closure:

```jsx
const Modal = ({ Content }) => {
  let [canProceed, setCanProceed] = useState(true);

  return (
    <div>
      <Content setCanProceed={(val) => setCanProceed(val)} />
    </div>
  );
};
```

(it isn't too bad, I just rewrote my whole component, because on second look the architecture was.. well, not good. Just wanted to inform you that if this is something you want to fix, even if it isn't breaking the app flow.)

**Comment by developit** [comment]
Hmm - in your sandbox, you're calling `render()` on an existing render root from within a component. That's sortof like telling Preact to change a bunch of things, then during those changes also telling Preact to undo everything and make different changes.

In terms of architecture, I'm guessing you're looking to implement some sort of authorization or gating thing - would it be possible to just render `null` instead of doing another whole `render(<div>global</div>,container)` call? A component with insufficient data or permissions rendering `null` to show nothing would be more in keeping with the philosophy of top-down rendering.

**Comment by wnayes** [comment]
Ran into this issue as well. Maybe it doesn't add much, but here's another sandbox that reproduces the issue - type somewhat quickly into the input field to trigger the race condition.

https://codesandbox.io/s/xenodochial-feather-9qu8n

The real case I'm trying to implement is a `Popup` component that wraps a third party modal popup, and renders its `children` into the third party modal during an effect. Sort of like a `Portal` except I'm not bothering with an actual `createPortal` here.

I will look into "throttling" the render (setTimeout), so that it doesn't occur during an effect, as a workaround.

**Comment by apfelbox** [comment]
@developit thanks for your explanation, it clears a lot of things up.

I would like to describe my use case / architecture style to make my point more concrete.

My architecture is that my backend renders most of the page server side and my frontend just injects small isolated components that live inside that larger prerendered HTML page. So I have a page with let's say 5 individually mounted components. I quite like this architecture, as it is really fast and simple to integrate.

However, this exact issue arises if one of these isolated components triggers a change in a different isolated component (due to global state).

I like that preact is really well suited for this type of "enhancing" a plain old HTML page, however this is the one issue I quite frequently run into.
It appears that preact has some global state, that just breaks in certain conditions when having multiple separate render roots that interact with each other.

**Comment by JoviDeCroock** [comment]
Hey @apfelbox

I'd be happy to look into this if you have a concrete example I could try this in

**Comment by apfelbox** [comment]
@JoviDeCroock thanks for your response!
The issue is still present in de codesandbox linked above: https://github.com/preactjs/preact/issues/2175#issuecomment-564249500

The issue comes basically down to this:

`useEffect()` in any component
-> change some global state
-> `render()` a different component

If that is a synchronous call chain, this will just break. While I understand that this is a maybe suboptimal architecture, this is a quite common setup in the "isolated components" architecture.
And from a DX perspective it is weird that this breaks, as the two components are completely isolated from each other.

**Comment by JoviDeCroock** [comment]
@apfelbox I put up a PR that is aimed at fixing this issue.

**Comment by apfelbox** [comment]
@JoviDeCroock wow, thank you! 🚀
