### ISSUE TITLE
Error from preact/debug for code wich doesnt exist?

### ISSUE THREAD

**Issue by CodCase** [preactjs/preact#2177]
Hello,

since Im using preact X with the debugger I get the following error:

> Calling "this.setState" inside the constructor of a component is a no-op and might be a bug in your application. Instead, set "this.state = {}" directly. 

Ive searched a lot in my codebase and didnt find any this.setState in a constructor neither online any solution for this error message.,

It would be nice if the debug mode would give me the name of the component wich causes the error.

**Comment by marvinhagemeister** [comment]
The PR to display component stack traces got approved and I merged it in `master`. We'll cut a new release sometime around next Tuesday probably (we don't release on weekends :) )

**Comment by CodCase** [comment]
Thank you for your fast support t.
Merry Xmas!
