### ISSUE TITLE
Strange ref assign order

### ISSUE THREAD

**Issue by ajihyf** [preactjs/preact#2194]
I'm trying to use same `ref` in two conditional rendering components like this.

```javascript
function App() {
    ...
    return state ? (
        <div key="a">
            <div ref={ref} />
        </div>
    ) : (
        <div key="b">
            <div ref={ref} />
        </div>
    );
}
```

When state changes from `true` to `false`, it seems that the first unmounting div's ref assignment happens after the second mounting div, which makes `ref.current = null`.

I've created a sandbox to reproduce this issue. https://codesandbox.io/s/preact-ref-bug-esfv7

**Comment by marvinhagemeister** [comment]
Can confirm that this is a bug. Here is the [React version](https://codesandbox.io/s/react-conditional-ref-7qgzg) which correctly sets the `ref`.
