### ISSUE TITLE
Whitespaces are being rendered twice

### ISSUE THREAD

**Issue by DavidZinatulin** [preactjs/preact#2221]
![image](https://user-images.githubusercontent.com/7558949/71658136-719af800-2d4b-11ea-8bd1-f0b56463c308.png)
if you turn on "Paint flashing" option in Chrome to highlight every DOM element, which is being updated, then you'll notice, that every element, which has a whitespace, is being rendered twice. However, if you replace that whitespace with `&nbsp;` in your .jsx code, it behaves as expected.

**Comment by developit** [comment]
Can you clarify which version of Preact you're seeing this with?  We just published a version that should have fixed this issue (#2215).

**Comment by DavidZinatulin** [comment]
Indeed, it has :)
thank you
