### ISSUE TITLE
React-compat type definitions for `preact/compat`?

### ISSUE THREAD

**Issue by BasixKOR** [preactjs/preact#2222]
I don't think this would be an easy task, but some libraries (i.e. [linaria](https://linaria.now.sh/)/react)'s type definitions are based on the type definitions of `@types/react`, which isn't compatible with Preact's type definitions. I tried aliasing TypeScript module resolution via tsconfig but it didn't give me the result I expected.

Could we have a compatible type definitions on preact/compat? Any solutions for solving this type issue is also welcome.

**Comment by BasixKOR** [comment]
P.s. The JSX-related types are global in `@types/react` [(source)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2880), but in Preact it's [in the module](https://github.com/preactjs/preact/blob/master/compat/src/index.d.ts#L11).

**Comment by ForsakenHarmony** [comment]
See https://github.com/preactjs/preact/issues/2150#issuecomment-558622551

It might help you

**Comment by BasixKOR** [comment]
Cool! But why we don't ship them by default?

**Comment by JoviDeCroock** [comment]
We do you can follow the `package.json` to find [them](https://www.runpkg.com/?preact@10.2.1/compat/package.json#11) so importing from `preact/compat` also imports from the typings file.

**Comment by BasixKOR** [comment]
I mean, we could improve even further by aliasing some of React types. Just a simple addition like https://github.com/preactjs/preact/issues/2150#issuecomment-558622551 could remove a lot of type incompatibilities in React libraries.

I'm willing to file a PR if you don't mind.

**Comment by bvella** [comment]
Added a pr that may solve some of these issues #2329

**Comment by ForsakenHarmony** [comment]
Can you alias them directly when you have compatible typings?
