### ISSUE TITLE
not-minified version of preact

### ISSUE THREAD

**Issue by ebraminio** [preactjs/preact#2233]
preact apparently used to be have not minified version of the library in dist folder https://unpkg.com/browse/preact@8.5.3/dist/ (preact.js 21.2 kB vs preact.min.js 8.43 kB) but apparently now doesn't https://unpkg.com/browse/preact@10.1.1/dist/ (preact.js 9.18 kB vs preact.min.js 9.18 kB), guess it wasn't intentional to have two same minified file in the distribution?

**Comment by developit** [comment]
Hiya! This was done intentionally - shipping both minified and unminified builds of Preact meant any tools that integrated with Preact needed to support both builds.

We added the `preact.min.js` alias in order to fix lots of demos being broken when 10 came out because they directly loaded `unpkg.com/preact/dist/preact.min.js`.

**Comment by ebraminio** [comment]
Can you put not minified version also somewhere? I like to use Preact in some environment that has it own minifier (MediaWiki) thus requiring not minified version, in place of React that I was experiencing with and have built some mini tools with it. Guess it should be easy to do that myself just it would be nice if I could put some public link as the source of the library so other also can update the library easily.

**Comment by developit** [comment]
@ebraminio We don't want to encourage folks to use Preact without our property mangling, since that creates a second variant of Preact with a different API. I'm guessing the goal here would be to have readable source code, which I think we can consider.

For Preact, that would be a `preact.js` that has properties mangled but not whitespace or local variables. that's probably something we could consider doing, though I don't think we'd necessarily want to ship it as `/dist/preact.js` (others may disagree, just my opinion).

If you want to see what that version might look like, it can be mostly emulated with the following changes to preact's [`mangle.json`](https://github.com/preactjs/preact/blob/master/mangle.json):

```diff
{
  // <snip>
  "minify": {
+   "mangle": {
+     "keep_fnames": true,
+     "toplevel": false,
+     "reserved": [
+       "dom",
+       "oldVNode",
+       "newVNode",
+       "vnode",
+       "oldDom",
+       "excessDomChildren",
+       "oldParentVNode",
+       "oldChildrenLength",
+       "oldChildren"
+     ],
+     "properties": {
+       "regex": "^@_"
+     }
+   },
+   "compress": {
+     "hoist_vars": true,
+     "reduce_funcs": false,
+     "keep_fnames": true
+   }
  },
  // <snip>
}
```

In terms of a real implementation, we'd want to add an option to Microbundle to support this type of output.

**Comment by ebraminio** [comment]
Ok, so let's close so you can decide later, thanks :)

**Comment by elias6** [comment]
I would really like a non-minified version of Preact 10 that I can easily step through using my browser debugger. That is not something I use often, but it is something I miss from Preact 8.

**Comment by evenfrost** [comment]
@developit ping. Today I've faced this issue when trying to debug an obscure error coming somewhere from the hooks code. Providing unminified code or/and source maps, which can be utilized by tools like `source-map-loader` would help debugging a lot.

![Screenshot from 2020-12-10 21-24-30](https://user-images.githubusercontent.com/3055750/101813987-83c21080-3b2e-11eb-90e9-85ba5a928210.png)

**Comment by marvinhagemeister** [comment]
FYI: We ship source maps in our npm package.

**Comment by evenfrost** [comment]
Weird, other packages' sources are shown okay. Must be issues with my config then. Still, allowing users to use their own tools for a build process feels more natural imo.

**Comment by evenfrost** [comment]
Is there any way to make webpack utilize unminified Preact files (to make debugging possible in development)?

**Comment by evenfrost** [comment]
Apparently, you need to map `preact` and all related imports to their unminified version via webpack's `resolve.alias`. Here is my code put in `webpack.config.js` for reference:

```js
// const path = require('path');
// const rootResolve = pathname => path.resolve(__dirname, pathname);

// ...
resolve: {
  alias: {
    react: rootResolve('node_modules/preact/compat/src/index.js'),
    'react-dom': rootResolve('node_modules/preact/compat/src/index.js'),
    'preact/hooks': rootResolve('node_modules/preact/hooks/src/index.js'),
    'preact/compat': rootResolve('node_modules/preact/compat/src/index.js'),
    preact: rootResolve('node_modules/preact/src/index.js'),
  },
},
// ...
```

**Comment by billti** [comment]
I was just searching on this topic as I want to learn more about Preact and understand its internals by stepping through some basic scenarios, but trying to step through code in the DevTools it's very hard to inspect values when all the names are mangled and don't match the (mapped) source.

How do y'all develop with it? I couldn't find any docs on how to create a local build which isn't the minified dist build, and most all of the exports in package.json point to those dist builds. Do you just develop/debug using the minified builds? I couldn't find any guidance on dev workflows on the repo or web site. Thanks!

**Comment by billti** [comment]
FWIW, I'm using esbuild (not webpack as outlined in the prior comments) and making the below couple changes seem to have it working for me (at least as far as having esbuild serve the Preact sources with my project goes)

In the root package.json

<img width="796" alt="image" src="https://user-images.githubusercontent.com/993909/235056433-10d4ad15-ae1d-4a35-a226-cad89ca2a8db.png">

And in the root jsconfig.json

<img width="780" alt="image" src="https://user-images.githubusercontent.com/993909/235056507-e6d23953-e3f7-4271-9881-4271526d4989.png">

I did similar in the package.json for the devtools. I'm only using "preact/debug" and "preact/hooks" entry points on top of the root "preact" module in my projects.

I then just did an 'npm link' in my local Preact clone, followed by 'npm link preact' in my test project. (Which is set up with TypeScript and es6 modules). Not sure if there's an easier way, but this unblocked me, and sharing in case it's of use to others. When I debug into Preact now I see unmangled locals and stack frames, can hover in the source to see values, etc.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/993909/235057560-babad8a8-cfe3-4a3e-ac79-e796477f1ae7.png">

**Comment by carlosxfelipe** [comment]
For anyone still looking for unminified and readable builds of Preact 10+, I've created a repository that provides these versions for Preact and Signals: [preact-readable](https://github.com/carlosxfelipe/preact-readable). It’s useful for debugging or self-hosting environments that require unmangled source code.
