### ISSUE TITLE
'two or more children with the same "key" attribute' error appears on non-array components

### ISSUE THREAD

**Issue by peterswallow** [preactjs/preact#2234]
Our website has been using Preact 8 for a while without any issues.

I recently started using `preact/debug` (rather than `preact/devtools`), but this started throwing *a lot* of these errors:

```
Following component has two or more children with the same "key" attribute.
This may cause glitches and misbehavior in rendering process.  
Component: <div />
```

I understand the purpose of the error, but sometimes the components it references e.g. <div /> aren't a rendered list nor do they have any key attributes.

For example, this component which just had two standard DOM elements would give me a specific error for this component...among lots of other errors for other sibling or parent components.

```
export const product = ({}) => {
    return (
        <div class="my-element">
            <span>Top</span>
            <span>Bottom</span>
        </div>
    );
};
```

I'm struggling to find the offending component as the error is ambiguous.

Thanks.

**Comment by peterswallow** [comment]
I wonder if this relates to it being a stateless component.

**Comment by JoviDeCroock** [comment]
I've tried this and it does not seem to do that for me

```
		it.only('should not print an error for functional components with nodes of the same type', () => {
			const App = () => (
				<div>
					<span>Top</span>
					<span>Bottom</span>
				</div>
			)
			render(<App />, scratch);
			expect(console.error).to.not.be.called;
		});
```

Can you reproduce this in codesandbox?

**Comment by ForsakenHarmony** [comment]
@peterswallow are you using `product` in a list?

i.e.

```
<div>
	{products.map(product)}
</div>
```

**Comment by peterswallow** [comment]
@ForsakenHarmony yes, which has a key attribute and there is only one item in the array, so it must be unique...although it doesn't render the key attribute, so can't see exactly what its doing.

Should I be able to see the **key=** attribute rendered?

I'm using Preact v8.2.1.

I've stripped out all the other code and can't see any other keys

**Comment by peterswallow** [comment]
Oh... think I've figured it out.

A simplistic example:
ListComponent.js - renders a list of Products
```
<ListComponent> //stateless functional component
   array.map((item) => {
      <ProductContainer key={item.id} /> //redux-connect and renders <ProductComponent />
   }
</ListComponent>
```
ProductContainer.js - connects <ProductComponent> to Redux store
```
export default connect({mapStoreToProps, mapDispatchToProps, component: ProductComponent});
```

ProductComponent.js - renders the product
```
export default class ProductComponent extends Component {
   render(){
      return <div key={id} />;
   }
}
```

So, before I only had a key on the `<ProductContainer>` component's prop, but it seems like the error only goes away if I also add a key= attribute to the root element (<div>) in `<ProductComponent>` component as well.

is that what you would expect? Seems strange as there are multiple `<ProductContainer>`s but one `<ProductContainer>` will only ever have one `<ProductComponent>`

**Comment by marvinhagemeister** [comment]
@peterswallow Only the topmost children need keys. In your case that's `ProductContainer`. The content of `ProductComponent` shouldn't be needed to modify in any way. I'm unable to reproduce the described behaviour on my end. Can you share a [codesandbox](https://codesandbox.io/) which shows the error?

**Comment by marvinhagemeister** [comment]
FYI: The 8.x release line will only receive security updates at this point. Updating to 10.x resolves this issue :tada:
