### ISSUE TITLE
Use Object.assign if available.

### ISSUE THREAD

**Issue by laino** [preactjs/preact#2241]
https://github.com/preactjs/preact/pull/1433 re-implemented ``Object.assign`` with a for-loop.

However using a for loop is only roughly half as fast in every browser I tested today (https://jsperf.com/object-assign-vs-for-loop-yaaay). Which isn't surprising.

So utils should check for ``Object.assign`` and export that if available instead of the polyfill.

**Comment by JoviDeCroock** [comment]
Hey thanks for the suggestion, I put up a PR where we implement this where we'll discuss this.

**Comment by lukeed** [comment]
It starts to get close when dealing with Objects with more than 24 keys, but `assign` still edges ahead. Even so, vnode objects aren't dealing with this many keys anyway

<img width="675" alt="Screen Shot 2020-01-10 at 12 51 02 PM" src="https://user-images.githubusercontent.com/5855893/72185590-0040f200-33a8-11ea-809a-d8814db191ec.png">

**Comment by marvinhagemeister** [comment]
Closing, because as demonstrated by @lukeed our custom polyfill is faster for small objects, like we have in our code.

**Comment by laino** [comment]
@marvinhagemeister It's generally not afaik. There was more discussion on the PR: https://github.com/preactjs/preact/pull/2242#issuecomment-573261721

**Comment by marvinhagemeister** [comment]
cc @developit who did tons of benchmarking on that. It seems like `jsperf` leads to different results than `esbench`.

**Comment by marvinhagemeister** [comment]
cc @developit who did tons of benchmarking on that. It seems like `jsperf` leads to different results than `esbench`.

**Comment by marvinhagemeister** [comment]
We can't switch to `Object.assign` in the 10.x release line, because it would be a breaking change as `Object.assign` isn't available in IE11. We removed it for the upcoming v11. Closing this issue, since no further action is required.
