### ISSUE TITLE
TypeError: n is null on a simple hello world

### ISSUE THREAD

**Issue by oreganoli** [preactjs/preact#2243]
Here's how my index.js looks:
```javascript
import { render } from 'preact'
import {html} from 'htm/preact';
render(html`<h1>Hello</h1>`, document.body);
```
Running it in the browser (Firefox) after bundling results in:
```
TypeError: n is null preact.module.js:1:7346
```
Preact version: 10.2.1
`webpack.config.js`:
```javascript
const path = require('path');

module.exports = {
    entry: "./src/index.js",
    output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, "dist")
    },
    devtool: "source-map"
};
```

This is likely not an issue with `htm` - I've tried rendering a component build with Preact's `h` function with the same result.

**Comment by oreganoli** [comment]
Nevermind - this seems to happen because the script is loaded before the body, or whatever element I'm mounting it on. My mistake, there is no bug. Still, the error message could be a little more specific.

**Comment by marvinhagemeister** [comment]
@oreganoli We do have nicer error messages for that. Simply import `preact/debug` to enable them💯
