### ISSUE TITLE
Question: is it possible build preact app as one single html file?

### ISSUE THREAD

**Issue by kishoreknowapp** [preactjs/preact#2248]
Hi,

I need a way to ship preact app (very small app) as a single html file. is this possible?

I need to embed this html into a mobile web-view and needed offline support

**Comment by marvinhagemeister** [comment]
Yes, you need to inline all resources like CSS, js and images as data urls into the HTML. There are numerous Tutorials for that out there as it's something that's not specific to a particular framework, and instead is something fundamental to the way the web works. You can do that with any website out there.
