### ISSUE TITLE
preact 10.X.X, missing lib directory ?

### ISSUE THREAD

**Issue by Breadbuddy** [preactjs/preact#2250]
Hello,
I have problem using preact 10.2.1 (haven't tried earlier versions). After installing and setting aliases i try to compile project but it throws errors on each component:
Module not found: Error: Cannot resolve module 'preact/compat/lib/ReactMount'

As I can see there is no such a directory "lib" in react/compat and, obviously, no libraries inside.
I checked that 'stand-alone' preact-compat had those libraries (tried using it and project compiled successfuly with preact-compat).
Could you help me with this?

React is 15.4.2

**Comment by marvinhagemeister** [comment]
We deprecated supporting APIs from react that are older than react 0.15. we did support than back in the 8.x release line which requires `preact-compat` as you noted.
