### ISSUE TITLE
Material-UI4 : Swipeable Drawer doesn't work properly

### ISSUE THREAD

**Issue by tky5622** [preactjs/preact#2256]
Swiping to open or close drawer don't work with preact.
only works swipe area's touch event.
In case of using react with same code, drawer works properly.

https://github.com/mui-org/material-ui/issues/18977

reproduction
sandbox (swipe is not work in sandbox editor)
https://codesandbox.io/s/exciting-worker-i67ug

[for reproduction] please swipe from right in this page
https://i67ug.sse.codesandbox.io/index

The cause of issue
https://github.com/mui-org/material-ui/issues/18977#issuecomment-573340815

**Comment by developit** [comment]
I had a really hard time with that demo since there's a bunch of Next.js stuff going on that isn't related to the bug.

Here's a preact-cli version of the MUI SwipeableDrawer code sample demonstrating the same result:

https://codesandbox.io/s/preact-mui-swipeable-drawer-73vmp

**Comment by tky5622** [comment]
The issue is solved by this PR
https://github.com/mui-org/material-ui/pull/19782/files

Thank you for your investigation !
