### ISSUE TITLE
Preact 10 rendering into document.body clobbers existing DOM nodes

### ISSUE THREAD

**Issue by cgwyllie** [preactjs/preact#2264]
Hello,

I'm seeing an unexpected behaviour when trying to render an app directly into `document.body`.

Maybe this isn't best practice but I'm using Preact in this way to append overlays and modal content to existing web pages, so it's not really a typical SPA where I control the entire page.

What is observed is that on first render an existing DOM node of the same type can be replaced by the rendered content. This does not happen with Preact 8 (although it seems subsequent updates just always append the content again).

What I'd expect is that the Preact app content is appended to the DOM if it was never previously mounted, and after that I'd expect only the 'Preact' nodes to be updated on subsequent renders.

You can see two examples here:

- Preact 8, semi-expected behaviour: https://codepen.io/cgwyllie/pen/YzPdPzW
- Preact 10, unexpected behaviour: https://codepen.io/cgwyllie/pen/QWwzWoQ

I found that if you render into a document fragment, then append the fragment to the body, this works as expected, but it performs poorly and feels a bit like a hack. The DOM nodes are removed from the fragment after initial render although Preact still manages to update them on subsequent renders.

I also looked into the 'replaceNode' parmeter of render, but couldn't achieve the desired effect with it.

Perhaps this isn't a bug, but I'm keen to understand exactly what is going on here, and if there is any more suitable workaround.

The use of Preact 10 is desirable because Fragments allow rendering multiple overlays at the same time without containing them inside another DOM node in the body.

Thanks,
  Chris

**Comment by cgwyllie** [comment]
Hi Jovi,

Thanks for the quick reply!

RE the portal option, yes I have since attempted this and confirm that wrapping `createPortal(<Fragment>...</Fragment>)` now behaves as I would expect.

To explain the use-case a little further tho, and gain a better understanding, the idea is a library for managing certian popover states then draws some UI using Preact.

Not all state exists in the UI component hierarchy, and is passed via props to the 'App' component. The desire to call `render(<App />, document.body)` multiple times is to drive UI updates based on the props managed outside of the UI state.

We did think about managing state inside the App component, but this seemed undersirable as it coupled the state management and UI concerns quite tightly. In our case, the UI is a small piece of the library behaviour and a lot of other state is managed without the UI needing to be aware of it.

Don't know if that helps explain, please ask for any further details!

**Comment by JoviDeCroock** [comment]
I have heard of this use case before for a `modals` library, what they did (and this happens for a lot of UI-libraries):

They create a placeholder node for the overlay and render into it when that component is requested, like my updated sandbox: https://codesandbox.io/s/muddy-moon-r9dze

Does this cover your use case?

**Comment by cgwyllie** [comment]
Hi Jovi,

That's helping make things clearer! Can you expand on:

> you should just make sure to only insert once for each time you want to render into a node

I take this to mean that for this case we should always use the 3-argument render, and replace into a node we only insert into the DOM once. Is that correct?

Thanks for taking the time on this issue, it's really appreciated!

**Comment by JoviDeCroock** [comment]
Yes, exactly in my codesandbox you see me do the following:

```
const firstPlaceholder = document.createElement("div");
document.body.appendChild(firstPlaceholder);
render(<App />, document.body, firstPlaceholder);

const secondPlaceholder = document.createElement("div");
document.body.appendChild(secondPlaceholder);
render(<App />, document.body, secondPlaceholder);
```

If we'd consider this to be abstracted out we should take in mind that this render call can also be used to update props as seen later in the sandbox like this:

```
render(<App newState={5} />, document.body, firstPlaceholder);
```

So let's assume we write

```
const renderModal = (Component, props) => {
  const placeholder = document.createElement("div");
  document.body.appendChild(placeholder);
  render(<Component {...props} />, document.body, placeholder);  
}
```

Then you'll have to make some way to uniquely identify said `placeholder` so you can reuse that for subsequent renders to update inserted properties, does this make sense?

An example could be

```
const renderModal = (Component, props, identifier) => {
  let placeholder = document.getElementById(`#${identifier}`
  if (!placeholder) {
    placeholder = document.createElement("div");
    document.body.appendChild(placeholder);
  }
  render(<Component {...props} />, document.body, placeholder);  
}
```

**Comment by cgwyllie** [comment]
Hi Jovi,

Thanks for your detailed explanations.

I've been trying to verify in our app, and from what I can see there is some strange behaviour using the 'replace' node render without also using a portal around the Fragment.

It seems for us that if the render (using replace) is called twice quickly without the portal wrapper, often the children of the UI component are not added to the DOM / they flash in then disappear on the subsequent renders.

I'm currently trying to verify this isn't some unrelated issue with our own state managment, but so far it looks as if both render calls receive the same props. Occasionally the UI widget children will render in, which makes this feel like some race condition (although that also strikes me as odd).

For us, adding the portal wrapper seems to resolve, and we can then either `render(<App />, placeholder)`, or `render(<App />, document.body, placeholder)`, both seem stable and to work without issue.

I'll also review the linked issue to see if it seems related.

Thanks again for your time on this.
