### ISSUE TITLE
Should useRef's TypeScript declaration also allow it to be "null"?

### ISSUE THREAD

**Issue by rdmurphy** [preactjs/preact#2268]
I noticed a subtle difference between Preact's `useRef` declaration and React's —  React's `useRef` type [has an overload that allows for the given `<T>` or `null`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b386065c272f250b98539176131bc82deb44f1bb/types/react/index.d.ts#L992), which is what you'd expect to be viable when you use `useRef` as directed by passing in `null` on initialization.

However Preact's [type for `useRef` doesn't account for this](https://github.com/preactjs/preact/blob/d439563134874a03d943c15460e6044d15632e0d/hooks/src/index.d.ts#L46-L60), which means it throws a type error immediately when it sees the `null` you initially passed.

Is this something that was intentionally excluded or was it perhaps an oversight?

Thank you!

**Comment by JoviDeCroock** [comment]
This is an oversight on our part and is welcome to be PR'ed

**Comment by armujahid** [comment]
@rdmurphy Can I take this up if you are not planing to send PR?

**Comment by peterbe** [comment]
Sorry for being late to the party but I upgraded recently and was hit with these cryptic errors. The solution was, much thanks to reading this issue + PR, to...

```diff
-  const textInputRef = useRef<HTMLInputElement>();
+  const textInputRef = useRef<HTMLInputElement>(null);
```

Although I admit I don't understand the details/subtleties of this but why can't `null` always be the default on these?
What's the point of a `Ref<HTMLInputElement | undefined>` type?
