### ISSUE TITLE
Preact 10.1.0 breaks Emotion styled components

### ISSUE THREAD

**Issue by eliseumds** [preactjs/preact#2275]
Version 10.1.0 broke my Emotion styled components using `preact/compat`.

CodeSandbox: https://codesandbox.io/s/cocky-stallman-27oh3

Change to version 10.0.5, for ex, and you'll see it working.

Possibly related to recent changes to className?

**Comment by hc-codersatlas** [comment]
Having tooltip and dropdown menus from baseweb framework break for similar reasons. 10.0 works and 10.1 onwards doesn't. It uses Styletron. Definitely not restricted to emotion.

**Comment by marvinhagemeister** [comment]
Found out what's causing this and the appropriate fix. Currently working on creating a unit test for our suite.
