### ISSUE TITLE
input tag with `size=null` crashes in Preact but not React

### ISSUE THREAD

**Issue by skvale** [preactjs/preact#2284]
This works in React
```jsx
<input size={null} />
```
But throws this error in Preact:

`Uncaught DOMException: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.`

repo created from `preact create default preact-input-size-null` as an example: https://github.com/skvale/preact-input-size-null

**Comment by marvinhagemeister** [comment]
Awesome, thanks a bunch for reporting this :+1:
