### ISSUE TITLE
The result of a nested React.Children.map is not consistent with React.isValidElement

### ISSUE THREAD

**Issue by skvale** [preactjs/preact#2286]
Something like:
```jsx
const ProblemChild = ({ children }) => {
  return React.Children.map(children, child => {
    return React.Children.map(child.props.children, innerChild => {
      return innerChild;
    });
  }).filter(React.isValidElement)
};

const App = () => {
  return (
    <ProblemChild>
      <div>
        <div>
          1
        </div>
        <div>
          2
        </div>
      </div>
    </ProblemChild>
  )
};
```

returns

```sh
1
2
```

in React, but nothing in preact/compat.

It looks like the nested React.Children.map causes `React.isValidElement` to return false for the `divs`

reproduce with this repo: https://github.com/skvale/preact-react.children.map-issue

**Comment by marvinhagemeister** [comment]
Awesome, thank you so much for taking the time to find a reproducible scenario :+1: They're making fixing these issues so much easier :100:
