### ISSUE TITLE
Preact 10.3.0 regression with react-fontawesome

### ISSUE THREAD

**Issue by luhis** [preactjs/preact#2308]
I am using Preact with great success.  Recently my Package bot updated to the latest version 10.3.0, but it's failing the render tests.  Branch here:
https://github.com/luhis/CodeGolf/tree/renovate/preact-10.x

Looking at it, in Preact 10.3.0, when I use FontAwesome, it's passing down an undefined className prop to the FontAwesomeIcon.
Rolling back to Preact 10.2.1 works fine with FontAwesome, and I can see it is passing in an empty string in the className prop.

I can work around it by specifying a className prop on the fontAwesome Icon component, however I cannot just specify an empty className as it gets mapped to undefined, i have to pass in a char in the string. Edit: I can pass in an empty class prop, and that is correctly routed to className in the Icon component, no errors there.

I will try to work out what is happening, but someone else might beat me to the answer.

**Comment by JoviDeCroock** [comment]
Thank you for the clear error description, I've put up a PR with the fix. This fix can be tried with the build provided here: https://github.com/preactjs/preact/pull/2309/checks?check_run_id=426445705

**Comment by luhis** [comment]
Thanks for this. I can confirm it fixed my issue
