### ISSUE TITLE
Is TypeScript completely supported?

### ISSUE THREAD

**Issue by nainardev** [preactjs/preact#2317]
If not, how much work is there?

**Comment by JoviDeCroock** [comment]
This is a pretty vague question, yes typescript is supported. We have a lot of `.d.ts` files in our repository these serve the purpose of providing typings for the jsx and the exported preact functions. [preact-cli](https://github.com/preactjs/preact-cli) offers a typescript preset out of the box

Are you encountering any specific issues or?
