### ISSUE TITLE
Preact is actually larger than React itself?

### ISSUE THREAD

**Issue by shirotech** [preactjs/preact#2325]
Perhaps I'm missing something, but it seems Preact is alot heavier than React in terms of bytes?

https://unpkg.com/browse/preact@10.3.1/dist/   - Production minified 9.3kB
https://unpkg.com/browse/react@16.12.0/cjs/    - Production minified 6.64 kB

**Comment by JoviDeCroock** [comment]
For React you also have to include: https://unpkg.com/browse/react-dom@16.12.0/cjs/ since both are needed to make an application

**Comment by marvinhagemeister** [comment]
As @JoviDeCroock said you need to take `react-dom` into account. The `react` package itself contains just the reconciler and no logic on how to render into the web. That's what `react-dom` comes into play. Preact is basically `react` + `react-dom` combined.

Here are the current sizes for the lazy:

| Framework | Size (min+gzip) |
|---|---|
| React + ReactDOM | 38.8kB (2.6kB + 36.2kB) |
| **Preact** | **3.6kB** |
