### ISSUE TITLE
Autofocus not working on Firefox

### ISSUE THREAD

**Issue by ohmlnz** [preactjs/preact#2328]
Hi there,

It seems like the `autoFocus` attribute  is not working properly on Firefox (latest version). All the other browsers are fine though. I've also tried the exact same app using React instead and haven't had any issues. 

It does work when using a ref and doing `inputRef.current.focus()` on mount but I'm curious as to why it would behave that way when using it as an attribute 🤔

I'm using Preact 10.3.0 by the way.

**Comment by JoviDeCroock** [comment]
I think this is something in firefox that's broken when reading threads like these: https://stackoverflow.com/questions/9955398/autofocus-attribute-of-html5-does-not-work-only-in-firefox-when-forminput-ar

**Comment by ohmlnz** [comment]
> I think this is something in firefox that's broken when reading threads like these: https://stackoverflow.com/questions/9955398/autofocus-attribute-of-html5-does-not-work-only-in-firefox-when-forminput-ar

You're right, it seems like something's off with how they deal with it. I was digging through React's codebase (since their autofocus works fine on Firefox) and they use `focus()` for consistent results.

It would be interesting to have a polyfill on Preact as well. Not a deal breaker but definitely more handy to use the attribute directly.

**Comment by JoviDeCroock** [comment]
@ohmlnz these event-polyfills are what makes React as big as it is and we give users the choice to add them themselves but won't ship with them.

**Comment by ohmlnz** [comment]
> @ohmlnz these event-polyfills are what makes React as big as it is and we give users the choice to add them themselves but won't ship with them.

@JoviDeCroock okay that's a fair point. Thanks for your input!

**Comment by bevali** [comment]
@ohmlnz  I just converted to preact and autofocus doesn't work for me in any browser now. It used to in react using `autoFocus="true".` Is there a different syntax needed to autofocus in preact?
