### ISSUE TITLE
Preact causes memory leak on useState?

### ISSUE THREAD

**Issue by avkonst** [preactjs/preact#2336]
I have spotted memory growth in a [performance benchmark](https://github.com/krausest/js-framework-benchmark). I have compared the same benchmark app with react. React clears memory when a component with useState is unmounted. Preact holds the state value after unmount:

![image](https://user-images.githubusercontent.com/3971413/74377643-34954b80-4e49-11ea-871c-ea8df9976abf.png)

I am not sure about the cause and if it is expected behaviour, but it definitely spoils performance comparison results for Preact and probably a red flag, which is worth investigating further.

## Here is how to reproduce it:

- Clone https://github.com/avkonst/js-framework-benchmark
- npm install
- npm start (notice webserver started, if it does not start check prerequisites here: https://github.com/avkonst/js-framework-benchmark)
- cd ./frameworks/keyed/preact-hookstate
- npm install
- npm run build-prod
- open crome at http://localhost:8080/frameworks/keyed/preact-hookstate/
- open development tools, memory tab
![image](https://user-images.githubusercontent.com/3971413/74378069-1e3bbf80-4e4a-11ea-89fe-612c366c58b8.png)

- take heap snapshot using chrome devtools
![image](https://user-images.githubusercontent.com/3971413/74378084-28f65480-4e4a-11ea-95ef-9cb2a6ddb7c0.png)

- click "Create 1000 rows"
![image](https://user-images.githubusercontent.com/3971413/74378093-2f84cc00-4e4a-11ea-9ca9-d91a38a9055f.png)

- take heap snapshot using chrome devtools
- click "Clear"
![image](https://user-images.githubusercontent.com/3971413/74378129-3d3a5180-4e4a-11ea-9d44-691a932853a6.png)

- take heap snapshot using chrome devtools

- go to snapshot 2 and setup comparison with snapshot 1
![image](https://user-images.githubusercontent.com/3971413/74378196-62c75b00-4e4a-11ea-9022-1a4383ccbedf.png)

- notice an object with 2001 allocations (this is the Hookstate state link referencing the state variable placed into useState)
- go to snapshot 3 and setup comparison with snapshot 2
![image](https://user-images.githubusercontent.com/3971413/74378314-9ace9e00-4e4a-11ea-8205-1380d590f6ec.png)

- notice only 1 state link deleted, although it is expected 2001 are deleted, at least eventually. 

- retantion tree for the state variable from useState() call is looking strange, I can not interpret much here:
![image](https://user-images.githubusercontent.com/3971413/74378551-057fd980-4e4b-11ea-963d-01964b4785fd.png)

I can see that React also retains states after component is unmounted, but it get's cleaned up eventually. I.e. if I run create/clear many many times in a loop, React releases states and you can see that about 1000 states are retained (about 4MB). If I run it many times with Preact, it retains all states from past mounted and unmounted components (I even reached 70MBs by doing this in cycle).

**Comment by avkonst** [comment]
BTW, if you are interested in to see how React compares with Preact on the benchmark with Hookstate, have a look here: https://github.com/avkonst/hookstate/issues/14#issuecomment-585023323

**Comment by developit** [comment]
Excellent analysis. A few initial guesses at the culprit here:

- circular references in the virtual DOM tree (`vnode._parent` 🔁 `vnode._children[0]`)
- `component._hooks` being attached to those vnodes as `vnode._component.__hooks`

**Comment by JoviDeCroock** [comment]
Hey @avkonst 

Thanks for the awesome explanation, we can validate point two made in the above reply by doing

```
yarn add https://github.pika.dev/preactjs/preact/pr/2337
```

I'll try this tonight or if you have time before I do feel free to report it! Thanks again for this awesome issue

**Comment by andrewiggins** [comment]
Hmm another circular reference is: (assuming `c.__hooks._list[0]` is the `useState` hook) `component.__hooks._list[0]._component == component`. Could that impact this?

**Comment by kiranmarshall** [comment]
I know this issue is pretty old, but it is still open. I wanted to see if this is any link to some totally weird behaviour I am seeing in my application. 

I have a hook which gets all possible user media video devices, filters them based on some undesirable properties, and then automatically populates the first one, if it exists. This works fine, but the peculiarity arises when I log the state value selectedDevice from anywhere it is accessible from within the component tree. 

Here is the code (partially redacted):

```ts
export const useDevices = () => {
  const [allDevices, setAllDevices] = useState<MediaDeviceInfo[]>([])
  const [selectedDevice, setSelectedDevice] = useState<MediaDeviceInfo | null>(null)

  useEffect(() => {
    navigator.mediaDevices.enumerateDevices().then((devices) => setAllDevices(devices))
    return () => setAllDevices([])
  }, [])

  const devices = useMemo(() => {
    const banned = ["unwanted", "devices"]
    return allDevices.filter((d) => {
      // filter here...
    })
  }, [allDevices])

  const handleDeviceChange = useCallback(
    (deviceLabel: string) => {
      // select device here...
    },
    [devices]
  )

  useEffect(() => {
    if (selectedDevice || !devices.length) return
    handleDeviceChange(devices[0].label)
  }, [selectedDevice, devices, handleDeviceChange])

  // console.log({ selectedDevice })

  return { devices, selectedDevice, handleDeviceChange }
}
```

If I console.log the property from a useEffect with any number of dependencies (including none, but not including no dependency array), the loop does not occur. Otherwise, it is an infinite loop which then blocks any further application state from loading or working.
I do not think this is a bug with the code I have written since the blocking loop does not occur otherwise.

If you can see some issue with the above code, please let me know, but otherwise I would be interested to know what the cause of this is. If I need to open this in a new issue with a minimal reproducible I am happy to do so. 
Equally I am happy to dig into the source code, given time, but I will need some guidance on how to get started with that.

**Comment by marvinhagemeister** [comment]
@kiranmarshall Please file a new issue. The problem you're describing is unrelated to memory growth.

**Comment by kiranmarshall** [comment]
@marvinhagemeister I ended up finding the issue and it was a totally unrelated. PEBCAK-ing hard, as usual. Thanks anyway!
