### ISSUE TITLE
Child gets ref while Element is not in DOM

### ISSUE THREAD

**Issue by quebits** [preactjs/preact#2341]
I'v made simple examples for `react` and `preact`. They have identical code except imports.

##### Preact example (https://stackblitz.com/edit/preact-children-example-1):

```typescript
import { render, createElement } from 'preact';
import { useCallback, useState } from 'preact/hooks';

const El = (props) => {
  const [inDom, setInDom] = useState(null)

  const ref = useCallback((node: HTMLElement | null) => {
    if (node) {
      setInDom(document.body.contains(node))
    }

  }, [])

  return createElement('div', { ref }, `#${props.id} in DOM: ${inDom}`, props.children)
}

render(createElement(El, {id: 1}, createElement(El, {id: 2})), document.getElementById('root'));
```

##### React example (https://stackblitz.com/edit/react-children-example-1):
```typescript
import { useCallback, useState, createElement } from 'react';
import { render } from 'react-dom';

const El = (props) => {
  const [inDom, setInDom] = useState(null)

  const ref = useCallback((node: HTMLElement | null) => {
    if (node) {
      setInDom(document.body.contains(node))
    }

  }, [])

  return createElement('div', { ref }, `#${props.id} in DOM: ${inDom}`, props.children)
}

render(createElement(El, {id: 1}, createElement(El, {id: 2})), document.getElementById('root'));
```

While `react` example shows that both elements in DOM on first render. `preact` example shows that only root (id: 1) element is in DOM.

I'm not found notes about it in preact's docs. Is it intended behaviour?

Also I see similar issues which are fixed but I don't understand in which way :). Could you clarify, please?

**Comment by JoviDeCroock** [comment]
Hey,

This is because our current diffing algorithm diffs top to bottom and when it reaches the bottom starts making/appending the nodes to the dom. This means that refs functions get called (on creation) before the node is actually appended to it's ancestor (in this case your root). When we switch over to 2-phase diffing we should be able to resolve this issue.

**Comment by JoviDeCroock** [comment]
Fixed in latest due to our transition to a `refQueue`
