### ISSUE TITLE
iframe reloads when parent's sibling returns null

### ISSUE THREAD

**Issue by tomrf1** [preactjs/preact#2350]
This caught us out in a recent upgrade from preact 8 to 10.
It does not happen with preact 8, nor react.
If a component updates and returns null (having previously been non-null), then any siblings' iframes will be reloaded. I'm not sure if it's expected behaviour in preact, but it took a long time to debug!

### Reproduction
Example here: https://codesandbox.io/s/runtime-silence-no4zx

### Steps to reproduce
In the above example:
1. Type an 'e' in the input, causing the `Label` component to render.
2. Deleting the 'e' triggers `Label` to return null, which unexpectedly(?) causes the `Iframe` component's iframe to be recreated.

### Expected Behavior
The iframe is not reloaded when a separate component returns null.

### Actual Behavior
The iframe is reloaded.
Making the `Label` component return e.g. `<div></div>` instead of null fixes the issue.
Also, moving the `Label` component below the `Iframe` component also fixes it.

**Comment by marvinhagemeister** [comment]
Awesome, thank you so much for the detailed bug report :heart: :+1: With it I'm able to reproduce the problem.

Some preliminary debugging reveals that this issue only occurs when the `iframe` itself or one of it's parent DOM nodes were moved via `appendChild/insertBefore`.

**Comment by marvinhagemeister** [comment]
Here is a slightly reduced test case:

```jsx
import React from 'preact/compat';

function Label(props) {
	return props.value.includes('e') ? 'has e' : null;
}

class Outer extends React.Component {
	state = { value: '' };
	render() {
		return (
			<div>
				<input
					onChange={ev => this.setState({ value: ev.target.value })}
					type="text"
				/>
				<Label value={this.state.value} />
				<iframe src="https://example.com" />
				<Label value={this.state.value} />
			</div>
		);
	}
}

render(<Outer />, document.body);
```

**Comment by marvinhagemeister** [comment]
Ah it looks like we match the wrong child when diffing the `iframe`. Instead of diffing the old one against the new one we diff it against the label before it.
