### ISSUE TITLE
Hooks failure on functional component as root

### ISSUE THREAD

**Issue by mkrasuski** [preactjs/preact#2357]
simple code like
```
import { h, render } from 'preact'
import { useState } from 'preact/hooks'

function Root(props) {
 const [ c, setC ] = useState(0) 
 return h('h1', { onClick:()=>setC(c+1) }, `counter is ${c}`)
) 

render(Root(), document.body)
```
fails with `TypeError: Cannot read property '__H' of undefined`
due to undefined `currentComponent` within hooks

notice that `currentComponent` is set on pre-render phase, but in case of `Root` being functional hook must be initialized before any render.

**Comment by cristianbote** [comment]
Hey @mkrasuski,

You need to wrap `Root` in a `h` call as well, when passing it to render. This is the whole code block:
```js
function Root(props) {
 const [ c, setC ] = useState(0) 
 return h('h1', { onClick:()=>setC(c+1) }, `counter is ${c}`)
} 

// Wrap the `Root` with `h` as well
render(h(Root), document.body)
```

Here's a jsfiddle that works with the above correction: https://jsfiddle.net/cristianbote/mjgq95dc/

**Comment by mkrasuski** [comment]
Thanks!
even simple `render(Root, el)` works, but what if we've to pass props to Root?

**Comment by JoviDeCroock** [comment]
`render(h(Root, { ...yourProps }), document.body)` would be the way to accomplish that

**Comment by mkrasuski** [comment]
Ok, I know `h(Root, {props})` will do the trick. But is it possible to break hooks' dependency from render environment? So many issues are reported due hooks limitations by this...

**Comment by JoviDeCroock** [comment]
That's not the purpose of hooks, hooks are a layer to enable stateful functional components. The complexity of them shouldn't be extended outside of reactive environments since the solutions there can be much easier.

Am I misunderstanding your question?

**Comment by mkrasuski** [comment]
Not exactly... Now `currentComponent` is set on pre-render and there are many issues with mis-use of hooks (like mine) with similar error like mine. Wonder if that dependency (hook acces only within render call) can be avoided.

**Comment by JoviDeCroock** [comment]
No it can't, do you have a use case where you would want to use a hook outside of `render`?

**Comment by mkrasuski** [comment]
Just noticed that many issues were similar to mine, but in other situations. Users had troubles with that and minified CDN versions of preact are little bit mysterious on that. Maybe some doc mentions on that would be also useful. Ok, thanks for your lightning fast and valuable support...and for great preact.
