### ISSUE TITLE
cloneElement type should include VNode?

### ISSUE THREAD

**Issue by Linksku** [preactjs/preact#2363]
Should the first argument and the return value of cloneElement be VNode and not Element? It's Element in the Typescript definition.

**Comment by ddayguerrero** [comment]
👋 I'm interested in looking into this. From what I can investigate, the issue here is a typing one.

```typescript
function cloneElement(
  vnode: JSX.Element,
  props?: any,
  ...children: ComponentChildren[]
): JSX.Element;
```

where `vnode` should return a `VNode`?

As of now, everything seems to work https://codesandbox.io/s/cloneelement-issue-o0x31. If anyone can confirm that would be nice!

**Comment by JoviDeCroock** [comment]
Hey!

Yes, we should be returning VNode and here's why:

- In `cloneElement` we call `createVNode` https://github.com/preactjs/preact/blob/master/src/clone-element.js#L14 
- In `createVNode` we make a `VNode` structure https://github.com/preactjs/preact/blob/master/src/create-element.js#L59
- We use `createVNode` for `createElement` (our jsx constructor) and this is the return type for that last method: https://github.com/preactjs/preact/blob/master/src/index.d.ts#L176
