### ISSUE TITLE
React-spring not working with Preact

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact#2384]
_Reported via Slack by @Faisal-Manzer._

## Reproduction

https://codesandbox.io/s/react-spring-kyyrw

### Steps to reproduce

1. Click and drag the background image. Same should work for touch events.
2. The background should switch to the next one, similar to a slider.

### Expected Behavior

React: https://codesandbox.io/s/n9vo1my91p?from-embed

### Actual Behavior

The images don't slide at all. Unable to switch to the next slide via drag/touch events.

**Comment by Faisal-Manzer** [comment]
Is issue with React Spring or is with that particular example?

**Comment by marvinhagemeister** [comment]
It's working in React so my guess is that there is something we don't do correctly in Preact. Most animation libraries rely heavily on specific `ref` timings, maybe we stumble on one of those assignments.

**Comment by marvinhagemeister** [comment]
Ahh found the culprit. The issue is caused by a different version of `react-use-gesture`. Updating to the latest version of that library breaks the React sandbox in the same way as with React. Downgrading it to `5.0.0` as in the original sandbox resolves that issue.

Closing this and marking as invalid as the issue is present in both React and Preact. My guess is that some of the APIs have changed of `react-use-gesture` in the two major versions that followed `5.0.0`.

Updated Preact sandbox where it's working: https://codesandbox.io/s/react-spring-kyyrw
