### ISSUE TITLE
Camelcase string prototype breaks preact/compat

### ISSUE THREAD

**Issue by damianhodgkiss** [preactjs/preact#2387]
When something has extended String with a camelcase function and using preact/compat, all strings are rendered as [object Object].

https://github.com/carrot/share-button/issues/265 is extending String with two functions, which isn't best practices but still shouldn't break preact.  This is due to the prefix cap matching the CAMEL_PROPS test.

### Steps to reproduce

`
String.prototype.capFLetter = function() {
  return this.charAt(0).toUpperCase() + this.slice(1)
}
`

prior to loading preact/compat.

This is traced to https://github.com/preactjs/preact/blob/master/compat/src/render.js#L127 which is treating props as an object when it can also be a string.

A suitable fix is:

`
if (typeof props !== 'string') for (i in props) if ((shouldSanitize = CAMEL_PROPS.test(i))) break;
`

This is the main issue, although unrelated the preact source contains lots of for (x in y) without using Object.hasOwnProperty() checks.

### Expected Behavior

Strings should work.

### Actual Behavior

All strings are rendering as [object Object]

**Comment by developit** [comment]
Hmm - props should never be a String in that callback. This seems like a potential issue with re-calling of `vnode` hooks on normalized children.

**Comment by damianhodgkiss** [comment]
Yeah not sure what the problem is mate,  not familiar enough with the code just tracked a bug down to there hence the patch so we could move past but I guess you'd know if it was a problem deeper up.

**Comment by JoviDeCroock** [comment]
Hey @damianhodgkiss 

Thanks for the nice issue-report, it was easy to reproduce and resulted in the fix PR! https://github.com/preactjs/preact/pull/2410

**Comment by damianhodgkiss** [comment]
wow quick work, very nice mate, look forward to the release.
