### ISSUE TITLE
'markerWidth' and 'markerHeight' svg attributes getting converted to 'marker-width' and 'marker-height'

### ISSUE THREAD

**Issue by moklick** [preactjs/preact#2404]
The SVG attributes `markerWidth` and `markerHeight` getting converted to `marker-width` and `marker-height` which are invalid attributes.

Input:
```
<marker id="arrow" viewBox="-10 -10 20 20" markerWidth="20" markerHeight="20" />
```

Preact output:
```
<marker id="arrow" viewBox="-10 -10 20 20" marker-width="20" marker-height="20" />
```

**Comment by marvinhagemeister** [comment]
To add to the above: The expect output is that the attribute names are not changed in casing. See the SVG spec:

- [markerWidth](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerWidth)
- [markerHeight](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerHeight)

**Comment by marvinhagemeister** [comment]
...and here is a page with all SVG attributes https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute 🎉✌️

**Comment by ddayguerrero** [comment]
👋 Curious about looking into this and I'm unable to reproduce on version 10.3.4.

In my [sandbox](https://codesandbox.io/s/preact-svg-issue-2404-dqxrs), I'm still getting `markerWidth` and `markerHeight` as rendered attributes.

Also not aware of particular normalization conditions with SVG when creating elements https://github.com/preactjs/preact/blob/master/src/create-element.js#L11.

I might be missing but would be glad to help!

**Comment by JoviDeCroock** [comment]
Hey @ddayguerrero 

These normalizations happen in our `compat-layer` and will only be there if you use `preact/compat` https://github.com/preactjs/preact/blob/master/compat/src/render.js#L137

**Comment by ddayguerrero** [comment]
Oh, missed that. Thanks for the guidance! 🙇

**Comment by jamesb3ll** [comment]
Are you using the latest version of Preact? This was fixed in v10.3.3 in this PR:
https://github.com/preactjs/preact/pull/2366
If you have a look at the tests it covers this test case for `markerWidth` and `markerHeight`.

**Comment by marvinhagemeister** [comment]
@jamesb3ll good catch :+1: 

@moklick are you sure that you are using the latest version of Preact?

**Comment by moklick** [comment]
oh no.. I was using v10.3.2.
