### ISSUE TITLE
A component that is a child of a PureComponent and uses useContext does not re-render when the context value is set to its initial value

### ISSUE THREAD

**Issue by mindgrub-egottlieb** [preactjs/preact#2419]
### Reproduction

[CodeSandbox Demo](https://codesandbox.io/s/preact-usecontext-issue-76cd8)
[React version of same demo](https://codesandbox.io/s/preact-usecontext-issue-working-properly-in-react-gyt22)
The VDOM tree is as follows:
```
App Root
L Context Provider(s) 
  L PureComponent wrapper
    L Everything else
```
Global app state is stored/managed by via `useState` or `useReducer` in the same component that creates the context provider(s). The state and its dispatch function are passed into `Context.Provider`s, which are then consumed by other components using `useContext`. The bug occurs when I change the value of the context.

### Expected Behavior

The context consumer should re-render whenever the context is updated, and other components that don't consume that context should not re-render. This behavior can be observed in the React version of the demo.

### Actual Behavior

When the consumer is wrapped in a PureComponent, it does not re-render when the context value is changed back to its initial value. 
When wrapped in a normal component, the consumer re-renders on context changes, but so does its sibling, which does not consume any contexts.

The latter is a discrepancy between the behavior of React and Preact that I discovered while making these demos. To my surprise, when the app content is wrapped in a normal component in React, components that don't consume context still don't re-render when context values are updated.

I also did [a quick version of the demo](https://codesandbox.io/s/preact-usecontext-issue-with-contextconsumer-gsily) using `Context.Consumer` instead of `useContext`, and it exhibits the same behavior.

**Comment by JoviDeCroock** [comment]
Hey,

Those were some wonderful reproductions that enabled me to quickly solve this issue, they look super nice as well! Thank you so much, awesome awesome issue report can't say this enough!
