### ISSUE TITLE
PR: Add support for e2e testing

### ISSUE THREAD

**Issue by amilajack** [preactjs/preact#242]
What if we could borrow react's end-to-end tests (or whatever high level tests they have that dont test internal methods) and use them as our own e2e tests?

Willing to make a PR for this.

**Comment by developit** [comment]
That would be amazing. I was actually thinking about this last week. Curious to see if it would work!

**Comment by gaearon** [comment]
I agree it’s a great idea, especially now that we have several libs claiming React compat.
These are some interesting tests you might want to consider porting over:


https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactMultiChildReconcile-test.js

https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactMultiChild-test.js

https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactMultiChildText-test.js

https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactCompositeComponent-test.js

https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactCompositeComponentState-test.js

https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactCompositeComponentNestedState-test.js

https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactCompositeComponentDOMMinimalism-test.js

**Comment by developit** [comment]
Awesome, thanks Dan.  Not sure if @amilajack is still interested, if not I can do the port!

**Comment by amilajack** [comment]
Sorry for not delivering the PR. I'll definitely looking into this. I've just started my sophomore school of college so I've been a bit busy recently. But I'll definitely start working on this.

**Comment by developit** [comment]
@amilajack no worries! I just didn't want to step on toes 😊

**Comment by amilajack** [comment]
<img width="271" alt="screen shot 2016-08-30 at 2 04 12 pm" src="https://cloud.githubusercontent.com/assets/6374832/18106964/af5f8582-6eba-11e6-829c-6b3c0173d38b.png">

**Comment by calebmer** [comment]
@amilajack or @developit I'd love to help, but unfortunately I can't give any time 😖

I'd like to make a request though, could this be non-Preact specific? Could we instead develop a test spec that can be run against any implementation that claims to follow the React API? I've definitely tried writing my own JSX diffing/patching algorithms before and a suite like this would have been super helpful.

I believe a suite of Preact independent tests would not only raise Preact's claim of being a drop in React replacement, but also improve the quality of the entire JSX rendering ecosystem and perhaps even inviting more external contributors potentially including some more core React team members.

This would better allow the community to focus on *contracts* and free the community to excitement with implementations.

**Comment by calebmer** [comment]
A good example of this in the wild is the observable proposal's test suite: https://github.com/tc39/proposal-observable/tree/master/es-observable-tests

**Comment by amilajack** [comment]
What about something like html acid tests?

http://www.acidtests.org

**Comment by calebmer** [comment]
So theoretically these tests don't have to be tied into the DOM considering React is trying to decouple itself from the DOM. When Preact runs the suite it will need a DOM, but if React ran the suite it should be able to use say the test renderer or a native renderer as well as a DOM renderer.

See the tests @dan_abramov linked and how they are written, I'm not sure if they are DOM specific.

**Comment by gaearon** [comment]
Yea, they’re not. I’m sure that DOM specifics will differ anyway (e.g. most impls don’t want to have event normalization like in React). I think what would be most valuable is to ensure that composite components, lifecycle, ref resolution, etc, works the same way.

We would obviously change React component model with time too. So unlike Promise A+ tests or similar, you can expect some churn with this. But if anything, having a shared test suite would help people to catch up with us, if they want to.

**Comment by calebmer** [comment]
Yeah, and I know Preact doesn't support `React.createClass`, but the test suite should probably include it for completeness sake as there's still a lot of legacy code that depends on it (and it's somewhat easier for beginners). Preact could just opt-out of those tests (unless I missed something and Preact *can* support `createClass` 😉).

**Comment by gaearon** [comment]
FWIW we’ll be separating `createClass` into a separate package. I don’t quite see the point of Preact reimplementing it because it should be usable as is—it just provides a class React can then use (and presumably its result would work with Preact as well).

**Comment by developit** [comment]
@gaearon not sure how this slipped through my inbox, but modularizing `createClass()` sounds like a great idea.  I'd be happy to switch `preact-compat` over to depending on that when available.

**Comment by marvinhagemeister** [comment]
We switched our test suite to run against real browsers. This includes several e2e tests that assert the final DOM output after specific actions have occured :+1: :100:  These tests are already in `master` so I think it's safe to close this issue :)

**Comment by chrisha22** [comment]
Hello @developit , I'm kind of confused here, I hope you bring me some clarification regarding to e2e testing support for preact, what is the current status of it?

is there any e2e framework compatible with preact?
