### ISSUE TITLE
`Component.render`'s `props` and `state` parameters should not be optional

### ISSUE THREAD

**Issue by b-gyula** [preactjs/preact#2421]
### Reproduction

`Component.render`'s `props` and `state` parameters are great and very convenient, but it should not be optional, since both `this.props` and `state` are defined for every `Component`. If it's not really necessary to call it without parameter, the typescript  definition shall not be define it as optional. (`Component.props` and `state` properties are not defined optional)

### Expected Behavior

`Component.render`'s `props` and `state` should not be optional

### Actual Behavior

`Component.render`'s `props` and `state` parameters optional

**Comment by jeremy-coleman** [comment]
Properties that have  initial values should be optional

**Comment by imrishabh18** [comment]
@marvinhagemeister Is this issue still relevant? Can I work on this?
