### ISSUE TITLE
Exception thrown during `act` callback breaks future effects

### ISSUE THREAD

**Issue by robertknight** [preactjs/preact#2432]
From the [code for `act`](https://github.com/preactjs/preact/blob/ca42c53210db925fe14d8f0f9122eb3bf43556d7/test-utils/src/index.js#L68) it is clear that exceptions thrown by the callback passed to `act` are not handled. If an exception is thrown, the cleanup code that flushes effects and renders before `act` returns is not run. As a result, the pending render/effect queues are left non-empty and subsequent calls to state updaters / `useEffect` don't schedule flushes of these queues.

A result that we've observed in our test suite is that one test failing with an error thrown inside a call to `act` ends up causing a cascade of spurious failures of other tests because any subsequent `useEffect` effects stop working.

### Expected Behavior

If an exception occurs in `act`'s callback, this should not affect future renders or effects.

### Actual Behavior

If an exception occurs during an `act` callback, the queue of pending renders and effects may be left non-empty. As a result, future state updates and effects don't schedule flushing of these queues.

**Comment by marvinhagemeister** [comment]
I'll see to cut a release shortly. Mainly I want to get #2386 in before making one 🙂
