### ISSUE TITLE
import ... from 'unpkg.com/preact/hooks?module'

### ISSUE THREAD

**Issue by joneit** [preactjs/preact#2439]
Is there a missing `unpkg` property in hooks/package.json ?

How do you load preact/hooks via unpkg.com?
(besides specifying a fully qualified file path 'preact/hooks/dist/hooks.module.js')

### Reproduction

https://unpkg.com/preact/hooks?module

### Steps to reproduce

Click link above

### Expected Behavior

Expected to be served response similar to that of https://unpkg.com/preact/hooks/dist/hooks.module.js

### Actual Behavior

```
Cannot find an index in "/hooks" in preact@10.3.4
```

**Comment by JoviDeCroock** [comment]
unpkg doesn't support subroutes so the import should be like this, https://github.com/JoviDeCroock/Vanilla-Preact-Application/blob/master/src/modules/home/index.js#L1

**Comment by marvinhagemeister** [comment]
Closing, since this is an issue with `unpkg` which doesn't seem to adhere to the node resolution algorithm completely. That should be fixed in `unpkg`.
