### ISSUE TITLE
Typescript definition for act does not account for promises

### ISSUE THREAD

**Issue by davidje13** [preactjs/preact#2441]
The [type definition for `act()`](https://github.com/preactjs/preact/blob/master/test-utils/src/index.d.ts#L2) implies it is always synchronous, but it actually [returns a promise in all cases](https://github.com/preactjs/preact/blob/master/test-utils/src/index.js#L27) (even if not given a promise-generating function).

### Reproduction

```ts
import { act } from 'preact/test-utils';

// Both of the following are valid, but rejected in TypeScript:

// calling .then()
// Property 'then' does not exist on type 'void'.
act(foo).then(() => {});

// or a linter rule:
// Unexpected `await` of a non-Promise (non-"Thenable") value (@typescript-eslint/await-thenable)
await act(async () => {
  // ...
});
```

### Expected Behavior

`act` should be marked as returning `Promise<void>` (and ideally as consuming `() => (Promise<void> | void)`, though that is more just for documentation.

**Comment by ddayguerrero** [comment]
Hey @davidje13, hope you don't mind that I took a stab at this (fairly straightforward)! I can mark it as ready if we're good 🙇‍♂️
