### ISSUE TITLE
Add support for React.StrictMode in preact/compat

### ISSUE THREAD

**Issue by davidje13** [preactjs/preact#2442]
I'm not sure if this would ever actually be implemented since I imagine this represents a lot of work, but React's `StrictMode` is useful for identifying non-pure components during development (it is automatically disabled in production builds). It would be nice if preact could offer similar functionality.

Since `StrictMode` is usually a whole-app wrapper (rather than used by individual components), it's less important to be API-compatible, so there's some flexibility in how this could look (e.g. one alternative would be to add a configuration option to `render` and consider this a global property, rather than a scoped one, if simpler).

For those unfamiliar, `StrictMode` will cause functional components, `render`, `shouldComponentUpdate`, etc. to be invoked twice (with the same arguments each time) whenever an update happens, and assert that it receives equivalent results both times (ignoring some things like function instances). This catches the majority of non-pure behaviour in components.

**Comment by devlato** [comment]
+1 to this issue 👍

**Comment by damianobarbati** [comment]
@developit would you consider adding a temporary "proxy" component (which just renders its children) while this is discussed, so that switching between `react` and `preact` does not result in a break in the application?

Thanks to StrictMode I can spot weird bugs in components I would probably never spot otherwise. So I'm developing with React but shipping Preact in staging and production environment.

**Comment by developit** [comment]
Yeah I think we could do that. It would just be an alias of Fragment.

**Comment by davidje13** [comment]
I'd caution that adding this as an alias of `Fragment`, though useful for compatibility in damianobarbati's use case, could give other developers a false sense of security. It's not obvious like this that `StrictMode` does no extra checks. As an interim solution, could it be implemented in a way which logs a message to the console when in dev mode (explaining that preact does not support `StrictMode`)? (if built in production mode it could be an alias of `Fragment` to save space).

I don't know if preact has any existing behaviour changes between dev and prod so it might not be trivial to implement depending on how the build is done.

**Comment by marvinhagemeister** [comment]
@davidje13 That's the tricky bit: We don't support different dev and prod builds as that would break es-module import. In general debug stuff lives in an additional module called `preact/debug`.

We merged the proxy variant for compatibility reasons. That way developers can easily try out Preact via a simple alias and don't have to do any real code changes. This is very high priority for us that it stays that simple.

This gives us time to think about a proper implementation or about better strategies to verify the pureness of render methods.
