### ISSUE TITLE
Debug helpers break the react-i18next <Trans> element

### ISSUE THREAD

**Issue by d3x7r0** [preactjs/preact#2445]
When trying to use react-i18next's <Trans> element I was confronted with the error message `getting vnode.children is deprecated, use vnode.props.children`. Removing the helpers removed the issue.

The issue seems to arise from these lines:
https://github.com/preactjs/preact/blob/384add36716177315f8458a352e6dca9da4ead25/debug/src/debug.js#L233-L246

I wonder if changing it to warn on console instead would be a better solution?

### Reproduction

Here's a simple use repo showing the issue using preact-cli:
https://github.com/d3x7r0/preact-i18next-issue

### Steps to reproduce

- Run the example using `npm run dev`
- Error should show up in console

- Run the example using `npm run build && npm run serve`
- Element should work correctly

### Expected Behavior

The component should correctly translate the string with correct string interpolation

### Actual Behavior

An error is thrown since the lib accesses `vnode.children`

**Comment by marvinhagemeister** [comment]
This was fixed in #2477 🎉
