### ISSUE TITLE
Focus displacement when components are added to a list above

### ISSUE THREAD

**Issue by wnayes** [preactjs/preact#2446]
### Reproduction

I've created a small sample that appears to me to have a focus handling bug.

https://codesandbox.io/s/preact-focus-boxes-m15qd

```ts
import { render } from "preact";
import { useState, useCallback, useRef } from "preact/hooks";

function App() {
  const boxNum = useRef(1);
  const [boxes, setBoxes] = useState([1]);

  const boxComponents = boxes.map(num => {
    return <div>box</div>;
  });

  const onAddBoxToEnd = useCallback(() => {
    boxNum.current++;
    setBoxes(boxes => [...boxes, boxNum.current]);
  }, []);
  const onAddBoxToFront = useCallback(() => {
    boxNum.current++;
    setBoxes(boxes => [boxNum.current, ...boxes]);
  }, []);

  return (
    <div>
      {boxComponents}
      <br />
      <button onClick={onAddBoxToFront}>Add box to front</button>
      <button onClick={onAddBoxToEnd}>Add box to end</button>

      <p>
        Place focus on either button and press space. Focus leaves the button,
        appearing to be offset due to the element changes above.
      </p>
    </div>
  );
}

if (typeof window !== "undefined") {
  render(<App />, document.getElementById("root"));
}
```

### Steps to reproduce

In the demo above:

1. Place focus on the second button.
2. Press spacebar.

### Expected Behavior

Expected focus to remain on the button that was activated, since it did not unmount.

### Actual Behavior

Focus moved to the prior button. It appears focus is offset by the number of elements inserted above (1) in the example.

The first button also has the issue, but it's less clear to see where focus goes, because there's no prior elements with focus indication.

**Comment by JoviDeCroock** [comment]
Could you try adding a key property on your divs, this is recommended in most fe frameworks for this scenario

**Comment by wnayes** [comment]
If I [add `key={num}` to the boxes map in the example](https://codesandbox.io/s/preact-focus-boxes-fcl9b), it continues to behave the same. I hadn't thought of `key` possibly being the cause here, though I definitely agree this example should be keyed in a real scenario.

**Comment by JoviDeCroock** [comment]
If `num` in this case is an array index it's supposed to fail since that's exactly the same as not keying, a key is meant to describe the element not it's position.

**Comment by wnayes** [comment]
The keys aren't technically array indices here, they're the array values. It's a bit contrived, but this demo creates a `<div key={num}>box {num}</div>` for each `num` in a number array. So for `[1, 2, 3]` we make 3 div boxes with those numbers as keys.

In any case, this demo only adds additional components to the list, so even with array index keys, I would expect the framework to behave the same.

From what I've seen, removal is showing correct focus behavior in a larger example, so I only scoped the repro to show adding.

**Comment by JoviDeCroock** [comment]
So the thing is that we're a bit different when it comes to keying in the sense that when there's a variable amount of elements combined with static ones like your buttosn we require the buttons to also be keyed.

**Comment by andrewiggins** [comment]
Another workaround - wrap your `{boxComponents}` in a `<Fragment>` so the list items aren't siblings of the buttons that require focus. With that workaround, you don't need to key the box components either (though in general, as was previously stated, it's probably a good idea 🙂)

https://codesandbox.io/s/preact-focus-boxes-c63zg

**Comment by wnayes** [comment]
It is good to know some workarounds, so I can advise developers at my company what to do if they run into this sort of issue.

I haven't been able to find any note about this difference in the docs, and it seems quite unexpected to me. I assumed the behavior from React, where it distinguishes arrays of children from static children, would apply here. If this limitation applies to the general reconciliation algorithm of preact, it seems important to know (possibly important enough to document [here](https://preactjs.com/guide/v10/differences-to-react/)). If these buttons were more complex components, it would be important for them to be keyed in order to avoid strange rendering issues (state being applied from one to the other, etc.).

So regarding this issue - it seems it could be used to track a potential change to the key behavior, or it could be closed if this issue is being tracked elsewhere or is intentional.
