### ISSUE TITLE
Feature: keep existing DOM attributes

### ISSUE THREAD

**Issue by dioslaska** [preactjs/preact#2449]
I have a use case where I'd like to keep the existing attributes on the elements, when rendering a Component into the DOM.

Here's an example:

Existing DOM node:

```
<div id="outer" data-foo="foo">
  <div id="inner" data-bar="bar"></div>
</div>
```

Component:

```
const TestComponent = () => <div class="outer">
  <div class="inner">
    Test component
  </div>
</div>;
```

Expected output:

```
<div id="outer" data-foo="foo" class="outer">
  <div id="inner" data-bar="bar" class="inner">
    Test component
  </div>
</div>
```

This did work in Preact 10.0.0, but not anymore in 10.0.1, as  mentioned in [this issue](https://github.com/preactjs/preact/issues/2022), so it look like this was actually a bug in 10.0.0?

Codepen with Preact 10.0.0: https://codepen.io/dioslaska/pen/mdebjga
Codepen with latest Preact: https://codepen.io/dioslaska/pen/jObNpdP

If yes, could you point me in the right direction what exact changes were made to avoid this? I could maybe use a custom preact version, if this won't be possible in the future. Also, I can't stick with 10.0.0 either, since there are other bug present as well.

A little details on the use case to explain why would be this useful: I'm working on a UI library supporting multiple frameworks. We need to support plain Javascript / jQuery as well, and the approach is to re-use the React components, and render them into the DOM using Preact.

A real world example, which enhances an existing input

```
<label id="my-label">
  <input id="my-input">
</label>
```

The Preact component will be rendered in the place of the label element. This works fine, but starting from Preact 10.0.1 the ids and other attributes are removed from the pre-existing elements.
This is not ok, since the users of the library should be able to access the elements, e.g. using getElementById, to add event listeners, etc.

Please let me know if there's any solution for this, or plans on changing this, or, in worst case, what could be modified in the preact source to make this work, and what are the potentially unwanted side effects.

**Comment by JoviDeCroock** [comment]
I can never edit codepens for some reason, could you try using `hydrate` instead of `render`? 😅

**Comment by dioslaska** [comment]
Thanks for getting back!

`hydrate` does not allow to specify the `replaceNode`, so if I specify my element as parent, the TestComponent will be rendered inside the given element (not replacing it). Also, it assumes the markup is completely ready, while my components might have additonal markup, and additional attributes as well - like css classes, aria attributes etc.

**Comment by developit** [comment]
Here's a workaround for hydrate that lets you specify the replaceNode:

```js
import { hydrate } from 'preact';

const toReplace = document.getElementById('inner');
hydrate(<App />, { childNodes: [toReplace] });
```

**Comment by dioslaska** [comment]
@developit 
Thanks for the tip, it solves indeed the extra outer element issue, it also keeps the existing attributes, but, as I mentioned previously, it will not add new attributes to the pre-existing elements. (https://codepen.io/dioslaska/pen/jObNpdP)
I'm trying to figure out what changed between 10.0.0 and 10.0.1 that changed the behavior on this.
I saw a reference to [this pull request](https://github.com/preactjs/preact/pull/1970/commits/7e4bdda4217e672c2f9350efabfdfd04bdaf17c8), but that change is about something else. I beleive it's something in the diffing algorithm, but so far I could not isolate the exact lines. Any help would be appreciated.

**Comment by dioslaska** [comment]
Meanwhile we release our first beta version using Preact 10.0.0 - I managed to find workarounds for the Preact issues causing problems (see it in action: https://demo.mobiscroll.com/v5/jquery/eventcalendar)

But I'm still interested on possible solutions for this (on keeping existing DOM attributes), because it  would be nice to get the benefits of the fresh Preact releases as well.

**Comment by developit** [comment]
@dioslaska I believe Preact 10.4.5 (not 100% sure if I got the patch version right) introduced support for morphing mismatched nodes during hydration, which should now fix this if using the trick I posted previously.

**Comment by dioslaska** [comment]
@developit 
I tested it with Preact 10.4.6, but still works the same: `hydrate` keeps the existing attributes on the DOM elements, but will not add any new attribute, like class, etc., like `render` does.
Here's the updated example: https://codepen.io/dioslaska/pen/jObNpdP

I'd really like to update to a newer version, since 10.0.0 has some bugs where the DOM element contents are getting mixed up, which I could overcome just by always forcing component re-render by passing an updated prop, but this has performance impacts as well.

**Comment by marvinhagemeister** [comment]
@dioslaska I think there is a misunderstanding of what `hydrate()` does. It is expected that it does not change the DOM and only attaches event listeners, otherwise it'd be the same thing as `render()`. We have the above-mentioned bailout for `hydrate()` in certain circumstances, but that's it.

**Comment by dioslaska** [comment]
@marvinhagemeister Yeah... I was aware that hydrate normally does not change the DOM, I just thought that the trick by @developit makes it work somehow.

So going with hydrate probably won't work. I'd be good with a modified version of the source code as well, where the `render` function keeps the existing attributes, I just could not figure it where this is handled - I figured out that this changed between 10.0.0 and 10.0.1, but was not able to identify the exact changes.

**Comment by developit** [comment]
If you're able to update to the latest version I know the spot that would need to be bypassed. There is probably a way to do it as a plugin.

**Comment by dioslaska** [comment]
@developit That sounds great. I can easily update to the latest, and do the changes where needed. Doing it as a plugin would be even better of course.

**Comment by dioslaska** [comment]
@developit I'm still interested in this. Meanwhile there were other priorities, and we lived with the workarounds for 10.0.0, but we're encountering other Preact bugs that are most probably fixed in more recent versions, so having this working would great.

**Comment by dioslaska** [comment]
@developit Just following up on this, to see if you can point me in the right direction, since I'd like to update to the latest Preact version in our library.

**Comment by marvinhagemeister** [comment]
@dioslaska Even there would be a band-aid that would paper over this for now, there is a very high chance that relying on this specific behavior will break in future versions. Your best path forward is to not rely on keeping unknown attributes around.

The third parameter to `render()` has caused a lot of headaches and is the main source for a lot of complex edge cases. With v11 we want to make Preact simpler again and this is one of the candidates that's up on the table for removals. Nothing is decided yet though.

**Comment by dioslaska** [comment]
@marvinhagemeister Thanks for the reply. For now that "band-aid" would help a lot :) For the future we should than re-think our approach and handle it differently.
So any help on how to restore keeping the original DOM attributes functionality with the latest Preact version would be much appreciated.

**Comment by dioslaska** [comment]
@marvinhagemeister @developit 
I'm just following up on this. We're approaching to a final release with Mobiscroll, our library, and it would be cool if I could upgrade to the latest Preact version for this.
Thanks!

**Comment by developit** [comment]
Hiya @dioslaska - do you have a way where we can try some changes/fixes? We might be able to hack on something more quickly via Slack: https://chat.preactjs.com

**Comment by andrewiggins** [comment]
@dioslaska Another workaround to consider is to first call `hydrate` then `render`. `hydrate` will claim the existing DOM elements and then `render` will ensure that any differences between your VNodes and the DOM nodes are patched. https://codepen.io/andrewiggins/pen/yLajMrw

**Comment by dioslaska** [comment]
@andrewiggins Thanks for the tip. While visually looks as it should, unfortunately this does not solve the original problem: to keep the original attributes on the existing DOM element. I checked the codepen you sent, but if you inspect the markup, you can see that the `id` and `data-foo` and `data-bar` attributes are no longer present on the elements.

**Comment by dioslaska** [comment]
> Hiya @dioslaska - do you have a way where we can try some changes/fixes? We might be able to hack on something more quickly via Slack: https://chat.preactjs.com

I shared a test project on [Slack](https://preact.slack.com/archives/C3M9NTD16/p1608334512354700):

I created a [test environment](https://stackblitz.com/edit/typescript-ut4qfm?file=renderer.ts) related to this issue. I added the source code of the latest Preact version, and one simplified component which showcases what we're doing. You can see on the resulting button, that it looses the id and data-attributes which were originally present, which we wish to avoid.

**Comment by andrewiggins** [comment]
Oh! My eyes glazed over the difference between `data-foo` and `data-foo-new` in that code and I totally missed that ID was unset. My bad.

I believe this would be a breaking change for Preact as I think we added this feature at the request of other users (the clearing of attributes). This might be something we consider enabling in Preact v11.

**Comment by dioslaska** [comment]
@andrewiggins The attributes were kept in Preact 10.0.0, the behavior changed in 10.0.1, so actually there was a breaking change between the bugfix versions.
Since we embed Preact in our lib, I'm also fine with branching and modifying the source code of Preact, I just could not figure out what exact change between 10.0.0 and 10.0.1 caused this change in behavior, so I can revert it in the latest Preact version. Or a plugin solution, like @developit suggested, would be even better.

Here's a test project with the Preact source loaded, where I tried to experiment with this:
https://stackblitz.com/edit/typescript-ut4qfm?file=renderer.ts

**Comment by dioslaska** [comment]
Resolved it using a solution provided by @developit

```
/** Prevent preact from diffing attributes during top-level render. */
function renderPreservingAttributes(vnode: any, parent: any, replaceNode: any) {
  const proto = Element.prototype;
  const descriptor = Object.getOwnPropertyDescriptor(proto, 'attributes');
  const old = descriptor.get;
  descriptor.get = () => [];
  Object.defineProperty(proto, 'attributes', descriptor);
  render(vnode, parent, replaceNode);
  descriptor.get = old;
  Object.defineProperty(proto, 'attributes', descriptor);
}
```
