### ISSUE TITLE
App keeps re rendering causing chrome to crash

### ISSUE THREAD

**Issue by rahulrsingh09** [preactjs/preact#2457]
We have a medium React application and planning to port it to preact 
libs uses - React, Redux and React Native Web, webpack and babel config
i have added the following config 

```
const commonResolveBlock = {
  alias: {
     "react-native$": "react-native-web/dist/index.js", // we use React Native Web
    'victory-native': 'victory',
    'react$': 'preact/compat',
    "react-dom$": "preact/compat",
    "react-dom/unstable-native-dependencies$": "preact-responder-event-plugin"
  },
};
```

Post that i have disabled hot reload as React Hot reload has some problem with preact.

> The app is compiling fine without any console errors but when i try to open the app in chrome it crashes it , i added a console log to my App .js which loads routes it constants prints preact

```
function AppRoutes() {
  trackRoutes();
  console.log('preact'); // always printing
  return (
    <Switch>
      <Route path={BASE_PATH}
             component={App}/>
      <Route path="*"
             component={PageNotFound}/>
    </Switch>
  );
}

const Root = ({store}: { store: IRootState }): React.ReactElement => {
  return (
    <Provider store={store}>
      <Router>
        <AppRoutes />
      </Router>
    </Provider>
  );
}
```

what causes preact to behave this way, or is it only for smaller apps ?

**Comment by JoviDeCroock** [comment]
The information provided is extremely limited, the size of your app has no impact on Preact. Could you provide a reproduction, most likely there's an infinite loop somewhere outlining a difference with one of the libs.

What version of Preact are you using, if it's 10.4.0, would you mind trying 10.3.4 as well? Thanks in advance

**Comment by rahulrsingh09** [comment]
@JoviDeCroock I wish i could provide a reproduction but the problem is app is already very big and which lib is causing this issue is really hard to know which i completely get . 
we are using the following version of preact 
    ```
"preact": "^10.3.3",
    "preact-compat": "^3.19.0",
    "preact-context": "^1.1.4",
```

**Comment by JoviDeCroock** [comment]
You don't need any of the last two dependencies

**Comment by rahulrsingh09** [comment]
without preact-compact how will webpack alias work out also , we are making use of React.context in couple of areas in our app ..

**Comment by JoviDeCroock** [comment]
`preact/compat` as per the docs https://preactjs.com/guide/v10/switching-to-preact#setting-up-compat

**Comment by rahulrsingh09** [comment]
okay i will try and remove the other to and then add just the alias as mentioned in alias above, the version i am using is it fine ? I will keep you posted thanks and appreciate helping with the limited info @JoviDeCroock

**Comment by JoviDeCroock** [comment]
That should be fine yes, so

```
alias: {
  react: 'preact/compat',
  'react-dom': 'preact/compat',
}
```

just to be clear on the information I'm providing, after that we could look at potential things causing infinite state loops but in your current version those should be matured out.

**Comment by rahulrsingh09** [comment]
@JoviDeCroock Still the same issue i am not sure why it re renders .. 
my webpack config

```
const commonResolveBlock = {
  alias: {
    "react-native$": "react-native-web/dist/index.js",
    'victory-native': 'victory',
    'react$': 'preact/compat',
    "react-dom$": "preact/compat",
    "react-dom/unstable-native-dependencies$": "preact-responder-event-plugin"
  },
};
```

My package.json structure - https://jsbin.com/lewuxeq/edit?js

**Comment by JoviDeCroock** [comment]
This is probably something in your app triggering updates (setState/forceUpdate)

**Comment by sventschui** [comment]
I had similiar Issues the past days when using next.js when I had runtime errors that were swallowed. Adding an error boundary helped to track down the issue. You might want to give this a shot.

**Comment by rahulrsingh09** [comment]
@JoviDeCroock this app is already running in prod using react, we were planning to move to preact, @sventschui will try with a Error Boundary thanks..

**Comment by jackyef** [comment]
Hi @rahulrsingh09, just curious, what's the version of `react-redux` you are using in this case?

**Comment by rahulrsingh09** [comment]
@sventschui I checked with Error boundary but i am not seeing any React errors poppingup too, just keeps re rendering also @jackyef my react-redux version is ```    "react-redux": "5.1.1",```

**Comment by jackyef** [comment]
I also had issue with some component suddenly re-rendering infinitely upon migrating to `preact/compat` from `react`. It was using `react-redux@6.0.1`. After upgrading to `react-redux@7.0.1` the problem no longer persist.

**Comment by marvinhagemeister** [comment]
We'd love to fix this, but we need a codesandboy or something similar where the error occurs.

**Comment by developit** [comment]
Try adding this code to your `index.js` (or whatever the main/first module in your project is):

```js
import { options, Component } from 'preact';

options.debounceRendering = f => {
  setTimeout(f, 1000);
};

['setState', 'forceUpdate'].forEach(method => {
  const old = Component.prototype[method];
  Component.prototype[method] = function(state, cb) {
    console.log(this, '.'+method+'(', state, ')');
    old.call(this, state, cb);
  };
});
```

This will throttle rendering to at most one update per second, and log when setState/forceUpdate is called. It's primitive, but it should let you inspect the components to see which is being rendered in a loop.

**Comment by marvinhagemeister** [comment]
Closing, we need more information to help and we haven't heard back from the original poster. We can't reproduce the described issue with the latest version of `react-redux`.

**Comment by theKashey** [comment]
Came around similar issue - using Preact 10.15.1 (+Preact-compat), and rendering multiple Suspense boundaries (>5) - Chrome is crashing, including Incognito mode. 
- Firefox renders perfectly
- Safari renders perfectly
- Storybook (using React) - renders perfectly

The issue exists only for Chrome, only with code splitting (preloading chunks resolves problem), and only for multiple boundaries being active simultaneously.

Hasn't isolated the case into something small I can share, let me just confirm that this case is still possible.
