### ISSUE TITLE
Support react-test-renderer

### ISSUE THREAD

**Issue by jackyef** [preactjs/preact#2467]
Continuing this [issue](https://github.com/preactjs/preact-compat/issues/249) from `preact-compat` repo.

Currently, some testing utilities libraries rely on `react-test-renderer`, for example [`@testing-library/react-hooks`](https://github.com/testing-library/react-hooks-testing-library). This library is used to test React hooks in a React application. Having an equivalent of `react-test-renderer` would help in migrating an existing React app to Preact.

**Comment by IgnusG** [comment]
I had the same issue so I ported this library https://github.com/andrew-w-ross/test-react-hooks to preact. You can find it here https://www.npmjs.com/package/test-preact-hooks

It's still very much alpha and might break like glass so please use at your own risk and leave an issue report if you run into problems!

**Comment by CarsonMcKinstry** [comment]
Hello! 

We had the same issue as well. So we ported the official @testing-library/react-hooks package :D 

[https://github.com/trivago/preact-hooks-testing-library](@trivago/preact-hooks-testing-library)

Would love some feedback as well. It should be _mostly_ at feature parity with the react hooks version, but that isn't 100% guaranteed.

**Comment by developit** [comment]
I wonder if we can close this issue out now that [@testing-library/preact-hooks](https://github.com/testing-library/preact-hooks-testing-library) exists?
