### ISSUE TITLE
cloneElement leaves visible ref="[object Object]"

### ISSUE THREAD

**Issue by vaneenige** [preactjs/preact#2468]
Hi there! Found something odd when using cloneElement, it's not a breaking issue, but it doesn't look pretty in the DOM.

**Reproduction:**

Here's a sandbox: https://codesandbox.io/s/epic-bird-1571e w/ preact@10.4.0

In this demo you see two elements being rendered:

- The first element is using cloneElement to pass a ref to it's children
- The second element uses the children callback to pass it down

If you look at the DOM you can see the first element receiving ref="[object Object]" which looks odd. In my project I've also seen that this doesn't happen when you hydrate or render over SSR'ed DOM. So in my case I noticed it after switching pages.

**Issue:** Normally refs are stripped from the DOM and with cloneElement it was visible.

**Comment by daniele-orlando** [comment]
I still can reproduce this bug with Preact **10.5.7**.
Of course no problem if I use React.

![ref](https://user-images.githubusercontent.com/504386/102650696-9ad6b300-416b-11eb-964a-23ba7051591b.png)
