### ISSUE TITLE
Fix typo in CSS Custom Properties section in Preact X Alpha 0 release note

### ISSUE THREAD

**Issue by 38elements** [preactjs/preact#2490]
The example in CSS Custom Properties section does not work.

### Reproduction

https://github.com/preactjs/preact/releases/tag/10.0.0-alpha.0

### Steps to reproduce

Checking CSS Custom Properties section in Preact X Alpha 0 release note.

### Expected Behavior

```js
function Foo(props) {
  return <div style={{ "--theme-color": "blue" }}>{props.children}</div>;
}
```

### Actual Behavior

```js
function Foo(props) {
  return <div> style={{ --theme-color: "blue" }}>{props.children}</div>;
}
```

**Comment by JoviDeCroock** [comment]
Thanks, updated it

**Comment by 38elements** [comment]
@JoviDeCroock 

It is necessary to replace `<div>` to `<div`.

```jsx
return <div> style={{ "--theme-color": "blue" }}>{props.children}</div>;
```
