### ISSUE TITLE
[FEATURE] Lets add native preact-hot-reload ?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [preactjs/preact#2492]
[FEATURE] Lets add native preact-hot-reload ?

`react-hot-reload` This is a hack that does not always work correctly with react, but does not work with preact at all. so react started doing its native hot-reload. let's add the same api to preact? component reloading without state change and unmounting. and then write a plugin on webpack hot module replacement that will use this api. Of course, in the production version of preact, this api will not be =)

**Comment by moonmeister** [comment]
duplicate of  #2184

**Comment by marvinhagemeister** [comment]
Yup, @moonmeister is correct. We track support for hot reloading in #2184 👍
