### ISSUE TITLE
add useMutationEffect hook

### ISSUE THREAD

**Issue by ColCh** [preactjs/preact#2502]
`useMutationEffect` is a hook which gets called **Before** DOM mutations

### Reproduction

there is no such hook

### Expected Behavior

there is useMutationEffect hook which is fired before DOM update

### Actual Behavior

It may be and should be used for styling

e.g. just for this lovely package: https://github.com/andywer/react-usestyles/blob/131793efef30328994514c4abe655b9372c550ee/packages/style-hook/src/index.js#L21-L24

Currently, we are forced to use `useLayoutEffect` hook to insert inline CSS, and this may produce flickering.

So, styles should be inserted **before** DOM mutations. And we may do with `useMutationEffect` hook

**Comment by ColCh** [comment]
Indeed, I may send PR for this issue, but just help me with overall generic description of changed components please

**Comment by JoviDeCroock** [comment]
How are you importing this from React, it doesn't seem to [exist](https://github.com/facebook/react/search?q=useMutationEffect&unscoped_q=useMutationEffect)

**Comment by ColCh** [comment]
That was only an example of usage. It's not my package :)

Doesn't exist? Hm... interesting! It seems that they have removed it in 16.8 (release with hooks) https://reactjs.org/blog/2019/02/06/react-v16.8.0.html

And some packages are adding styles right in `render` phase, like this one https://github.com/cssinjs/jss/blob/9f7924eb79bf1e78816db7aaa4cf3244710a90d5/packages/react-jss/src/createUseStyles.js#L38

It seems that there is no use for `useMutationEffect` in `preact` context and we may close this issue.

Thank you!
