### ISSUE TITLE
Suspense goes mad inside Fragment

### ISSUE THREAD

**Issue by droganov** [preactjs/preact#2504]
Preact renders my code twice on f/e when `Suspense` is used inside `Fragment`
If I replace fragment with div, things get normal

Code example:
```
<Fragment>
      <Helmet>
        <title>Hello World</title>
      </Helmet>
      <Suspense fallback={null}>
        <Switch>
          <Route path="/" exact>
            <Home />
          </Route>
          <Route path="*">
            <NotFound />
          </Route>
        </Switch>
      </Suspense>
    </Fragment>
```

**Comment by sventschui** [comment]
Hi @droganov 

Excuse the late reply, was pretty busy past weeks. I tried to reproduce your issue in tests but wasn't able to. Are you able to provide a minimal repro in a codesandbox or similar? That would be awesome

**Comment by droganov** [comment]
Hi @sventschui 
I checked my repo, I'm no longer able to reproduce double render.

Closing this, thank you for the update!
