### ISSUE TITLE
lazy does not respect preact-render-to-string

### ISSUE THREAD

**Issue by droganov** [preactjs/preact#2505]
Hi.
The below construction throws at first request and then works at next requests

```
import render from 'preact-render-to-string';
const Home = lazy(() => import('pages/Home'));
....
const app = <Suspense fallback={null}>
  <Switch>
    <Route path="/" exact>
      <Home />
    </Route>
  </Switch>
</Suspense>
....
ctx.body = render(app)
```

**Comment by JoviDeCroock** [comment]
Suspense on the server-side isn't supported in `render-to-string` atm, you can support it through [`preact-ssr-prepass`](https://github.com/sventschui/preact-ssr-prepass)

**Comment by droganov** [comment]
@JoviDeCroock thnx!
