### ISSUE TITLE
render fails in iOS 7 Safari - TypeError: 'undefined' is not a function (evaluating 'Object.setPrototypeOf(n,b)')

### ISSUE THREAD

**Issue by kenfoo** [preactjs/preact#2512]
### Reproduction

A simple code of `render(<div>hello</div>, document.body)` will fail on iOS 7 Safari with Preact 10.4.1. I believe I wasn't having this issue with an earlier build of Preact X which I tested some time back.

The error that I see from Safari remote debugging is
"TypeError: 'undefined' is not a function (evaluating 'Object.setPrototypeOf(n,b)')"

Seems to work fine in newer iOS Safari.

**Comment by kenfoo** [comment]
https://github.com/preactjs/preact/commit/3c6cb62b551c427dedc887fb02b63a7548e8ca88 seems to be the cause

**Comment by marvinhagemeister** [comment]
Looks like this version of Safari doesn't support `Object.setPrototypeOf`. Does this little polyfill resolve it?

```js
Object.setPrototypeOf = Object.setPrototypeOf || function (obj, proto) {
  obj.__proto__ = proto;
  return obj;
}
```

**Comment by kenfoo** [comment]
Yes, that fixes it. Thanks!
