### ISSUE TITLE
how i can use hot-loader for Preact?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [preactjs/preact#2518]
situation:

```jsx
function Popup(){
  const [state, setState] = useState(false)

  function openPopup(){ setState(true) }

  return <div>
    <button onClick={openPopup}>Open</button>

    {state && <div className='popup'>
      My Popup
    </div>}

  </div>
}
```

1) I want open popup
2) then i want change text `My Popup` to `My Popup!!!` and press `ctrl + s`
3) text must change, but popup should not close

Now I am doing this with `react + react-hot-loader`, how can this be do this with `preact`?

**Comment by marvinhagemeister** [comment]
We're working on that.

**Comment by MaxmaxmaximusGitHub** [comment]
@marvinhagemeister small offtop, `preact fibers` and` stream pipe render` are also planned? =)

**Comment by JoviDeCroock** [comment]
Work for a hot-reloader for Preact is being done [here](https://github.com/JoviDeCroock/preact-refresh) it's experimental for now.

**Comment by marvinhagemeister** [comment]
1) Fibers won't gain us anything we don't have already.
2) No framework has pulled of true streamed SSR rendering yet. Most do a synchronous render and put the result into a stream. Don't think this will happen anytime soon, since there are a lot of details to work out to make it work, and be beneficial.

**Comment by MaxmaxmaximusGitHub** [comment]
> Fibers won't gain us anything we don't have already.

1) component use Suspence 
2) component use graphql hook for fetch data from database
3) we not need render component two times, we can suspence render stage, and send to stream already rendered part
4) when suspense is completed and data is received, render system push new data to stream

I thought this is the main task now for reactivity-based ssr systems, did not think that it has a low priority, but ok

**Comment by MaxmaxmaximusGitHub** [comment]
@marvinhagemeister 

the algorithm is simple:

1) we synchronously render the entire application
2) in the application we meet 10 bounds of Suspense
3) we send the stream data before the first Suspence bound
4) we wait until Suspense is completed
5) send its result to the stream
6) send the stream before the second Suspense to the stream etc...


in fact, the react simply came up with a STANDARD for declaring Suspence bounds, and preact can use this standard


Can I create a separate issue to discuss this issue? Do you mind?
