### ISSUE TITLE
Bug with Fragment diff

### ISSUE THREAD

**Issue by webschik** [preactjs/preact#2527]
### Reproduction

CodeSandbox: https://codesandbox.io/s/preact-frament-diff-bug-g4u0h?file=/src/index.jsx

### Steps to reproduce

1. Go to the [CodeSandbox link](https://codesandbox.io/s/preact-frament-diff-bug-g4u0h?file=/src/index.jsx)

2. Initially, you will see a red-bordered panel with a label "bottom panel".
Click on the "Toggle panel position" button several times.

### Expected Behavior

The red panel is rendered before or after `props.children` depending on the state.

### Actual Behavior

After several state changes, the "bottom" panel is rendered inside the child tree instead of being rendered after.
It's reproducible in `preact` and `preact/compat`

**Comment by developit** [comment]
Looks like this is a bug introduced in `10.4.0` - it works correctly in `10.3.3`.
