### ISSUE TITLE
react-three-fiber on Preact? (discussion)

### ISSUE THREAD

**Issue by Astrak** [preactjs/preact#2538]
React-three-fiber (R3F) is a React reconciler to use ThreeJS with JSX' declarative syntax. Preact's syntax matches many of the latest React features. Additionally, in a very performance-heavy app where the 60FPS are hardly reached, having this nice declarative syntax but on the much faster Preact could be a strong advantage. However I don't know much about reconcilers and how Preact's source differs from React's.

Would it be possible to use react-three-fiber with Preact? What would it require?

(Question started on [R3F's discussion page](https://github.com/react-spring/react-three-fiber/discussions/402))

**Comment by developit** [comment]
Preact does not support reconcilers, so this is likely not possible.

**Comment by tresabhi** [comment]
Any updates on this? Seems like preact has a reconciler now.

**Comment by marvinhagemeister** [comment]
@tresabhi Preact always had a reconciler internally, but we don't expose it as it's closely married to the DOM. There are no current plans to change that, which means react-three-fiber is not supported.

**Comment by tresabhi** [comment]
Thanks for the info, @marvinhagemeister

**Comment by drcmda** [comment]
@Astrak @tresabhi https://twitter.com/Cody_J_Bennett/status/1632674026408558592

**Comment by tresabhi** [comment]
![Pooping_Toothpaste_banner](https://user-images.githubusercontent.com/43380238/223121362-7fc257c3-af86-4944-a314-8ff4f7db7e15.jpg)

**Comment by tresabhi** [comment]
That is wonderful news! I am exhilarated to see what this evolves into. I am, for now, going to wait until this is mature enough before implementing this into any of my projects. But, again, this is very promising; after all, Preact is a free boost in performance.
