### ISSUE TITLE
RecoilJS support

### ISSUE THREAD

**Issue by khuyennguyen7007** [preactjs/preact#2544]
Hi, I'm just wandering if there are any ways to intergrate RecoilJS?

**Comment by marvinhagemeister** [comment]
It should work out of the box with our `preact/compat` layout. The only issue we've found so far is that there is a bug in a babel plugin that's used in `preact-cli`: https://github.com/babel/babel/issues/11569#issuecomment-629601129

If you're not using the `cli` you should be good to go 👍
