### ISSUE TITLE
useContext not triggering re-render for nested child components

### ISSUE THREAD

**Issue by PatrickStephansen** [preactjs/preact#2549]
### Reproduction

Repo demonstrating the issue: https://github.com/PatrickStephansen/preact-context-hooks-test.
Try the "Working" and "Broken" links once running.

### Steps to reproduce

Using the context API, create an app with Preact 10.4.4 that uses the `children` component argument at least twice between the provider and the consumer (I don't know the proper term for this. Angular js used to call its closest equivalent transclusion). The consumer will not update after the first render. 

Some other factors of the demo might also turn out to be important eg.

- The value of the context provider is given using `useReducer`
- The actions that change the state are dispatched using `useEffect` with an empty arguments list

### Expected Behavior

The broken and working cases should have the same behaviour since they only differ by one wrapper component called `Abstraction` that doesn't really do anything.

### Actual Behavior

In Preact 10.3.2, the code works the same in both cases shown in the "Working" and "Broken" pages. In Preact 10.4.4, the "Broken" link doesn't render anything visible. I haven't tried a lot of versions in between, but I suspect the issue was introduced with the 10.4.0 with the "Strictly equal vnodes bail out of render" feature.

In Preact 10.4.4, the state actually does update according to the new dev tools hooks inspection and some logging I added, but re-rendering stops before it gets far enough down the tree to actually show the new values.

This issue is stopping me from upgrading to 10.4 on a client project.

**Comment by JoviDeCroock** [comment]
Hey

I've been taking a look at your issue, it seems that the addition of strict-equality for VNodes has surfaced an issue with mutations. We'll look into this but for now I got a small workaround for you:

```
		const Abstraction = ({ defaultState, children }) => {
			const [state, dispatch] = useState(defaultState);
			return (
				<BadContext.Provider value={[state, dispatch]}>
					<Wrapper>{children}</Wrapper>
				</BadContext.Provider>
			)
		}
```

Will fix it because you can't mutate the `Provider.props.value` which the dispatch is doing atm.
