### ISSUE TITLE
Issue on render

### ISSUE THREAD

**Issue by aralroca** [preactjs/preact#2562]
This bug was introduced on `10.4.2`. In `10.4.1` is working fine.

Preact 10.4.1 vs 10.4.2

![image](https://user-images.githubusercontent.com/13313058/83268238-9ba2fa00-a1c5-11ea-8d38-aefc361fd108.png)

### Reproduction

I don't understand when it happens exactly. But look an error on SSR. 

### Steps to reproduce

* clone the repo https://github.com/aralroca/preact-issue-report
* `yarn && yarn dev` -> Is working fine
* Upgrade Preact from 10.4.1 to 10.4.2 (or 10.4.4).
*  `rm -rf node_modules yarn.lock && yarn && yarn dev ` -> Is not rendering well the content

### Expected Behavior

Render the content in the same way than 10.4.1

### Actual Behavior

It's not rendering the content.

**Comment by JoviDeCroock** [comment]
There are some interesting things to see here, let me pop open the 10.4.1 dom-tree and compare it to the 10.4.2 one.

10.4.1

![image](https://user-images.githubusercontent.com/17125876/83269597-a1014400-a1c7-11ea-95c2-54b107403700.png)


10.4.2

![image](https://user-images.githubusercontent.com/17125876/83269639-b1b1ba00-a1c7-11ea-88d3-997c7d8f0c66.png)

**Comment by aralroca** [comment]
@JoviDeCroock what I see is that it only happens on SSR. Using CSR is working fine 😕 Or at least using Next.js... Are you using SSR in your local instance?

BTW; What are the `__self` and `__source` doing? Are they only for devtools?

**Comment by JoviDeCroock** [comment]
These are debug attributes originating from https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-self, what I don't understand is why they weren't applied with 10.4.1 and they were with 10.4.2 the only change that could impact this is that starting at 10.4.2 we are actually using `hydrate` rather than `rendeer` which in essence makes less sense.

**Comment by JoviDeCroock** [comment]
This has been fixed in `preact-render-to-string` 5.1.9

**Comment by aralroca** [comment]
It works very well now 👏
