### ISSUE TITLE
forwardRef is always sending ref object 

### ISSUE THREAD

**Issue by droganov** [preactjs/preact#2566]
A construct like:

```javascript
forwardRef((props, forwardedRef) => {
  const localRef = useRef(null);
  const ref = forwardedRef || localRef;
})
```

is not possible with Preact because `forwardedRef` is always defined by preact.

Expectedly it would be `undefined` if we didn't pass ref to the Element.

**Comment by marvinhagemeister** [comment]
Just checked with React and they fall back to `null` instead of `undefined`.

**Comment by droganov** [comment]
@marvinhagemeister yes, you're right it's nullable in react.
thnx!
