### ISSUE TITLE
input with value will not trans to fully controlled

### ISSUE THREAD

**Issue by s0urcelab** [preactjs/preact#2580]
### Reproduction
give a input some constant value will make it become a fully controlled component, but it still can be inputed by user keyboard.
i  migrate a <NumberInput> component from react code, the problem above make it malfunction.
https://codesandbox.io/s/agitated-wildflower-fmf27

### Steps to reproduce

input some words

### Expected Behavior
input has a contant value, should never change

### Actual Behavior
value could be change

**Comment by marvinhagemeister** [comment]
Related #1899, #2202 .

**Comment by andrewiggins** [comment]
Would using the [HTML `readonly` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly) work for your scenario?

Would probably be better for accessibility since browsers can then communicate that this input value is constant in the accessibility tree used by screen readers and such. Can also use the `:readonly` pseudo-select to do custom styling.

**Comment by s0urcelab** [comment]
> Would using the [HTML `readonly` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly) work for your scenario?
> 
> Would probably be better for accessibility since browsers can then communicate that this input value is constant in the accessibility tree used by screen readers and such. Can also use the `:readonly` pseudo-select to do custom styling.

thx for your advise, but my purpose is filter words not to disable user input, so it's no help for me.
I've read the issue mention above, seem like many developer has been confused by this problem for a long time, is there any plan to fix this?
After all, most Preact user may expect the same behavior compare to React, right?

**Comment by marvinhagemeister** [comment]
> I've read the issue mention above, seem like many developer has been confused by this problem for a long time, is there any plan to fix it?

We tried a few approaches to fix this in the past months but none of them have been good enough so far as they all lead to more problems in other areas. Input elements in HTML are really tricky as they don't have an API to set the value without leading to jumping cursors or losing text selection if there was any.

The solution react chose for this is quite big and requires a full proprietary event system. It's not something we can adapt for Preact as it would likely more double our size and impose additional maintenance overhead.

> After all, most Preact user may expect the same behavior compare to React, right?

No, that's what `preact/compat` is for. It's our compatibility layer for having 1:1 compatibility with the React API. Preact itself doesn't share that goal and never will do so. That's what the compatibility layer is for.

**Comment by s0urcelab** [comment]
> > I've read the issue mention above, seem like many developer has been confused by this problem for a long time, is there any plan to fix it?
> 
> We tried a few approaches to fix this in the past months but none of them have been good enough so far as they all lead to more problems in other areas. Input elements in HTML are really tricky as they don't have an API to set the value without leading to jumping cursors or losing text selection if there was any.
> 
> The solution react chose for this is quite big and requires a full proprietary event system. It's not something we can adapt for Preact as it would likely more double our size and impose additional maintenance overhead.
> 
> > After all, most Preact user may expect the same behavior compare to React, right?
> 
> No, that's what `preact/compat` is for. It's our compatibility layer for having 1:1 compatibility with the React API. Preact itself doesn't share that goal and never will do so. That's what the compatibility layer is for.

thx for reply，i'm gonna try some workaround.
