### ISSUE TITLE
8.5.1 tag is actually 10.0.0-rc.1

### ISSUE THREAD

**Issue by 4r7d3c0** [preactjs/preact#2587]
Hi I was browsing through the repo and trying to understand when fragments were introduced, and got confused as this diff https://github.com/preactjs/preact/commit/1491826b68de0b62877981dbf2c11f7addec7b4f points to 8.5.1 and in tree, for 8.5.1 the source has `create-element` which is a feature of X as I gather. the actual package on npm is fine it's just the tag.

**Comment by marvinhagemeister** [comment]
Good catch! I've updated the tag to point to the correct commit. Thanks a again for reporting this 🙌 🥇

**Comment by 4r7d3c0** [comment]
@marvinhagemeister it doesn't seem to have commits in it though ? https://github.com/preactjs/preact/commits/8.5.1 i know it's hardly matters just want to get to the bottom of this

**Comment by marvinhagemeister** [comment]
Yeah that's because the 8.5.0 was a bad publish. It included some code from the X release line because of some leftover files in the `dist` folder when switching branches.
