### ISSUE TITLE
compat in-browser error: VNode is undefined index.js:56

### ISSUE THREAD

**Issue by Kulak** [preactjs/preact#2591]
### Reproduction

[Fiddle Demo](https://jsfiddle.net/Lhgty3q5/1/).

`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://unpkg.com/preact@10.4.4/dist/preact.umd.js" crossorigin></script>
  <script src="https://unpkg.com/prop-types@15.7.2/prop-types.js" crossorigin></script>
  <script src="https://unpkg.com/preact-compat@3.19.0/dist/preact-compat.js" crossorigin></script>
</head>
<body>
</body>
</html>`

### Steps to reproduce

Just create 'index.html` page or use fidle demo above.  Open browser console and see error message.

### Expected Behavior

No Errors in console.

### Actual Behavior

Error message:

`TypeError: VNode is undefined index.js:56`

**Comment by JoviDeCroock** [comment]
`preact-compat` isn't used anymore we're using `preact/compat` atm https://preactjs.com/guide/v10/upgrade-guide

**Comment by Kulak** [comment]
Thank you.  I assume it is not an issue then.
