### ISSUE TITLE
Question about Custom Element events (camalcase vs pascalCase)

### ISSUE THREAD

**Issue by nathan-barrett** [preactjs/preact#2592]
### Reproduction

Hello! I am having some issues with the event handlers for Custom Elements. My project is using a library which has custom components and typed attributes and events for those components. Looking over the documentation, i found this on event handlers: 

> Elements often fire custom events as part of their public API, and there's no way to know what custom events might be fired. In order to ensure Custom Elements are seamlessly supported in Preact, any unrecognized event handler props passed to a DOM Element will have their casing preserved.

To reproduce, you'll have to click the button, and then click on an item in the dropdown.
[ׁCodesandbox link](https://codesandbox.io/s/preact-calcite-dropdown-v3gxm?fontsize=14&hidenavigation=1&theme=dark)

### Actual Behavior

In the typings for the components, the eventHandler should be `onDropdownClose` but only `ondropdownClose` is working

Wondering what my options are since the types and what preact does with custom events don't seem to line up?

**Comment by marvinhagemeister** [comment]
> (...) any unrecognized event handler props passed to a DOM Element will have their **casing preserved**.

This means that if the custom element defines an event as `calciteDropdownClose` then this casing must not be changed. `calciteDropdownClose` therefore becomes `on + calciteDropdownClose` -> `oncalciteDropdownClose`. Changing the casing by making the c uppercase is invalid as that would refer to a different event.

The reason behind this is that events are always case sensitive and there is no way to programatically know which events are supported on a Custom Element. It's an oversight in the spec of Custom Elements.
