### ISSUE TITLE
Uncontrolled textarea

### ISSUE THREAD

**Issue by olabala** [preactjs/preact#2604]
this issue kinda like #1899 
same code, you can not clear the value of textarea under preact, but react can

React - ✅
https://codesandbox.io/s/react-controlled-input-0mfvp?file=/src/index.js

Preact - ❌
https://codesandbox.io/s/preact-controlled-input-xpt53?file=/src/index.js

(not sure if this is raised, if any, feel free to close it)

**Comment by rjyo** [comment]
Stucking in the same situation.

I have tried to change textarea to a normal input, and everything just works.

**Comment by developit** [comment]
This is fixed by #2615 and will be released shortly.
