### ISSUE TITLE
state change, but not render 【textarea】

### ISSUE THREAD

**Issue by wallena3** [preactjs/preact#2605]
### Reproduction
state change not render

### Steps to reproduce
```html
        <textarea
          style={{ width: '100%', height: '20vh' }}
          onChange={this.handleCommentChange}
          value={this.state.comment}
          id="comment_textarea"
        ></textarea>
```

```html
<button onClick={this.handleCommentCreate}>add comment</button>
```

In handleCommentCreate func
```javascript
this.setState(
          {
            comment: '',
          }
        );
```

### Expected Behavior
<textarea> value turn to ' '

### Actual Behavior
<textarea> value not change

**Comment by JoviDeCroock** [comment]
Seems to work for me https://codesandbox.io/s/determined-taussig-l2wok?file=/index.js

**Comment by wallena3** [comment]
@JoviDeCroock 
In your example it works. But you do import  like this 
```javascript
import { render, Component } from "preact";
```
what i do is 
```javascript
import React, { Component } from 'react';
```
and add config of webpack
```
  config.resolve.alias = {
    react: 'preact/compat',
    'react-dom/test-utils': 'preact/test-utils',
    'react-dom': 'preact/compat',
  };
```

ref Issue: https://github.com/preactjs/preact/issues/2604

**Comment by JoviDeCroock** [comment]
Replacing `preact` with `preact/compat` in my example still seems to work, I'll take another look.

**Comment by wallena3** [comment]
@JoviDeCroock Ok. I try to replace hook with class this problem still here.
