### ISSUE TITLE
Nesting portals that target the same container clobbers state

### ISSUE THREAD

**Issue by gregfagan** [preactjs/preact#2613]
### Reproduction

https://codesandbox.io/s/preact-nested-portal-bug-uyc5z

Please see the above codesandbox for a demonstration of the issue. It also describes what I believe to be the root cause.

### Steps to reproduce

Render a component into a portal, which itself renders a portal into that same container

### Expected Behavior

Contents of both portals correctly render adjacently in the container

### Actual Behavior

The inner portal clobbers the outer portal's state, causing new nodes to be created

**Comment by JoviDeCroock** [comment]
This is fixed in latest
