### ISSUE TITLE
Possible explanation(s) for why setState callbacks would continue to stack?

### ISSUE THREAD

**Issue by lf94** [preactjs/preact#2614]
For some reason, whenever I click the button I have, it just keeps stacking the setState callback, and never re-renders. It's like the render cycle is just not happening. What could be potential causes for this, which I could look out for and investigate?

### Reproduction

├── preact@8.4.2
├── preact-redux@2.0.3
├── preact-router@2.6.1

### Steps to reproduce

I have no idea.

### Expected Behavior

A re-render should happen?

### Actual Behavior

The renders / callbacks just stack up.

**Comment by marvinhagemeister** [comment]
One thing you can try is upgrading to the latest version of Preact. We're at version `10.4.5` at the time of this writing. Most of us haven't looked at the 8.x codebase in years and what you're experiencing sounds like a bug.

**Comment by lf94** [comment]
Thank you for your reply. Unfortunately I cannot upgrade preact, but fortunately, preact codebase is very consumable :slightly_smiling_face: 

I'll continue to trace the issue in the 8.4.2 version and report back if I find anything.

**Comment by lf94** [comment]
So one obvious thing is that my "root" component, is constantly `component._dirty == true`, which prevents a deferred rerender to happen.

**Comment by lf94** [comment]
I noticed a version mismatch between two projects which use the same component: 8.4.2 vs 8.5.3. Hopefully this upgrade fixes the issue.

**Comment by lf94** [comment]
Same issue is present...

**Comment by lf94** [comment]
Ok! Getting somewhere. The dev build seems to exhibit different behavior.

Race condition?

**Comment by lf94** [comment]
The issue if anyone ever encounters this:

webpack is bundling preact into my component, which is exposed via `window`. I then linked preact.min.js into an index.html to render the initial component.

The issue is now there are two instances of preact with their own states. The state-mismatch confuses preact what needs to be re-rendered and what not.

When bundling, be sure to add `externals: ['preact']`  to leave it out. We also use preact-router and preact-redux, but I haven't tried excluding these since I don't use them "externally".

Mystery solved.
