### ISSUE TITLE
Can I use 'createPortal' with 'preact'?

### ISSUE THREAD

**Issue by iorate** [preactjs/preact#2616]
I ran into a problem similar to #2604 when I used `preact` and `createPortal`:

```typescript
import { h, render } from 'preact';
import { createPortal } from 'preact/compat';

// ...
```

and could fix it by patching #2615.
Although I import `h` and `render` from `preact` (not from `preact/compat`), a fix to `compat/src/render.js` takes effect.
I guess it is because importing `createPortal` from `preact/compat` indirectly modifies a module shared between `preact` and `preact/compat`. Actually `compat/src/render.js` modifies `options` imported from `preact`.

That is to say, importing `createPortal` modifies `preact`'s behavior.
Is it intended behavior? Shouldn't I use `createPortal` with `preact`?

**Comment by developit** [comment]
That is how they're currently designed to work, yes. Some features in compat modify preact's behavior because it's impossible to know whether a given virtual DOM tree will be used by preact (core) or by compat.

As an example, imagine this:

```js
// foo.js
import * as React from 'preact/compat';
export default class Foo extends React.Component {
  render() {
    return <div className={this.props.children.className}>blah</div>
  }
}

// bar.js
import { h, render } from 'preact';
import Foo from './foo.js';

// we're rendering a "compat" component, but passing it non-compat VNodes from h():
render(<Foo><span class="bar" /></Foo>, document.body);
```

**Comment by developit** [comment]
As an aside though, we really do want to make it so that `preact/compat` is fully tree-shakeable. Currently it relies on side-effects (intentionally, for the reason noted above), but for folks who want to just use a couple things from compat that is not ideal. Perhaps in the short-term, it might be worth publishing the individual pieces of compat as standalone modules some place like `preact/compat/lib/createPortal.js`.

**Comment by iorate** [comment]
Thank you for your kind reply. I understand well.

It will be nice if I can import `createPortal` as a standalone module in future.
