### ISSUE TITLE
Uncontrolled checkbox

### ISSUE THREAD

**Issue by olabala** [preactjs/preact#2625]
I set checked to true in every change event, preact ignores this while react not

React - ✅
https://codesandbox.io/s/reactuncontrol-checkbox-cmezk?file=/index.js

Preact - ❌
https://codesandbox.io/s/preactuncontrol-checkbox-yeltw?file=/src/index.js

(not sure if this is raised, if any, feel free to close it)

**Comment by olabala** [comment]
find a work around
https://github.com/preactjs/preact/issues/1899#issuecomment-525744533
![image](https://user-images.githubusercontent.com/20949823/87530872-86c1ed80-c6c3-11ea-9d72-85c74341f2c7.png)

**Comment by developit** [comment]
This is the same issue as #1899
