### ISSUE TITLE
@Crysp it seems the only workaround is to leverage the behavior that `useState` does shallow comparison, and use a non-primitive to force re-render:

### ISSUE THREAD

**Issue by olabala** [preactjs/preact#2626]
@Crysp it seems the only workaround is to leverage the behavior that `useState` does shallow comparison, and use a non-primitive to force re-render:

```js
const ControlledInput = () => {
  const [data, setData] = useState({ value: "" });

  const onChange = event =>
    setData({ value: event.target.value.replace(/[^a-z]/gi, "") });

  return <input value={data.value} onChange={onChange} />;
};
```

https://codesandbox.io/s/preact-controlled-input-2-rvghz

_Originally posted by @dwelle in https://github.com/preactjs/preact/issues/1899#issuecomment-525744533_

**Comment by marvinhagemeister** [comment]
Let's not take away time from the maintainers by duplicating issues ;)
