### ISSUE TITLE
flushSync not in compat

### ISSUE THREAD

**Issue by tomByrer** [preactjs/preact#2636]
When trying to use Adobe's [React-Spectrum](https://react-spectrum.adobe.com/react-spectrum/index.html) I get this error:
`ERROR  in ./node_modules/@react-aria/virtualizer/dist/module.js 154:4-13
"export 'flushSync' was not found in 'react-dom'`

It is used only in [one place](https://github.com/adobe/react-spectrum/blob/c700898916bbd076bcc63e49d77c16d80623a8e7/packages/%40react-aria/virtualizer/src/ScrollView.tsx#L77).

React has [two](https://github.com/facebook/react/blob/4c7036e807fa18a3e21a5182983c7c0f05c5936e/packages/react-reconciler/src/ReactFiberWorkLoop.old.js#L1188-L1214) different [versions](https://github.com/facebook/react/blob/4c7036e807fa18a3e21a5182983c7c0f05c5936e/packages/react-reconciler/src/ReactFiberWorkLoop.new.js#L1156-L1182) listed in their codebase.  Only docs I could find is [this comment](https://github.com/facebook/react/issues/11527#issuecomment-360199710):

> You also have an option to flush the entire tree if you know what you’re doing. The API is called ReactDOM.flushSync(fn).  Note that it actually forces complete re-rendering for updates that happen inside of the call, so you should use it very sparingly. This way it doesn’t break the guarantee of internal consistency between props, state, and refs.

I'm wondering if a noop would be OK for now rather than having to implant the flushing?

**Comment by marvinhagemeister** [comment]
A no-op or stubbing it out via `useEffect` is worth a try. If we're lucky that could be all that's needed. In our case we'll have already flushed the tree to the DOM by then, so it should work.

**Comment by JoviDeCroock** [comment]
Added in https://github.com/preactjs/preact/pull/3094
