### ISSUE TITLE
preact Uncaught (in promise) TypeError: n is undefined when initialize func aftre this.state = { ... }

### ISSUE THREAD

**Issue by tkassila** [preactjs/preact#2638]
Hi,

I have a preact material app, created with preact-cli. Error came with latest firefox and edge, but not on chrome, because I had a local call into my function: initialstate(props) after creating smaller this.state = {...}; inside of a class constructor. (And then I had the same call initialstate(props) inside of componentWillReceiveProps(nextProps). 

The above error dismissed when I merged the old this.state = .... and all setState({ .... } from initialstate(props)  function into one this.state = { .... }; !! The same happend on another preact class also, when a constructor have only one merged this.state = and not one this.state = and another this.setState(...) inside a constructor !!

I try'ed to reproduce this error, which failed on  the another small app. It worked very very and with no errors.
Even with the same structure.

Tuomas

**Comment by marvinhagemeister** [comment]
I have trouble parsing what the scenario is that you're describing. Can you share a snippet of the component where the error occurred and what you did to "merge" state?

**Comment by sventschui** [comment]
I think the issue that @tkassila is reporting here is that `setState` inside `constructor` throws in FF/Safari but works in Chrome. The problem is that `_nextState` is `undefined` in FF/Safari and thus the assign in `setState` throws: https://github.com/preactjs/preact/blob/103c2054b1044a9ada5bc94d8736272f55fda2b2/src/component.js#L32

See this CSB (works in Chrome, throws in FF/Safari): https://codesandbox.io/s/eloquent-noyce-f0lxz

**Comment by developit** [comment]
the codesandbox throws in chrome for me.

It seems like we need to change this line:

https://github.com/preactjs/preact/blob/103c2054b1044a9ada5bc94d8736272f55fda2b2/src/component.js#L30

... to instead be:

```js
		s = this._nextState || {};
```

**Comment by tkassila** [comment]
Hi, seems you makes some change to correct. Good. I can reproduce it now with an another project. I have now one setstate code in constructor and my real code runs without error. Below are a code snippet causes this error:

export default class Home extends Component {
	constructor(props)
	{
		super(props);
		this.state = {
			test: 'porpstest',
			test2: null,
			data: props.data
		};
		/* this call makes an error: */
		this.setState( {
			data2: props.data
		});
