### ISSUE TITLE
Errors not showing in console after upgrading to PreactX

### ISSUE THREAD

**Issue by scotthypernetlabs** [preactjs/preact#2639]
after i had upgraded my preact version debugging errors are not being shown in the console.

i did the exact same way where we import the preact/debug but it didn't work either.

i added this code to my index js at the top of the file like that:

```
// Must be the first import
if (process.env.NODE_ENV==='development') {
  // Must use require here as import statements are only allowed
  // to exist at the top of a file.
  require("preact/debug");
}
```

and i tried to import preact/debug explicitly like that `import 'preact/debug';`, didn't work either.

when i run a buggy line in my component like that `someUndefinedFunction()` i am not getting the error in the console along with any other errors.

any suggestion to fix this issue, please!

**Comment by marvinhagemeister** [comment]
@scotthypernetlabs Can you share a codesandbox or a repro where the error is reproducible? For me the errors always appear, see this sandbox: https://codesandbox.io/s/gifted-jang-dlcd2

**Comment by moahammadalt** [comment]
i had the same problem it was from an old eventListener on errors `window.addEventListener('error', function(event) {});` causing preact debugging issues, when i removed it the problem solved

**Comment by scotthypernetlabs** [comment]
addEventListener was causing the problem, closing the issue.
