### ISSUE TITLE
debug is not working propely after upgrading Preact version

### ISSUE THREAD

**Issue by moahammadalt** [preactjs/preact#2642]
i have some kind of problem in debugging my preact project, most of the js errors are nor showing up in the console.

for example i added this code to my component:
```
<button onClick={() => {
  const someVar = someUnknownVariable;
}}>
  fire error
</button>
```
and when i click on the button there is no error showing up in the says that someUnknownVariable is not defined, other js errors are not showing up too.

here is my preact.config.js file:
```
import compose from 'lodash.compose';
export default (config, env, helpers) => {
  return compose(addEmotionPlugin, configRules)(config, env, helpers);
};
function addEmotionPlugin(config) {
  let babel = config.module.rules.filter(loader => loader.loader === 'babel-loader')[0]
    .options;
  babel.plugins.push([
    'emotion',
    {
      hoist: true,
      sourceMap: false,
      autoLabel: true,
      labelFormat: '[local]',
      extractStatic: false,
      outputDir: '',
    },
  ]);
  return config;
}
function configRules(config, env) {
  if (env.isProd) {
    config.devtool = 'source-map';
    config.output.filename = '[name].js';
    config.output.publicPath = process.env.NODE_ASSETS || '/';
  }
  return config;
}
```

and in my index.js file i have this code at the beginning.
```
if (process.env.NODE_ENV==='development') {
  require("preact/debug");
}
```

this happened after i upgraded preact version, any help, please.

**Comment by developit** [comment]
I would advise against setting `config.output.filename` and `config.devtool`.

You can remove the `require("preact/debug")` condition you mentioned, that's actually done for you in preact-cli v3.

Also - are you using an older version of Preact?  Preact CLI v3 should really only be used with Preact version 10.3 and higher.

**Comment by moahammadalt** [comment]
the problem was from an old eventListener on errors `window.addEventListener('error', function(event) {});` causing preact debugging issues, when i removed it the problem solved
