### ISSUE TITLE
Uncontrolled select support?

### ISSUE THREAD

**Issue by thurfir** [preactjs/preact#2646]
Hi, the _defaultValue_ attribute for `<select>` does not work in preact: https://stackblitz.com/edit/preact-bug-defaultvalue-zn7r9a . 

Switching to a selected attribute (in `<option>` ) seems to work but causes some strange behaviour on late renderings (no sandbox yet).

**Comment by ForsakenHarmony** [comment]
Does `defaultValue` even exist for `<select>`?

**Comment by thurfir** [comment]
Hi @ForsakenHarmony , yes it exists; React even asked me (with a console warning) to replace <option default... /> by defaultValue during my tests ;-) .

**Comment by andrewiggins** [comment]
To be clear for anyone looking to work on this, `defaultValue` on `<select>` is not a DOM prop ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement)) but is something React supports, so support for `defaultValue` on `<select>` needs to be in `preact/compat`.

`<option>` does have a `defaultSelected` property ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement)), but not sure what React does with this.

**Comment by Rafi993** [comment]
Hello there, If this issue is up for taking I would like to help.

**Comment by themre** [comment]
Hi, i just encountered this bug with defaultvalue on the select and i have a stackblitz example here: https://stackblitz.com/edit/preact-starter-template-yktscr?file=App.jsx. I used `defaultValue` on the select, but no luck. Or am I missing something?
