### ISSUE TITLE
Missing forwardRef with Ant Design Table

### ISSUE THREAD

**Issue by martinoppitz** [preactjs/preact#2652]
Ant Design Table does not work.

![image](https://user-images.githubusercontent.com/6279703/88701420-4a05e580-d10a-11ea-8b66-bbdd5d84c596.png)

Repo: https://github.com/developit/preact-boilerplate/pull/357/files

... more later.

**Comment by marvinhagemeister** [comment]
Just checked and the repo in question is using the Preact 8.x release line. There we have no support for `forwardRef`. Upgrading it to to the 10.x release line by upping the dependencies and swapping out the `preact-compat` alias for `preact/compat` resolves the issue (and brings many improvements).

The 8.x release line is in maintenance mode and will only receive security updates or other critical bug fixes at this point.

In general we don't recommend the `preact-boilerplate` repo as a starting point and point to the [preact-cli starter template](https://github.com/preactjs/preact-cli#usage) instead.
