### ISSUE TITLE
Error in useSound library attempting to use react, "Cannot read property '__H' of undefined"

### ISSUE THREAD

**Issue by Danack** [preactjs/preact#2654]
Possibly similar to #1321 though errors in browser not build.

### Reproduction

Checkout https://github.com/Danack/preact_error

Install the stuff ```npm install```

build the stuff ```npm run build:dev```

Open the file ```public/index.html``` in a browser

### Expected Behavior

No error.

### Actual Behavior

```
Uncaught TypeError: Cannot read property '__H' of undefined
    at v (index.js:96)
    at _ (index.js:202)
    at Object.h [as useRef] (index.js:177)
    at useSound (index.ts:18)
    at Module../tsx/sound_button.tsx (sound_button.tsx:16)
    at __webpack_require__ (bootstrap:63)
    at Module../tsx/bootstrap.tsx (bootstrap.tsx:1)
    at __webpack_require__ (bootstrap:63)
    at Object.0 (sound_button.tsx:24)
    at __webpack_require__ (bootstrap:63)
```

Example error should also be viewable in browser here:  https://danack.github.io/preact_error/

**Comment by Danack** [comment]
This is probably my error....of trying to use something in a class component that may only be usable in a function component.....trying to confirm.

**Comment by Danack** [comment]
Yeah, this was me trying to use something in a class component that apparently only works in a function component.

Obviously people shouldn't write bad code, but it's hard to work back from that error message to how to fix it. I only found it by switching back to React, which gives a clue in it's error message of something along the lines of "using hook outside of function".

Works
```
export function BoopPanel(props: BoopPanelProps) {
  const [play] = useSound(boopSfx);

  // @ts-ignore: I don't understand that error message.
  return <button onClick={play}>Boop!</button>;
}
```

Doesn't work
```
const [play] = useSound(boopSfx);

export class BoopPanel extends Component<BoopPanelProps, BoopPanelState> {
    render(props: BoopPanelProps, state: BoopPanelState) {

        // @ts-ignore: I don't understand that error message.
        return <button onClick={play}>Boop!</button>;
    }
}
```

**Comment by marvinhagemeister** [comment]
@Danack FYI: You may be missing the `preact/debug` import at the top of your entry file. It will print similar warnings to the one you can find in Preact and some other ones that may be an error in Preact.
