### ISSUE TITLE
Missing: `defaultValue` Typescript Types

### ISSUE THREAD

**Issue by amiller-gh** [preactjs/preact#2668]
### Reproduction

Preact 10.4.6 does not contain typescript types for React's `defaultValue` despite being supported by `preact/compat`

### Steps to reproduce
Try to use it in a Typescript project 🙂 

I was able to work around the missing types by adding this override declaration to my project:
```ts
declare module 'preact/src/jsx' {
  /* eslint-disable-next-line @typescript-eslint/no-namespace */
  namespace JSXInternal {
    interface HTMLAttributes<RefType extends EventTarget = EventTarget> {
      defaultValue?: string;
    }
  }
}
```

### Expected Behavior
It builds!

### Actual Behavior
It doesn't...
```
Property 'defaultValue' does not exist on type 'HTMLAttributes<HTMLInputElement>'.
```

**Comment by Rafi993** [comment]
Hello there, If this issue is not taken I would like to help

**Comment by JoviDeCroock** [comment]
Resolved by https://github.com/preactjs/preact/commit/3957522a9b5393681ca66ad879e046c2f978a3e9
