### ISSUE TITLE
[compat] portals not unmounting

### ISSUE THREAD

**Issue by gitcatrat** [preactjs/preact#2669]
Not really sure if this is on people's radar or if there's an easy workaround I'm not seeing but issue is still open in old compat repository and I've just encountered this bug with latest version.

### Reproduction
https://github.com/preactjs/preact-compat/issues/501

### Steps to reproduce
See the first link.

### Expected Behavior
Portal should unmount if it shouldn't be rendered.

### Actual Behavior
Portal doesn't unmount if e.g `flag === false`.
```jsx
{flag && (
  ReactDOM.createPortal(
    <PortalContent />,
    document.body
  )}
)}
```

**Comment by JoviDeCroock** [comment]
This is a bug in Preact v8 but should work in our new X line: https://codesandbox.io/s/laughing-cray-xvsr3?file=/package.json

**Comment by gitcatrat** [comment]
@JoviDeCroock Played around a bit more and finally found the bug. Visit the link below and toggle the button 5-10 times.

Issue comes from `createPortal` inside `createPortal`. I know it doesn't make sense in this case but I have a case where menu is rendered with `createPortal` and it uses `createPortal` to draw dark background when menu is opened. If I'm not mistaken, I did it to avoid z-index porn.

Would be cool to know if this is a bug or I should change my code. PS! Worked with React.

https://codesandbox.io/s/interesting-leavitt-4m76v?file=/src/index.js

**Comment by sventschui** [comment]
Just added a repro in #2686 

I'll try to dig into this but I guess we need to summon the lord of the portals @JoviDeCroock here 🙄

**Comment by sventschui** [comment]
What I found so far:

The `hydrate` call in https://github.com/preactjs/preact/blob/master/compat/src/portals.js#L41 makes this line https://github.com/preactjs/preact/blob/master/compat/src/portals.js#L56 restore the wrong children.
