### ISSUE TITLE
Preact does not throw "Invalid hook call" error

### ISSUE THREAD

**Issue by kenny-f** [preactjs/preact#2671]
React throws an Invalid hook call error when hooks are not called directly inside the body of a function component.
Preact does not throw this error. Not sure if this is by design or an oversight as I couldn't find any issues relating to it. This caused some subtle bugs.

### Reproduction
Contrived example, but shows the difference.
 
React - https://codesandbox.io/s/blue-darkness-zhnx1

Preact - https://codesandbox.io/s/musing-margulis-v5xx7

### Expected Behavior

Should Preact also throw this error?

### Actual Behavior

Preact works as normal, but might be hiding issues from the user.

**Comment by marvinhagemeister** [comment]
Awesome, thank you so much for the bug report! We do throw when a hook is used outside a render method already, but we missed the case where a hook is used inside `useEffect/useLayoutEffect` callback. PR #2672 addresses that.

_Note: You need to add the `import "preact/debug";` at the top of the main entry file to enable debug messages._

**Comment by kenny-f** [comment]
@marvinhagemeister Thanks for the reply and fix. We have `preact/debug` imported, but i guess for this scenario it was inside a `useEffect` so didn't output anything.
