### ISSUE TITLE
Preact removes option values on hydration

### ISSUE THREAD

**Issue by kenny-f** [preactjs/preact#2678]
Option values for select tags are removed during hydration

Page source:
<img width="1483" alt="Screenshot 2020-08-04 at 14 28 04" src="https://user-images.githubusercontent.com/1841819/89299570-bf1f7080-d65e-11ea-932a-ff0684186ab8.png">

Elements tab after hydration:
<img width="641" alt="Screenshot 2020-08-04 at 14 15 21" src="https://user-images.githubusercontent.com/1841819/89299523-aca53700-d65e-11ea-94a2-457ec516eb18.png">
 

### Reproduction
Clone this branch 
https://github.com/kenny-f/preact-hydration-repro/tree/hydrate-select-options-preact-only

`npm i`
`npm start`

See that the values are missing in the value output for the options (like screenshots above)

NOTE: `render` does not have this problem and works fine, only `hydrate`

**Comment by kenny-loveholidays** [comment]
Update: This started happening since version `10.4.5`
