### ISSUE TITLE
Next.js + Preact template uses `"react": "github:preact-compat/react#1.0.0"` in package.json but docs say v8+ should use preact/compat?

### ISSUE THREAD

**Issue by GavinRay97** [preactjs/preact#2684]
Hi, sorry to clutter up your issues with silly questions but I was a bit confused about this one and couldn't find much after Googling:

The docs for `preact/compat` state:
> This module is for Preact 8.x and prior - Preact X includes compat by default. For Preact X, please uninstall preact-compat and replace your aliases with preact/compat.

I used the lovely reference implementation with `@prefresh` and aliases configured for Next.js, but I noticed that in `package.json` the React libs are aliased to `preact-compat` and not `preact/compat` (maybe because you can't alias to a sub-module?)

https://github.com/vercel/next.js/blob/c11ee1d8573c2c264ee146b365900dce25ac0f4d/examples/using-preact/package.json#L17-L19

I'm just curious whether this is correct or if I should change the alias library. Thank you, keep being awesome :smiley:

**Comment by ForsakenHarmony** [comment]
Yes that does seem outdated, unless there's something special going on with the aliasing

**Comment by GavinRay97** [comment]
@ForsakenHarmony What should the values below be changed to? Not sure how this works since `preact/compat` is a folder inside of the `preact` repo:

```json
"react": "github:preact-compat/react#1.0.0",
"react-dom": "github:preact-compat/react-dom#1.0.0",
```

Would it just be `github:preact/compat`?

**Comment by christianpv** [comment]
> maybe because you can't alias to a sub-module?

I think so. Both are using preact/compat v10 behind the scenes.

https://github.com/preact-compat/react/blob/1.x/index.js
https://github.com/preact-compat/react/blob/1.x/package.json

https://github.com/preact-compat/react-dom/blob/1.x/index.js
https://github.com/preact-compat/react-dom/blob/1.x/package.json

**Comment by JoviDeCroock** [comment]
Yes, this is used to alias consistently in a Node environment. The standard alias will only alias inside of the web (webpack) env while the ssr-bundle/static-bundle would contain both copies of React and Preact.

**Comment by GavinRay97** [comment]
Ahh alright, understood now. Thanks everyone, clears up the confusion, appreciate the responses =)
