### ISSUE TITLE
Cannot read property '__H' of undefined when I try to use mjs-version of the "hooks" package

### ISSUE THREAD

**Issue by pokatomnik** [preactjs/preact#2690]
### Reproduction

Try to import hooks using from the mjs (with no bundlers) as described in the docs:
https://preactjs.com/guide/v8/getting-started/
https://preactjs.com/guide/v10/getting-started/#alternatives-to-jsx
The Preact itself is being imported fine, but I do not understand how should I import the `hooks` package properly.

### Steps to reproduce
Try to import hooks using `mjs` modules format like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)
```
<script type="module">
import {useState} from 'https://unpkg.com/preact@10.4.7/hooks/dist/hooks.mjs?module'

export const useFoo = () => {
  const [state, setState] = useState(0);
  return {state, setState};
}
</script>
```

### Expected Behavior

Hooks module is imported successfully

### Actual Behavior
I see
```
Cannot read property '__H' of undefined
```
error in the console and everything crashes (blank page).

**Comment by sventschui** [comment]
Usually it should work when using imports like this:

```js
import { createElement as h, render, Component } from 'https://unpkg.com/preact@latest?module';
https://unpkg.com/preact@latest/hooks/dist/hooks.module.js?module
``

(see https://github.com/JoviDeCroock/Vanilla-Preact-Application/blob/master/src/index.js#L1 ; https://github.com/JoviDeCroock/Vanilla-Preact-Application/blob/master/src/modules/home/index.js#L1 )

I guess this is a duplicate of #2564 #2439 #1961 #2571 

Or am I missing your point?

**Comment by pokatomnik** [comment]
Thank you, I'll try It. I'll let you know about the results of snippet you provided. Please do not reject the issue today.

**Comment by pokatomnik** [comment]
Yep, I seems to be right: there is an issue with the module you provided.
1) Importing the `setState` hook:
```
/* some-component.mjs */
import { useState } from 'https://unpkg.com/preact@latest/hooks/dist/hooks.module.js?module';

const MyComponent = () => {
  const [state, setState] = useState(0);
  // ... the rest code
};
```
And what I've got in the console:
![image](https://user-images.githubusercontent.com/6039544/89731703-c923e380-da51-11ea-8861-e51f7d6454e3.png)

**Comment by JoviDeCroock** [comment]
There's no issue for me when I run my example, could you fork it and change however the issue is caused?

**Comment by pokatomnik** [comment]
Yes, I figured out that hooks are working fine: https://jsfiddle.net/7mh09vx4/3/
I appreciate your effort, @sventschui, @JoviDeCroock. Thank you!

**Comment by pokatomnik** [comment]
I think, the problem is with the `latest` word you used. The `@latest` means that you want to use the latest available version of the package. I wanted to define version I need, the latest one (at this moment). And if you define a particular version, the preact minified code will not update the version, It is still using the `latest`. And this is the reason of this issue.

**Comment by pokatomnik** [comment]
For future searchers, here is a simple snippet for importing the Preact as the native Ecmascript module:
- The Skypack CDN is used as the only one which has the ES modules CDN I found (yes, the unpkg has this feature as well, but It is still _experimental_)
- The HTM is also included as a good replacement for the JSX.
```javascript
import * as _Preact from 'https://cdn.skypack.dev/preact@10.4.7';
import * as _Hooks from 'https://cdn.skypack.dev/preact@10.4.7/hooks';
import htm from 'https://cdn.skypack.dev/htm@3.0.4';
export const html = htm.bind(_Preact.h);
export default _Preact;
export const Hooks = _Hooks;
```

**Comment by vyushin** [comment]
The same error. I think this is because hooks.mjs imports latest version of preact for every version. Make an issue #3074

**Comment by pokatomnik** [comment]
@vyushin, the solution is not to use CDN you tried to use. ES modules feature they introduced is experimental. I have prepared a snippet, and It works just fine for me. Have you tried It?

**Comment by joel-chu** [comment]
Having the same problem, when using it with next.js and the trace indicate webpack is import the module from preact/hooks/dist/hooks.module.js

**Comment by JMPSequeira** [comment]
Was facing these exact issue with the typescript template.

I was using the `preact watch ` command and  as soon as I used `npm run dev` everything works.
Not sure if related or not but direct call do `preact watch` uses ts 4.2.4 and `run dev` uses 4.6.2.

**Comment by FunctionDJ** [comment]
In case anyone else comes here that aliases react to preact/compat: It seems like at least with Next.js, preact/compat is not yet fully compatible with React 18. Installing React/React-DOM 17 fixed an error for me that was similar to this one which occurred when trying to navigate.

**Comment by danielweck** [comment]
my workaround with preact/hooks has been to delete the sub-package.json so that the top-level export map in Preact's root package.json is used instead in a type=module context. otherwise I get runtime issues due to mixed CJS / ESM module loading

**Comment by DylanMashini** [comment]
Having this error on pages that use [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote). Any idea what causes this? It doesn't happen when I comment it out load the page, than uncomment it. (in dev mode) I think this is because it only happens on server renders, not on client renders. 
[Here's a minimum reproducible example](https://stackblitz.com/edit/nextjs-zg7kn5?file=next.config.js)

**Comment by marvinhagemeister** [comment]
For everyone coming across this thread: This error means that you have multiple copies of Preact running at the same time in your project. This can be caused by various reasons. Please make sure you only use one copy of Preact.

**Comment by sant123** [comment]
> For everyone coming across this thread: This error means that you have multiple copies of Preact running at the same time in your project. This can be caused by various reasons. Please make sure you only use one copy of Preact.

In case of importing through esm.sh like signals, be sure to specify external=preact so it is not loaded twice:

`"@preact/signals": "https://esm.sh/@preact/signals@1.2.3?external=preact"`

Thank you so much @marvinhagemeister

**Comment by emerak** [comment]
currently experiencing this as well

**Comment by rschristian** [comment]
> currently experiencing this as well

Without more information about your setup we can't do much besides tell you that you have a usage or tooling mistake then. Do you have a project or reproduction we can look at?
