### ISSUE TITLE
No working invite link for Preact's Slack workspace

### ISSUE THREAD

**Issue by rjharmon** [preactjs/preact#2696]
Hi all, looks like the working path to Slack is borked.  

### Reproduction

1. click to https://preact-slack.now.sh.  Error: "This deployment is not available anymore"
2. fiddle with Slack, end up at preact.slack.com, but have no access
3. fiddle with Slack, end up at https://slack.com/your-workspaces but have no access to the Preact workspace.  "Looking for a different workspace? You can [try another email address] or ask your Workspace Administrator for an invitation.

### Expected Behavior

A person can get to the Preact slack workspace

**Comment by marvinhagemeister** [comment]
Does https://chat.preactjs.com work for you?

**Comment by rjharmon** [comment]
ah, good.  that redirects to an invite URL.  :+1:

**Comment by marvinhagemeister** [comment]
We've updated all known places to us where we use the old url to use `chat.preactjs.com` instead 🎉
