### ISSUE TITLE
Suspense fails after upgrading to 10.4.7

### ISSUE THREAD

**Issue by hc-codersatlas** [preactjs/preact#2712]
Hi, tested all the previous releases up to 10.4.6 and it was fine. Likely the change in #2664 or #2661  that broke it. Using prefresh if that matters.

Reproduced with a blank project as follows: main renders -> app -> app is:

```
const Test = lazy(() => import("./Test"))

function App() {
  return (
    <div className="App">
      <Suspense fallback={<div>...</div>}>
        <Test />
      </Suspense>
    </div>
  )
}

export default App
```

Where Test is a button on screen.

Error is:

```
Uncaught TypeError: Cannot read property '__e' of undefined
    at h.__e (suspense.js:66)
    at Object.options.<computed> [as __e] (catchError.js:14)  
    at T (index.js:260)  
    at g (children.js:143)  
    at T (index.js:214)  
    at g (children.js:143)  
    at T (index.js:214)  
    at g (children.js:143)  
    at j (index.js:397)  
    at T (index.js:245) 
```

**Comment by JoviDeCroock** [comment]
Hey,

Seems to be working with current latest https://codesandbox.io/s/competent-matsumoto-62oz4?file=/package.json

**Comment by hc-codersatlas** [comment]
Thanks, has fixed this issue. Now get an error related to nested suspense, but I can already see a PR for it.

**Comment by JoviDeCroock** [comment]
Yes, `nested-suspense` boundaries without dom-nodes in between are currently an issue. It hasn't been fixed yet but it has been identified.

**Comment by aguilera51284** [comment]
any update for this ... i get the same error but with wouter-preact and suspense router 👍
