### ISSUE TITLE
umd build of preact/compat not working in standalone html file

### ISSUE THREAD

**Issue by JohnDDuncanIII** [preactjs/preact#2719]
I am working on a minimal `index.html` `preact`/`preact-compat`/`htm` example using `Suspense` and `Lazy` that should work in a standalone `index.html` file.

While it is easy to get this to work in an es6 module (see https://github.com/preactjs/preact-compat/issues/544#issuecomment-647805941), I cannot seem to get it to work in a standalone `index.html` file.

---

### Reproduction / Steps to reproduce
```html
<!DOCTYPE html>
<html lang="en">
	<meta charset="UTF-8">
	<title>Example</title>
	
	<script src="https://unpkg.com/htm@latest/dist/htm.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/dist/preact.min.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/compat/dist/compat.umd.js"></script>
</html>
```

errors out with

`compat.umd.js:1 Uncaught TypeError: Cannot set property 'preactCompat' of undefined`

since `e.preactCompat` is undefined in

`https://npm.reversehttp.com/preact@latest/compat/dist/compat.umd.js`

<img width="480" alt="Screen Shot 2020-08-26 at 1 50 44 AM" src="https://user-images.githubusercontent.com/9257785/91264306-94e14000-e73e-11ea-8479-b5d4fde99966.png">

---

```html
<!DOCTYPE html>
<html lang="en">
	<meta charset="UTF-8">
	<title>Example</title>
	
	<script src="https://unpkg.com/htm@latest/dist/htm.js"></script>
	<script src="https://unpkg.com/preact@latest/dist/preact.min.js"></script>
	<script src="https://unpkg.com/preact@latest/compat/dist/compat.umd.js"></script>
</html>
```

errors out with

`Uncaught TypeError: Cannot read property 'useState' of undefined`

since `useState` is undefined in

`https://unpkg.com/preact@latest/compat/src/index.js`

<img width="484" alt="Screen Shot 2020-08-26 at 1 53 09 AM" src="https://user-images.githubusercontent.com/9257785/91265517-e8538e00-e73e-11ea-9d5d-280a22f9f339.png">

---

I also tried

```html
<!DOCTYPE html>
<html lang="en">
	<meta charset="UTF-8">
	<title>Example</title>

	<script src="https://unpkg.com/htm@latest/dist/htm.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/dist/preact.umd.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/compat/dist/compat.umd.js"></script>
</html>
```

as well as

```html
<!DOCTYPE html>
<html lang="en">
	<meta charset="UTF-8">
	<title>Example</title>
	
	<script src="https://unpkg.com/htm@latest/dist/htm.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/dist/preact.min.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/hooks/dist/hooks.umd.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/compat/dist/compat.umd.js"></script>
</html>
```

since I didn't see `useHooks` in the `preact` global var, but ran into similar errors for both.

---

While I understand that the optimal way to use `preact`/`preact-compat`/`htm` is inside of an es6 module, given that this is a lightweight react alternative, I was hoping that I could just import it as a umd global without needing to use a bundler nor define an es6 module.

### Expected Behavior
`react-compat` should load successfully

### Actual Behavior
`react-compat` fails to load successfully

---

Thanks for your time!

Similar issues:
https://github.com/preactjs/preact-compat/issues/544
https://github.com/preactjs/preact/issues/2564
https://github.com/preactjs/preact/issues/2571

**Comment by JohnDDuncanIII** [comment]
I was actually able to get this to work with

```html
<!DOCTYPE html>
<html lang="en">
	<meta charset="UTF-8">
	<title>Example</title>
	
	<script src="https://unpkg.com/htm@latest/dist/htm.js"></script>
	<script src="https://unpkg.com/preact@latest/dist/preact.umd.js"></script>
	<script src="https://unpkg.com/preact@latest/hooks/dist/hooks.umd.js"></script>
	<script src="https://unpkg.com/preact@latest/compat/dist/compat.umd.js"></script>
</html>
```

<img width="1392" alt="Screen Shot 2020-08-26 at 2 51 23 AM" src="https://user-images.githubusercontent.com/9257785/91270775-2eaceb00-e747-11ea-8688-8bfaf9b2a972.png">

It seems as if `hooks/dist/hooks.umd.js` is a hard requirement to use `compat/dist/compat.umd.js`, which I did not realize.

---

Curiously,

```html
<!DOCTYPE html>
<html lang="en">
	<meta charset="UTF-8">
	<title>Example</title>

	<script src="https://npm.reversehttp.com/htm@latest/dist/htm.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/dist/preact.umd.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/hooks/dist/hooks.umd.js"></script>
	<script src="https://npm.reversehttp.com/preact@latest/compat/dist/compat.umd.js"></script>
</html>
```

does not work.

<img width="1392" alt="Screen Shot 2020-08-26 at 2 50 59 AM" src="https://user-images.githubusercontent.com/9257785/91271079-9e22da80-e747-11ea-976b-417d07b84ee9.png">

**Comment by developit** [comment]
Hi @JohnDDuncanIII - `npm.reversehttp.com` should only really be used for ES Modules, I'm not sure that it will successfully serve UMD bundles since it tries to convert everything to ESM.

The two options are:

**1. Use UMD from unpkg**: _(as you discovered)_

```html
<script src="https://unpkg.com/htm@latest/dist/htm.js"></script>
<script src="https://unpkg.com/preact@latest/dist/preact.umd.js"></script>
<script src="https://unpkg.com/preact@latest/hooks/dist/hooks.umd.js"></script>
<script src="https://unpkg.com/preact@latest/compat/dist/compat.umd.js"></script>
<script>
    const React = preactCompat,
        ReactDOM = preactCompat;
    const html = htm.bind(preact.h);
    function App () {
        const [c, add] = React.useReducer(x => x+1, 0);
        return html`<button onClick=${add}>${c}</button>`;
    }
    ReactDOM.render(html`<${App} />`, document.body);
</script>
```

**2. Use ESM from npm.reversehttp.com**:

This has the benefit of delivering all your dependencies in a single optimized bundle.

```html
<script type="module">
    import { html, render, preactCompat as React } from 'https://npm.reversehttp.com/preact,preact/compat,htm/preact';
    function App () {
        const [c, add] = React.useReducer(x => x+1, 0);
        return html`<button onClick=${add}>${c}</button>`;
    }
    render(html`<${App} />`, document.body);
</script>
```

**Comment by developit** [comment]
I'll close this issue out since it seems like everything's working.

**Comment by JohnDDuncanIII** [comment]
Thanks for the response, @developit! Your examples were helpful.

All good on my end 👍
