### ISSUE TITLE
createContext has a non-standard (and not used) argument

### ISSUE THREAD

**Issue by dvoytenko** [preactjs/preact#2736]
### Reproduction

See [create-context.js](https://github.com/preactjs/preact/blob/df748d106fb78fbd46d14563b4712f921ccf0300/src/create-context.js#L5). The value of the `contextId` argument appears to be unused. Some compilers, such as Closure error out when migrating. This can normally be ignored, but not clear if it's justified in this case since the value is unused.

### Expected Behavior

The React's `createContext` is declared with one argument.

### Actual Behavior

The Preact's `createContext` is declared with two argument and the value of the second argument is not used.

**Comment by JoviDeCroock** [comment]
It is used on the line underneath, this is a byte saving trick since you don't have to use the `keyword var`.

**Comment by dvoytenko** [comment]
@JoviDeCroock hmm. IMHO such byte-saving tricks should be left to the bundler/rollup/compiler/etc rather than break method signature.

**Comment by JoviDeCroock** [comment]
A bundler does no code optimizations so that isn't really its responsibility.

**Comment by developit** [comment]
There are a number of cases where we do this in Preact, though typically not in exported methods.

Unfortunately, there are no current compilation tools use this technique. We might be able to do it via Babel, but that'd be a feature request for Microbundle rather than for Preact.

**Comment by dvoytenko** [comment]
Certainly. But I do think "typically not in exported methods" is a good standard to follow. W.r.t. to React compatibility. I agree - it'd certainly make sense to diverge APIs where it has semantic meaning. In this case, however, this is purely an implementation detail. E.g. tomorrow it might disappear from the `createContext` with no perceptible API difference but would force strict-compiler users to change their code.

**Comment by JoviDeCroock** [comment]
Closing this as a deliberate design choice we've made
