### ISSUE TITLE
Add SSR hydration mismatch errors

### ISSUE THREAD

**Issue by JamesBurnside** [preactjs/preact#2737]
In React when hydrating a server side rendered page using `ReactDom.hydrate` this API will produce a warning in debug builds when the html generated client side did not match the html generated server side, for example:
![image](https://user-images.githubusercontent.com/2684369/91904341-9c7e7880-ec59-11ea-96dc-24289d69a3b5.png)

Preact should show the same warnings so developers know when a mismatch has occured.

**Comment by betula** [comment]
I consider this a significant point.
Please Preact - this is sorely lacking!
