### ISSUE TITLE
Upgrading to 10.4.8 breaks IE11 support.

### ISSUE THREAD

**Issue by CheesyFeet** [preactjs/preact#2738]
10.4.8 breaks on IE11, fails with error: "Assignment to read-only properties is not allowed in strict mode". Tested on 10.4.7 without issue.

### Reproduction
1. Install 10.4.8
2. Run on IE11

### Steps to reproduce
Occurs when loading the Preact app - no interaction is needed. Difficult to say what the error is exactly as no useful stack trace is given, but we're using hooks, including useRef (which I saw mentioned in the 10.4.8 changelog). Not using preact/compat.

### Expected Behavior
IE11 should work without problem (as it does on 10.4.7).

### Actual Behavior
App fails to load. IE console shows '[object Error]' object with message "Assignment to read-only properties is not allowed in strict mode".

Sorry for the poor pointers to where the problem lies - IE devtools are showing their age!

**Comment by JoviDeCroock** [comment]
This problem should be fixed in current master, you can try the build offered [here](https://github.com/preactjs/preact/runs/1041191457) to  see if it resolves your issue.

**Comment by CheesyFeet** [comment]
Yep that fixes it thanks - sorry I didn't see the fix had been merged already!

**Comment by marvinhagemeister** [comment]
No worries, we'll cut a new release soon 👍

**Comment by klh** [comment]
you should add this to the release notes of latest release as a bug fix.
