### ISSUE TITLE
onKeyDownCapture and onKeyDown overwrite each other

### ISSUE THREAD

**Issue by mischnic** [preactjs/preact#2739]
### Reproduction

https://codesandbox.io/s/preact-on-capture-overwrite-e8dfk?file=/src/index.js:0-548

```js
//import React from "react";
//import ReactDOM from "react-dom";

import React from "preact/compat";
import ReactDOM from "preact/compat";

function App() {
  return (
    <div
      onKeyDown={() => console.log("div noncapture")}
      onKeyDownCapture={() => console.log("div capture")}
    >
      <input
        onKeyDown={() => console.log("input noncapture")}
        onKeyDownCapture={() => console.log("input capture")}
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

### Steps to reproduce

Open codesandbox and type into the input field

### Expected Behavior

Console:
```
div capture 
input capture 
input noncapture 
div noncapture 
```
This is how React behaves

### Actual Behavior

```
div capture 
input capture 
input capture 
div capture 
```

**Comment by marvinhagemeister** [comment]
Interesting! Both map to the same `keydown` event, but with different options passed to `node.addEventListener()`. Looks like we need a more generic way to differentiate them.

**Comment by devongovett** [comment]
https://github.com/preactjs/preact/blob/952a7e279eb2d4346b26d5d00ece18f32beb2c17/src/diff/props.js#L92-L104

Maybe something in there? `Capture` gets removed from `name` on line 92. Then if you had both capture and not, `dom._listeners[name]` would overwrite each other.

**Comment by devongovett** [comment]
Attempted to make a PR for this #2740
