### ISSUE TITLE
Differences in Preact Suspense and React Suspense

### ISSUE THREAD

**Issue by ahabhgk** [preactjs/preact#2747]
### Reproduction

[React Suspense Demo](https://codesandbox.io/s/silent-framework-bd3l8?file=/src/index.js)

[Preact Suspense Demo](https://codesandbox.io/s/damp-wood-2rkdc?file=/src/index.js)

### Expected Behavior

Same as React, first show `Loading Profile...`, then show `Loading posts...` after profile is loaded

### Actual Behavior

Showing `Loading Profile...` and `Loading posts...` at the same time

**Comment by developit** [comment]
This likely changed in 10.5.

**Comment by ahabhgk** [comment]
> This likely changed as of 10.5, need to update and check if it's fixed.

The Preact version in the codesandbox demo is 10.5.2, but still has the problem.

**Comment by JoviDeCroock** [comment]
We seem to have a bug that requires you to wrap the Inner suspense with a real dom-node: https://codesandbox.io/s/loving-voice-0t6ol?file=/src/index.js:1645-1651 We'll look into this

**Comment by tanhauhau** [comment]
i believe this will be fixed by https://github.com/preactjs/preact/pull/2910

**Comment by JoviDeCroock** [comment]
I can confirm this is fixed in our HEAD https://codesandbox.io/s/wizardly-thunder-p1qjv?file=/package.json
