### ISSUE TITLE
[preact/debug] false positive complain about memoization

### ISSUE THREAD

**Issue by o-alexandrov** [preactjs/preact#2758]
### Reproduction

Libraries:
- preact `10.4.8`

### Steps to reproduce

[Press here to see an example](https://github.com/framer/motion/blob/main/src/components/AnimatePresence/PresenceChild.tsx#L61).
Dynamic dependencies of memoized calculations through `useMemo/useCallback` result in a false positive complain about memoization.

<img width="687" alt="Screen Shot 2020-09-19 at 5 13 31 AM" src="https://user-images.githubusercontent.com/9992724/93664765-f7281a80-fa36-11ea-9648-e90f1b5d7821.png">

### Expected Behavior

Dynamic dependencies shouldn't result in a console's complain.

### Actual Behavior

False positive complain.

**Comment by marvinhagemeister** [comment]
I'm not sure I understand. Looking at the linked code, it sets the dependency array to `undefined`. That's the same as not setting it in the first place in JavaScript. So the code is essentially doing this:

```js
useMemo(() => ...)
// vs
useMemo(() => ..., [])
```

Without a dependency array the memoization will not work as the value is always recomputed on each render.

**Comment by o-alexandrov** [comment]
@marvinhagemeister based on the comment above the linked line in the description of this issue, seems like `framer-motion`'s devs intent was exactly **to disable memoization conditionally**.

Based on your comment, I understand that your proposal is to:
- not to set `undefined`, but instead explicitly mark all dependencies

The problem is:
- they don't need memoization in certain conditions
- it's much more efficient to disable memoization by passing `undefined`, rather than specifying dependencies, that you would know would always be triggered as **changed** in that certain condition
  - hence there is a conditional memoization

**Comment by o-alexandrov** [comment]
@InventingWithMonster could you please share your view?
Hopefully, I didn't misinterpreted the intention in the mentioned file in the description of this Issue above.
This issue is about DX when working with `preact` and `framer-motion`

**Comment by InventingWithMonster** [comment]
@o-alexandrov That's correct. In some circumstances we want to disable memoisation, so we pass `undefined`. We can't count on this being true for the duration of the lifecycle of the component so we can't conditionally use the hook, and the alternative is goofy stuff like `[isPresent] : [Math.random()]`

IMO I don't think it's helpful to have these warnings. They will run for external libraries and they haven't been written in the same development env as the one they're consumed in. Most likely these will be written for React, which doesn't have this warning, so it isn't easy for library authors to avoid. I also don't think library internals should be exposed in this way.

Linting feels more appropriate.

**Comment by afzalsayed96** [comment]
Is there a way to turn this off in dev? Can I contribute a PR for resolving this?

**Comment by marvinhagemeister** [comment]
> Is there a way to turn this off in dev?

No.

> Can I contribute a PR for resolving this?

Yes 👍

**Comment by afzalsayed96** [comment]
@marvinhagemeister Okay what would be the right approach here according to you?

**Comment by marvinhagemeister** [comment]
@afzalsayed96 remove that check in `preact/debug`. My understanding is that linters can/should take care of that already and linter rules can be easily ignored on a case-by-case basis.
