### ISSUE TITLE
Question regarding the use of Preact + TypeScript + custom elements (as in "web components")

### ISSUE THREAD

**Issue by mcjazzyfunky** [preactjs/preact#2761]
I really wonder: What rules should a custom element satisfy to work out of the box perfectly fine with (a decent subset of) JSX based UI libraries like Preact, Dyo, Crank etc. when you are using TypeScript and you want 100% type safety?

As for the custom element's properties and attributes, things are normally not a problem (even if the name of the property and the corresponding attribute differ => e.g. property name "labelText" vs. attribute name "label-text").
Almost all JSX based UI libraries use (in case of custom elements) a heuristic of something like: If there's a property with the given JSX prop name then use that, otherwise use `setAttribute`.

But things are quite different for events, if the event names are not always lowercased without hyphen (e.g. 'tablecolumnheaderclick') but kebab-cased instead (e.g. 'table-column-header-click'), which is quite common.

Let's say you have a third-party custom element `<some-component.../>` which sends out events of type `'some-event'`, so you can use `someComponent.addEventListener('some-event', ..)`.
Let's say this custom element also has a corresponding property for this event called `onSomeEvent`, so you can also use `someComponent.onSomeEvent = (ev) => ...` as an alternative to the use of `addEventListener` (and let's assume for each event type there's always such a corresponding 'onWhateverEvent' property).

If you use this custom element with for example Preact or Dyo you have to write (as both will use `addEventListener`internally):

```jsx
<some-component onsome-event={someEventHandler}/>
```

But if you want to use this custom element with for example Crank.js, you have to write (as Crank.js only uses onevent properties in this case, no `addEventListener`):

```jsx
<some-component onSomeEvent={someEventHandler}/>
```
(btw: This looks much nicer IMHO - but beauty may be in the eye of the beholder :wink:)

You may say: Not a big deal, just use one pattern if you are working with UI library ABC and the other pattern if you are using UI library XYZ.

But things get more challenging when everybody uses TypeScript and everybody agrees that things should be 100% type safe (at least where possible).

How shall the 3rd party author of that custom element type her components (as she does not know what UI libraries the users of her custom elements are using)?

You may say: For Preact you can use the Preact specific JSX namespace and maybe something like the following will do the job (please be lenient if this may not be 100% correct - I think you'll understand what I mean)

```typescript
declare global { 
  // this is for Preact
  namespace preact {
    namespace JSX {
      interface IntrinsicElements {
        'some-component': {
          'onsome-event': ...
        }
      }
    }
  }
  
  // this is for the other UI libraries (for example Crank.js)
  namespace JSX {
    interface IntrinsicElements {
      'some-component': {
        'onSomeEvent': ....
      }
    }
  }
}
```

Now things are type safe, let's say at least for Preact and Crank.

Now you have another problem: Normally that 3rd party component author has the type of the props of her custom elements, and normally she could use them easily with

```typescript
  namespace JSX {
    interface IntrinsicElements {
      'some-component': SomeComponentProps
    }
  }
```

But for the current Preact version, for each event she always has to write the TS type info by hand (as it is not `onWhateverEvent` but `onwhatever-event`), which seems quite annoying (even if she does it somehow semiautomatically).

:question: Wouldn't things be way easier if Preact (and other JSX based UI libraries) use the following heuristics for custom elements?
For each JSX prop first check whether there's a custom element property with exact that name. If yes then set that property directly (even if it starts with 'on'), otherwise if the JSX prop name starts with 'on' then derive the event name from the JSX prop name (whatever heuristic the UI library uses for that) and use `addEventListener` otherwise use `setAttribute`.
So you could always use `onWhateverEvent` in the TypeScript definition and typing is far more easy and things are at least working fine if the custom elements always also provide an `onWhateverEvent` property for each event type.

Many thanks in advance for your answer - and sorry for the long text ...

**Comment by marvinhagemeister** [comment]
Whilst we do have that exact logic for all properties except event listeners, we cannot broaden it to include events. Doing so would be a spec violation as events are case-sensitive. Dispatching an event `foo` is different from dispatching `Foo`.

There is an argument to be made here in what's actually being used in the wild vs the spec for sure.

The cool thing about Preact is that you can easily add that logic in user-land.

```jsx
import { options } from "preact";

// Will be called whenever a vnode is constructed.
let oldVNode = options.vnode;
options.vnode = vnode => {
  const { type, props } = vnode;
  if (type === "my-custom-element") {
    for (const key in props) {
      if (key[0] === "o" && key[1] === "on") {
        const lower = key.replace(/[A-Z0-9]/, '-$&').toLowerCase();
        props[lower] = props[key];
        delete props[key];
      }
    }
  }

  // Call previously defined option hook as to not break the chain
  if (oldVNode) oldVNode(vnode);
}
```

**Comment by mcjazzyfunky** [comment]
Thank you very much, Marvin, for your answer. May I ask what exactly you mean by
>  Doing so would be a spec violation as events are case-sensitive.

What "spec" is violated?
Event names are case-sensitive, that's 100% true, of course. But that does not mean, that Preact violates any spec when property `onClick` handles events of type/name `click` (with lower case "c"). So why should a custom element property named `onRowSelect` not be allowed to handle events of name `row-select`?

For example [DOM onevent handlers](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers) are a similar concept and you can read there: 

> The onevent handler is usually named with the event it reacts to, like onclick, onkeypress, onfocus, etc.

"is usually named" does not mean "must always exactly be named", does it?
Please see these questions in a more general context, not only Preact specific, they may concern other JSX based UI libraries as well.

**Comment by marvinhagemeister** [comment]
@mcjazzyfunky The "classic" DOM event names are all in lowercase. This makes it a lot easier to ensure compatibility. Custom Elements opened up the flood-gates by being case sensitive. An event named `row-select` is different from `Row-Select`. According to the CE spec they are not the same.

I guess it more or less comes down to what people are actually doing vs what the spec says. Are there really examples in the wild where CE's use uppercase letters or does everyone use a completely lower cased event anyways.

**Comment by mcjazzyfunky** [comment]
Thanks again, Marvin. So, I close this issue now.

Just for information:
> Are there really examples in the wild where CE's use uppercase letters or does everyone use a completely lower cased event anyways.

Actually for example [Shoelace web components](https://shoelace.style/components/dialog?id=events) use camelCase event names (e.g. `slOverlayDismiss`). SAP UI5 web components use kebab-case event names (e.g. `after-close`).
