### ISSUE TITLE
preact rendering <style> tag inside <noscript>, whereas react does not

### ISSUE THREAD

**Issue by jaredh159** [preactjs/preact#2797]
I'm not sure if this matters to the library maintainers, or how much compatibility/interop with React is a goal, but I noticed a subtle difference between React and Preact that caused a fairly big blocker trying to switch a Gatsby site over to preact.

Basically, this jsx:

```jsx
<noscript>
  <style dangerouslySetInnerHTML={{ __html: "body { background-color: pink }" }} />
</noscript>
```

Renders differently between React and preact.  In react, you get an **empty** `<noscript>` tag.  Preact renders out the `<style>` tag inside the noscript.  Codepens below.

The use-case here is that I'm trying to use `gatsby-background-image` which adds styles to `noscript` like the example above. With react, nothing renders, but with preact, I get extra style tags which load in un-optimized images, destroying any performance benefit gained from switching to preact.

### Reproduction

Codepen with React:
https://codepen.io/jaredh159/pen/NWrGyPq?editors=1010

Codepan with Preact:
https://codepen.io/jaredh159/pen/mdEeXJg?editors=1010

_Note: you'll have to use the dev tools to inspect to see the `<noscript>` contents, as it's not visible, of course._

### Steps to reproduce

See codepens above ^^^

### Expected Behavior

I would have hoped that preact matched the behavior of react.

### Actual Behavior

preact rendered the contents of the `<noscript>` tag, unlike React.

**Comment by marvinhagemeister** [comment]
That sounds like React isn't following the [HTML-Spec](https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element) correctly. It states:

> When scripting is disabled, not in a `<head>` element: transparent, but there must be no `<noscript>` element descendants.

Which translates as any of the usual elements is a valid descendant of a `<noscript>` element, even `<style>` tags. The rules are different when the `<noscript>` is inside the `<head>` section of the document. In the linked codesandbox that's not the case.

Looks like React has a bug there. I can't come up for valid reasons to disallow style-tags in that context as it is often used to customize the fallback experience on sites I've seen.

**Comment by jaredh159** [comment]
@marvinhagemeister yeah, i understand your reasoning here.  digging into it a bit more, it seems react made a conscious decision to ignore the contents of the `<noscript>` when they are client-rendering:

https://github.com/facebook/react/blob/e614e6965749c096c9db0e6ad2844a2803ebdcb6/packages/react-dom/src/__tests__/ReactDOMServerIntegrationElements-test.js#L594

Which kind of makes sense, if you think about it -- if react is there, doing things on the client, then the `<noscript>` by definition is going to be not necessary. So maybe in a sense they consider it a performance optimization?  A little more background here:

https://github.com/facebook/react/issues/11423

**Comment by developit** [comment]
Here's a patch that makes Preact skip noscript contents on the client only:

```js
import { options } from 'preact';
const CLIENT = typeof document !== 'undefined';
const old = options.vnode;
options.vnode = vnode => {
  if (vnode.type === 'noscript' && CLIENT) {
    vnode.props.children = null;
  }
  if (old) old(vnode);
};
```

**Comment by jaredh159** [comment]
@developit thanks! I didn't know about the options hooks API, but i looked it over and I think I understand.  I'm not exactly sure _where_ I'd implement this, but I'm guessing if I stick it in some entry-type file to hook in before Preact does any work, that would be the ticket.  I'll give it a go. Appreciate the help!

**Comment by developit** [comment]
@jaredh159 yep! Just have it run before your component code.
