### ISSUE TITLE
[Typescript] Allow alt attribute to be string or Element?

### ISSUE THREAD

**Issue by coldshower** [preactjs/preact#2799]
https://github.com/preactjs/preact/blob/master/src/jsx.d.ts#L607

How do you feel about making the type for `alt` be allowed to be either a string or an Element?

Asking because when internationalization libraries like `react-intl` are used, we may want to do something like this:

```
<img
  alt={<FormattedMessage/>}
```

but the current types prohibit this and ask us to pass a `string` to the `alt` attribute instead.

**Comment by marvinhagemeister** [comment]
It's a slippery slope as any attribute can potentially be a JSX element at which point everything would result in being typed as `any`. A more practical approach is to use the hooks API from `react-inlt`. It avoids this problem alltogether.

According to [one of their examples](https://github.com/formatjs/formatjs/blob/main/packages/react-intl/examples/Hooks.tsx) it would look like the following:

```jsx
function MyComponent() {
  const { formatMessage } = useIntl();
  return <p>{formatMessage({ id: 'simple' })}</p>;
}
```

**Comment by coldshower** [comment]
Thanks for the response!
