### ISSUE TITLE
Babel ^7.12.0 breaks preact jsx-runtime export

### ISSUE THREAD

**Issue by johakr** [preactjs/preact#2801]
Hi,

due to this change in babel https://github.com/babel/babel/pull/12116/commits/d6b0822ee9e95321a417b321a6687048faf1c3a1, the preact jsx runtime can't be imported anymore. Preact exports the jsx-runtime as folder, but babel expects a file with file ending `.js` now (`${source}/jsx-runtime.js` and `${source}/jsx-dev-runtime.js`).

`Module not found: Error: Can't resolve 'preact/jsx-runtime.js'`

Is that something we should address at the babel repo, or do we need to change how the runtime is exported in preact?

**Comment by nicolo-ribaudo** [comment]
Fixed in `@babel/helper-builder-react-jsx-experimental@7.12.4`

**Comment by rati-dzidziguri** [comment]
any ideas on how to fix this I am getting the same error 
`Module not found: Can't resolve 'react/jsx-dev-runtime'` and using preact 10.5.7 with craco.

**Comment by nicolo-ribaudo** [comment]
@rati-dzidziguri 

You need to pass `"importSource": "preact"` to the JSX plugin/preset.

**Comment by rati-dzidziguri** [comment]
@nicolo-ribaudo, thank you very much. Would you please provide a little more details on which plugin to install and how to do this? Highly appreciate this answer.

**Comment by nicolo-ribaudo** [comment]
I'm not sure about your setup (or the default build setup for Preact), but there is _already_ compiling JSX in your build process (either TS, or Babel): you need to find this existing tool and update its config.

**Comment by rati-dzidziguri** [comment]
I understand; thank you very much. here are my package JSON and configs.
![image](https://user-images.githubusercontent.com/52178984/100460225-44340700-30e0-11eb-872c-2544f0961a8d.png)

craco.config.js
![image](https://user-images.githubusercontent.com/52178984/100460270-57df6d80-30e0-11eb-994d-d9ced496002c.png)

I have no other customizations, but this and initially used CRA to create the base skeleton.

**Comment by developit** [comment]
I'm guessing this is something strange "craco" is doing.
