### ISSUE TITLE
wrong export

### ISSUE THREAD

**Issue by hiltpold** [preactjs/preact#2807]
The index.js exports `export { unmount as __u } from './diff';` on line 13. 
Shouldn't that be changed to `export { unmount as __u } from './diff/index';` ?

**Comment by JoviDeCroock** [comment]
When building Preact this will automatically be converted to `./diff/index.js` since most build tools support this.

**Comment by hiltpold** [comment]
Thank you! I don't use such tools and work with vanilla ES6 modules. But I configured my web server to imitate the behaviour you explained.

**Comment by JoviDeCroock** [comment]
This behavior is not present in the built files, you can just use https://unpkg.com/preact@10.5.5/dist/preact.module.js?module in an import statement.
