### ISSUE TITLE
Suspense renders twice on client when used with SSR

### ISSUE THREAD

**Issue by droganov** [preactjs/preact#2809]
To reproduce render a page on server, and then do client render

As a result Suspense blocks got rendered twice on the same client page
Client block is rendered above server block, and captures user events
SSR block is rendered below and does not capture user events

Expected behavior is to replace SSR blocks client with client blocks

If I disable JS in browser the blocks do not duplicate
When no lazy/Suspense is used  the blocks do not duplicate

Preact version
10.5.5
reproducible in both FF and Chromium

**Comment by JoviDeCroock** [comment]
Could you provide a reproduction, main question to be answerred here isare you resolving boundaries on the server?

Example sandbox: https://codesandbox.io/s/reverent-colden-i3jcu

**Comment by droganov** [comment]
@JoviDeCroock Thank you for quick response

I checked you example and I need to close this.

The case was that I used "preact-ssr-prepass": "^1.1.1"
it wasn't resolving lazy imports, so I had a direct import on server side to prevent errors

after bumping it to "preact-ssr-prepass": "^1.1.2" the problem has gone
