### ISSUE TITLE
An effect that inserts iframes may run twice in Safari

### ISSUE THREAD

**Issue by GoodForOneFare** [preactjs/preact#2814]
### Reproduction
Here's a codesandbox showing a Preact effect running twice in Safari: https://codesandbox.io/s/safari-duplicate-effects-b2lnf.

| Chrome result | Safari result |
| ----- | ----- |
| <img width="477" alt="safari-duplicate-effects - CodeSandbox 2020-11-04 12-58-32" src="https://user-images.githubusercontent.com/673655/98150995-7ebdd180-1e9d-11eb-8134-d6b418b015e1.png"> | <img width="447" alt="safari-duplicate-effects - CodeSandbox 2020-11-04 13-00-00" src="https://user-images.githubusercontent.com/673655/98151106-ab71e900-1e9d-11eb-9029-1fcacc83b957.png"> |

The root cause appears to be Safari running pending promises when an iframe is inserted into the DOM.  You can verify by running this code in Safari's dev console:
```
// Inserting a div results in panda/monkey
defer = Promise.prototype.then.bind(Promise.resolve())
defer(() => console.log("🐵")); document.body.appendChild(document.createElement('div')); console.log("🐼")
🐼
🐵

// Inserting an iframe results in monkey/panda
defer = Promise.prototype.then.bind(Promise.resolve())
defer(() => console.log("🐵")); document.body.appendChild(document.createElement('iframe')); console.log("🐼")
🐵
🐼
```

As far as I can tell, the exact setup to reproduce is:
* A parent component that can have its state updated by a child component
* An effect that updates the parent component's state
* Another effect that inserts an iframe into the DOM

The state update enqueues components for re-render, then the iframe insertion causes Safari to immediately kick off a re-render _inside Preact's current render loop_.  This happens before the current render has cleared effects arrays, so the effects are executed again.

The sandbox looks contrived, but I ran into this while integrating PayPal into a Preact app.

### Steps to reproduce
Running the sandbox in Safari 13.1.2 should illustrate the problem.  The same sandbox will show one less element in Chrome.

### Expected Behavior
Preact should not run an effect with no dependencies twice.

### Actual Behavior
Preact runs an effect with no dependencies twice.

**Comment by marvinhagemeister** [comment]
I can reproduce that in the latest Safari. It seems like it does something different when scheduling `requestAnimationFrame` callbacks and all `useEffect` callbacks are called twice. When replaced with a micro-task scheduler it works as expected:

```jsx
import { options } from "preact";

// Works in Safari
options.requestAnimationFrame = Promise.prototype.then.bind(Promise.resolve());
```

**Comment by developit** [comment]
Another option would be to use a double promise resolution for the render queue.

**Comment by gaearon** [comment]
Did anyone file a WebKit bug for this? We're seeing the same issue in https://github.com/facebook/react/issues/22459.

**Comment by gaearon** [comment]
Filed as https://bugs.webkit.org/show_bug.cgi?id=235322.

**Comment by developit** [comment]
Awesome, thanks for filing that @gaearon!

**Comment by JoviDeCroock** [comment]
Should be fixed in https://github.com/WebKit/WebKit/pull/1909

**Comment by mdentremont** [comment]
Despite being fixed in Webkit - this issue is still present on Safari <16 which is a huge number of users still.

On the React side, they were able to ship a workaround so that users of the library don't need to implement workarounds, should something similar be considered for preact?

See:
- https://github.com/facebook/react/issues/22459
- https://github.com/facebook/react/pull/24459
