### ISSUE TITLE
class prop is getting leaked again when using className 

### ISSUE THREAD

**Issue by ansonatloop** [preactjs/preact#2821]
The `class` prop is getting leaked to components when using `className` since `10.5.4`.

This bug was fixed in `10.5.3` via #2772 and seems to have an older, still-open bug via #2582. I'm opening this issue as it seems #2582 was forgotten about. 

It would be great to squash this zombie bug for eternity, as it causes quite a bit of issues (predictably).

Example:
```
const App = ({className, ...rest}) => (
  <div className={className}>
    <div {...rest} />
  </div>
);

<App className="my-class" />
```
In `10.5.3`, `"my-class"` will be added to the container div _only_. In `>10.5.4`, the class is added to both divs.

**Comment by Menci** [comment]
Yes. This breaks [semantic-ui-react](https://react.semantic-ui.com/)'s `Form.Field`.

**Comment by damianobarbati** [comment]
Wow I just stumbled upon this: I see both className and class prop passed with same value, I was debugging a weird double-class applied and found out it (spreading `{ className, ...props }`)).

Confirming 10.5.3 does not have the bug.

**Comment by JoviDeCroock** [comment]
This seems fixed in our later versions https://codesandbox.io/s/cranky-lalande-5ukb8c?file=/src/index.js
