### ISSUE TITLE
componentDidCatch and errorInfo

### ISSUE THREAD

**Issue by sqal** [preactjs/preact#2835]
Hi. I have a question regarding componentDidCatch lifecycle hook. React's componentDidCatch receives two parameters, the first one is an error and the second is errorInfo which contains additional details about the error (like stack trace). I wanted to replace React with preact/compact in my app, however, I didn't manage to do it because I use @sentry/react package and its ErrorBoundry component relies on errorInfo parameter https://github.com/getsentry/sentry-javascript/blob/master/packages/react/src/errorboundary.tsx#L62 so missing `errorInfo`  in preact simply crashes my app.

What's the reason for errorInfo not being present in Preact's componentDidCatch hook? Shouldn't preact/compat be 100% compatible with the React? 

`...preact/compat, which is a thin layer over Preact that attempts to achieve 100% compatibility with React.`

**Comment by marvinhagemeister** [comment]
> What's the reason for errorInfo not being present in Preact's componentDidCatch hook? Shouldn't preact/compat be 100% compatible with the React?

Afaik there never was a conscious decision to leave that out. Looks more like something that got forgotten or overlooked, simple as that.

**Comment by donlion** [comment]
Any news on this?
