### ISSUE TITLE
Yarn offline-mirror: Integrity check failed for "@preact/compat"

### ISSUE THREAD

**Issue by lindsaybloomsonos** [preactjs/preact#2837]
Hi! My team is migrating one of the packages in a monorepo to Preact. The monorepo uses yarn offline-mirror. The package that we are migrating uses Next.js.

### Reproduction
When we run the following command in terminal:

```bash
yarn workspace [package name] add next-plugin-preact preact preact-render-to-string react-ssr-prepass@npm:preact-ssr-prepass react@npm:@preact/compat react-dom@npm:@preact/compat
```

This is the output:
```bash
yarn workspace v1.22.4
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/@preact/compat/-/compat-0.0.3.tgz: Integrity check failed for "@preact/compat" (computed integrity doesn't match our records, got "sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg== sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=")
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /Users/lindsay.bloom/.yarn/lib/cli.js add next-plugin-preact preact preact-render-to-string react-ssr-prepass@npm:preact-ssr-prepass react@npm:@preact/compat react-dom@npm:@preact/compat
Directory: [deleted for privacy purposes]
Output:
```

If I try running the command a second time, there is no error.

### Expected Behavior

There should be no error when running the command the first time.

### Actual Behavior

The https://registry.yarnpkg.com/@preact/compat/-/compat-0.0.3.tgz tarball causes build issues as well. The tarball never gets properly added to the npm-packages-offline-cache directory, which then causes build errors in CI/CD when trying to install dependencies.

Here's a screenshot of the error:
![Screen Shot 2020-11-19 at 11 09 40 AM](https://user-images.githubusercontent.com/54584729/99698717-19eaa580-2a5f-11eb-8fec-ea24f3c3ff19.png)

Thanks so much in advance!

**Comment by rschristian** [comment]
If I'm understanding your setup correctly then this is correct behavior. 

The integrity check here is making sure that the package you're installing (`@preact/compat`) matches the checksum they have on record for React. This way you can be sure your installation source hasn't been compromised, and no one's giving you a bad version of React to install.

But here the goal is to purposefully install something else. You're installing `@preact/compat` as `react` and `react-dom`. The integrity checks aren't going to pass, and shouldn't either. You are in fact providing something else.

**Comment by marvinhagemeister** [comment]
To me it sounds like a feature that would be awesome to have in `yarn`. It knows about the aliasing so it is in the right position to apply the correct integrity hash.

**Comment by arcanis** [comment]
This bug isn't present in 2.x; integrity hashes are now kept for the full package locator.

**Comment by marvinhagemeister** [comment]
@arcanis Any plans to backport that to the 1.x release line? Homebrew on Mac still ships with 1.x by default.

**Comment by arcanis** [comment]
Unfortunately no, 1.x is pretty much frozen - its next update will probably just be to suggest to upgrade to v2.

I've however improved the [migration guide](https://yarnpkg.com/getting-started/migration#step-by-step) last week, and I think you'll find the upgrade fairly easy! If not, we're happy to collect feedbacks on Discord 🙂

**Comment by JoviDeCroock** [comment]
Closing as this was related to yarn and the way the next-plugin-preact advises installation😅
