### ISSUE TITLE
Preact loses state in toplevel components of Nextjs when switching routes

### ISSUE THREAD

**Issue by ljosberinn** [preactjs/preact#2838]
### Reproduction

React sandbox: https://codesandbox.io/s/brave-bhabha-j40tx?file=/pages/_app.js
Preact via next-plugin-preact: https://codesandbox.io/s/quizzical-mccarthy-0cikd?file=/package.json

### Steps to reproduce

React sandbox:
- wait until the fake promise resolved on index (1.5 seconds)
- click the link to About
- see no change in `ComponentWithState` occuring

Preact sandbox:
- wait until the fake promise resolved on index
- click the link to About
- watch the previously resolved state getting moved below link for whatever reason
- watch `ComponentWithState` getting remounted entirely, triggering `loading` again
...if you continue switching routes, this will just pile on. If you click the links often, the states will lag behind and add multiple instances.

### Expected Behavior

`ComponentWithState` does not lose its state when navigating.

### Actual Behavior

`ComponentWithState` is apparently remounted, resetting state entirely. Additionally, the component is _added_ to the DOM, moving the old one below the contents of _app.

In my more complex component I see `__source="[Object object]"` on almost all elements within `ComponentWithState`.

Edit: happens in prod too.

**Comment by srdjan** [comment]
I have the same issue. 
After tracking it down, this behaviour starts with [10.0.2-canary.10 ](https://github.com/vercel/next.js/releases/tag/v10.0.2-canary.10)

This release has only one change:

'Replace page loader with new route loader: #19006'

**Comment by montanodoto** [comment]
I have the same issue, any news ?

**Comment by ljosberinn** [comment]
Closing in favor of https://github.com/vercel/next.js/issues/19399 - thanks for the heads up!
