### ISSUE TITLE
[Preact compat] SVG prop dominant-baseline is not properly managed by preact/compat when written in camel case

### ISSUE THREAD

**Issue by nmondon** [preactjs/preact#2858]
Hi, 

First of all, thanks for the amazing work!

I'm using preact/compat a lot and I've noticed that [the tag attribute dominant-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline) is not properly managed by preat/compat when written in camel case. 

### Reproduction

Here is [a codesandbox](https://codesandbox.io/s/cocky-villani-41suh?file=/src/index.js)

### Expected Behavior

The attribute `dominantBaseline` should be transformed into `dominant-baseline`

### Actual Behavior

The attribute `dominantBaseline` is not transformed into `dominant-baseline`

I think it's just the [CAMEL_PROPS var in the preact/compat render](https://github.com/preactjs/preact/blob/master/compat/src/render.js) to change in order to manage this pretty uncommon attribute (I couldn't tell the difference with alignment-baseline...).

Let me know if you want me to submit a PR!

**Comment by developit** [comment]
Hi @nmondon - that sounds like the right approach!

I'm glad we're able to land changes like this in compat though. From a technical standpoint, we should really be writing that property in JSX as `dominant-baseline` - there's actually no property or attribute in SVG called `dominantBaseline`, it's a name that is specific to React :o

**Comment by nmondon** [comment]
OK, I'lm gonna make a PR!

Indeed, it feels Kafkaesque to manage these attributes conventions from React... I usually write them `dominant-baseline` but my VS Code editor or whatever extensions in it continues to suggest me the camel cased version in a JSX context...

**Comment by rschristian** [comment]
Closing, fix was released in v10.5.15
