### ISSUE TITLE
Preact/compat not resolvable for dependency

### ISSUE THREAD

**Issue by Ninerian** [preactjs/preact#2967]
### Reproduction

Hello, 

I currently try to setup a project, where I want to use an internal library, which is heavily relying on react. I setup the project both with rollup and snow pack and setup the aliases for react as it is documented. Unfortunately both bundlers cannot resolve the preact/compat module within the dependency. 

In Rollup I simply get the error message: 

`[!] Error: Could not load preact/compat (imported by ../../ui/dist/index.mjs): ENOENT: no such file or directory, open 'preact/compat'`

My rollup config:

```js
import alias from '@rollup/plugin-alias';
import resolve from "@rollup/plugin-node-resolve";
import serve from 'rollup-plugin-serve';
import typescript from "rollup-plugin-typescript2";


const packageJson = require("./package.json");

export default {
    input: "src/index.ts",
    output: [
        {
            file: packageJson.module,
            format: "es",
            sourcemap: true
        }
    ],
    plugins: [
        alias({
            entries: [
                { find: 'react', replacement: "preact/compat" },
                { find: 'react-dom', replacement: "preact/compat" }
            ]
        }),
        // peerDepsExternal(),
        resolve({
            extensions: ['.mjs', '.js', '.jsx', '.ts', '.tsx']
        }),
        typescript(),
        serve({
            contentBase: ['dist', 'resources'],
            open: true
        }),

    ]
};
```

For snowpack the error message: 
`[snowpack] ../../ui/dist/index.mjs
   Module "preact/compat" could not be resolved by Snowpack (Is it installed?).
`

My snowpack config:

```js
/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  mount: {
    public: {url: '/', static: true},
    src: {url: '/dist'},
  },
  plugins: [
    '@snowpack/plugin-dotenv',
    '@snowpack/plugin-typescript',
    '@prefresh/snowpack',
  ],
  routes: [
    /* Enable an SPA Fallback in development: */
    // {"match": "routes", "src": ".*", "dest": "/index.html"},
  ],
  optimize: {
    /* Example: Bundle your final build: */
    // "bundle": true,
  },
  packageOptions: {
    /* ... */
  },
  devOptions: {
    /* ... */
  },
  buildOptions: {
    /* ... */
  },
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat"
  }
};
```

The library is compiled as ESM build with rollup. 

Some issues I found where rather old and the solution didn't work. Do you have any recommendations how to handle this?

### Expected Behavior

Preact/compat is resolved for dependencies

### Actual Behavior

Error while resolving Preact/compat

**Comment by Ninerian** [comment]
I found the issue. I used the lib via npm link, which seems to have issues with the resolving. After manual copying it into the node_modules folder, everything worked.

**Comment by marvinhagemeister** [comment]
Yeah, bundlers usually don't play well with `npm link` in my experience :S
