### ISSUE TITLE
Unable to load/import 'preact/jsx-dev-runtime'

### ISSUE THREAD

**Issue by esanzgar** [preactjs/preact#2974]
The `package.json` for preact version 10.5.12 lists `preact/jsx-dev-runtime` as submodule:

```
"./jsx-dev-runtime": {
	"browser": "./jsx-runtime/dist/jsxRuntime.module.js",
	"umd": "./jsx-runtime/dist/jsxRuntime.umd.js",
	"require": "./jsx-runtime/dist/jsxRuntime.js",
	"import": "./jsx-runtime/dist/jsxRuntime.mjs"
},
```
However, I am unable to load/import it.

Babel `preset-react` has a [couple of option](https://babeljs.io/docs/en/babel-preset-react#importsource) to use `runtime: "automatic"` and `importSource: "preact"`. When these options are enable, babel loads `jsx-runtime` on production or `jsx-dev-runtime` on development environment.

This is my .babelrc:

```
{
  "presets": [
    [
      "@babel/preset-react",
      {
        "runtime": "automatic",
        "importSource": "preact"
      }
    ],
  "env": {
    "development": {
      "presets": [
        [
          "@babel/preset-react",
          {
            "development": true,
            "runtime": "automatic",
            "importSource": "preact"
          }
        ]
      ]
    }
  }
}
```

### Steps to reproduce

1. `import { jsx } from "preact/jsx-dev-runtime";`

See also the error here: https://codesandbox.io/s/affectionate-paper-bo98u?file=/index.js

### Expected behavior

I should be able be able to import the `preact/jsx-dev-runtime`

### Actual behavior

`preact/jsx-dev-runtime` can not be imported.

Babel reports:
`Error: Can't walk dependency graph: Cannot find module 'preact/jsx-dev-runtime'`

**Comment by marvinhagemeister** [comment]
This doesn't sound like an error coming from babel, but rather the bundler that's used here. Babel has no knowledge about the dependency graph and works on each file in isolation. Which bundler are you using in your project (webpack, rollup or something else)?

**Comment by esanzgar** [comment]
We use Browserify in our project.

Babel transpiles the code in this way:

```
var _jsxDevRuntime = require("preact/jsx-dev-runtime");
```

If I changes the Babel's importSource to 'preact/compat', I found that Browserify successfully finds and loads `jsx-dev-runtime`:

```
var _jsxDevRuntime = require("preact/compat/jsx-dev-runtime");
```

**Comment by marvinhagemeister** [comment]
> We use Browserify in our project.

This sounds a lot like  a bug in browserify's resolution logic. From what you're describing it seems like they don't support [package entry points](https://nodejs.org/api/packages.html#packages_package_entry_points) (often referred to as package exports). Instead they seem to traverse the filesystem and look for `./node_modules/preact/jsx-dev-runtime.js`. This is definitely an upstream bug in browserify 👍 

Happy to hear that you found a workaround via `preact/compat`. It might be worth notifying the browserify devs of this issue so that they have a chance at fixing at for the next release.

**Comment by esanzgar** [comment]
I filed an issue with Browserify: https://github.com/browserify/browserify/issues/1995

**Comment by devongovett** [comment]
Perhaps Preact should add add a directory like the one that exists for the `jsx-runtime`? https://unpkg.com/browse/preact@10.6.5/jsx-runtime/ This would be broken in any tool that doesn't support package.json#targets. This affects usage in Parcel, as well as Browserify and any other tool that uses the `resolve` module. Not sure support for it is widespread enough to rely on yet.

**Comment by marvinhagemeister** [comment]
@devongovett is adding support for the `exports` field in `package.json` on parcel's roadmap? With libraries switching over to ESM there might be more issues like this in the future. Supporting the `exports` field would solve all those problems at once for parcel.
