### ISSUE TITLE
Issue in integrating (Preact X + styled-components) project/widget inside (React)

### ISSUE THREAD

**Issue by AhmeeedMostafa** [preactjs/preact#2997]
Hey, I have found some while integrating a project (used preact & styled-components together) inside another react project.

### Reproduction

Check this [repo](https://github.com/AhmeeedMostafa/react-preact-recursion-test)

### Steps to reproduce

1. start some preact project & add styled-components
2. create some styled component by styled-components
3. Integrate that preact project inside react project 

or check the above repository's README.

### Expected Behavior

No errors are shown and components render normally

### Actual Behavior

The following error is shown:

![image](https://user-images.githubusercontent.com/22754338/107384837-03eaff00-6afb-11eb-95d2-99aceafe4057.png)

### Versions
- preact v10.5.12

- styled-components v5.2.1

- react v17.0.1

- react-dom v17.0.1

My use case is creating some widget using preact + styled-components and to be utilized through other JS libraries ex. (React).

Am I missing smth. in the configurations or this is a known/new issue?

``note: I have included the aliases of `react, react-dom/test-utils & react-dom `through the microbundle alias``

**Comment by rschristian** [comment]
I believe that, because of the way `styled-components` works, you need to bundle it with your widget, else you'll run into issues.

That being said, I didn't get the error you posted when running your demo example repo. You might have another issue there.

**Comment by AhmeeedMostafa** [comment]
> I believe that, because of the way `styled-components` works, you need to bundle it with your widget, else you'll run into issues.
> 
> That being said, I didn't get the error you posted when running your demo example repo. You might have another issue there.

Nice, works after bundling styled-components in the dist yes,
but what if I need to use not bundled but transpiled version through babel (aka lib. not dist. build)?

**Comment by rschristian** [comment]
Why would you need to do that?

**Comment by AhmeeedMostafa** [comment]
@rschristian for giving the chance for the user to use the relative es modules for the components from NPM and also use his installed dependencies not to have the same dependency with multiple versions/times for avoiding the unneeded size increasing (which would be bundled in dist. Version and might the user has it already in his project)

**Comment by rschristian** [comment]
From what I understand, `styled-components` injects itself into React in order to do what it does. That won't work with what you're trying to do here, mixing React and Preact, as far as I know. 

I totally get the reasoning, that a peer-dep would be nicer, but I don't think you can get away with that using `styled-components`.

**Comment by AhmeeedMostafa** [comment]
So the only solutions for now either to bundle it with the dist. Or to styled-components starts to support preact also in the same way it supports react, right?

**Comment by rschristian** [comment]
As far as I know the solution is to bundle it, yes, 

The issue as I understand it isn't with `styled-components`, it's that the way that `styled-components` runs means it won't really work with this setup. It doesn't expect you to be using multiple different UI solutions. Generally, if you want that. you bundle everything into the widget so it can be run anywhere.

**Comment by AhmeeedMostafa** [comment]
Hmmm...thanks your answer was helpful!
And let's hope if someone else have a better suggestion
