### ISSUE TITLE
Error with new JSX runtime in NextJS: `Can't resolve 'preact/jsx-dev-runtime'`

### ISSUE THREAD

**Issue by madeleineostoja** [preactjs/preact#3029]
### Reproduction

Using NextJS 10 with:
- next-plugin-preact@3.0.3
- preact@10.5.12
- preact-render-to-string@5.1.12
- @preact/compat@0.0.4

And the following Babel config:

```json
{
  "presets": [
    [
      "next/babel",
      {
        "preset-react": {
          "runtime": "automatic",
          "importSource": "preact"
        }
      }
    ]
  ]
}
```

I get the following error: 

```
Module not found: Can't resolve 'preact/jsx-dev-runtime'
```

### Steps to reproduce

- Install latest NextJS with plugin-preact
- Setup new JSX runtime according to Preact/Next docs
- See error

### Expected Behavior

- Should support new JSX runtime via babel config

### Actual Behavior

- Gives error and does not compile new JSX runtime

**Comment by marvinhagemeister** [comment]
Thanks for reporting this issue. The steps to reproduce listed here are not as detailed as they should be. Can you share an example repository where the issue is reproducible?

**Comment by madeleineostoja** [comment]
I can't share the codebase I'm working on since it's for a private company, but I'll see if I can whip up a demo repo when I get a moment.

**Comment by marvinhagemeister** [comment]
Yeah, no need to share that repo. The listed repro steps make it sound like it's reproducible in a fresh nextjs project.

**Comment by JoviDeCroock** [comment]
@madeleineostoja have you tried changing the `importSource` to `preact/compat` or `react` instead?

**Comment by madeleineostoja** [comment]
@JoviDeCroock setting `importSource` to `preact/compat` fixes it, thanks! Might be worth noting the gotcha with Next somewhere in the docs? Just because it's such a popular framework.

**Comment by JoviDeCroock** [comment]
Good point @madeleineostoja I'll make a PR to `next-plugin-preact` as that seems to be an ideal location, thanks for pointing this out to us 🙌
