### ISSUE TITLE
Preact version 10.5.11 (& 10.5.12) breaks a specific rendering scenario

### ISSUE THREAD

**Issue by ludvigeriksson** [preactjs/preact#3045]
As of Preact v 10.5.11 I noticed a scenario in my app in which rendering of an overlay in OpenLayers breaks. 

### Reproduction

I've distilled it down to a minimal example here: https://codesandbox.io/s/gifted-shaw-xvoyg. The background map is only there for demonstration purposes & is not needed for the bug. The file responsible for the overlay rendering is `oloverlay.js`.

### Steps to reproduce

1. Open the sandbox
2. Click somewhere on the map
3. See a red rectangle appear where you clicked (expected behaviour)
4. Change the preact version in the sidebar from 10.5.10 to 10.5.11 or 10.5.12.
5. See the red rectangle is now pinned above the map, & nothing happens when you click the map.

### Expected Behavior

A red rectangle should appear where you clicked on the map.

### Actual Behavior

The red rectangle is pinned above the map.

**Comment by Aswathprabhu** [comment]
I'm too facing a similar issue recently (version **10.5.11** onwards) and I've managed to repro this in an example.
In my example, I'm rendering a custom element which is a modal dialog. Everything works fine in the initial render until I mutate any state in a context wrapping the app. I mutate the state in the modal and the **deep child elements** get **pulled out to the top level** within the modal.

**DOM during Initial Render:**

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/25875367/109934031-0dc6e300-7cf2-11eb-9684-c374ad9a4a30.png">

**DOM on Re-render:**

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/25875367/109934140-2fc06580-7cf2-11eb-9813-8fae0f824067.png">

[Example using Preact 10.5.10](https://torpid-sedate-bakery.glitch.me/) - _Works fine_
[Source Code](https://glitch.com/edit/#!/accessible-silken-jade)

[Example using Preact 10.5.11](https://accessible-silken-jade.glitch.me/) - _Facing issue_
[Source Code](https://glitch.com/edit/#!/accessible-silken-jade)

**Comment by MaximePlancke** [comment]
We are also facing the same problem. Moving back to 10.5.10 solved it. We haven't tested on 10.5.13 yet

**Comment by ludvigeriksson** [comment]
Tested & broken on 10.5.13 as well

**Comment by Aswathprabhu** [comment]
@marvinhagemeister just pinging to check if this any known issue! I can contribute if this is something quite easy to fix 😃

**Comment by developit** [comment]
Not sure it's a quick fix @Aswathprabhu, but it is indeed still an issue. I'll try to look into it asap.
