### ISSUE TITLE
Preact throws with @material-ui/data-grid

### ISSUE THREAD

**Issue by jschill** [preactjs/preact#3055]
### Reproduction
https://codesandbox.io/s/busy-bash-qxfs0

### Steps to reproduce
JS error on page load

### Expected Behavior
The above code is copy/paste from their example:
https://material-ui.com/components/data-grid#mit-version

### Actual Behavior
`TypeError: i.current.getLocaleText is not a function`

That error is referencing to this LOC:
https://github.com/mui-org/material-ui-x/blob/c179435dbd6a2cf365347b8e555de3271187e2f5/packages/grid/_modules_/grid/components/containers/GridRoot.tsx#L31

**Comment by mapringg** [comment]
Having the same problem. What can I do besides forking and adjusting @material-ui/data-grid?

**Comment by oliviertassinari** [comment]
While we support Preact for [MUI Core](https://github.com/mui-org/material-ui), the support of Preact might be challenging for [MUI X](https://github.com/mui-org/material-ui-x). We might look into it in the future, bundle size matters, and it could even be important for us if we need to expose an Angular or Vue wrapper with Preact.

**Comment by rschristian** [comment]
Going to close this out in favor of #4344, which tracks an issue with a more modern version of the library.
