### ISSUE TITLE
 No known conditions for "./compat/server" entry in "preact" package

### ISSUE THREAD

**Issue by chmelevskij** [preactjs/preact#3057]
I'm using `vitejs` with custom server in quite large monorepo with typescript, but for single application and keep getting this error:
```
Error: No known conditions for "./compat/server" entry in "preact" package
```

every time I switch my branches.

Aliasing is done in similar fashion as in rollup
```
  resolve: {
    alias: [
      { find: 'react', replacement: 'preact/compat' },
      { find: 'react-dom', replacement: 'preact/compat' },
    ],
  },
```

And it used to work, but now, I need to tinker around with modules in some quite unpredictable fashion to get it to work 😢 

It does work with react.

### Reproduction

```
  "preact": "10.4.8",
  "preact-render-to-string": "^5.1.10",
  "vite": "^2.0.5"
```

### Steps to reproduce

Didn't manage to reproduce in small scale. Will try to look more into this.

### Expected Behavior

SSR should load aliased preact.

### Actual Behavior

Breaks

**Comment by marvinhagemeister** [comment]
This issue was resolved with PR #2873 and released as part of Preact version `10.5.8`. The current version is `10.5.12`. To resolve this issue, update to the current version of Preact.

**Comment by chmelevskij** [comment]
Interesting, I think that pr brakes the vitejs though 😢 I keep getting `require` is not defined there

**Comment by marvinhagemeister** [comment]
Reopening: Sounds like we need to add an esm version.
