### ISSUE TITLE
Suspense component.__hooks might be null

### ISSUE THREAD

**Issue by johakr** [preactjs/preact#3066]
- [x] Check if updating to the latest Preact version resolve the issue

**Describe the bug**
There seems to be a regression with lazy Suspense and hooks, triggering this error message `Cannot set property __h of null`, resulting in the component infinitely rendering the fallback markup. 

Everything seems to work fine until preact 10.5.4. First broken version seems to be preact 10.5.5.

Changing this condition

https://github.com/preactjs/preact/blob/e523a82cda1d982b6fa82d23cc7539f5f5b4701d/hooks/src/index.js#L295

to `if (component._parentDom && component.__hooks)` seems to fix the issue. But I don't have enough understanding of the preact core to tell if that is the right approach & place to fix it.

**To Reproduce**

https://github.com/preactjs/preact/issues/2488

**Expected behavior**
Suspense switches out of fallback.

**Comment by joehua87** [comment]
I've used the `lazy` function mentioned here https://github.com/preactjs/preact/issues/2915#issuecomment-761283581 & it works

**Comment by davidrhoderick** [comment]
As of `10.5.14`, I get a `t.__H is null` error.  When I downgrade to `10.5.4` it goes away.

**Comment by developit** [comment]
@davidrhoderick does the error happen when you modify hook state after a component is suspended? Or is something else triggering rendering?

A few of the comments in the linked issue mention this only happens with Suspense from `preact/compat`, and not with ErrorBoundary/lazy from `preact-iso`, which makes me think it's the hook state preservation code in compat that is causing the issue.

**Comment by davidrhoderick** [comment]
It's a rather complex application so I am not able to quickly test that but I can definitely tell you that hook state is being modified in suspended components.  Also suspended components load other suspended components.

**Comment by ruben-tkww** [comment]
Same issue here `Cannot set property __h of null` and also working fine with `10.5.4`

**Comment by JoviDeCroock** [comment]
This has been fixed with 10.18.1 https://github.com/preactjs/preact/commit/1658d434669a4e81b5d8fb3eb06115ab81d802f2
