### ISSUE TITLE
colSpan="100%" becomes colspan="0"

### ISSUE THREAD

**Issue by eliseumds** [preactjs/preact#3069]
**Describe the bug**

When using `<td colSpan="100%">`, the output is `<td colspan="0">`.

![image](https://user-images.githubusercontent.com/640840/111183096-901a9700-857d-11eb-8020-0f8d1197b631.png)

**To Reproduce**

https://codesandbox.io/s/busy-waterfall-it1tt

**Expected behavior**

It shouldn't change the attribute value, it should output `<td colspan="100%">`.

**The culprit**

```js
let td = document.createElement('td');

td['colSpan'] = '100%';

td.getAttribute('colSpan'); // "0"
```

https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/src/diff/props.js#L121

Yeah, it doesn't necessarily seem to be a problem with Preact. I wonder if the project wants to deal with cases like this one.

**Comment by marvinhagemeister** [comment]
Using a string for `colspan` is invalid HTML. [The spec](https://html.spec.whatwg.org/multipage/tables.html#attr-tdth-colspan) has this to say:

> The `td` and `th` elements may have a `colspan` content attribute specified, whose value must be a valid non-negative integer greater than zero and less than or equal to 1000.

So only positive integers are allowed.

**Comment by eliseumds** [comment]
@marvinhagemeister so React is doing magic under the hood. Thanks for the info.
