### ISSUE TITLE
Prerendering/snapshotting white screen flash with async components

### ISSUE THREAD

**Issue by iMakedonsky** [preactjs/preact#3071]
**Describe the bug**
Preact causes white screen flash during rehydration of async components
See: https://github.com/theKashey/react-prerendered-component/issues/8
https://github.com/stereobooster/react-snap#%EF%B8%8F-caveats

**To Reproduce**

1. Have preact 10.5.13 configured via `preact/compat`
2. Have a page with nested lazy components(e.g. React-router switch with all root components being lazy-loaded 
3. Do the trick desribed in react-snap docs
3. run build + react-snap
4. See flash of white screen after Root <App /> component started rendering, but children lazy chunks aren't loaded yet.

**Expected behavior**
Same as React, that is – no white flash with these packages.

**Comment by marvinhagemeister** [comment]
Check out [`preact-iso`](https://www.npmjs.com/package/preact-iso) for the current recommended way to do partial hydration in Preact. It keeps the current page alive until the new one is ready.

The Preact section in the README of `react-snap` is aimed at Preact <=8.x. The third argument to `render()` should not be used anymore. We've sort of deprecated that with the introduction of Preact 10 and we'll remove it in 11.

So the snippet should actually be the same as the React example, with the sole difference being the import source:

```js
import { hydrate, render } from "preact";

const rootElement = document.getElementById("root");
if (rootElement.hasChildNodes()) {
  render(<App />, rootElement);
} else {
  render(<App />, rootElement);
}
```

**Comment by iMakedonsky** [comment]
Thanks for pointing to preact-iso, @marvinhagemeister. After proxying `react.lazy` to `preact-iso.lazy` in combination with `preact/compat` and `react-router`, it works like a charm even faster and smoother than before, both with and without pre-rendering with react-snap!

🎉
