### ISSUE TITLE
当我使用preact和 //translate.google.com/translate_a/element.js 时，会渲染不正确

### ISSUE THREAD

**Issue by lvzegeng** [preactjs/preact#3078]
渲染的错误Dom元素，包含了翻译之前的文字：
![image](https://user-images.githubusercontent.com/26923315/112134044-44b05a80-8c07-11eb-884f-ae5d8e7c71eb.png)

渲染的正确Dom元素：
![image](https://user-images.githubusercontent.com/26923315/112134329-98bb3f00-8c07-11eb-945a-fe8744ab4fe6.png)

**Comment by developit** [comment]
Please use this patch:
https://gist.github.com/developit/3e807962630ddbd4977cbd07b597f24f

I've spoken to the Translate team about this and suggested fixes, but it will take a long time.

**Comment by lvzegeng** [comment]
How should I use this patch
There is a problem with the options variable

**Comment by developit** [comment]
@lvzegeng - sorry, I forgot to include the import. I have updated the Gist, it should work now.

Just import this before any rendering happens:

```js
import { render } from 'preact';
import './preact-google-translate-patch';

render(...);
```

**Comment by oscar-reyes-beachbody** [comment]
Hello @developit I'm having the same problem and I have tried to use the patch but by the nature of the project I'm working on everything gets rendered using portals (it's a nav). Do you know how could I apply the patch to work for this scenario? Thanks!

This how I tried to use it.

```
/** @jsx h */
import { FunctionalComponent, VNode } from 'preact';
import { createPortal } from 'preact/compat';
import '../../utils/translationFix';
```

**Comment by JoviDeCroock** [comment]
Let's track this in https://github.com/preactjs/preact/issues/948
