### ISSUE TITLE
Cannot bind onended or autoplay to VideoElement (tsx)

### ISSUE THREAD

**Issue by K0IN** [preactjs/preact#3098]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I cannot bind the video / HTMLMediaElement properties to a video element when I use typescript(build).

**To Reproduce**

```
<video
     style="min-width: 100%; width: 100%; max-height: 66vh;"
     src={state.currentStream}
     controls={true}         
     autoplay={true}
     onended={() => true}>
</video>
```

Error message:

```
TS2322: Type '{ children: never[]; style: string; src: string; controls: true; onended: () => Promise<void>; }' is not assignable to type 'HTMLAttributes<HTMLVideoElement>'.    
  Property 'onended' does not exist on type 'HTMLAttributes<HTMLVideoElement>'.
```

**Expected behavior**
Should be possible to bind.

**Comment by JoviDeCroock** [comment]
In JSX we have to use the camelCase syntax https://github.com/preactjs/preact/blob/master/src/jsx.d.ts#L486

**Comment by JoviDeCroock** [comment]
Closing due to it looking like it's resolved

**Comment by developit** [comment]
(fwiw the lowercase name is supported, it's just not in the type defs).
