### ISSUE TITLE
setState callback not called

### ISSUE THREAD

**Issue by CaptainChaos** [preactjs/preact#3104]
- [ ] Check if updating to the latest Preact version resolves the issue
No, I'm using the latest version (10.5.13)

**Describe the bug**
The callback parameter of setState is never called

**To Reproduce**
```
await new Promise<void>((res, rej) => {
    console.log("Promise 1"); // happens
    this.setState({
        status: "loading"
    }, () => {
        console.log("Callback!"); // never happens
        res();
    });
});
```

**Expected behavior**
The callback should be called

**Comment by marvinhagemeister** [comment]
Would you mind sharing the surrounding component, in particular where you call `this.setState()`?  Without that it's kinda hard to guess what your scenario looks like from the snippet provided.

**Comment by CaptainChaos** [comment]
Hmm, thank you very much for the sandbox setup. I'll take a deeper look, will update here.

```
import { Component } from "preact";

class x extends Component<..., ...> {
    private loadData = async () => {
        await new Promise<void>(...);
    }
}
```

No preact-compat installed, project is typescript + webpack. Everything else works fine, e.g. other libraries, all other preact functions, other Promises etc.

**Comment by marvinhagemeister** [comment]
Where are you calling `loadData()`? Showing the full component might help.

**Comment by CaptainChaos** [comment]
I managed to reproduce the error in [codesandbox](https://codesandbox.io/s/agitated-greider-zbtip?file=/src/index.js). Did I misunderstand the concept somehow? Or is this indeed a bug?

```
class App extends Component {
  constructor() {
    super();
    this.state = {
      value: 0
    };
    this.loadData();
  }

  loadData = async () => {
    console.log("loadData");
    this.setState(
      {
        value: 10
      },
      () => {
        console.log("loadData callback");
      }
    );
  };

  onClick = () => {
    console.log("onClick");
    this.setState(
      {
        value: this.state.value + 1
      },
      () => {
        console.log("setState callback");
      }
    );
  };

  render() {
    return (
      <div>
        <p>value {this.state.value}</p>
        <button onClick={this.onClick}>click me</button>
      </div>
    );
  }
}
```

**Comment by JoviDeCroock** [comment]
@CaptainChaos async stuff in `constructor` is quite subject to this, it's better to use a lifecycle for this purpose like: `componentDidMount()` https://codesandbox.io/s/cranky-khorana-1vnxg

**Comment by CaptainChaos** [comment]
Aha! Thank you very much for this perfect explanation! I'll close this, but first, is this somewhere mentioned in the docs?
