### ISSUE TITLE
componentDidCatch should pass the errorInfo parameter.

### ISSUE THREAD

**Issue by MasterEric** [preactjs/preact#3118]
**Describe the feature you'd love to see**
Preact's version of componentDidCatch is not compatible with React's variant. The React variant includes a parameter called `errorInfo`; in the latest version of React, this is an object that contains only one string, which contains the component stack trace for the error that was caught.

This is important and useful as it allows improved error reporting for the application, but Preact does not include this functionality by default.

**Additional context (optional)**
See the documentation for Preact: https://preactjs.com/guide/v10/whats-new/#componentdidcatch

Compare with the corresponding documentation for React: https://reactjs.org/docs/error-boundaries.html

**Comment by el-gringo** [comment]
This is required for Sentry JS

https://github.com/getsentry/sentry-javascript/blob/cabb53c67ab202bb12c517f8a4aa65641cac606e/packages/react/src/errorboundary.tsx#L67

**Comment by adit-hotstar** [comment]
When will this fix be released?
