### ISSUE TITLE
Troubleshooting element scroll size change after `useLayoutEffect` fires

### ISSUE THREAD

**Issue by natevw** [preactjs/preact#3119]
- [ ] Check if updating to the latest Preact version resolves the issue

(Full disclosure: this project is still on `^10.4.5` for now **but** the problem persists when testing against `^10.5.13` manually too, so I don't think it's been fixed.) 

**Describe the bug**

I have an accordion component which uses CSS for an animation and but includes some JS support code to configure an exact height for the styles:

```
  useLayoutEffect(() => {
    // this sets a CSS variable to actual content size for nicer effect…
    // see https://stackoverflow.com/a/38210749/179583
    var el = baseRef.current.querySelector('.group-content');
    el.style.setProperty('--expected-height', `${el.scrollHeight}px`);
  }, []);
```

This seemed to work but in practice it turns out it ends up setting too small of a height maybe 15% of the time. Currently this breaks the UI and I'll likely apply some sort of "fixup" workaround but it'd be nice to get to the bottom of this.

**To Reproduce**

This is still something of a TODO, to figure out a repro in isolated circumstances. As I mentioned, it does not even happen reliably in the app itself. It also may [or may not] be somewhat dependent on some of the styling in this situation. My WIP sample is https://codesandbox.io/s/sleepy-oskar-ddgxg which is supposed to alert if the situation happens but that whole IDE is a bit complicated and I'm not sure when/how to re-trigger it running the code to begin with [or if it even allows an alert, etc. etc.]

In my own app I've added the following logic so far:

```
useLayoutEffect(() => {
    // this sets a CSS variable to actual content size for nicer effect…
    // see https://stackoverflow.com/a/38210749/179583
    var el = baseRef.current.querySelector('.group-content');
    el.style.setProperty('--expected-height', `${el.scrollHeight}px`);

var orig = el.scrollHeight,
    origHTML = el.innerHTML;
console.log("layout:", el.scrollHeight, cls);
setTimeout(() => {
  if (el.scrollHeight > orig) {
    console.log("10 msec:", el.scrollHeight, cls);
    console.log(origHTML === el.innerHTML, '\n', origHTML, '\n', el.innerHTML);
    orig = el.scrollHeight;
  }
}, 10);
setTimeout(() => {
  if (el.scrollHeight > orig) {
    console.log("1 sec:", el.scrollHeight, cls);
    console.log(origHTML === el.innerHTML, '\n', origHTML, '\n', el.innerHTML);
  }
}, 1e3);
  }, []);
```

i.e. I double-check the height after both 10 milliseconds and 1000 milliseconds, and spew some additional data if the height has unexpectedly changed. The results from that so far indicate that:

* the content does have something of a "filled in" height initially (e.g. `188`, not just `0` or `20`/`50` of only some padding)
* if the height changes, it does so within 10msecs (e.g. from `188` to `493` or from `243` to `580` pixels high)
* the `innerHTML` does **not** change

**Overall issue**

Unfortunately I can't conclusively point to a bug in Preact yet. There *may* be some subtle CSS edge case that makes my content actually shorter for a brief moment. But in researching this I see that e.g. https://github.com/preactjs/preact/issues/1893 was closed but there's still some "known issues" related to 2-phase rendering. Is this the sort of thing that could be expected until the Preact rendering architecture is fully worked out?

**Comment by JoviDeCroock** [comment]
I've tried reproducing this but it looks to be fixed, going to close this out but feel free to reopen when there's a reliable way to test this.
