### ISSUE TITLE
Unexpected behavior with replaceNode parameter

### ISSUE THREAD

**Issue by mjomble** [preactjs/preact#3126]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
My apologies if this is a duplicate bug report. I did see some similar issues, but I'm not familiar enough with the internals to figure out reasonably quickly if it's the same issue or a different one 🙂

Basically, while the replaceNode parameter usually works fine, I stumbled upon a case where it behaves very strangely.

**To Reproduce**

https://codesandbox.io/s/preact-replacenode-bug-msuv6

1. Click on the 'Toggle' button a few times

**Expected behavior**
The element containing the text "First line" should toggle between visible and hidden states.
No other changes should happen, more specifically:
* "Second line" should never disappear.
* There should never be multiple copies of "First line" visible.

**Actual behavior**
The initial render renders "Second line" without "First line" as expected.
On the first click, "First line" appears as expected, but "Second line" disappears.
On the second click, "First line" disappears as well, as expected.
On the third click, "First line" appears twice, with still no sign of "Second line".
Further clicks toggle between neither line visible and "First line" rendered twice.

Removing the replaceNode parameter fixes the toggling, but messes up the order of elements inside the parent.

**Comment by marvinhagemeister** [comment]
Marking as `wont fix` because we've already removed the third `replaceNode` parameter in the current branch for `v11` as it always has been against the overall design architecture of the rest of the framework. That's why we don't advertise it in the v10 docs at all too. Preact expects a single DOM node to render into that it has full control over.
