### ISSUE TITLE
PropTypes not working with preact/compat

### ISSUE THREAD

**Issue by bbgvalayev** [preactjs/preact#3133]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When using `prop-types` with `preact/compat` there is no validation happening.

**To Reproduce**

Install `preact ` 10.5.7 and `prop-types` version 15.7.2. Add prop type definitions to component. Pass wrong prop. Check console in dev tools. Also, tried enabling `preact/debug` but also no luck.

**Expected behavior**
What should have happened when following the steps above?

Should see prop type validation warnings.

**Comment by marvinhagemeister** [comment]
One key difference between React and Preact is that we don't rely on bundler magic to display errors or warnings during development. Instead we architected Preact to be pluggable from the get go. The addon you're looking for is `preact/debug`. This enables helpful warnings for potential errors like prop type validation during development.

To add that addon insert the import statement the top of your entry file:

```js
import "preact/debug";
import App from "./my-cool-app";

render(<App />, document.getElementById("app"));
```

**Comment by marvinhagemeister** [comment]
nvm reopening because the OP mentioned that he tried `preact/debug`

**Comment by marvinhagemeister** [comment]
@bbgvalayev PropType errors are printed to the console as expected for me. See this code sandbox: https://codesandbox.io/s/preact-prop-types-4dexz?file=/src/index.js

To be able to help we need to know more about your setup and a reproduction case.
