### ISSUE TITLE
component._suspended is not a function, is true

### ISSUE THREAD

**Issue by JonasKruckenberg** [preactjs/preact#3150]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

When triggering hmr with prefresh while using suspense & lazy the following error gets thrown:
(Note that you have to trigger the HMR from a different file that you main entry file)
```
suspense.js:235 Uncaught (in promise) TypeError: t.__e is not a function
    at U (suspense.js:235)
    at L.__c (suspense.js:124)
    at Object.n.__e (suspense.js:18)
    at I (index.js:255)
    at m (children.js:137)
    at I (index.js:198)
    at m (children.js:137)
    at I (index.js:198)
    at m (children.js:137)
    at I (index.js:198)
```
From what I can gather on [suspense.js#L18](https://github.com/preactjs/preact/blob/master/compat/src/suspense.js#L18) we check if the vnode is suspended, but and the check on [suspense.jsL235#](https://github.com/preactjs/preact/blob/master/compat/src/suspense.js#L235) expects the parents _suspended property to be a function or false, but somewhere this _suspended property got rewritten to true. (How is this even possible?)

**To Reproduce**

The repro is more complicated since it involves prefresh but I'll try to create a minimal example tomorrow!

1. Create an async function that returns an element
2. Add a suspense + lazy that uses the async function
3. Import the suspense + lazy component in a separate file and render the app from that file
4. Cause a hmr refresh from the first file and see the error

**Expected behavior**
What should have happened when following the steps above?
No error

**Comment by developit** [comment]
This feels like it might be a property mangling collision, similar to #3165. 

The properties that could be colliding (if they end up also being set on Component instance):

- `_force` (hmm - this actually does get set on Components...)
- `_dom` (shouldn't collide, only used on `VNode`)
- `_catchError` (shouldn't collide, only used on `options`)

This leads me to believe the `true` value is being set [in forceUpdate()](https://github.com/preactjs/preact/blob/014750e10d14dced960640c464a1768d48f6e196/src/component.js#L66), overwriting the _suspended property that appears to have been minified to the same name.

**Comment by milochristiansen** [comment]
I am getting this exact error, but I'm not doing anything weird as far as I know.

I trimmed my project down to a very minimal reproduction, presented here as a zip with 4 files. Three page components and one index.html that uses PReact Router. All libraries are loaded with unpkg via an import map. The server I'm using to test this is a simple static webserver that is coded to redirect all requests that do not match a file to index.html. No HMR was used.

There are three pages: Main, A, and B. Main is loaded with a simple import. A and B are loaded with Suspense and lazy. You can always navigate to Main. Attempting to navigate to A or B will always fail with the exact same error message as in the OPs post. If you refresh the page it works, but then navigating to the other page fails. Navigating to Main from one of the failing routes and then back works.

[repro.zip](https://github.com/preactjs/preact/files/6765647/repro.zip)
