### ISSUE TITLE
Preact compat: class is forwarded without className

### ISSUE THREAD

**Issue by dios-david** [preactjs/preact#3159]
Hey guys 👋 

I know you already put lot of effort into fixing class/className issues in Preact compat, but I just found another weird thing which doesn't happen when rendering with React.

I prepared a unit test to [demonstrate the issue here](https://github.com/preactjs/preact/commit/57779bb68354fa1083f2b674fcf44b7bb1c7e87d):
```jsx
const Foo = ({ className, ...props }) => {
	return (
		<section className={className}>
			<div {...props} />
		</section>
	);
};

render(<Foo className="bar" />, scratch);
expect(scratch.firstChild.className).to.equal('bar'); // the <section> element
expect(scratch.firstChild.firstChild.className).to.equal(''); // the <div> element
```

This test fails with:

```
FAILED TESTS:
  compat render
    className normalization
      ✖ shout not forward class when className is not forwarded
        Chrome Headless 90.0.4430.212 (Mac OS 10.15.7)
      AssertionError: expected 'bar' to equal ''

      + expected - actual

      -bar
      
    at Context.<anonymous> (compat/test/browser/render.test.js:24144:60)
```

I think this happens because after doing `{ className, ...props }`, `props` becomes something like: `{ class: 'bar' }` which then gets passed to `<div>`.
Then when normalising the props [here](https://github.com/preactjs/preact/blob/master/compat/src/render.js#L189) the `classNameDescriptor` is added to the normalised props because `class != className`, making `{ class: 'bar' }` to be used when rendering that inner `<div>` element.

If I do `<div className="" {...props} />` instead of `<div {...props} />` then it works fine, as `className` takes precedence.
Alternatively, I could do `{ className, class, ...props }` when destructuring the props, but this is a bit hacky.

Do you think there is any better way of dealing with this? Is this something that compat should handle better to match how React behaves?

**Comment by developit** [comment]
Thanks for the detailed repro! I think in order to fix this we will need to make `class` a non-enumerable descriptor when props.className is provided.

**Comment by saadtazi** [comment]
Note: I got the issue while using `createPortal` (which is imoprted from `preact/compat`): here is a [codeSandbox](https://codesandbox.io/s/bug-preact-class-96iyv) to repro: `props` received by the component contains `className` and `class` when `preact/compat` is imported (it doesn't happen if it is not imported). I hope it helps.
