### ISSUE TITLE
options.requestAnimationFrame signature is incorrect

### ISSUE THREAD

**Issue by arocheleau** [preactjs/preact#3160]
I am using **preact** in a _TypeScript_ project.

According to the [guide](https://preactjs.com/guide/v10/options/), the **options.requestAnimationFrame** signature is `(callback: () => void) => void`.  However, in the _index.d.ts_ file, **options.requestAnimationFrame** is declared as

```
interface Options {
  ...
  requestAnimationFrame?: typeof requestAnimationFrame;
  ...
}
```

where the signature match the one from the default [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame).  In the current case, it looks like `(time: number) => number`.

I would like to know which signature **options.requestAnimationFrame** should be.  To me, `(callback: () => void) => void` is more flexible than `(callback: FrameRequestCallback) => number` since the developer does not have to provide a time parameter to the callback or return a handle from the function.

Actually, the signature `(callback: FrameRequestCallback) => number` prevents me to provide my own hook that does not rely on the default **requestAnimationFrame**.  The fact that I must return a handle (number) tells me that **preact** may wish to cancel the operation sometimes.  However, there is no option for **cancelAnimationFrame** which would allow me to undo the work of **option.requestAnimationFrame**.  If **preact** is invoking the default **cancelAnimationFrame** internally, it would make no sense for **option.requestAnimationFrame** to return a handle that was not generated by the default **requestAnimationFrame**.

**Comment by developit** [comment]
This is a good argument. We do not rely on the `time` parameter or any other `requestAnimationFrame`-specific logic. I think the types can be changed to:

```
interface Options {
  ...
  requestAnimationFrame?: (callback: () => any) => any  // or void?
  ...
}
```
