### ISSUE TITLE
'_unmount' is not exported from 'preact' (

### ISSUE THREAD

**Issue by yiliminiqihang** [preactjs/preact#3161]
'_unmount' is not exported from 'preact' 

![image](https://user-images.githubusercontent.com/66466781/119271296-93906580-bc33-11eb-969f-94516f15e327.png)

**Comment by marvinhagemeister** [comment]
What's the code that lead to this error? It's an internal function that should not be used by anyone other than Preact itself. The stack trace seems to point to something trying to import `_unmount` from `preact/compat` which looks very suspicious as we don't have such an import in our code base.

**Comment by developit** [comment]
This appears to be a broken local build. 

mangle.json is required in order to build successfully.
