### ISSUE TITLE
Issue while running npm run build 

### ISSUE THREAD

**Issue by Abhi-ak** [preactjs/preact#3164]
Name expected 

`[../node_modules/svelte-range-slider-pips/dist/svelte-range-slider-pips.mjs:22,0]`

This is the import i used in my component:
`import RangeSlider from "svelte-range-slider-pips";`

What is the reason for this error and how to fix this ?

**Comment by marvinhagemeister** [comment]
Please fill out the issue template and don't just delete that. We have it enabled for a reason and not just for fun.

You cannot render Svelte components with Preact.
