### ISSUE TITLE
Trying to get storybook to work

### ISSUE THREAD

**Issue by jliebrand** [preactjs/preact#3168]
Hi there - apologies if this is not a bug or if I should have put this elsewhere, but I can't get storybook to work with preact X

I'm getting
Module parse failed: Identifier 'h' has already been declared (31:9)

If I remove the import { h } from both the example components AND the stories, then it "works" but that's clearly not the right solution since I need it in the components?

I read in some older issues something about npm alias'ing, but afaik I'm not using those?

**Comment by jliebrand** [comment]
I should have probably added that I'm just doing the standard instructions from 

https://www.npmjs.com/package/@storybook/preact

After which I do not see any components (but the dev console shows the warnings about 'h' being already defined). Removing the import of h 'solves' it and shows the components, but as I said I suspect I ought to be doing something else, because the components would clearly not work inside my app without the 'h' import.

relevant npm packages:
```
...
    "@storybook/addon-actions": "^6.2.9",
    "@storybook/addon-essentials": "^6.2.9",
    "@storybook/addon-links": "^6.2.9",
    "@storybook/preact": "^6.2.9",
    "preact-cli": "3.2.0",
....
```

**Comment by JoviDeCroock** [comment]
This doesn't sound like an issue with `Preact` itself, have you tried whether the components work without the `h` import because as far as I am aware, both `preact-cli` and `storybook` automatically import your vnode-constructor for you.

**Comment by JoviDeCroock** [comment]
Closing due to my previous comment, if you face issues feel free to ping here but I think `@storybook/preact` is probably a better issue target
