### ISSUE TITLE
Preact 10.x unnecessarily updates DOM for <select> options

### ISSUE THREAD

**Issue by albv** [preactjs/preact#3171]
**Describe the bug**
Preact 10.x unnecessarily updates DOM (options's values specifically) for `<select>` element even if it's not changed.

**To Reproduce**
https://codesandbox.io/s/objective-jepsen-g55oi

1. Open Chrome Dev Tools and inspect select element options
2. Click on 'Render' button
3. See that every option's value is updated (highlighted with pink)

**Expected behavior**
DOM is not updated at all

**Comment by developit** [comment]
Yep, this is on the radar. That whole behavior is being removed in Preact 11, as it is a workaround for Internet Explorer 11.

**Comment by RReverser** [comment]
I'm running into this as well - I'm frequently updating a large form from an external source and I see all the `select>option[value]` constantly rerendering:

![image](https://user-images.githubusercontent.com/557590/125535479-ef765df8-817a-426a-978b-a033f5f8a184.png)

Another issue I've noticed - not sure whether related or not - is that if I omit `value` attribute on `option`s (which is perfectly valid per HTML and should default to text content of the `option`), Preact adds it and sets to an empty string.

**Comment by RReverser** [comment]
> I'm running into this as well - I'm frequently updating a large form from an external source and I see all the select>option[value] constantly rerendering:

Also: in Chrome Canary it's actually even worse - opening a dropdown immediately closes, I assume due to `option` changes. On Chrome stable it still works fine-ish.

**Comment by albv** [comment]
@RReverser FWIW I ended up using something like this https://codesandbox.io/s/focused-lichterman-m68bb

**Comment by JoviDeCroock** [comment]
Hmm I guess [this IE11 workaround](https://github.com/preactjs/preact/blob/master/src/diff/children.js#L182-L196) is the biggest issue here where we have to reset value and have it set later through the `diff`. This is not present in 11 but if this is causing issues we should look at an alternative workaround.
