### ISSUE TITLE
[compat] ComponentProps not in the React namespace

### ISSUE THREAD

**Issue by VottusCode** [preactjs/preact#3178]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

1. Use React.ComponentProps from "preact/compat"
2. You will get an error that the React namespace doesn't contain said type.

Example libraries: @heroicons/react 

**Expected behavior**
The type should be present as the compat types should be 1:1. This unfortunetely fails my builds.

**References**
see https://github.com/preactjs/preact/pull/2680#issuecomment-855804948

**Comment by developit** [comment]
I believe the current recommendation is to use `@types/react` rather than relying on `preact/compat` for 1:1 (swappable) typings (though I'm not a huge TypeScript user myself).
