### ISSUE TITLE
useEffect sequence difference with react

### ISSUE THREAD

**Issue by lishoulong** [preactjs/preact#3179]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
in some circumstance in nested components,  useEffect execute in reverse order. 
we expected the order is from child  to parent, but in reality the order is from parent to child.

**To Reproduce**

- react [example](https://codesandbox.io/s/hooks-shixu-forked-n6oz3?file=/index.js).
- preact [example](https://codesandbox.io/s/preactuseeffect-setstate-j197s)

1. see console

**Expected behavior**
in react  the sequence is 'child and then "parent: ++++" '.
but in preact the sequence is '"parent: ++++" and then  child '.

**Comment by developit** [comment]
I believe this is a bug. `useLayoutEffect()` fires in the correct (inner to outer) order.

**Comment by JoviDeCroock** [comment]
This has been resolved in latest https://codesandbox.io/s/preact-useeffect-setstate-forked-dz1uw?file=/src/index.js
