### ISSUE TITLE
Add onfocusin/onfocusout to jsx.d.ts

### ISSUE THREAD

**Issue by jramanat** [preactjs/preact#3186]
Based on the comments in https://github.com/preactjs/preact/issues/1611, it sounds like the recommendation for using the focusin + focusout DOM events is to use the standard all-lowercase forms (onfocusin/onfocusout) which will result in Preact calling addEventListener for the corresponding events.  This works fine at runtime, but we're running into issues in our TypeScript-only project as these properties are not defined in the list of IntrinsicElement properties.  As a result, we're forced to use workarounds like patching IntrinsicElements ourselves or using the spread operator on the element to sidestep type-checking.

Would it make sense to add these two props to jsx.d.ts to make it easier to use these in TypeScript?  Thanks!

**Comment by developit** [comment]
Yes! We should absolutely be including these in the TypeScript definitions as you described. If you're open to doing a PR, we'd be happy to review.
