### ISSUE TITLE
Cannot create property 'current' on string 'embedContainer', 

### ISSUE THREAD

**Issue by Hayk-js** [preactjs/preact#3203]
"next": "11.0.0",
    "next-plugin-preact": "^3.0.6",
    "preact": "^10.5.13",
    "preact-render-to-string": "^5.1.19",
    "react": "npm:@preact/compat",
    "react-dom": "npm:@preact/compat",
    "react-ssr-prepass": "npm:preact-ssr-prepass",
![Selection_022](https://user-images.githubusercontent.com/86301296/122926952-6ee5f580-d379-11eb-8857-e2285860d2fe.png)

**Comment by marvinhagemeister** [comment]
So what's the code esnippet that's causing the error?

**Comment by marvinhagemeister** [comment]
Closing as we've never heard back from the reporter of this issue.
