### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by AJamesPhillips** [preactjs/preact#3208]
- [x] Using Preact version: 10.5.13

**Describe the bug**
A memory leak on creating multiple elements

**To Reproduce**

Minimal repo with instructions to recreate [here](https://github.com/AJamesPhillips/possible_preact_redux_mem_leak).  Steps to reproduce:

1. [clone repo](https://github.com/AJamesPhillips/possible_preact_redux_mem_leak)
2. install node dependencies: `pnpm install`, `yarn install` or `npm install`
3. run `npm start`
4. The application should open in a new tab, if not go to http://localhost:8080/
5. If using Chrome: open the dev tools and go the Chrome performance tab and:
1. hit `record`
2. trigger garbage collect
3. click "Trigger leak"
4. wait for "Done." to appear under the "Trigger leak" button and then manually trigger another garbage collect
5. repeat a few times then stop recording

I got these results when I did this:
![Preact](https://raw.githubusercontent.com/AJamesPhillips/possible_preact_redux_mem_leak/main/preact_mem_leak.png)

Could not recreate memory leak on CodeSandbox (see screenshot below)

**Expected behavior**
After each manual GC the memory heap should go back down to or near the initial value.

**Additional screenshots**

Also could not recreate using React
![React](https://raw.githubusercontent.com/AJamesPhillips/possible_preact_redux_mem_leak/main/react_no_mem_leak.png)

Could not recreate memory leak on CodeSandbox:
![dreamy-booth-ekswz_-_CodeSandbox](https://user-images.githubusercontent.com/526509/123523073-564b4780-d6b9-11eb-8d14-2d8d42c9de39.png)

**Comment by JoviDeCroock** [comment]
Are you seeing these leaks in production as well? They seem heavily tied to the `$refreshreg$` helper of `prefresh`
