### ISSUE TITLE
Can dangerouslySetInnerHTML be used with htm template rendering?

### ISSUE THREAD

**Issue by klues** [preactjs/preact#3221]
I'm using htm template rendering and trying to use `dangerouslySetInnerHTML` like this:
```
render(props) {
        props.label = props.label || '';
        return html`<div dangerouslySetInnerHTML="${props.label}"></div>`;
}
```
However the `div` remains empty. Can `dangerouslySetInnerHTML` be used in any other way with htm template rendering?

**Comment by marvinhagemeister** [comment]
Yes, but the `dangerouslySetInnerHTML` prop expects an `object`, not a `string`. That's why it's not working for you.

```diff
  render(props) {
    props.label = props.label || '';
-   return html`<div dangerouslySetInnerHTML="${props.label}"></div>`;
+   return html`<div dangerouslySetInnerHTML="${{ __html: props.label }}"></div>`;
  }
```

**Comment by klues** [comment]
Thank you, it's working! 👍
