### ISSUE TITLE
Exception when hook arguments are changed from an array to undefined

### ISSUE THREAD

**Issue by mario-strohmeier** [preactjs/preact#3241]
**Describe the bug**
An exception is thrown when the arguments of a hook are changed from `[...someArgs]` to no args (e.g. `useEffect(() => {}, [arg1])` to `useEffect() => {})`. This happens because it is only checked that the oldArgs are undefined, however in this case the newArgs are and throw the exception when the length is checked. See [here](https://github.com/preactjs/preact/blob/7e33abd70ceb32f19e82c281e6b4d35091920f6a/hooks/src/index.js#L378)

**To Reproduce**
Sadly I can't seem to reproduce the issue in a minimal way.

**Expected behavior**
As a workaround we are now using an empty array as the args, however because it is possible to not define any args at all. This should not throw an error.
So a check like this in `argsChanged` should do the trick:
```
return (
    !oldArgs || (oldArgs && !newArgs) ||
    oldArgs.length !== newArgs.length ||
    newArgs.some((arg, index) => arg !== oldArgs[index])
);
```

**Comment by developit** [comment]
@mario-strohmeier hmm - I believe we debated accounting for this case but decided it would be encouraging an antipattern.  Hook dependency arrays really shouldn't be dynamic in the first place. Do you have a use-case where this is showing up that is important to you?

**Comment by mario-strohmeier** [comment]
@developit Oh sorry, thought i already closed the issue.

The issue was that the hook was called conditionally. Only later found out about the `react hooks` plugin.
Maybe a reference to it would be good in order to avoid this for other users.
