### ISSUE TITLE
Question about the render function

### ISSUE THREAD

**Issue by fredrikstave** [preactjs/preact#3250]
Hi Preact team 🙂 

First of all, sorry if this is not the correct place to post questions 🙏 I couldn't find a message board on the Preact website.

In the Preact documentation I found out that the `render` function has a third (optional) parameter — `replaceNode` — which can be used to target content in the container node to be replaced by the rendered preact component.

My question is: **Is it safe if these replace nodes is the same DOM element?**

Reason I'm asking is that I'm currently writing a web app in [Laravel](https://laravel.com/) and is using Preact for some of the interactive front end components. Some of these are _above the fold_, and I really want to server render these to avoid having an empty space on the page when visitors enter.

In my previous setup it looked like this:

```
index.html:

<body>
	<div class="header-component"></div>
</body>

app.js:

const el = document.querySelector('.header-component');

function Header() {
	return (
		<div class="header-component">
			  <h1>My Awesome Webpage</h1>
			  <nav>
				  <a href="#">Test 1</a>
				  <a href="#">Test 2</a>
			  </nav>
		</div>
	);
}

render(<Header />, el);
```

But now I have changed it to this, using the `replaceNode` parameter to replace the contents of `el`:

```
index.html:

<body>
	<div class="header-component">
		<h1>My Awesome Webpage</h1>
		<nav>
			<a href="#">Test 1</a>
			<a href="#">Test 2</a>
		</nav>
	</div>
</body>

app.js:

return (
		<div class="header-component">
			  <h1>My Awesome Webpage</h1>
			  <nav>
				  <a href="#">Test 1</a>
				  <a href="#">Test 2</a>
			  </nav>
		</div>
	);
}

const el = document.querySelector('.header-component');
render(<Header />, el, el);
```

It works like a charm (🤩), but is it safe to do replacement like this?

**Comment by marvinhagemeister** [comment]
It's safe for now, but will be removed in a future Preact version. The reason for that is that it introduces a lot of edge cases which makes our renderer more complex than it has to be. The maintenance cost of it is pretty high too and given that we are a smaller team, we'd rather use that time to improve other aspects of Preact.

**Comment by fredrikstave** [comment]
I see. That makes sense 👍 Does that mean the entire replace logic will be removed, and the function can only be used like this?:
```
render(<Component />, node);
```

**Comment by marvinhagemeister** [comment]
yup 👍

**Comment by fredrikstave** [comment]
Ah, okay. Then I'll have to come up with another workaround 😞 

Thank you very much for the swift reply 🙏 🤩
