### ISSUE TITLE
Should grouping of rendered children matter for key="…" matchup?

### ISSUE THREAD

**Issue by natevw** [preactjs/preact#3254]
I have a regression in my app UI that started when I upgraded from `preact@10.0.0-beta.2` to `preact@10.4.5` and has persisted ever since (through `preact@10.5.14`). 

The component is a list editor which always keeps a "pending" (empty placeholder) row available for entry of a new item — as soon as the user starts typing in the "pending" row, it should *turn into* an "item" row and a *new* pending row gets added underneath. To preserve the user's focus/cursor it is important that the same `<input />` DOM element is preserved as it goes from "pending" to "item" status and so I am careful to provide a stable `<input key=${ … } />` value. But in recent `preact` versions this is no longer sufficient!

My (once-working, now-broken) example at https://codesandbox.io/s/unruffled-rain-78146 renders the list as…

```js
html`<div>
  ${items.map(item => html`<input key=${item._id} … />`)}
  <input key=${pendingId} … />
</div>`
```

…and does **not** work as expected. When the input for `pendingId` gets "upgraded" to represent an actual `item._id`, the cursor position is *lost* — indicating that a new `<input />` element was created, rather than reused. So a user has to notice that something broke, put their cursor back into the box, and only then can they finish typing their new entry.

However when I add a `.concat` workaround to this (modified) example at https://codesandbox.io/s/frosty-williamson-j5b7r renders the list as…

```js
html`<div>
  ${items
    .map(item => html`<input key=${item._id} … />`)
    .concat(html`<input key=${pendingId} … />`)}
</div>`
```

…and it **works** as intended. When the input for `pendingId` gets "upgraded" to represent an actual `item._id`, the cursor position is *preserved* — indicating that the original `<input />` element lives on in the DOM. So the user can just type in a new entry, and then tab to the next and type another, no disruption.

**Is this expected behavior?** That is, for DOM reconciliation purposes should it matter if a sibling element came from an array vs. inline? Or should both variants be equivalent?

---

Additional background: this is possibly something of a regression of behavior related to https://github.com/preactjs/preact/issues/1524, and the sandboxes above are derived from the ones there with the following changes:

* updated to latest `preact@10.5.14` and `html@3.0.4` dependencies
* replaced some questionable synchronous usage of `setState` with a `useMemo` trick

**Comment by developit** [comment]
I believe this behavior was intended for Fragments, but perhaps it was unintentionally also applied to Arrays by virtue of them being treated as implicit fragments.

I believe we've revisited this in Preact 11 and Arrays are no longer implicit Fragments with their own "keyspace".

**Comment by natevw** [comment]
Thanks, so I think the situation is:

* for Preact 10 keys will *probably* be "namespaced" only within a fragment/array
  - so if nodes **need** to be considered equivalent for DOM/UI stability, they should come from the same group to ensure reliable match-up
  - but otoh, keys should still be unique within their whole parent as well (i.e. don't rely on just the group/fragment being the solely relevant scope, for 11.x compat and/or in case this situation flip-flops again in 10.x)
* for Preact 11 keys will be "namespaced" to their parent node, regardless of provenance

Is that a fair assessment?

**Comment by marvinhagemeister** [comment]
@natevw Keys are bound to the immediate parent, regardless of whether it's component or a DOM element.

```jsx
<div>
  <Foo>{/* <- Bound here to Foo */}
    {[1,2,3].map(n => <span key={n} />}
  </Foo>
  <>{/* <- Bound here to Fragment */}
    {[1,2,3].map(n => <span key={n} />}
  </>
</div>
```

When it comes to arrays they are converted to a Fragment. They cannot be moved into the children array of the parent as there might be duplicated keys.

```js
<div>
  {/* Inlining both arrays would lead to duplicate keys */}
  {[1,2,3].map(n => <span key={n} />}
  {[1,2,3].map(n => <span key={n} />}
</div>
```

Therefore the above is turned into:

```js
<div>
  <>
    <span key={1} />
    <span key={2} />
    <span key={3} />
  </>
  <>
    <span key={1} />
    <span key={2} />
    <span key={3} />
  </>
</div>
```

That logic is the same in Preact 10 and Preact 11.

I think what's instead happening here is that something with the Fragments seems to trigger an unexpected behavior. From the description it looks like everything is inserted at the end _after_ the `<input>`-element and moved back into place. That's notorious for the v10 diff algorithm as it relies too much on the DOM when diffing.

**Comment by natevw** [comment]
Thanks @marvinhagemeister for even more details here!

> I think what's instead happening here is that something with the Fragments seems to trigger an unexpected behavior.

Actually based on what you've explained, I don't think the behavior is unexpected.

I was basically rendering:

```
<div>
  <>
    <input key={1} />
    <input key={2} />
  </>
  <input key={3} />
</div>
```

And expecting it to re-use the original `key={3}` DOM node when re-rendered as:

```
<div>
  <>
    <input key={1} />
    <input key={2} />
    <input key={3} />
  </>
  <input key={4} />
</div>
```

This *did* work in some early Preact 10.x builds — perhaps only prerelease ones — but it sounds like it wasn't ever supposed to. So to summarize in terms of my question:

> Should grouping of rendered children matter for key="…" matchup?

sounds like the answer is **yes**. Key matchup is grouped within the *immediate parent*, and a fragment itself is considered the parent for its children, and an array is treated as a fragment.

(I'll close this since it doesn't sound like there's any 10.x fixup needed currently regarding this. Really I was just overestimating how "transparent" arrays and even fragments were — they must be tracked/preserved for more of the DOM reconciliation process than I imagined.)
