### ISSUE TITLE
SVG property renaming in compat impacts non-SVG custom elements

### ISSUE THREAD

**Issue by jramanat-oracle** [preactjs/preact#3258]
**Describe the bug**
The code in preact/compat which converts camelCased SVG properties to their kebab-case attribute forms is impacting non-SVG custom elements as well.  I've attached a (contrived) test case to show the issue, but in our application we are using a custom element within our Preact component to render a chart and that custom element has an Object-valued 'xAxis' property.  However, when we try to specify that property, preact/compat rewrites it to 'x-axis' and it ends up writing an invalid attribute value ('[object Object]') to the DOM.  (Note that 'yAxis' works fine since the regex in preact/compat doesn't match it).

**To Reproduce**

1. Go to https://codesandbox.io/s/keen-cherry-j0inc?file=/src/index.js
2. Go to the browser console and you should see a log for the setter of the 'yMarks' property, but not the 'xMarks' property.
3. If you inspect the DOM, you'll see x-marks="[object Object]"

**Expected behavior**
The xMarks property setter should have been called (i.e. the xMarks property on the vnode should have been left as is so that it could be rendered to the DOM via property rather than attribute)

**Comment by jramanat-oracle** [comment]
(Don't see how to link the PR, but I've started https://github.com/preactjs/preact/pull/3259)

**Comment by rschristian** [comment]
(Completely irrelevant to the issue, but here's [the docs on how to link issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) if you're curious)

**Comment by jramanat-oracle** [comment]
Thanks for creating the link!  I did come across those instructions, but I don't seem to have any interactive UI in the Linked issues section of my PR.  In fact, I _still_ don't, other than the issue link you just created.

**Comment by jramanat-oracle** [comment]
Ah, that clears it up, thanks!
