### ISSUE TITLE
Hooks ref type should provide null option

### ISSUE THREAD

**Issue by maximgavrilov** [preactjs/preact#3263]
The `current` type can be not only `T`, but also `null`. So it should be:

```
type Ref<T> = { current: T | null };  
```

https://github.com/preactjs/preact/blob/778607e618ae4d768f9e8ac13bb7c858e9a645c1/hooks/src/index.d.ts#L50

**Comment by rschristian** [comment]
I believe this is correct. Where `Ref` is used (vs `RefObject`, which is represented as `{ current: T | null }`) you want to specify the exact type with your generic, rather than having a `| null` appended for you. 

For example, `useRef<HTMLDivElement | null>()` vs `useRef<HTMLDivElement>()`

**Comment by nmain** [comment]
Yes, this is correct. `useRef` has no opinion on the type of `.current`; it will set it to the initial passed value and then allow you to set and get whatever values you want on it, so the typing is just for your benefit.

When you pass a ref object as a `ref` prop on a VDOM node, that's when the types matter and when Preact will set `ref.current = null` if the target is unmounted.  But the typing for that interface does include the `null`: https://github.com/preactjs/preact/blob/778607e618ae4d768f9e8ac13bb7c858e9a645c1/src/index.d.ts#L40

**Comment by JoviDeCroock** [comment]
This is indeed correct, closing for now
