### ISSUE TITLE
Increase size from 3kb to 4kb in the documentation

### ISSUE THREAD

**Issue by respel** [preactjs/preact#3268]
**Describe the bug**
The website and the docs mention that preact is 3kb in size. However, the latest bundlephobia informs that it's 4kb instead. 

Is there some error there in the calculation of bundlephobia? If not, can we update the docs please?

**Comment by gu-stav** [comment]
It has been mentioned before that 3kB will stay, because that's what preach is aiming for. Apparently v11 will be much closer (maybe even smaller) than 3kB from what I have read.

Also it heavily depends on which features you are using in the end, because unused ones will be tree-shaked away.
