### ISSUE TITLE
Support components that return a raw DOM node

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/preact#3278]
**Describe the feature you'd love to see**

Some context: I work on a Markdown-based notes app, I'm trying to make it as fast as possible but I've found the inability to return raw DOM nodes from Preact components to be a major performance issue for me.

Ideally I'd like the app to take the following steps:

1. Compile the Markdown to HTML: that's necessary in order to render it on screen.
2. Construct nodes out of the HTML: that's necessary for sanitizing them.
3. Sanitize the nodes: can't have XSS issues.
4. Now those fresh nodes need to be swapped in and out of the DOM.
5. Finish.

Essentially every step in the list is necessary, at least for parts of the input string.

The problem is with Preact I can't quite just do those steps easily, because I can't just return DOM nodes from components at step 4. and let Preact manage the swapping in and out for me.

So instead of a simple step 4. I need to either:

1. Convert those nodes into actual JSX elements, which will then be converted back into nodes, which is just wasteful since I already had the fresh nodes to begin with.
2. Break out of Preact and manage swapping nodes in and out manually, which isn't ideal since I'm using Preact precisely because I'd rather avoid mutating the DOM imperatively like that.

Maybe there are some fundamental issues with allowing this, but it seems like the cleanest solution to me. Maybe managing this manually is actually quite easy and quick and it's better to ask users to do that to squeeze some extra performance if their use case allows for it. I'm not sure what the best path forward is on this, both for myself and Preact.

**Additional context (optional)**

Kind of off-topic but Solid supports returning raw DOM nodes from components.

**Comment by JoviDeCroock** [comment]
You can use `dangerouslySetInnerHtmk` for this case as that won't be 'wasteful' and will just insert the html.

**Comment by fabiospampinato** [comment]
> Well managing dom-nodes somewhere outside (p)react breaks all sort of features like server side rendering or hydration.

I don't need those, if the internet imploded my app would work just the same basically. I suppose nodes could be serialized somewhat though, and hydrated back on the client.

> Also there are a load of libraries that support rendering markdown into components at various levels. e.g. mdxjs at build time or react-markdown at runtime. I've used both of them successfully with preact in past.

The problem isn't doing it, is doing it with optimal performance. Performance-wise bypassing Preact/React is the least of the problems those ready-made runtime-rendering solutions have.

> But if you need to manage nodes yourself, preact gives you all the tools to do so using refs and disabling component updates.

Yes, it's quite simple in the end. Perhaps it should be made simpler though, I'm not sure.

**Comment by developit** [comment]
@fabiospampinato Here's an implementation of Markdown processing and HTML sanitization in a Worker. It uses DOMPurify in the Worker by instantiating it against [Linkedom](https://github.com/WebReflection/linkedom):
https://jsfiddle.net/developit/fjdh23pc/

As for the windowing/diffing bit, this could probably be done more simply in Preact because it could use referential equality rather than a bidirectional search algorithm.

Iframes won't help performance sadly, since they're only out-of-process when the iframe is loading content from another origin.

**Comment by fabiospampinato** [comment]
> @fabiospampinato Here's an implementation of Markdown processing and HTML sanitization in a Worker. It uses DOMPurify in the Worker by instantiating it against Linkedom:

Oh wow, that's amazing!

On one hand I'm allergic to adding ~200kb+ of dependencies, on the other hand this is awesome, with something like that I could potentially sanitize stuff in parallel too. Other drawbacks are that I most probably would still want to use the new Sanitizer API, which just isn't available in a worker, and while parsing and sanitization is offloaded to the worker some nodes would still need to be created on the main thread, but I guess in this scenario it'd be better to just output VDOM and let Preact do its magic. I wonder if LinkeDOM not being 100% spec compliant could cause issues in some edge cases, maybe not, I'm not sure which parts of the DOM DOMPurify actually relies on.

> Iframes won't help performance sadly, since they're only out-of-process when the iframe is loading content from another origin.

Oh really? 😢 Maybe that'll change in the future, maybe it's just a limitation of the browser that will eventually be lifted.

**Comment by fabiospampinato** [comment]
Pretty amazing how far very little code can get you.

To summarize:

- I should definitely explore doing the sanitization and conversion to vdom in a worker, the potential performance improvement seems too juicy to pass on this. 
- I wonder if there's something even smaller than linkedom that I could use though 🤔 I'd bet DOMPurify doesn't even need most of it. Maybe trimming linkedom down is too much trouble though.
- I should perhaps check what the difference in memory usage would be for large-ish documents between keeping the vdom around and bypassing it entirely. But that shouldn't be significant anyway once windowing is always used, which is necessary for large-enough documents anyway.
- Lastly I need to be careful with the html/dom -> vdom conversion part, it's too easy to have little cracks that malicious inputs can get through, like: `<script>document.body.innerHTML = 'pwned!';</script>`. It might be still worth exploring the iframe idea even if just as an added layer of isolation.

---

I'm closing this as the component mentioned [here](https://github.com/preactjs/preact/issues/3278#issuecomment-941543846) seems to basically address the issue already, and mutating the DOM manually with a ref to the parent is quite doable too.

**Comment by fabiospampinato** [comment]
@developit I think I've spotted some issues with the component for returning raw dom nodes:

```js
function DomNode({ children }) {
  this.shouldComponentUpdate = () => false;
  return Object.defineProperty(h(children.localName), '__e', { get: () => children, set: Object });
```

1. It throws for text nodes if preact/debug is loaded, because children.localName would be undefined in that case and preact/debug is explicitly [checking](https://github.com/preactjs/preact/blob/c7f57db13af43b8cc3353a138639ad9dd9523e16/debug/src/debug.js#L123) for that.
2. It kinda works for text nodes if I use `null` or `span` as the node type, but then I get some quirks during development, multiple nodes get injected in the page with each HMR event basically. Maybe I should detach the child node manually when the component is unmounted?

https://user-images.githubusercontent.com/1812093/139543595-e57532fc-7657-4b35-b6bb-5e5961900e35.mov

**Comment by developit** [comment]
@fabiospampinato that makes sense - Preact uses `null` internally for text nodes as the vnode type.

**Comment by djalmajr** [comment]
> ```js
> function DomNode({ children }) {
>   this.shouldComponentUpdate = () => false;
>   return Object.defineProperty(h(children.localName), '__e', { get: () => children, set: Object });
> }

Awesome!! 🎉 Just one question: is it safe to use this approach long term? Can I trust this implementation or will this change in minor releases? I know it's working so far, but it doesn't hurt to ask 😬 (I don't know what that "__e" means... It seems to me it's something internal)

**Comment by rschristian** [comment]
> or will this change in minor releases?

It's stable.

> I don't know what that "__e" means... It seems to me it's something internal

It's the `__dom` property, which is set to be consistently [mangled](https://github.com/preactjs/preact/blob/main/mangle.json) to `__e`. This is done specifically to facilitate this sort of thing.
