### ISSUE TITLE
Fragment is undefined

### ISSUE THREAD

**Issue by Husdady** [preactjs/preact#3289]
**Preact Version**
^8.5.3

**Description**
I was testing preact, the alternative to react, with better performance, but I have noticed that Fragment is undefined, it is also missing several things from React.

1. Install preact
2. Import { Fragment } from preact
3. Fragment is undefined

**Object returned**
```
{
    Component: ...
    h: ...
    cloneElement: ...
    createElement: ...
    createRef: ...
    rerender: ...
    options: ...
    render: ....
}
```

**Test image**
![image](https://user-images.githubusercontent.com/76859196/138530517-680340bf-b731-4dda-9b75-6abc6dc0630c.png)

** Note **
I am not using preact-cli. I am using webpack for it, I installed preact and preact-compat to use preact instead of react and I come across this

**Comment by marvinhagemeister** [comment]
Like @JoviDeCroock said, you're on an old version of Preact. The Preact 8.x release line does not support Fragments. Support for Fragments was added with Preact 10.x.

Updating to the latest version will resolve that. Note that `preact-compat` is for older versions of Preact which didn't have Fragments. In current Preact the compat entry is part of the core package and can be loaded via `preact/compat` (note the slash in the name).

**Comment by Husdady** [comment]
Thank you, just now I had realized that I am not using version 10, my bad, thanks!
