### ISSUE TITLE
Doesn't hydrate when there are html comments

### ISSUE THREAD

**Issue by thelucid** [preactjs/preact#3290]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
If hydrating markup that contains html comments, a confused re-render happens. It should probably skip comment nodes, or ideally treat them as first class citizens.

**To Reproduce**

Render component to a string, add some html comments, try to `hydrate`.

1. Render a component to string.
2. Add some html comments.
3. Try to `hydrate`.

**Expected behavior**
Should hydrate component but it gets confused and causes duplicate nodes.

**Comment by developit** [comment]
This is [fixed on `restructure`](https://github.com/preactjs/preact/blob/f41132a707af4cfad1251bce1532ac5d23a944aa/src/diff/mount.js#L133-L138) and will be in Preact 11.
