### ISSUE TITLE
Textareas are empty on reload

### ISSUE THREAD

**Issue by tkafka** [preactjs/preact#3291]
**Describe the bug**
I use next.js with preact 10.5.15, and it behaves as if this bug wasn't fixed: https://github.com/preactjs/preact/issues/2556

**To Reproduce**

1. I have a next.js project with preact according to https://darrenwhite.dev/blog/nextjs-replace-react-with-preact
2. Have a controlled `textarea` on page (`<textarea value={track.trackNote} onChange={this.handleChange.bind(this, 'trackNote')} rows="5" />`) with nonempty content.
3. Load page (textarea content appears)
4. Refresh the page in browser (cmd+r)

**Expected behavior**
I can see the initial content

**Actual behavior**
During reload, the textarea content appears briefly (after the page loads from server and before client side rendering takes over), then client side render removed all textarea content.
After first render (eg. triggered by input change → state change) the textarea is rendered correctly and content appears again.

**Comment by developit** [comment]
Does this happen if you change the `onChange` to `onInput`?

**Comment by tkafka** [comment]
@developit This seems to fix the problem, thank you! (Although, it still remains a trap for everyone else.)

Is working with onInput an expected behavior?

**Comment by developit** [comment]
Yep - Preact uses standard DOM events, so `onchange` is the "change" event that gets fired when an input field is committed (usually on blur). 

If you use `preact/compat` (for your JSX), it will internally convert any `onChange` handlers in your JSX to oninput.

**Comment by tkafka** [comment]
@developit Thank you very much! It would help (at least in my case) if preact in dev mode detected onChange handler without onInput on same element, and printed some warning.
