### ISSUE TITLE
[preact/compact] Suppport `isImmediatePropagationStopped`

### ISSUE THREAD

**Issue by diegocmaia** [preactjs/preact#3293]
**Describe the feature you'd love to see**
My suggestion is pretty simple:

Instead of checking `isPropagationStopped`, some libraries check for `isImmediatePropagationStopped` ([documentation](https://api.jquery.com/event.isimmediatepropagationstopped/)), which returns whether event.stopImmediatePropagation() was called.

So, it'd be helpful to also include it. :)

Please let me know your thoughts.

**Comment by developit** [comment]
@diegocmaia I can only find that method implemented in jQuery - is React providing it too?

**Comment by diegocmaia** [comment]
@developit React is not, indeed.

**Comment by marvinhagemeister** [comment]
Closing, as this property is coming from jQuery as mentioned above.
