### ISSUE TITLE
[preact/compat] Avoid using 'cancelBubble'

### ISSUE THREAD

**Issue by diegocmaia** [preactjs/preact#3294]
Currently, the `isPropagationStopped` uses the `cancelBubble` property from Event, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelBubble) and it can lead to issues in the future.

Current [implementation](https://github.com/preactjs/preact/blob/master/compat/src/render.js#L94):

```javascript
function isPropagationStopped() {
	return this.cancelBubble;
}
```

One possible solution could be to extend the `stopPropagation` function and define an internal boolean property for `isPropagationStopped`, like it was implemented [in the past](https://github.com/preactjs/preact/commit/200826b44aacdba276f902833af770e06379fb59#diff-ca4ea8ca0432690f6ba6b72b44897d4980f8efa6ca6290d8a82a4e511d973af2).

I'd be glad to read your thoughts about it.

**Comment by developit** [comment]
This was done intentionally - all browsers implement `get cancelBubble` the same way. It's reliable, the deprecated status is meant to encourage new code to be written using other APIs.
