### ISSUE TITLE
Option hook for the hyperscript function

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/preact#3312]
**Describe the feature you'd love to see**

I'd like to see an option hook for intercepting calls to the "h" function basically.

**Additional context (optional)**

This is useful in some cases, for example my niche use use is having my own Component class, which I would like h to instantiate properly basically, without me having to manually generate something that h understands for each component class.

Also while this can be done already by simply writing another h function that calls the previous one, doing that breaks all sorts of tooling. 

Potentially a more performant alternative would be just to be able to reassign "h" in preact, but that throws currently as that property is read-only, probably for good reasons.

**Comment by JoviDeCroock** [comment]
This is what you're looking for I think https://github.com/preactjs/preact/blob/master/src/create-element.js#L79

**Comment by fabiospampinato** [comment]
That works brilliantly for my use case, I overlooked it. Thank you very much!
