### ISSUE TITLE
Possibly broken importless JSX runtime

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/preact#3324]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

I can't manage to make importless JSX work.

**To Reproduce**

Open the following project: [asd.zip](https://github.com/preactjs/preact/files/7538933/asd.zip).

<img width="1728" alt="Screen Shot 2021-11-15 at 13 20 26" src="https://user-images.githubusercontent.com/1812093/141789049-1142a075-1875-4ea0-902d-7b08e7832e48.png">

**Expected behavior**

My understanding is that by configuring TS this way, as the docs say, I wouldn't need to import preact  or h everywhere, but unless I uncomment the `import 'preact';` line I get the following error: `Cannot find module 'preact/jsx-runtime' or its corresponding type declarations.`. And I can totally import `require ( 'preact/jsx-runtime' )` from the repl, I'm not sure why TS (v4.4.3) can't find it.

**Comment by JoviDeCroock** [comment]
Hmm, I wonder if TypeScript expects a separate import for the runtime like [React does](https://www.runpkg.com/?@types/react@17.0.34/jsx-runtime.d.ts)

**Comment by fabiospampinato** [comment]
This really looks like some nonsense on TS' end to me.

I get the error for the following:

```tsx
function Asd ( props: { children: number } ) {
  return null;
}

<Asd>{2}</Asd>
```

But suddenly this works 😆:

```tsx
import "asd123";

function Asd ( props: { children: number } ) {
  return null;
}

<Asd>{2}</Asd>
```

And the "asd123" module doesn't even exist, I'm not even getting an error about that for whatever reason.

**Comment by JoviDeCroock** [comment]
Yes 😅 I don't think there's much more we can do on our end as the types, ... are there

**Comment by fabiospampinato** [comment]
Let's keep track of this on TS' end: https://github.com/microsoft/TypeScript/issues/46809

**Comment by kentr** [comment]
FWIW, the problem is not occurring for me using the latest `typescript` template from `preact-cli`. Though, it is occurring on a typescript version of the codesandbox `preact` template.

The coresponding issue in the typescript repo was closed because it was deemed an "external" issue.

**Comment by kentr** [comment]
> the problem is not occurring for me using the latest typescript template from preact-cli.

I was mistaken. The issue wasn't appearing for me in the b/c I already had imports from `preact` and `preact/hooks`.

**Comment by kentr** [comment]
@JoviDeCroock 

It appears that the cause of this could be the default value of `classic` for typescript's `moduleResolution` config option. 

The error comes and goes when I set the value to `node`, and the community-maintained Create React App base config [uses `node` for this config option](https://github.com/tsconfig/bases/blob/7660eb9dd6327622ff921c31158723ff2628bc52/bases/create-react-app.json#L17).

The following config is working for me with typescript `4.6.3` and the `@tsconfig/create-react-app` package:

```
{
  // tsconfig.json
  "extends": "@tsconfig/create-react-app/tsconfig.json",
  "compilerOptions": {
    "jsxImportSource": "preact"
  },
  "include": ["src"]
}

```

```
// Test.tsx
export default function Test() {
  return <div />;
}
```

This might warrant an update to the Preact typescript docs.
