### ISSUE TITLE
Component unmount fails when exception is thrown from effect cleanup function.

### ISSUE THREAD

**Issue by AlexIII** [preactjs/preact#3329]
## Describe the bug

If exception is thrown from the components effect cleanup function, the component fails to unmount properly, leaves garbage in the DOM, following cleanup functions are not called.

preact - 10.5.15
preact-compat - 3.19.0

## To Reproduce

```typescript
const RootComponent = () => {
    return (
        <ErrorBoundary>
            <MainContent/>
        </ErrorBoundary>
    );
};


class ErrorBoundary extends React.Component<{}, {error: Error | null}> {
    constructor(props: {}) {
        super(props);
        this.state = { error: null };
    }
    componentDidCatch(error: Error) {
        this.setState({ error });
    }
    render() {
        return this.state.error
            ? <h2> { `Error! ${this.state.error}` } </h2>
            : this.props.children
        ;
    }
}

const MainContent = (props: {}) => {
    const [val, setVal] = React.useState(false);

    React.useEffect(() => {
        setTimeout(() => setVal(v => !v), 1000);
        return () => { throw new Error("oops"); };
    }, [val]);

    React.useEffect(() => {
        console.log(`MainContent mount`);
        return () => console.log(`MainContent unmount`);
    }, []);

    return <h1>Hello world</h1>;
};
```

In 1 second the cleanup function of the first effect in `MainContent` throws and interrupts `MainContent` unmount process. This leaves the second effect cleanup function uncalled and `<h1>Hello world</h1>` stays in the DOM. After that `ErrorBoundary` renders its content and we have an "impossible" situation when both `<h1>Hello world</h1>` and `<h2>Error! ...</h2>` are in the DOM.

![2021-11-17 14 29 08](https://user-images.githubusercontent.com/10047074/142177638-401de670-3e0e-4869-9839-fb7a40342ebf.png)

Console output:

```
MainContent mount
bundle.js:3087
Error: oops
    <trace>
```

## Expected behavior

With react everything works as expected. After the exception is thrown, the second effect cleanup function is called and the content of `MainContent` is removed from the DOM.

![2021-11-17 14 25 10](https://user-images.githubusercontent.com/10047074/142178096-4489676b-c5e4-4d3e-b7de-cabbd6344e98.png)

Console output:

```
MainContent mount
Error: oops
    <trace>
React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
Error: oops
    <trace>
MainContent unmount
```

**Comment by JoviDeCroock** [comment]
When reproducing this error there it doesn't look to happen https://codesandbox.io/s/tender-water-w17jr?file=/src/App.js

**Comment by AlexIII** [comment]
@JoviDeCroock your example uses react and not preact. I said in my comment that react works fine with this code, hence the issue.

![image](https://user-images.githubusercontent.com/10047074/143181108-840426db-e3eb-4467-8b1b-7c6de62b2466.png)

Bwt I couldn't make codesandbox run the example with preact, it always complains something about tslib.

**Comment by AlexIII** [comment]
Here, https://codesandbox.io/s/preact-issue-3329-iseff

![image](https://user-images.githubusercontent.com/10047074/143184453-480b301f-074b-4941-a17d-708916852e2f.png)
