### ISSUE TITLE
I start education preact. I run code in tutorial. And it is not working. I know that I stupid, but you are? why is every textbook written for someone who already understands and not for a fool?

### ISSUE THREAD

**Issue by Olegborodko** [preactjs/preact#3333]
<script type="module">
		import { h, Component, render } from 'https://unpkg.com/preact?module';
import { h, render, Component } from 'preact';

class App extends Component {
  render() {
    return <h1>Hello, world!</h1>;
  }
}

render(<App />, document.body);
</script>

**Comment by JoviDeCroock** [comment]
Sorry I'm closing and locking this as this is not really actionable and just a bit offensive with the

> I know that I stupid, but you are?
