### ISSUE TITLE
WebpackError: TypeError: Cannot read property '__H' of undefined 

### ISSUE THREAD

**Issue by urmik-zwt** [preactjs/preact#3352]
We are facing a build time "WebpackError: TypeError: Cannot read property '__H' of undefined" error when we add the gatsby-plugin-preact you can also see in the below image.

**Screen Shot:**

![Screen Shot 2021-12-02 at 4 32 29 PM](https://user-images.githubusercontent.com/79259238/144422784-c22affb9-02ae-4227-a800-32f390582027.png)

**Package.json**

"dependencies": {
"@artsy/fresnel": "^1.3.1",
"@babel/core": "^7.12.9",
"@reach/router": "^1.3.4",
"@sentry/gatsby": "^6.3.1",
"algoliasearch": "^4.11.0",
"axios": "^0.21.1",
"clsx": "^1.1.1",
"consolidated-events": "^2.0.2",
"document.contains": "^1.0.2",
"gatsby": "^4.2.0",
"gatsby-cli": "^4.2.0",
"gatsby-plugin-algolia": "^0.24.0",
"gatsby-plugin-algolia-search": "^0.5.7",
"gatsby-plugin-image": "^2.2.0",
"gatsby-plugin-less": "^6.2.0",
"gatsby-plugin-manifest": "^4.2.0",
"gatsby-plugin-offline": "^5.2.0",
"gatsby-plugin-preact": "^6.2.0",
"gatsby-plugin-prismic-previews": "^5.2.1",
"gatsby-plugin-react-helmet": "^5.2.0",
"gatsby-plugin-robots-txt": "^1.6.14",
"gatsby-plugin-sass": "^5.2.0",
"gatsby-plugin-sharp": "^4.2.0",
"gatsby-plugin-sitemap": "^5.2.0",
"gatsby-remark-images": "^6.2.0",
"gatsby-remark-lazy-load": "^1.0.2",
"gatsby-source-filesystem": "^4.2.0",
"gatsby-source-prismic": "^5.2.2",
"gatsby-transformer-remark": "^5.2.0",
"gatsby-transformer-sharp": "^4.2.0",
"lazysizes": "^5.2.2",
"less": "^3.12.2",
"node-sass": "^4.14.1",
"object.values": "^1.1.2",
"preact": "^10.6.2",
"preact-render-to-string": "^5.1.19",
"prismic-javascript": "^3.0.2",
"prismic-reactjs": "^1.3.3",
"prop-types": "^15.7.2",
"rc-slider": "^9.7.1",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-helmet": "^6.1.0",
"react-hook-form": "^6.15.5",
"react-hook-form-input": "^1.1.10",
"react-instantsearch-dom": "^6.10.3",
"react-live-chat-loader": "^2.3.2",
"react-share": "^4.4.0",
"react-slick": "^0.28.1",
"semantic-ui-css": "^2.4.1",
"semantic-ui-react": "^2.0.3",
"slick-carousel": "^1.8.1",
"slugify": "^1.5.0",
"url-pattern": "^1.0.3",
"use-mobile-detect-hook": "^1.0.4",
"validator": "^13.5.2",
"vercel": "^21.3.3"
},

**gatsby-config.js**

![gatsby-config](https://user-images.githubusercontent.com/79259238/144419108-6e74d930-262f-4b32-94bb-5b440da05b30.png)

**Steps to reproduce the behavior:**

1. npm install gatsby-plugin-preact preact preact-render-to-string.
2. Add gatsby-plugin-preact to gatsby-config.js.
3. gatsby clean && gatsby build.

**Expected behavior**

1. gatsby build should run without any errors.
2. the JS bundle build should be reduced in size.

**Comment by JoviDeCroock** [comment]
I'd assume this issue would be meant for `gatsby-plugin-preact` as if your bundle isn't smaller (expected behavior) or if this error occurs it will often indicate a webpack configuration error which we don't really do 😅

**Comment by lkrugertogetr** [comment]
I'm getting the same error as of today, and I'm using ESBuild:
![image](https://user-images.githubusercontent.com/86956017/144572385-0dfbd09c-3d0b-4e81-83a6-36dcb7edda62.png)

Sourcemapped:
![image](https://user-images.githubusercontent.com/86956017/144572684-ab799a50-d38e-4699-bc5e-940a08dc5302.png)

Frankly it might be build configuration, but I have no idea what changed that could suddenly be causing this.

**Comment by JoviDeCroock** [comment]
Generally you're looking for duplicate copies of Preact 😅 so what mostly happens is one version is used for rendering and the other included by `preact/hooks` won't know what's going on as it has a different version it's looking at

**Comment by lkrugertogetr** [comment]
> Generally you're looking for duplicate copies of Preact 😅 so what mostly happens is one version is used for rendering and the other included by `preact/hooks` won't know what's going on as it has a different version it's looking at

You're right, preact/hooks is imported in two separate chunks. As you may see this app is running in a sub-folder `examples` which has its own package.json with preact while the root also has a package.json with preact. Don't know if it's a workspaces thing but I'll see how I can fix that. Thanks!

**Comment by JoviDeCroock** [comment]
No problem, I think there's a deduplicate option. If these are two separate build processes you should mark `preact` as a `peerDependency` (or mark it explicitly as an external) for the module being consumed (the library) and the app can provide `preact` in that case. That's how it's mostly done for libs

**Comment by urmik-zwt** [comment]
This has resolved my issue.  https://github.com/gatsbyjs/gatsby/pull/34337
