### ISSUE TITLE
TypeError: Cannot read properties of null (reading '__H') after Preact update

### ISSUE THREAD

**Issue by maltium** [preactjs/preact#3393]
We have a project that uses Preact that was mostly written when 10.0.0 was released. After updating to the latest Preact version, I'm getting a runtime error when mounting certain components.

![image](https://user-images.githubusercontent.com/4674453/148092539-283408ff-d32d-4b20-95f0-73508cfd8c44.png)

After some digging I realized that this is happening upon mounting components that use hooks. Moreover, I performed a bisect on Preact version dependencies and found out that it starts to break from Preact **10.5.6** upwards (all other previous versions are fine).

**To Reproduce**

Unfortunately it's hard to isolate into a smaller project since the Preact part is only a small part of the whole project.

For now I've converted the affected components into class components and got things working again on the latest Preact.

**Comment by JoviDeCroock** [comment]
Are you calling `render` from a different component by any chance 😅 tried  to analyze your stacktrace but not getting that much wiser from it, it's also the only hooks-related change as of that release. The only _other_ option is your bundler somehow duplicating code so the `options` calls aren't equal anymore.

We'll need a reproduction however if it's the former.

**Comment by maltium** [comment]
@JoviDeCroock it does seem to be the case of Preact being bundled twice, once for each library, but for some reason earlier versions didn't crash. So I'm closing this, thanks.

**Comment by jakeonfire** [comment]
also having this issue. looks like it’s trying to read at this line in the un-minified source: https://github.com/preactjs/preact/blob/10.10.3/hooks/src/index.js#L135
for whatever reason `currentComponent` isn’t set, which i think is supposed to happen in `_render`.

@JoviDeCroock what did you mean by:
> The only _other_ option is your bundler somehow duplicating code so the `options` calls aren't equal anymore.

what `options` calls?

**Comment by JoviDeCroock** [comment]
Your bundler might be duplicating the `preact` bundle which would lead to `currentComponent` not being set as it would use the `options` from the `preact` that isn't used to render your DOM

**Comment by tombohub** [comment]
And what should we do to stop this double bundle?

**Comment by super-kamil** [comment]
in my case, i had to switch from class component to functional component to get rid of this error

**Comment by rschristian** [comment]
You were probably misusing classes in some way, but would need a reproduction to offer any more guidance than that.

**Comment by matthias-ccri** [comment]
I observed this error happening because a component (functional component) was synchronously triggering a separate call to `preact.render` in another part of the codebase, triggered by code within a `useMemo`. 

Noting this for posterity to help avoid hours of painstaking debugging. `preact@10.11.2`

**Comment by marvinhagemeister** [comment]
@matthias-ccri Thanks for sharing your experience. If it isn't on your roadmap already I'd encourage upgrading to a newer version of Preact. Version `10.11.2` was released over 3 years ago at the time of this writing and a few bug fixes have happened since then.
