### ISSUE TITLE
Preact 11.x/main branch: ref callback not invoked on unmount if added after the initial render

### ISSUE THREAD

**Issue by mstarets** [preactjs/preact#3397]
I realize that I am logging an issue for an unreleased branch, but I wanted to give you heads up that ref handling is broken on the main branch.

If a VNode has no ref callback during the initial render, and the ref callback is provided during a subsequent VDom re-render, the ref callback is not invoked on unmount

1. Run the attached test-ref.html
2. Click 'Render with no ref' button
3. Click 'Render with ref' button. Note that the console message is logged.
4. Click 'Render empty'. Note that the console message is not logged

The expected behavior is that after step (3) a console message with null will appear.

It appears that childInternal does not get updated with ref after it is provided during a re-render
[test-ref.html.zip](https://github.com/preactjs/preact/files/7830144/test-ref.html.zip)

**Comment by JoviDeCroock** [comment]
Fixed in #3398
