### ISSUE TITLE
spellCheck property not working

### ISSUE THREAD

**Issue by pauhull** [preactjs/preact#3399]
I am using TypeScript to bundle JSX for use with preact. I noticed that the "spellCheck" property on input elements is not working correctly. `<input spellCheck={false} />` doesn't even render the property in the DOM, `<input spellCheck="false" />` works, but there is a TypeScript error because it doesn't fit the definition.

**Comment by developit** [comment]
@pauhull the correct property to use if you're setting a boolean value is `spellcheck` (lower-case):

```jsx
<input spellcheck={false} />
```

The `spellCheck` prop will always be set as an HTML attribute, and the HTML spellcheck attribute is a boolean attribute. I think we patch a few of these awkward behaviors, but this isn't one of them.

**Comment by JoviDeCroock** [comment]
@developit do we want to patch this in compat?

**Comment by martpet** [comment]
Only `spellcheck="false"` works, but it produces a Typescript error.

**Comment by rschristian** [comment]
@martpet `spellcheck={false}` works just fine from my tests. Can you share any more info?

**Comment by martpet** [comment]
In this example it doesn't work - https://github.com/martpet/hotspace/blob/main/components/RegForm.tsx#L18 ([preview here](https://hotspace-b8wdx0d746p4.deno.dev/)), though I'm using "preact-render-to-string", if it matters.

**Comment by rschristian** [comment]
Yes, rts matters a lot -- it's a different environment entirely.

Care to open [an issue](https://github.com/preactjs/preact-render-to-string)? I'll try to take a look at that later, schedule permitting.
