### ISSUE TITLE
Issue 3397 is not fully fixed: childInternal is not updated when ref transitions from non-null to null

### ISSUE THREAD

**Issue by mstarets** [preactjs/preact#3404]
Applies to: main branch (11.x) 

To reproduce, use test case included with issue 3397
1) Press 'Render with ref'. <span>Hello World with ref!</span> gets logged as expected
2) Press 'Render with no ref'. Nothing gets logged as expected
3) Press 'Render with ref'. Two messages logged: 'null' and '<span>Hello World with ref!</span>'

In (3), the expected behavior is that only one message should be logged (<span>Hello World with ref!</span>)

I think the issue is that childInternal.ref only gets updated when childVNode.ref is non-null. We should be updating it every time IMO, i.e. the assignment should happen before the 'if' block:

			childInternal.ref = childVNode.ref;
			if (childVNode.ref) {
				if (!refs) refs = [];
				// childInternal.ref = childVNode.ref;
				refs.push(
					oldVNodeRef,
					childVNode.ref,
					childInternal.flags & TYPE_COMPONENT
						? childInternal._component || newDom
						: newDom,
					childInternal
				);
			}

**Comment by JoviDeCroock** [comment]
Sorry about that, been a bit of a dummy in my previous solution 😅
