### ISSUE TITLE
Add file extension in source code

### ISSUE THREAD

**Issue by dmail** [preactjs/preact#3406]
**Describe the feature you'd love to see**

I would like to have file extension for every import in the preact source code. I am willing to open a pull request to do this.

Currently imports are omitting file extension, for example:

https://github.com/preactjs/preact/blob/4f08ae4d607964ae8222e910d3b209def75626b0/src/util.js#L1

With your approval I would like to open a pull request adding file extensions to these imports 

```diff
- import { EMPTY_ARR } from "./constants";
+ import { EMPTY_ARR } from "./constants.js";
```

**Additional context** 

Web browser, build tool, any tool could use preact source code without having to implement "magic extensions".

**Comment by JoviDeCroock** [comment]
Browser usage like this is already possible through tools like unpkg and skypack.

We can use something like:

```
import { h, render } from 'https://cdn.skypack.dev/preact@10.6.4';

render(h('p', {}, 'hello world'), document.body)
```

JSX can be made easier through tools like [htm](https://github.com/developit/htm)

**Comment by dmail** [comment]
The only thing preventing to use source files directly are the file extension so I was thinking it would be great to make it possible.
For example if I am developing something using preact and I have to disable sourcemap for some reason, I can still debug code inside preact as it would not be minified. Skypack would work but importing from url is not yet widely supported by build tools.

> we could change to another language and so on

I was expecting this motivation and I understand.
