### ISSUE TITLE
Hooks order in portals are wrong after 10.6.3

### ISSUE THREAD

**Issue by maddoger** [preactjs/preact#3415]
First of all, thank you for such a great library!

- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

In 10.6.3 (and 10.6.4) update hooks order was changed. Now it differs from React (inverted). But the main issue is hooks order with `createPortal`. `createPortal`-level hooks fire before portal's content hooks, which is wrong and a breaking change.

**To Reproduce**

The main concept is to have 2 useEffect hooks in a portal parent and child. Child hook is expected to be fired before the parent.

```jsx
const Modal = ({ children }) => {
  return createPortal(<div className="modal">{children}</div>, document.getElementById('modals'))
}

const ModalButton = () => {
  useEffect(() => {
    // set an event listener
  }, [])

  return <button>Action</button>
}

const ExampleModal = () => {
  useEffect(() => {
    // fire an event
  }, [])

  return (
    <Modal>
      <ModalButton />
    </Modal>
}
```

10.6.2 behaviour: https://codesandbox.io/s/hooks-order-preact-10-6-2-m90mp

Correct order as expected:
```
Child 1 
Child 2 
Child 3 
Parent 
Portal Child 1 
Portal Child 2 
Portal Child 3 
Portal Parent 
Portal
```

10.6.4 behaviour: https://codesandbox.io/s/hooks-order-preact-10-6-4-n4ny3

Unexpected order: 
```
Portal Child 3 
Portal Child 2 
Portal Child 1 
Child 3 
Child 2 
Child 1 
Portal 
Portal Parent 
Parent 
```

As you can see Portal useEffect fires earlier than direct child hook.

**Expected behavior**

Hooks order should be as expected from child to parent in all cases.

**Comment by JoviDeCroock** [comment]
The order you see in the "unexpected" order is actually the correct one as they go from bottom to top, which has bene a long standing bug, however the wrong child ordering is something we need to fix
