### ISSUE TITLE
Render not updating DOM more than once given replacement with differences.

### ISSUE THREAD

**Issue by papiro** [preactjs/preact#3419]
Scenario:
 
1. SSRing a trivial page (via `preact-render-to-string` in Deno).
2. A JS script with a single call to `hydrate` the `Index` component is requested, bundled by the server, and served.
3. The document `body` is hydrated given the `Index` component.
4. A websocket is opened with the server and when any changes are made to any `tsx` file, it sends a message to the client (browser).
5. The browser dynamically imports `Index` and the `render` function.
6. The `Index.tsx` file is requested, bundled with preact and with the `render` function re-exported from the bundle, and served.
7. The updated component is rendered to the document `body`.

The above `render` works one time. After that it no longer renders anything further. I am verifying that the component it is being supplied does indeed have the changes (minor changes, it doesn't work with even a single letter change in a string) and matches the exact structure of the currently mounted DOM (because it is the same component) but for some reason the DOM is not updating. If I do the same thing with `hydrate`, it _does_ update as many times as it is called, but only updates text nodes, as far as I can tell and does not render any HTML attribute changes. With `hydrate` being what it is though, this is not unexpected to me.

I would expect subsequent calls to `render` beyond the first to update the DOM tree of `body` with the changes made to that tree. 

Note that the `h` function is made available via `import` in the websocket client file. Thus, it is from the same "instance" of preact in all cases. I tried the above with re-exporting `h` from the bundle as I do with `render` with no luck.

**Comment by JoviDeCroock** [comment]
Hmm, I think it's worth  checking what the VNode produced in those subsequent renders has as `.__b`, my reasoning being that if we are in fact working with separate dynamic bundles of Preact then we'll always start recounting the vnode-identifier which means we'll end up [here](https://github.com/preactjs/preact/blob/master/src/diff/index.js#L141) it also makes sense that we wouldn't hit this for hydrate 😅

**Comment by papiro** [comment]
`.__b` is `0`, but it's also `0` on the first render. Interesting though, I can sort of see why I might be running into issues although I am admittedly a bit lost looking at the preact source code you referenced 😅. Anyways, would you think this issue of mine should be fixed if I just use one Preact bundle?

**Comment by papiro** [comment]
OMG... that fixed it. I literally just imported `render` along with `h` and used it instead of a per-bundle render. Cheers! Thank you so much!

**Comment by JoviDeCroock** [comment]
No problem, glad I could help out 🎉

**Comment by papiro** [comment]
@JoviDeCroock I am running into a similar issue now that I have just introduced the useState hook. I am assuming hooks need to come from the same bundle as `h` and `render`. Will that be the case in v11? I'm on the verge of rethinking my solution since it seems to be rife with pitfalls.

**Comment by JoviDeCroock** [comment]
Yes, the options hooks are a singleton tied to the render process.

**Comment by loubrevetti** [comment]
so i have both the render and h being imported form the same area, and yet re-renders our failing for me. h() reapply's and updates entity however when render() is fired it does not reflect updates on view

**Comment by marvinhagemeister** [comment]
@loubrevetti Sounds like you're experiencing something unrelated to this issue here. Can you file a new one and preferable add a reproduction case? It might be easier for us to understand what problem you're facing by seeing the code.
