### ISSUE TITLE
props attributes of child from toChildArray() are not found in typescript: Property 'myProp' does not exist on type '{ children: ComponentChildren; }'

### ISSUE THREAD

**Issue by nathanbrnrd** [preactjs/preact#3437]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
This is more a question for which I try to get an answer.

I added Typescript to my Preact project but I can't figure out why I get this Typescript error:

```tsx
interface Props {
  ...
}

interface State {
  ...
}

export default class MyComponent extends Component<Props, State> {

  constructor (props) {
    super(props);
  }
  
  render () {
    
    const { children } = this.props;
    const myComponentChildren = toChildArray(children) // return Array<VNode | string | number>
      .filter(isValidElement) // filters only VNodes
      .filter((child) => child.type === MyComponentChild); // filters only the wanted VNodes
      
     const modifiedChildren = myComponentChildren.map((child) => {
         const { childProp1 } = child.props; // ERROR: Property 'childProp1' does not exist on type '{ children: ComponentChildren; }'
         return /* Whatever you want */;
      })

     return (/* MyCompoenent markup  */)
  }
}
```

I tried to get rid of the error `Property 'childProp1' does not exist on type '{ children: ComponentChildren; }'` but can't figure out the problem.
`myComponentChildren` is of type `VNode<{}>[]` which is the expected type and the type definition of VNode in the source code is:

```tsx
export interface VNode<P = {}> {
	type: ComponentType<P> | string;
	props: P & { children: ComponentChildren };
	key: Key;
	/**
	 * ref is not guaranteed by React.ReactElement, for compatibility reasons
	 * with popular react libs we define it as optional too
	 */
	ref?: Ref<any> | null;
	/**
	 * The time this `vnode` started rendering. Will only be set when
	 * the devtools are attached.
	 * Default value: `0`
	 */
	startTime?: number;
	/**
	 * The time that the rendering of this `vnode` was completed. Will only be
	 * set when the devtools are attached.
	 * Default value: `-1`
	 */
	endTime?: number;
}
```

Whatever I do, the child props are not detected by typescript.
If I try to force the type another error appears:
`
myComponentChildren.map((child: VNode<ChildComponent>) => { ... }
`
errors to:
```
Argument of type '(child: VNode<ChildComponent>) => VNode<ChildComponent>' is not assignable to parameter of type '(value: VNode<{}>, index: number, array: VNode<{}>[]) => VNode<ChildComponent>'.
  Types of parameters 'child' and 'value' are incompatible.
    Type 'VNode<{}>' is not assignable to type 'VNode<ChildComponent>'.
      Types of property 'type' are incompatible.
        Type 'string | ComponentType<{}>' is not assignable to type 'string | ComponentType<ChildComponent>'.
           ....
```
So I assume that casting the type is not the solution.

I'd like to understand why, after retrieving the children with toChildArray(), typescript doesn't recognize the child props but keeps referring to `{ children: ComponentChildren; }` instead of `<P>` as in the type definition: `props: P & { children: ComponentChildren };`.
The type defintion found for `child.props` is only ` VNode<{}>.props: { children: ComponentChildren; }` and not `VNode<{}>.props: P & { children: ComponentChildren };`

I've been struggling with that for a few hours and I'd like to fill my lack of understanding on this point.
Thanks a lot.

_Maintainer edit: Fix formatting + typos by @marvinhagemeister_

**Comment by marvinhagemeister** [comment]
Honest answer is that TypeScript isn't good enough to infer the correct type here and needs a little help. As great as TS has become it still has noticeable limits on how well it can follow types through control flow. TS loosens the return type of the second filter call to just `VNode<{}>` which can match any vnode.

The best we can do for now is hint to TS via casting which type the filter call returns:

```ts
const myComponentChildren = toChildArray(children)
      .filter(isValidElement)
      .filter((child) => child.type === MyComponentChild) as VNode<Foo>[] // <-- cast here
```

**Comment by JoviDeCroock** [comment]
Closing this as stale and answered

**Comment by jrson83** [comment]
> Honest answer is that TypeScript isn't good enough to infer the correct type here and needs a little help. As great as TS has become it still has noticeable limits on how well it can follow types through control flow. TS loosens the return type of the second filter call to just `VNode<{}>` which can match any vnode.
> 
> The best we can do for now is hint to TS via casting which type the filter call returns:
> 
> ```ts
> const myComponentChildren = toChildArray(children)
>       .filter(isValidElement)
>       .filter((child) => child.type === MyComponentChild) as VNode<Foo>[] // <-- cast here
> ```

This example code is really important if you want to do without preact/compat or `React.children` and should be mentioned in the preact docs under `toChildArray`.

@marvinhagemeister would be great if you add this to the docs.
