### ISSUE TITLE
Aliasing via webpack or module-alias/register looks like no longer necessary

### ISSUE THREAD

**Issue by zsolt-dev** [preactjs/preact#3438]
Hello everyone,

Leaving this here, since I have spend many hours trying to make aliasing work (I have SSR...)

What worked for me, is to ignore the documentation (no aliasing in webpack) and just add this to your package.json:

```
    "react": "npm:@preact/compat@17.0.3",
    "react-dom": "npm:@preact/compat@17.0.3",
```

This will also solve the eslint warnings about importing package that is not installed etc.

Are there any downsides / potential issues with this approach? 

If no can I create a PR to update the documentation? Thank you

**Comment by JoviDeCroock** [comment]
PR welcome at https://github.com/preactjs/preact-www will close this issue here
