### ISSUE TITLE
Web Components Styling 

### ISSUE THREAD

**Issue by ArielGueta** [preactjs/preact#3439]
Hi,

I want to start using preact with web components but I can't find anything about styling and **shadow dom**. What options do we have to style a preact web component?

Thanks.

**Comment by ArielGueta** [comment]
I was referring to a Preact component that is turned into a web component with [preact-custom-element](https://github.com/preactjs/preact-custom-element).

```ts
import register from 'preact-custom-element';

const Greeting = ({ name = 'World' }) => (
  <p>Hello, {name}!</p>
);

register(Greeting, 'x-greeting', ['name']);
```

How do we add styles to this component?

**Comment by ArielGueta** [comment]
Cool. It works with state?

**Comment by marvinhagemeister** [comment]
@joshuabaker yup that's the way to style them. In the context of shadow DOM there are some additional CSS pseudo selectors that might be useful like [`:host`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host) or [`::slotted`](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted) which aren't available outside of that context.

Other styling solutions that are typically used won't work with web components and shadow DOM as the whole point of web components is encapsulating styles in the first place. Most other styling solutions work on a global level instead and therefore are not applied inside shadow DOM.

> Cool. It works with state?

I'm not sure I understand the question. CSS in itself doesn't have a notion of state, but you can leverage CSS Custom Properties (=variables) to pass information at runtime from JS to CSS.

**Comment by ArielGueta** [comment]
```ts
import register from 'preact-custom-element';

const Greeting = ({ name = 'World' }) => {
  const [color, setColor] = useState('green');

  return (
      <>
        <style>.myClass {color: {color} }</style>
        <p className={"myClass"}>Hello, {name}!</p>
      </>
);
}

register(Greeting, 'x-greeting', ['name']);
```

**Comment by joshuabaker** [comment]
Thanks, @marvinhagemeister. Good context for those happening upon this thread.

> Other styling solutions that are typically used won't work with web components and shadow DOM as the whole point of web components is encapsulating styles in the first place. Most other styling solutions work on a global level instead and therefore are not applied inside shadow DOM.

Have run into this already. For others, you can often `import styles from "./path/to/styles.css"` and put those directly into the `<style>` tag.

**Comment by ArielGueta** [comment]
Cool, Thanks!

**Comment by lgh06** [comment]
I am using vite & preact & preact-custom-element , strugling with style too.  
I am also a vue user, from vue world:  
as vue's vite plugin, it auto transform *.ce.vue (which means custom element) 's style part as shadow dom's inline css
https://github.com/vitejs/vite/blob/9a7b133d45979de0604b9507d87a2ffa2187a387/packages/plugin-vue/src/main.ts#L295  
https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue  

> The official SFC toolings support importing SFCs in "custom element mode" (requires @vitejs/plugin-vue@^1.4.0 or vue-loader@^16.5.0). An SFC loaded in custom element mode inlines its <style> tags as strings of CSS and exposes them under the component's styles option. This will be picked up by defineCustomElement and injected into the element's shadow root when instantiated.

> To opt-in to this mode, simply end your component file name with .ce.vue:


maybe preact can do sth like vue does.

**Comment by lgh06** [comment]
also, seems preact's custom elements are not rendered inside a shadow DOM, so it's inline style actually will pollute global css style

**Comment by BennyAlex** [comment]
Can you explain how to do that eg with parcel or vite ?

**Comment by HowieG** [comment]
@BennyAlex I just figured this out after struggling with it for a bit. Code below but feel free to message me for more detail.

`
import tailwindBase from "@/styles/style.css?inline";
import output from "@/styles/output.css?inline";

export default function MyComponent() {
...
  return (
    <>
      <style>
        {tailwindBase}
        {output}
      </style>
      <div...</div>
    </>
  );
}
`

`
import MyComponent from "./components/MyComponent";
import register from "preact-custom-element";

const a = register(MyComponent, "my-component", [], {
  shadow: true,
  // @ts-ignore
  mode: "closed",
});
const root = document.createElement("div");
const customElement = document.createElement("my-component");
root.appendChild(customElement);
document.body.appendChild(root);
`

NOTES:
Have to use ?inline after the name of the css file you're importing (specific to Vite)
tailwindBase and output are arbitrary names
I'm using shadow DOM with mode closed

The most important part:
output.css is the generated file with all the Tailwind styles I get from manually running `npx tailwindcss build -o output.css`
I'll need to figure out how to make this part of my build process so it's not manual, should be trivial if not already part of the build process but a lot of this is new to me.

**Comment by BennyAlex** [comment]
I think i am using open Mode with inline
