### ISSUE TITLE
The `<template>` tag does not have the correct `content` property

### ISSUE THREAD

**Issue by scottrippey** [preactjs/preact#3444]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When using Preact to render a `<template>` tag, the template's `content` property remains empty.

The native HTML parser appends all children to the template's `content` property (and the template's `children` remains empty).
But Preact creates DOM nodes by appending them to the template's `children`, so the `content` remains empty.

This also happens in React: https://github.com/facebook/react/issues/19932

**To Reproduce**

Codepen reproducing the issue:
https://codesandbox.io/s/nifty-kowalevski-5syzm?file=/src/index.js

1. Render a `<template>` tag using Preact; eg:
```
render(<template><h1>HELLO</h1></template>, document.getElementById("root"));
```
2. Inspect the rendered `<template>` element in dev tools
3. Using dev tools, check the template's "content" property: `$0.content.children.length` will be 0 (it should be 1).
4. Check the template's "children" property: `$0.children.length` will be 1 (it should be 0).
5. Check the template's innerHTML: `$0.innerHTML` will be an empty string (it should be `"<h1>HELLO</h1>"`)

**Comment by developit** [comment]
JSX is not HTML and Preact is not an HTML parser, so I'm not sure we actually want to attempt to emulate this behavior.

FWIW, reparenting to `.content` is relatively easy to implement in userland, and for non-JSX usage `<template>` is already supported via:

```js
render(<template textContent="<h1>HELLO</h1>" />, document.getElementById("root"));
```

**Comment by developit** [comment]
I poked around the React issue you linked (thanks!). The comments by @BasixKOR on their implementation PR are a good summary of my thoughts here: https://github.com/facebook/react/pull/23277#issuecomment-1036707365

**Comment by scottrippey** [comment]
The conclusions in the above link are totally understandable, and I agree with the choice not to fix this.  
My main purpose for this issue was to document the issue and workarounds.

**Comment by scottrippey** [comment]
For quick reference: the best workaround for this issue is to use `dangerouslySetInnerHTML` like so:
```jsx
<template dangerouslySetInnerHTML={{ __html: `
  <p> Some text </p>
` }} />
```
