### ISSUE TITLE
model-viewer web component missing attributes with preact

### ISSUE THREAD

**Issue by chaitanya-deep** [preactjs/preact#3447]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I'm trying to use the model-viewer web component in Preact.  
Some of the attributes(namely `exposure`, `alt`, `ar`, `src`) cannot be seen in the dom when I inspect element.  
Although the src seems to be set or the model wouldn't be visible, I'm unable to adjust the exposure of the model.  

**To Reproduce**
I made a codepen available here: https://codepen.io/cdeep/pen/ZEayBvZ?editors=0011
I confirmed that the exposure is working fine when set in a simple JS file without Preact and all the attributes are visible in inspect element.

**Expected behavior**
The exposure should work and the model will look darker.  

I'm sorry if I missed something but the documentation page on using web components in Preact doesn't seem to mention about attributes.

**Comment by marvinhagemeister** [comment]
Just checked and it seems like `<model-viewer>` expects a number instead of a string as the exposure value. Changing the value to a number makes the codepen work as expected.

```diff
   <model-viewer
-     exposure="0.1" // Wrong, type is string
+     exposure={0.1} // Correct, is a number
   />
```
