### ISSUE TITLE
does not provide an export named 'Component'

### ISSUE THREAD

**Issue by theLMGN** [preactjs/preact#3456]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Class components cannot be created because Preact does not have a Component class. 

**To Reproduce**
[Archive.zip](https://github.com/preactjs/preact/files/8098358/Archive.zip)

Attempt to import `Component` from the Preact JS file

**Expected behavior**
Preact exports a compnent class for use

**Comment by JoviDeCroock** [comment]
We export `Component` https://github.com/preactjs/preact/blob/master/src/index.js#L9

**Comment by JoviDeCroock** [comment]
Something like skypack https://www.skypack.dev/view/preact can help
