### ISSUE TITLE
Using urql's useMutation hook inside tests yields "TypeError: Cannot read properties of undefined (reading '__H')" error possibly because of currentComponent in getHookState is undefined

### ISSUE THREAD

**Issue by EmreErdogan** [preactjs/preact#3468]
**Describe the bug**
I'm getting `TypeError: Cannot read properties of undefined (reading '__H')` error on test environment when rendering a component which uses [urql](https://formidable.com/open-source/urql/)'s `useMutation` hook. The component renders without a problem on browser.

**Project structure**
[@preact/preset-vite](https://www.npmjs.com/package/@preact/preset-vite) + [@urql/preact](https://www.npmjs.com/package/@urql/preact) + [vitest](https://www.npmjs.com/package/vitest) + [@testing-library/preact](https://www.npmjs.com/package/@testing-library/preact)

**About the hook**

Link to [source code](https://github.com/FormidableLabs/urql/blob/8e92357c5d1a7db2e28827377bda4e781dcd8e3b/packages/preact-urql/src/hooks/useMutation.ts) of `useMutation`.

Please see the source code of the hook, it looks fine imho. I don't see any problem with its implementation.

As far as I could debug the problem and dug into the source code of Preact hooks, I saw that this line yields the error.

https://github.com/preactjs/preact/blob/d4a301391c21632828a1a9c19e08486a18075974/hooks/src/index.js#L107

Because, at the time of calling `getHookState` function, `currentComponent` variable is `undefined`. So, trying to access `currentComponent.__hooks` fails.

**Error output**
<pre>
 FAIL  src/Home.test.tsx > Home > should render Home
TypeError: Cannot read properties of undefined (reading '__H')
 ❯ m file:/Users/emrebaba/sandbox/preact/vite-preact-test/node_modules/preact/hooks/dist/hooks.mjs:1:151
 ❯ d file:/Users/emrebaba/sandbox/preact/vite-preact-test/node_modules/preact/hooks/dist/hooks.mjs:1:792
 ❯ s file:/Users/emrebaba/sandbox/preact/vite-preact-test/node_modules/preact/hooks/dist/hooks.mjs:1:628
 ❯ Module.useMutation file:/Users/emrebaba/sandbox/preact/vite-preact-test/node_modules/@urql/preact/dist/urql-preact.mjs:225:11
 ❯ d.Home [as constructor] src/Home.tsx:14:27
     12|
     13| export const Home = () => {
     14|   const [result, mutate] = useMutation(mutation);
       |                           ^
     15|
     16|   return <div>Hello world!</div>;
 ❯ d.M [as render] node_modules/preact/dist/preact.js:1:7851
 ❯ I node_modules/preact/dist/preact.js:1:5598
 ❯ m node_modules/preact/dist/preact.js:1:2096
 ❯ I node_modules/preact/dist/preact.js:1:5831
 ❯ m node_modules/preact/dist/preact.js:1:2096

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  1 failed | 1 passed (2)
      Time  2.18s (in thread 6ms, 39248.40%)
</pre>

**To Reproduce**
I created a simple repository to show the issue => https://github.com/EmreErdogan/vite-preact-test

1. Clone the repository (sorry, couldn't make the tests play nice with CodeSandbox/Stackblitz environments)
2. `cd` into it and run `npm install`
3. run `npm run test`

**Expected behavior**
Test should succeed.

**Comment by JoviDeCroock** [comment]
This isn't really a Preact issue, to make this work you would need to add something like this to the vite-config I assume

```js
  optimizeDeps: {
    include: ['preact/hooks', 'preact/compat', 'preact']
  },
```

This because we see a duplicate entry of `preact` in the bundle atm CC @marvinhagemeister should we also mirror this in the vite-preset

**Comment by EmreErdogan** [comment]
Hi @JoviDeCroock Thanks for your attention!

I tried your suggestion

```JavaScript
  optimizeDeps: {
    include: ['preact/hooks', 'preact/compat', 'preact']
  },
```

but I got the same error. As a side note I've managed to make the same setup work with`react` instead of `preact` without any problem. But I'd definitely stick with `preact` if I could find a solution for this issue.

Thanks again 😊

**Comment by JoviDeCroock** [comment]
I tried that solution with your reproduction and it worked perfectly 😅

**Comment by EmreErdogan** [comment]
Really appreciate that. I'd happily contribute to this if you direct me to the correct path 😬

**Comment by RapidOwl** [comment]
@EmreErdogan I just ran into this issue with Preact + Vitest and found this solution on a similar issue on the Vitest repo: https://github.com/vitest-dev/vitest/issues/1652#issuecomment-1195323396. Forcing the aliased module to load using `require` fixed it for me.

Stuck this at the top of my `vite.config.js`:
```
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
```

And my alias now looks like this:
```	
resolve: {
	alias: [
		{
			find: 'https://unpkg.com/preact@latest/hooks/dist/hooks.module.js?module',
			replacement: require.resolve('preact/hooks')
		}
	]
}
```

This is apparently due to the way Vite imports unprocessed modules. I don't really understand the CJS vs ESM madness and wish it wasn't a thing.

Weirdly, I only had this problem with `preact/hooks`. `htm/preact` worked fine without `require`.

**Comment by nakaakist** [comment]
In a project that aliases react to preact using `preact/compat`, I had to slightly modify @EmreErdogan's  solution.

At the top of `vite.config.js`:
```
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
```

Then, add the following inside the `defineConfig`:
```
resolve: {
  alias: [
    {
      find: 'react',
      replacement: require.resolve('preact/compat'),
    },
    // below is the same as https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact
    { find: 'react-dom/test-utils', replacement: 'preact/test-utils' },
    { find: 'react-dom', replacement: 'preact/compat' },
    { find: 'react/jsx-runtime', replacement: 'preact/jsx-runtime' },
  ],
}
```
