### ISSUE TITLE
Can't call "this.setState" on an unmounted component error.

### ISSUE THREAD

**Issue by oscartbeaumont** [preactjs/preact#3470]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
This bug looks to be the same as #2056 but on a version `10.6.6` of Preact.

I am creating a modal (using `@headlessui/react` and `preact/compat`) and when you press the modals close button the following warning appears in the console.

```
debug.js:379 Can't call "this.setState" on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

It should be noted that the component works as expected but this warning is definitely something I would like to get fixed. Given there is a similar issue mentioned above I am assuming this is a bug in Preact but it could definitely be an issue on my side so let me know if that is the case.

**To Reproduce**

I had some issues getting CodeSandbox working so I created a [Stackblitz](https://stackblitz.com).

1. Go to [demo application](https://stackblitz.com/edit/vitejs-vite-qkdrfy?file=src/App.jsx)
2. Right-click anywhere in the application preview and press "Inspect" and open the "Console" tab. You will probably want to clear it.
3. Click on 'Open Dialog' to show the modal
4. Observe no error in the console
5. Click on 'Got it, Thanks!' or press `Esc` on your keyboard to close the modal
6. Observe the error above in the console.

**Expected behavior**
No error should appear in the console.

**Comment by developit** [comment]
FWIW, this is likely the result of a callback execution ordering difference between React and Preact. We've worked to reduce these in version 11, but I'm quite certain this one is harmless.

The debug warning is mainly designed to help point out possible memory leaks, but in this case that's not the cause. I'm hopeful the change in 11 will remove whatever ordering issue is causing this specific warning, but for now I'd recommend ignoring it.

**Comment by Schlumpf9** [comment]
HeadlessUi also has this error with Preact:
https://github.com/tailwindlabs/headlessui/issues/1115  TypeError: Cannot read property '__H' of undefined
I would love to see this combination working...

**Comment by JoviDeCroock** [comment]
This is a bit off-topic, next seems to duplicate Preact in the bundles hence the hooks aren't working from time to time 😅 (I think especially in `getStaticProps` usage area's)

**Comment by ekwoka** [comment]
I believe this warning was removed in React. Dan Abrimov commented on the fact that the warning is a bit misleading and is very rarely an instance of actual memory leak, and the way people "get around" the warning doesn't actually accomplish anything aside from warning suppressing.

https://github.com/facebook/react/pull/22114#issuecomment-929191048

Could be worth just removing the warning like React did.

**Comment by developit** [comment]
@ekwoka ooh! Nice. Yes, I would be 100% in favor of removing this warning.
