### ISSUE TITLE
web components created by preact not renderer inside a shadow DOM

### ISSUE THREAD

**Issue by lgh06** [preactjs/preact#3485]
**Describe the feature you'd love to see**
as https://preactjs.com/guide/v10/web-components/ not clearly says preact's behavior, I am not sure it's a bug or it's a feature.  

![image](https://user-images.githubusercontent.com/1688639/159147643-54b1719c-405a-4388-a1ad-b8ea9b167a46.png)

when using preact & vite & preact-custom-element together, the element I created not rendered inside a shadow DOM.  
also, the CSS inside the component's <style> part pollute global style.

<details>
<summary>my main codes:</summary>
<pre>
import register from 'preact-custom-element';

import styles from "./greeting.css";
const Greeting = ({ name = 'World' }) => (
  <>
    <style>{styles}</style>
    <p>Hello, {name}! </p>
  </>
);
register(Greeting, 'x-greeting', ['name']);
</pre>
</details>

**Comment by lgh06** [comment]
compared to Vue Single File Component & its web component:  
![image](https://user-images.githubusercontent.com/1688639/159147860-246e75a7-176c-42a7-9a63-2d957d8547b4.png)

**Comment by lgh06** [comment]
my codes are all from https://stackblitz.com/?starters=vite and modified just a little, with preact's `preact-custom-element#register` and vue's `defineCustomElement`

**Comment by mikerob215** [comment]
@lgh06 The last parameter to the register function is a boolean to turn shadow dom on, its off by default

Should be:
`register(Greeting, 'x-greeting', ['name'], true);`

**Comment by lgh06** [comment]
from https://github.com/preactjs/preact-custom-element/blob/5790765ec0227ebb16add2f1469aef648e9f9f9e/src/index.js#L8 , we can see the fourth parameter , and it should be `{shadow: true}` , however both preact-custom-element 's REAME usages and https://preactjs.com/guide/v10/web-components/ are not mention this fourth parameter.

**Comment by JoviDeCroock** [comment]
Added to docs
