### ISSUE TITLE
Package.json export condition order leads to using CommonJS even if the `import` condition is set

### ISSUE THREAD

**Issue by lemonmade** [preactjs/preact#3488]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

As noted on [Node's modules page](https://nodejs.org/api/packages.html#conditional-exports), the order of conditional exports (the `"exports"` key in package.json) matters — Node will choose the first thing that matches a condition it supports by going down the list. Most build tools, including rollup, have a way of supporting the same behaviour.

The current package.json lists the ESM (`import`) condition for the package root before the CommonJS (`require`) one, which means you will get the `import` version if your runtime supports both conditions: https://github.com/preactjs/preact/blob/1bbd687c13c1fd16f0d6393e79ea6232f55fbec4/package.json#L16-L17

However, all the other subpath exports list the `require` version first, meaning it is preferred in those cases: https://github.com/preactjs/preact/blob/1bbd687c13c1fd16f0d6393e79ea6232f55fbec4/package.json#L22-L23

**Expected behavior**

In general, I think folks have landed on putting the `import` version first — this ensures you get the "modern" version for environments that support both, which will include better tree-shakability in build tools like Rollup. Node also seems to suggest to put the `import` condition first, as it shows this in its examples. Would it be possible to have Preact consistently favour this export condition by listing it before `require`?

**Comment by developit** [comment]
Strong +1 to this. I seem to recall we had some strange reason to do this, but it doesn't seem to make sense.
