### ISSUE TITLE
Preact v10.7.0 breaks hooks inspection in preact-devtools

### ISSUE THREAD

**Issue by oliverfindl** [preactjs/preact#3504]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug:**
Upgrade to v10.7.0 breaks hooks inspection in [preact-devtools](https://github.com/preactjs/preact-devtools). Tested with Chrome and Firefox extensions.

Error message (v10.7.0):
`Please upgrade to Preact >=10.4.1 to enable hooks inspection.`

**To Reproduce:**
Upgrade to v10.7.0 and check dev-tools. Then downgrade back to v10.6.6 and check dev-tools again.
Please close and re-open dev-tools between different versions.

**Expected behavior:**
Hooks inspection should work.

**Comment by JoviDeCroock** [comment]
Will be fixed by https://github.com/preactjs/preact-devtools/pull/335
