### ISSUE TITLE
`Error: Cancel rendering route` and `TypeError: Cannot read properties of null (reading '__H')` when using Next.js Router

### ISSUE THREAD

**Issue by laymonage** [preactjs/preact#3512]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Using the latest Preact (10.7.1) and Next.js (12.1.4) **and React 18 installed**, changing the route (e.g. calling `Router.replace`, `Router.push`) will throw three errors:

- Error: Cancel rendering route
- TypeError: Cannot read properties of null (reading '__H')
- TypeError: Cannot read properties of null (reading '__H')

Next.js requires React to be installed (otherwise the server won't start), that's why I have it installed. With React 17, it works fine.

**To Reproduce**
Link: https://codesandbox.io/s/dank-frost-eeb42x
Also on GitHub: https://github.com/laymonage/repro-preact-nextjs-router-issue

1. Go to https://codesandbox.io/s/dank-frost-eeb42x
2. Click on the "Demonstrate the issue" button
3. See error

**Expected behavior**
No errors

**Notes**
I don't know if this issue should be fixed in Next.js or Preact.

Possibly related: #3393, #3261

**Comment by JoviDeCroock** [comment]
This might be a Next.JS thing, we have already had a few issues that were mentioned in #3393 that is on their side with regards to duplicated Preact bundles etc. `TypeError: Cannot read properties of null (reading '__H')` typically points at a duplicated bundle or one not getting called 😅 

Generally however, we advise to replace `react` as a dep with `@preact/compat` like we examplified in the next-plugin https://github.com/preactjs/next-plugin-preact

**Comment by laymonage** [comment]
Thanks! I just remembered that I used to do it that way, but then I encountered the same problem as https://github.com/preactjs/next-plugin-preact/issues/53. It's fixed if `esmExternals` is `false`, but I'm not sure if that should be necessary.

`esmExternals: false` is not needed if I install React 17 instead of using `@preact/compat`.

**Comment by liby** [comment]
Any progress on that?
