### ISSUE TITLE
A TypeScript example for Webpack + Babel toolchain please?

### ISSUE THREAD

**Issue by OnkelTem** [preactjs/preact#3538]
It would be really great to have a simple working example of a TypeScript project with standard tooling: **Webpack, Babel  and TypeScript.**

I passed through the tutorial and read the docs, but I cannot make a simple hello world app working.

My source code is:

```ts
import { h, render, createElement } from "preact";
function vdom() {
  return <p class="big">Hello World!</p>;
}
render(vdom, document.body);
```

and I get an error:

```
Uncaught TypeError: p is undefined
```
![image](https://user-images.githubusercontent.com/114060/167439560-efa245b8-0eac-4652-b627-eea9ff07aab4.png)

Why is this happening? 

My `tsconfig.json` for **TypeScript 4.6.2**:
```json
{
  "compilerOptions": {
    "lib": ["es2017", "dom", "dom.iterable"],
    "module": "commonjs",
    "target": "es2021",

    // I'm really not sure in the following three lines as the documentation seems to be vague, see the picture below
    "jsx": "preserve",
    "jsxFragmentFactory": "Fragment", 
    "jsxImportSource": "preact",

    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src"]
}
```

My `webpack.config.js` related lines:
```js
rules: [
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: [
              "@babel/preset-env",
              ["@babel/preset-typescript", { jsxPragma: "h" }],
            ],
            plugins: [
              "@babel/transform-runtime",
              ["@babel/plugin-transform-react-jsx", { pragma: "h" }],
            ],
          },
        },
      },
    ],
```

### What should be the correct content of `tsconfig.json`?

The documentation is not specific enough about it:
![image](https://user-images.githubusercontent.com/114060/167438680-2c9aebca-d4c7-4ee4-87fe-8ae56fe367bb.png)

**Comment by OnkelTem** [comment]
Answering to myself.

My main problem was that I simply missed the call signature of the `vdom` function in:

```ts
render(vdom, document.body);
```

which must be instead:
```ts
render(vdom(), document.body);
```

So it's not a "feature"  request anymore, although an example would still be welcome. I think I can make one and share it as a repo.

Here only question is left really. It is: **Do I really need to import those unused imports h and createElement from preact?**.

**Comment by wahur666** [comment]
To answer your question, why you need the h/createElement, it that JSX is not standard JS. When the Typescript compiler or Babel will transform the code, it will go through the JSX and apply the following translation:

Input:

```jsx
function vdom() {
  return <p class="big">Hello World!</p>;
}
```

Result:

```js
function vdom() {
  return h("p", {
    class: "big"
  }, "Hello World!");
}
```

As you see, there is no magic here, just a simple function call, JSX is just an illusion. 

For you exact problem, I would not recommend, calling the component function directly, if you can use JSX/TSX then call it like:

```jsx
render( <vdom />, parent)
```

Or if you constrained, that the entry point is TS, use the **h** function

```js
render( h(vdom, {some: prop}, parent)
```

**Comment by rschristian** [comment]
Closing as it seems the issue has been answered.
