### ISSUE TITLE
Not sure how to use 3rd party libraries with preact/compat

### ISSUE THREAD

**Issue by backmeupplz** [preactjs/preact#3547]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
So I'm trying to get rid of `@types/react` so that the code fully relies on `preact` and `preact/compat`. For some reason I get the following errors:

```
'ReactTooltip' cannot be used as a JSX component.
  Its instance type 'ReactTooltip' is not a valid JSX element.
    Type 'ReactTooltip' is missing the following properties from type 'Component<any, any>': state, props, context, setState, and 2 more.
```
```
JSX element class does not support attributes because it does not have a 'props' property.
```

I use vite as my bundler, which uses rollup. It starts fine without any issues with `yarn start`, seems like only typescript is upset with this behavior (which in turn breaks the bundling with `yarn build`).

It seems like most libraries work fine, except for these two. They are declared in `node_modules` like `class SimpleBar extends React.Component<SimpleBar.Props>`. Which should be fine as I'm using `preact/compat`? Maybe my tsconfig is somehow messed up? I'm currently working in this repo: https://github.com/BigWhaleLabs/seal-cred-frontend — but it's a bit tedious to set it up so I provide it here just as a reference to my config files.

I'm sure I'm doing something wrong but I can't put my finger on it. Are there any extra steps to achieve `react/compat` working with 3rd party components from npm except for modifying tsconfig as noted in here: https://preactjs.com/guide/v10/typescript?

**To Reproduce**
Try using https://github.com/wwayne/react-tooltip or https://github.com/grsmto/simplebar.

**Expected behavior**
No error should be shown?

**Screenshots**
<img width="893" alt="Screen Shot 2022-05-19 at 4 23 30 PM" src="https://user-images.githubusercontent.com/3192028/169420183-80647028-dcf9-4e7f-8494-e4bc70bba589.png">
<img width="948" alt="Screen Shot 2022-05-19 at 4 23 43 PM" src="https://user-images.githubusercontent.com/3192028/169420190-45ccd34e-85d4-4b11-8ca9-7e47d3391a1b.png">

**Comment by backmeupplz** [comment]
Nvm, fixed it like this: https://github.com/BigWhaleLabs/seal-cred-frontend/pull/185/commits/7b2e517102bd0f9dc24cd65a5f1f6c13c0dfa4fc. Seems like a thing that should be applied as a part of the preact typescript setup?

**Comment by backmeupplz** [comment]
Also, the docs fix is already suggested in #2748

**Comment by rschristian** [comment]
I agree, I think that's a fair addition. More and more things are seemingly resolved by adding `paths` nowadays.

**Comment by rschristian** [comment]
Created https://github.com/preactjs/preact-www/pull/850 for this.

**Comment by Kazumz** [comment]
Sorry @JoviDeCroock, not sure what you mean.

Are you saying that you're closing this issue due to a fix, but the PnP mode discussion is a separate issue? 

If so, could you link a thread to the PnP issue here please.

**Comment by JoviDeCroock** [comment]
Do you want us to create an issue on yarn for you?

**Comment by Kazumz** [comment]
@JoviDeCroock What makes you think this is a yarn issue?

**Comment by JoviDeCroock** [comment]
I don't know what you are trying to get at but it seems like this issue generally consisted of the fix outlined in documentation and the linked issue. If there are issues with how certain resolutions work we'll need an elaborate explanation as to why and what's going wrong. If yarn PnP does not create symlinks the author must be suggesting other things or would need other paths, sorry if I am misunderstanding what you are trying to get at but is the issue posted by the OP solved or? 😅
