### ISSUE TITLE
[Custom Renderer] Provide some APIs to enable custom renderers.

### ISSUE THREAD

**Issue by ZhUyU1997** [preactjs/preact#3549]
I am trying to port preact to a custom platform based on `quickjs` recently. 
Preact written by javascript is hard to do it. I don't know what HTML feature preact depends on.
How about providing some APIs to enable custom renderers?
As far as I know, React, Vue, and Solid, all provide related APIs.

React： https://github.com/facebook/react/tree/main/packages/react-reconciler
Vue: https://vuejs.org/api/custom-renderer.html
Solid: https://github.com/solidjs/solid/releases/tag/v1.2.0

**Comment by developit** [comment]
You could provide a minimal DOM implementation to Preact based on the code from undom:
https://github.com/developit/undom

**Comment by ZhUyU1997** [comment]
> You could provide a minimal DOM implementation to Preact based on the code from undom: https://github.com/developit/undom

Thanks. It is very useful
