### ISSUE TITLE
Automate release of pre-built modules to ease re-use

### ISSUE THREAD

**Issue by amirouche** [preactjs/preact#3556]
I would like to see an archive that contains both source and `preact.module.js` that is automated with github actions upon tagging the primary release branch in preact project [releases](https://github.com/preactjs/preact/releases).

**Additional context (optional)**

`preactjs.js` is the best tool (so far) to bind in other languages. I use it at (direct link the javascript source folder): https://git.sr.ht/~amirouche/python-babelia/tree/main/item/hyperdev/static and in several private Scheme project.

Thanks in advance!

**Comment by JoviDeCroock** [comment]
Do you mean that currently the source files are missing? We have an automated step that attaches our built files to the tag relevant tar: https://github.com/preactjs/preact/releases/tag/10.7.2 do you mean that one is missing the source files?

**Comment by JoviDeCroock** [comment]
Something went wrong while publishing 10.7.3 normally it's in there 😅 we have another one about state settling ready for in a few days so that should be sorted then
