### ISSUE TITLE
Uncaught TypeError: startTransition is not a function

### ISSUE THREAD

**Issue by liby** [preactjs/preact#3557]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
This is a bug related to Preact with Next.js. When an exception is throw in the render phase of a clientside rendered page the Next.JS pages/_error fails to render.

Using the latest Preact@10.7.3 and Next.js@12.1.6 and React@18.1 installed, changing the route (e.g. calling Router.replace, Router.push) will throw three errors(Local development):
  1. Error: Cancel rendering route
  2. Uncaught (in promise) TypeError: startTransition is not a function
  3. Uncaught TypeError: startTransition is not a function
	<img width="1052" alt="image" src="https://user-images.githubusercontent.com/38807139/172140871-3eb70fd2-2004-4093-8187-80ff390db98c.png">

**To Reproduce**

- [Demo](https://blog-liby.vercel.app)
- [Repo](https://github.com/liby/blog/tree/main)

1. Go to [Demo](https://blog-liby.vercel.app)
2. Open DevTools
3. Click on any of the post links,  page does not navigate to the specified page
	<img width="1044" alt="image" src="https://user-images.githubusercontent.com/38807139/172139179-2cf2aa64-13bd-4745-9531-edab73d77937.png">

**Expected behavior**

The page navigates to the specified link as expected.

**Notes**

> What is the reason for having React 18 installed alongside Preact?
>
> I use React while developing and only replace it with Preact in production.

The same as mentioned in #3233, even if I add `pages/failing` and `pages/_error`, when an exception is throw in the render phase of a client-side rendered page the Next.js `pages/_error` fails to render.

Possibly related: #3512, #3502, #3233, https://github.com/preactjs/next-plugin-preact/issues/53

**Comment by wesley0609** [comment]
I have the same issue.

**Comment by JLucasCAmorim** [comment]
Same here, any updates on this?

**Comment by jsphkhan** [comment]
The same issue when enabling preact via next config file

```js
webpack: (config, { dev, isServer }) => {
    if (!dev && !isServer) {
      Object.assign(config.resolve.alias, {
        react: 'preact/compat',
        'react-dom/test-utils': 'preact/test-utils',
        'react-dom': 'preact/compat',
      });
    }

    return config;
```

However, I do not see this issue if I use the preact plugin - https://www.npmjs.com/package/next-plugin-preact
