### ISSUE TITLE
New state-settling logic causes hooks + cleanup to fire unexpectedly

### ISSUE THREAD

**Issue by jbt** [preactjs/preact#3569]
**Describe the bug**

After updating to the latest version of Preact (10.8.0) I've noticed bugs occurring that indicate a hook's cleanup is running unexpectedly.

In particular, under certain circumstances, a `useEffect(() => { ... }, [])` (which I commonly use as a "on mount/unmount" hook) is triggering even when the component isn't being mounted/unmounted

**To Reproduce**

Here's an example: https://codesandbox.io/s/modest-ritchie-musy7y?file=/index.js

Operative part: 

```js
function Foo() {
  const [a, setA] = useState(false);

  useEffect(() => {
    return () => {
      alert("This should only happen when component is unmounted?");
    };
  }, []);

  setA(false);

  return <button onClick={() => setA(true)}>Hi</button>;
}
```

1. Go to the codesandbox above
2. Click on "hi"
3. Alert pops up.

**Expected behavior**

Unless I've misunderstood hooks behaviour, the cleanup for a `useEffect` with empty arguments should only ever be called when the component is being unmounted. And since no unmounting is happening in the above example, the alert should never fire.

I've confirmed that this behaviour is fine with Preact up to and including 10.7.3 and only started appearing in 10.8.0

**Comment by JoviDeCroock** [comment]
Thank you for testing that @jbt I was about to try that ❤️

**Comment by jbt** [comment]
Great stuff! Can confirm that 10.8.1 fixes all the various derived issues I was seeing, nice one 🎉
