### ISSUE TITLE
setState() causes endless re-renders and page hangs

### ISSUE THREAD

**Issue by otoomey** [preactjs/preact#3605]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
The following setup worked yesterday but causes infinite re-renders today in both firefox and edge. Page bootstraps once, then re-renders endlessly until firefox asks to force-stop the page.

**To Reproduce**
I was unable to reproduce the issue in codepen, I believe it may be a bug in the current preact lib available on unpkg.com. Here is a simple one file demo:

```html
<!DOCTYPE html>
<html>

<body>
    <script type="module">
        import { h, Component, render } from 'https://unpkg.com/preact?module';
        import htm from 'https://unpkg.com/htm?module';

        // Initialize htm with Preact
        const html = htm.bind(h);

        function component(props) {
            // this.setState({ width: 8, height: 8 }) // <--- uncomment this line
            console.log("render!")
            return html`
                <div class="editor">
                   <h1>Foo</h1>
                </div>
            `;
        }

        console.log("bootstrap!")
        const app = html`<${component}/>`;
        render(app, document.body);
    </script>
</body>

</html>
```

Uncomment the indicated line to observe behaviour. Open console to see "render!" messages.

**Expected behavior**
The page should render normally, without causing the page to hang.

**Comment by JoviDeCroock** [comment]
That is intended to infinitely loop, you are setting state with a different object every render meaning we should rerender.

**Comment by otoomey** [comment]
... I managed to mix up `useState` and `setState` . 🤦
