### ISSUE TITLE
useMemo factory being called more frequently / unnecessarily

### ISSUE THREAD

**Issue by wnayes** [preactjs/preact#3616]
There seems to have been a change with useMemo around the 10.8.1 release, I believe starting with PR #3567.

When a state updater is called during render, and a useMemo hook is present, the memo "factory" function will get called more than once. The prior behavior was that we would reuse the memoed value from the first render.

I believe this is because the code now stores the computed value in `_pendingValue` and doesn't copy it over to `_value` until a later point. Renders triggered by a state updater must be happening quicker than this copy over, causing the work to be lost.

**To Reproduce**

https://codesandbox.io/s/goofy-cherry-emgdox?file=/index.js

A demo component illustrates the behavior.

```ts
let idState = 0;
function createId() {
  return "_id" + ++idState;
}

const TestComp = () => {
  const id = useMemo(() => createId(), []);
  const [stateId, setStateId] = useState("");

  if (!stateId) {
    setStateId(id);
  }
  return <div>Last id from memo: {id}</div>;
};

render(<TestComp />, window.root);
```

The browser displays "Last id from memo: _id2" indicating that `createId` (the function being memoized) was called twice.

**Expected behavior**
I would expect the memoized computations not to be lost between renders, even if they are happening in quick succession.

**Comment by wnayes** [comment]
Got it - just checked React as well and the behavior is the same there. It was kind of a surprising change for a minor release (broke some tests doing re-renders like this). But as long as it is expected, I don't think a change is needed then. Thanks!

**Comment by JoviDeCroock** [comment]
I have gone back and forth on this being a minor but in general what played most part in this is that it would only result in weird behavior for side-effects/inpure memoization.

i.e. if we were to do `useState(createId)` this would not have been an issue or similarly if we defer setting the stateId to an effect/... as it kind off is a side-effect which mutates global state.

I can however relate that in practice this isn't the most fun answer to get and I apologize for any inconvenience this caused you
