### ISSUE TITLE
Types for props in h / createElement function doesn't allow ref

### ISSUE THREAD

**Issue by oliverfindl** [preactjs/preact#3618]
- [ ] Check if updating to the latest Preact version resolves the issue.

**Describe the bug:**
`h` / `createElement` function doesn't allow `ref` in `props`, although code compiles successfully.

**To Reproduce:**
```jsx
// DummyComponent.tsx

import { FunctionalComponent, h } from "preact";
import { useRef } from "preact/hooks";

const DummyComponent: FunctionalComponent = ({ children }) => {
    const node = useRef<HTMLDivElement>();
    return h("div", { ref: node }, children);
});

export default DummyComponent;
```

Error in VS Code:
`Type 'MutableRef<HTMLDivElement | undefined>' is not assignable to type '(Ref<EventTarget> & Ref<SVGElement>) | undefined'. `

**Expected behavior:**
No errors.

**Comment by mikerob215** [comment]
I believe `createRef` is for classes, `useRef` is what you need in a functional component. The [hooks docs](https://preactjs.com/guide/v10/hooks#useref) mention making sure not to mix up `createRef` and `useRef` but maybe the ref docs could too.

**Comment by oliverfindl** [comment]
Hello,

sorry, this was an oversight at my end. Updated my first post to `useRef` hook. Unfortunately, it does not solve this issue.

Error:
`Type 'MutableRef<HTMLDivElement | undefined>' is not assignable to type '(Ref<EventTarget> & Ref<SVGElement>) | undefined'. `

Thanks.
