### ISSUE TITLE
v10.10.0 broke cypress test

### ISSUE THREAD

**Issue by corinnaSchultz** [preactjs/preact#3620]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I have a cypress test that check that closing a modal results in the focus being set on the button that triggered the modal.  The test worked with preact version 10.9.0, and broke when I upgraded to preact 10.10.0.  

The Cypress tests worked with version 10.0.2, and 10.3.0. 

Please advise if there's something I need to modify in my code or my test in order to remain compatible with preact. Or even some hints of things to try would be useful.

**To Reproduce**

I'm not sure I can create a simple reproducible test case.  I'm mostly looking for advice here, since I'm not sure this is actually a preact bug.

I disable animation styles  before each test by injecting this CSS:

```
'*, ::after, ::before { transition-duration: 0s !important; animation-name: none !important; }'
```

The cypress commands I was using are:

```
 cy.get('[data-cy=close-button]').click()
 cy.get('[data-cy=modal-box]').should('not.exist')
 cy.get('[data-cy=footer-clear-button]').should('have.focus')
```

The code that is triggered by clicking the Close button looks like this:

```
    // need to wait for everything to load so wrapping it in requestAnimationFrame
    window.requestAnimationFrame(() => {
      clearModalTrigger.current.shadowRoot.querySelector('button').focus()
    })
```

And the modal popup button (clearModalTrigger) is a web component, which is why we go into the shadowRoot to set the focus.

**Expected behavior**
The Cypress expectation that the button has the focus should still be true, and my test should pass.

**Comment by JoviDeCroock** [comment]
My first question would be does it still work in the UI? Generally the only cause I can see is the way we switched our renderer to be tick-based rather than microtick based. i.e. what happens if that `requestAnimationFrame` is a `setTimeout`? I imagine you do some stuff that trigger a render in the above so the paint-event might not be active yet in this scenario. I hope this helps

**Comment by corinnaSchultz** [comment]
@JoviDeCroock  Yes, I confirmed that it still works live in the browser (I forgot to mention, all this testing refers to Chrome, both manually and Cypress) before I wrote this.  That's why I was pulling out my hair trying to track this down. :D

ok, thanks for your response. I'll look deeper into this, and post a new issue here if I can definitely trace this back to a preact issue. 

If anyone else is reading this and has a similar problem, please reach out!

**Comment by JoviDeCroock** [comment]
Well I did mention the solution 😅 

>  Generally the only cause I can see is the way we switched our renderer to be tick-based rather than microtick based (this because it solves a bunch of issues with how events work in Preact)

```js
    window.requestAnimationFrame(() => {
      clearModalTrigger.current.shadowRoot.querySelector('button').focus()
    })

   // Try this instead
       window.setTimeout(() => {
      clearModalTrigger.current.shadowRoot.querySelector('button').focus()
    })
```

**Comment by corinnaSchultz** [comment]
I finally had a some time today to circle back and track this down.  Use setTimeout() resolved the issue, cy.wait() didn't. 

I also had a mobx function that was calling focus() on an element, and I had to wrap that call in a setTimeout, too.

Thanks for your help, @JoviDeCroock :)
