### ISSUE TITLE
Cannot set properties of null (setting '__h') error when suspending the entire app

### ISSUE THREAD

**Issue by theninthsky** [preactjs/preact#3642]
Preact version: `10.10.0` (happens in earlier versions aswell).

**Bug Description**

When wrapping the entire `<App>` with Suspense, I get the following error:

```
Uncaught TypeError: Cannot set properties of null (setting '__h')
    at M
```
And the app breaks after navigating to another page (it becomes unresponsive).

This **does not** happen if I only wrap the `<Routes>` component with Suspense.

**To Reproduce**

1. Clone my repo: https://github.com/theninthsky/client-side-rendering/tree/preact.
2. Execute `npm i` and `npm start`.
3. Refresh the page a few times until this error shows (it's inconsistent, as if it depends on script loading times or something).

You can even visit the preview deploy here: https://70f42741.client-side-rendering.pages.dev

**Expected behavior**
No error should be thrown and the app should be responsive.

I'd like to add that I really love Preact and its great compatibility with React codebase, and that the ability to suspend the entire app is very important to me (in order to prevent when I call _[Sequenced Rendering](https://github.com/theninthsky/client-side-rendering/tree/preact#preventing-sequenced-rendering))_.

**Comment by theninthsky** [comment]
@JoviDeCroock 
Thanks for the very quick fix!
However, I now get another error, will be opening a new issue soon.

**Comment by JoviDeCroock** [comment]
Heh, I even thought about you when making #3645 but then completely forgot to guard for that
