### ISSUE TITLE
app.js:16 Uncaught TypeError: Cannot read properties of undefined (reading '__H')

### ISSUE THREAD

**Issue by gideonmkp98** [preactjs/preact#3658]
I've got a problem when building Preact with gulp.

 After building the project my console gives me this error: "app.js:16 Uncaught TypeError: Cannot read properties of undefined (reading '__H')"

![image](https://user-images.githubusercontent.com/48789974/183705303-cd080de0-61a9-49f3-8c67-5842e8862b0b.png)

And this is the code where import the useState

`
import { useState } from 'preact/compat';

const [count, setCount] = useState(0);

const increment = () => setCount(count + 1);

export default () => (
    <div>
      <button onClick={increment}>{count}</button>
    </div>
);
`

and this is the function in my gulpfile.js: 

![image](https://user-images.githubusercontent.com/48789974/183705659-998afc6e-a32d-488a-aa8d-4ba0c7fd716e.png)

does someone know how i can fix this problem? or are there any recommendations as alternative for gulp?

**Comment by JoviDeCroock** [comment]
You are using different aliases 😅 your alias goes to `preact-compat` which probably menas that you are working with conflicting versions of preact

**Comment by gideonmkp98** [comment]
> You are using different aliases 😅 your alias goes to `preact-compat` which probably means that you are working with conflicting versions of preact

What alias do i have to use to get it working ?

**Comment by JoviDeCroock** [comment]
The same one as your code there `preact/compat`, `preact-compat` is used with v8. You can read about the aliases in our [docs](https://preactjs.com/guide/v10/switching-to-preact/)

**Comment by gideonmkp98** [comment]
> The same one as your code there `preact/compat`, `preact-compat` is used with v8. You can read about the aliases in our [docs](https://preactjs.com/guide/v10/switching-to-preact/)

Still the same error as before after changing it :(

![image](https://user-images.githubusercontent.com/48789974/183708483-b2b88e6d-167e-4f02-b80a-84e9cc14ae17.png)

**Comment by JoviDeCroock** [comment]
I mean, let's maybe first get our details sorted. Did this work before, or what did you have before? Is this a fresh project, ...?

Generally this error happens when your bundler is generating duplicate versions of libraries.

**Comment by gideonmkp98** [comment]
> 

Yeah it's a fresh project..

https://github.com/gideonmkp98/preact-test this is the link to my repo maybe you can see something that's weird about it

**Comment by nmocruz** [comment]
this error seems to occur on a few different bundlers. I checked my bundle on webpack and I can be wrong but it doesn't generate a duplicate version, maybe it resolve wrongly

**Comment by dmail** [comment]
Got the same issue when updating preact from `10.0.0` to `10.0.6`.
I end up with two copies of preact in the node_modules, see output of `npm explain` below

```console
npm explain preact     
preact@10.10.6
node_modules/preact
  preact@"10.10.6" from the root project
  peer preact@"^10.0.0" from @prefresh/core@1.3.4
```

**Comment by dmail** [comment]
This suggest `@prefresh/core@1.3.4` depends on preact "10.0.0" but I have opened the package.json and found the following:

```json

  "peerDependencies": {
    "preact": "^10.0.0"
  }
```

By the way I have to reinstall from scratch with the following

```console
rm -rf node_modules
rm package-lock.json
npm cache clean --force
npm install
```

The issue persists

**Comment by dmail** [comment]
Found a fix for my situation: use an other browser.
Which makes me realize it was due to browser cache so I reloaded the page with cache disabled in chrome devtools. Now the issue is gone.

**Comment by rschristian** [comment]
This is not a valid use of hooks. All hooks need to be called from within components:

```diff
import { useState } from 'preact/compat';

-const [count, setCount] = useState(0);

-const increment = () => setCount(count + 1);

export default () => {
+ const [count, setCount] = useState(0);
+ const increment = () => setCount(count + 1);

  return (
    <div>
      <button onClick={increment}>{count}</button>
    </div>
  )
}
```
