### ISSUE TITLE
unable to import Preact via UNPKG CDN

### ISSUE THREAD

**Issue by trusktr** [preactjs/preact#3665]
Solid.js borrowed the filesystem pattern Preact uses with sub folders having package.json files (sub-packages of sorts). This format causes some ESM CDNs that don't fully support edge cases of Node ESM format to fail at making these libraries importable.

More details, discussion, and examples of both libraries and multiple CDNs in this issue:

https://github.com/solidjs/solid/issues/1159

**Comment by JoviDeCroock** [comment]
Not sure whether you read it but we have a pinned issue around this, thought I would mention that to be sure 😅 https://github.com/preactjs/preact/issues/2564#issuecomment-636201423

**Comment by developit** [comment]
Afaik the only CDNs that don't work right now are unpkg and jsdelivr.

**Comment by ekwoka** [comment]
just use `https://esm.sh/v90/preact`

**Comment by JoviDeCroock** [comment]
Will close this for now
