### ISSUE TITLE
Types for FunctionalComponent doesn't allow returning just children

### ISSUE THREAD

**Issue by oliverfindl** [preactjs/preact#3672]
- [ ] Check if updating to the latest Preact version resolves the issue.

**Describe the bug:**
`FunctionalComponent` doesn't allow returning just `children`, although code compiles successfully (with `// @ts-ignore`) and works as expected.

**To Reproduce:**
```tsx
// DummyComponent.tsx

import { FunctionalComponent, h } from "preact";

const DummyComponent: FunctionalComponent = ({ children }) => {
    return children;
});

export default DummyComponent;
```

Error in VS Code:
`  Type 'ComponentChildren' is not assignable to type 'VNode<any> | null'. `

**Expected behavior:**
No errors.

**Comment by developit** [comment]
I've run into this as well.
