### ISSUE TITLE
Drag and drop feature of react-big-calendar stopped working in version 10.10.x

### ISSUE THREAD

**Issue by lomber1** [preactjs/preact#3673]
- [ x ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Hi,

I updated preact to version 10.10.x and drag and drop feature of [react-big-calendar](https://github.com/jquense/react-big-calendar) (1.5.0) stopped working properly. Dragging and resizing works only on the second try (it just "ignores" being dragged on first try). In versions prior to 10.10.x everything worked correctly.
 
I'm attaching code sandboxes with both versions and videos of issue.

Thanks.

https://user-images.githubusercontent.com/27731530/185110195-7da54289-708f-4953-ad8b-e90c3b81d551.mp4

https://user-images.githubusercontent.com/27731530/185110207-4ec440f4-cdf4-4d20-be24-47d68176343f.mp4

**To Reproduce**
1. Go to [the working version first](https://codesandbox.io/s/focused-darkness-ipo8ve) 
2. Try dragging some event around, it should "just work". Note that when dropped, event won't change its position and this is intentional, as state management is not necessary in this example. The thing that matters is that events can be dragged.
3. Go [the broken version](https://codesandbox.io/s/dry-wood-9rd1e3)
4. Do the same thing as in step 2, just drag some events.
5. You should immediately notice the difference, events can't be dragged, they become draggable only on second try.

**Expected behavior**
Dragging in react-big-calendar should work just like in previous versions.

**Comment by JoviDeCroock** [comment]
This seems related to https://github.com/preactjs/preact/pull/3608 as doing the following change makes everything work correctly:

```js
options.debounceRendering = Promise.prototype.then.bind(Promise.resolve())
```

**Comment by lomber1** [comment]
Yes, this solution solved the problem, thanks.
