### ISSUE TITLE
Type for `Element` changed to `ElementType`: intended?

### ISSUE THREAD

**Issue by shalomvolchok** [preactjs/preact#3679]
Before we update our types, just checking if it was intentional to remove the `Element` type and replace it with `ElementType`? Getting a TS error with `10.10.4` for `h.JSX.Element`

https://github.com/preactjs/preact/commit/7d54883b6e45b3d0cc670254c0078cee3a2aaa87#diff-814abe9ce1d0e89a7fa1ef941142487296d1423ffad605dc1188b544056c2bcfL29

**Comment by JoviDeCroock** [comment]
What error are you getting? I can double check 😅

**Comment by shalomvolchok** [comment]
Namespace JSXInternal has no exported member `Element`

**Comment by marvinhagemeister** [comment]
Ohh this is a good catch! Yeah we should keep `JSX.Element`. I missed that in my review.

**Comment by JoviDeCroock** [comment]
On what code? Are you referencing JsX.Element yourself, with more information I can check 😅

**Comment by birtles** [comment]
I also have code importing `React` as `import * as React from 'preact/compat';` and referencing `React.JSX.Element` which is broken by 10.10.4.

**Comment by nurav97** [comment]
This breaking the @fullcalendar package 

![image](https://user-images.githubusercontent.com/89197239/185555118-6222f127-48b4-45f5-9490-1cacfd8f37a5.png)

**Comment by JoviDeCroock** [comment]
Sorry about that I jumped into our tests and figured out why this doesn't show up as an error for us, we have a local override to do namespace testing. Will fix

**Comment by JoviDeCroock** [comment]
Sorry about the inconvenience, published as 10.10.5
