### ISSUE TITLE
Reuse component instance from a parent component to another one.

### ISSUE THREAD

**Issue by ruojianll** [preactjs/preact#3685]
I'm working on building a low code WYDIWYG platform to build web pages. So we need to drag a component from an old parent to a new one. The component should be reused to prevent destroy and rebuild it. The dom elements(vnode tree) of the component should be kept cause of some third party libs may alter dom directly.

In other words, move a component to another parent component whit it's html element.

These components don't need props and other interactions with it's parent.

Maybe we can use component instance as vnode tag instead of component class constructor or html string tag, move the html element of the instance to the new place and call some hooks(e.g. `parentChanged`). We could provide a new component base class e.g. `InstanceComponent` with no props and events to determine if the tag is a reusable component.

It's type safe because of there are not props and events pass to/from parent component.

**Comment by ruojianll** [comment]
The diff algorithm is O(n^3) if we diff whole trees.  But if we could mark the old place to the instance, trace it after moved and remove it. The algorithm is still O(n). The diff algorithm is designed for no more information about the tree state.

**Comment by developit** [comment]
This is possible using Options Hooks, or `this.base` in a component. 

We don't support recycling of elements in Preact anymore because it causes endless issues with stateful DOM elements (img, video, input, iframe, etc).
