### ISSUE TITLE
Functional component destroys and rebuilds every time its parent rerenders.

### ISSUE THREAD

**Issue by CaffeinatedCodeMonkey** [preactjs/preact#3694]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When a functional component's parent rerenders, the functional component will always rebuild. Whereas a class component survives.

**To Reproduce**
https://codesandbox.io/s/dazzling-bogdan-65hw3b?file=/components/app.js

1. Go to the sandbox.
2. Wait ~10 seconds

**Expected behavior**
I would expect FunctionComponent to have the same lifespan as the ClassComponent.

**Comment by JoviDeCroock** [comment]
Your useEffect has no dependencies, passing [] fixes this
