### ISSUE TITLE
MUI component wrapped in a custom element passes invalid type to `document.createElement`

### ISSUE THREAD

**Issue by valdemarrolfsen** [preactjs/preact#3703]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I am trying to build a simple web component using preact and MUI based on the provided example from:

https://github.com/mui/material-ui/tree/master/examples/preact

I am able to build the web component successfully but when I render it in the browser it crashes due to:

`Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.` at: https://github.com/preactjs/preact/blob/e70238f2d9572688d4a8fc2de1892e837e6e9122/src/diff/index.js#L362

Preact assumes that newNode.type is always a string but when using MUI the node type is actually an object.

Not sure if using third party libraries in preact is supported when building web-components, but thought it was worth it to report it :) 

**To Reproduce**

Try building a simple web component using MUI and load it in the browser:

```typescript
import Button from "@mui/material/Button";
import register from "preact-custom-element";

export interface ButtonProps {
  label: string;
  testId: string;
  onClick: () => void;
}

function UIButton({ onClick, label, testId }: ButtonProps) {
  return (
    <Button data-testid={testId} onClick={onClick}>
      {label}
    </Button>
  );
}

register(UIButton, "ui-button", ["label", "onClick"], { shadow: true });
```

**Expected behavior**
The MUI button should load as expected inside the web-component

**Comment by marvinhagemeister** [comment]
I'm unable to reproduce the described error with the code provided in the original comment. The button renders as expected, regardless of the build tool I use (tried the CRA setup in the link and vite).

**Comment by valdemarrolfsen** [comment]
Hmm, that is wierd. I build with tsup (esbuild) with the following configuration:

import { defineConfig } from "tsup";
import { sassPlugin } from "esbuild-sass-plugin";
import alias from "esbuild-plugin-alias";

```javascript
export default defineConfig({
  minify: false,
  dts: true,
  sourcemap: true,
  target: "esnext",
  esbuildPlugins: [
    alias({
      react: require.resolve("preact/compat"),
      "react-dom": require.resolve("preact/compat"),
      "react/jsx-runtime": require.resolve("preact/jsx-runtime"),
      "@mui/styled-engine": require.resolve("@mui/styled-engine-sc"),
    }),
  ],
  format: ["esm", "cjs", "iife"],
});
```

**Comment by valdemarrolfsen** [comment]
I render the component using a standard create-react-app:

```javascript
import "./App.css";
import "@ignite-analytics/ui-kit";

function App() {
  return (
    <div className="App">
      <ui-button label="Button" onClick={() => console.log("Test")} />
    </div>
  );
}

export default App;
```

**Comment by marvinhagemeister** [comment]
@valdemarrolfsen rather than supplying more information piece by piece, can you share a small repository where the problem is reproducible? That way we can ensure that we're running the same setup as you on your machine.

**Comment by valdemarrolfsen** [comment]
Sure, sorry about that. Here is a repo where the issue can be reproduced:

https://github.com/valdemarrolfsen/preact-button

**Comment by rschristian** [comment]
In your repo you're not setting up aliases in CRA [as the original example does](https://github.com/mui/material-ui/blob/master/examples/preact/config-overrides.js). This results in the unexpected data shape being given to Preact.

**Comment by valdemarrolfsen** [comment]
Hmm, but in ts-config I add:

```
esbuildPlugins: [
    alias({
      react: require.resolve("preact/compat"),
      "react-dom": require.resolve("preact/compat"),
      "react/jsx-runtime": require.resolve("preact/jsx-runtime"),
    }),
],
```

This should be the equivalent of the original example using `esbuild`?

**Comment by rschristian** [comment]
That's your component.

Your app is React. You haven't set up the Preact aliases in CRA.

**Comment by valdemarrolfsen** [comment]
I see, then I understand the issue, thank you very much :) 

In general, I think that web components should be framework agnostic and work regardless of which web framework they are used with. But I know there are still many issues with React and web components in general.

Anyway, thanks for the help, then I will find another way of doing this 😄

**Comment by rschristian** [comment]
If you're not meaning to use Preact as your app framework then you should alternatively be able to bundle the MUI component into your custom element.

**Comment by valdemarrolfsen** [comment]
Yes, that makes sense. It will make the bundle quite big, but it seems it's the only option. Thanks for all the help :)
