### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '__H')

### ISSUE THREAD

**Issue by renhiyama** [preactjs/preact#3725]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
```
hooks.js:2 Uncaught TypeError: Cannot read properties of undefined (reading '__H')
    at a (hooks.js:2:205)
    at j (hooks.js:2:907)
    at <anonymous>:1:1
```
**To Reproduce**
Run the below code in browser:
```js
let React = await import("https://esm.sh/preact");
let { useState, useEffect } = await import("https://esm.sh/preact/hooks");
useEffect()
```

**Expected behavior**
What should have happened when following the steps above?
Return `[count, setCount]` if I am not wrong...

**Comment by JoviDeCroock** [comment]
Seems to work correctly for me https://codepen.io/jovidecroock/pen/ZEopMze I. think that using async imports however won't work because you are creating race conditions where the node/browser module cache will have to create dupes.

**Comment by renhiyama** [comment]
Ah yes ur version did really work!

**Comment by renhiyama** [comment]
Ah your version works on csr, but when using ssr mode with preact ssr, the error remains :(
![image](https://user-images.githubusercontent.com/92968534/190086518-56dbf483-f512-4055-9a1d-1b735122b4e7.png)

**Comment by renhiyama** [comment]
To get more specific, htm is causing this error if I am not wrong.
![image](https://user-images.githubusercontent.com/92968534/190088870-06328e52-80df-429e-b9cd-7b402d34c4c2.png)
The version which doesnt work:
```js
let { render, h } = await import('https://esm.sh/preact');
let htm = (await import('https://unpkg.com/htm?module')).default;
const html = htm.bind(h);
let { useState } = await import('https://esm.sh/preact/hooks');

const App = () => {
  const [count] = useState(20)
  return html`<p>${count}</p>`;
}

render(html`<${App()} />`, document.body);
```

Your version:
```js
let { render, h } = await import('https://esm.sh/preact');
let { useState } = await import('https://esm.sh/preact/hooks');

const App = () => {
  const [count] = useState(20)
  return h('p', {}, count)
}

render(h(App, {}), document.body)
```

**Comment by JoviDeCroock** [comment]
Again, you are using async imports 😅 static imports which is the intended use in the global scope won't cause this

**Comment by renhiyama** [comment]
ah, is there any possible method with async/dynamic imports? the setup I have created wont allow me to use static imports...

**Comment by renhiyama** [comment]
Wierd, the same code seems to work now :sus:

**Comment by renhiyama** [comment]
![image](https://user-images.githubusercontent.com/92968534/190116963-1e4f5d3a-95f3-45d2-b349-be7540ee27f4.png)
Looks like something happens regarding ssr rendering :(

**Comment by marvinhagemeister** [comment]
@renhiyama Took a look into this and the issue is that multiple different versions of Preact are loaded. The `https://esm.sh/preact-render-to-string` and `https://esm.sh/htm/preact` code Preact `10.10.6` whereas the other imports reference Preact `10.11.0`. This is a bug in `esm.sh`.

You can override the incorrect default behavior of `esm.sh` with a `?dep=<package>@<version>` query parameter. That forces esm.sh to pick the correct version.

```diff
- const render = await import("https://esm.sh/preact-render-to-string");
+ const { render } = await import("https://esm.sh/preact-render-to-string?deps=preact@10.11.0");
  const React = await import("https://esm.sh/preact/compat");
- const preact = await import("https://esm.sh/htm/preact");
+ const preact = await import("https://esm.sh/htm/preact?deps=preact@10.11.0");
const { useState } = await import("https://esm.sh/preact/hooks");

function App() {
  const [count, setCount] = useState(0);

  return preact.html`<p>hello</p>`;
}

console.log(render(preact.html`<${App} />`));
```

**Comment by ynwd** [comment]
@marvinhagemeister 

Still happened in: `preact@10.16.0`

```
TypeError: Cannot read properties of undefined (reading '__H')
    at l (https://esm.sh/stable/preact@10.16.0/denonext/hooks.js:2:194)
    at B (https://esm.sh/stable/preact@10.16.0/denonext/hooks.js:2:328)
    at k (https://esm.sh/stable/preact@10.16.0/denonext/hooks.js:2:297)
    at Object.App (file:///src/pages/app.tsx:8:21)
    at v (https://esm.sh/v131/preact-render-to-string@6.2.1/denonext/preact-render-to-string.mjs:2:3070)
    at v (https://esm.sh/v131/preact-render-to-string@6.2.1/denonext/preact-render-to-string.mjs:2:4883)
    at v (https://esm.sh/v131/preact-render-to-string@6.2.1/denonext/preact-render-to-string.mjs:2:2581)
    at v (https://esm.sh/v131/preact-render-to-string@6.2.1/denonext/preact-render-to-string.mjs:2:4883)
    at v (https://esm.sh/v131/preact-render-to-string@6.2.1/denonext/preact-render-to-string.mjs:2:2581)
    at v (https://esm.sh/v131/preact-render-to-string@6.2.1/denonext/preact-render-to-string.mjs:2:4883)
```

**Comment by ynwd** [comment]
Solution:

```
export {
  default as renderToString,
} from "https://esm.sh/preact-render-to-string?deps=preact@10.16.0";
```

**Comment by renhiyama** [comment]
> Solution:
> 
> ```
> export {
>   default as renderToString,
> } from "https://esm.sh/preact-render-to-string?deps=preact@10.16.0";
> ```

Preact render to strings comes with its own preact version, and it may or may not be same with the version of preact ur currently using. As such, duplicate versions starts to exist as soon as a new preact or render to string update comes up.
