### ISSUE TITLE
Hydration breaks styles and classes

### ISSUE THREAD

**Issue by alexander-entin** [preactjs/preact#3733]
- [x] Check if updating to the latest Preact version resolves the issue
    "preact-cli": "^3.0.0",
    "preact": "^10.1.0",
    "preact-render-to-string": "^5.1.2"

**Describe the bug**
Differences in the markup produced by pre-rendering and the very first render on the client are not handled properly by hydration

**To Reproduce**
1. `npx preact-cli create simple`
2. Put the following into src/index.js
```javascript
export default function App() {
    let tz = global.window && Intl.DateTimeFormat().resolvedOptions().timeZone
    return (
        <>
            <div className="tz1" style={{ display: tz ? 'block' : 'none' }}>{tz}</div>
            {tz && <div className="tz2">{tz}</div>}
            <div className="content">
                <div>bar</div>
            </div>
            <div className="footer">foo</div>
        </>
    )
}
```
3. `preact build --prerender`

What we get after hydration:
![image](https://user-images.githubusercontent.com/10639790/190869345-c681c92d-4299-4adb-bdbb-c7989aad2c97.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/10639790/190869383-95cc2ef2-4c7e-40a8-b81a-5518ed3a616e.png)

**Comment by developit** [comment]
This is how hydration works. The initial rendered DOM is required to exactly match the SSR'd/prerendered HTML. 

You can use render() instead of hydrate() if you want to pay the cost of comparing attributes on the initial render.

**Comment by rschristian** [comment]
A bit more context can be found here: https://preactjs.com/guide/v10/api-reference#hydrate

To fix this in `preact-cli` specifically, you can add the following to your `preact.config.js`, assuming you'd like to keep prerendering enabled:

```js
export default (config, env, helpers) => {
    if (env.isProd && !env.isServer) {
        const definePlugins = helpers.getPluginsByName(config, 'DefinePlugin');
        const { plugin: definePlugin } = definePlugins.find(
            ({ plugin }) => plugin.definitions['process.env.PRERENDER'],
        );
        definePlugin.definitions['process.env.PRERENDER'] = false;
    }
};
```

`process.env.PRERENDER` is used in our entry as part of determining whether to hydrate or render, no where else. So you can set it to `false` to use `render()`, but still get your app prerendered normally.

**Comment by alexander-entin** [comment]
> To fix this in `preact-cli` specifically, you can add the following to your `preact.config.js`, assuming you'd like to keep prerendering enabled:

Thanks a lot!
