### ISSUE TITLE
`componentDidUpdate` affects component state

### ISSUE THREAD

**Issue by zjhch123** [preactjs/preact#3742]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

`componentDidUpdate` affects component state

**To Reproduce**

https://codesandbox.io/s/crimson-worker-1koisq?file=/src/index.js

1. Open Console, it shows `{ count: null, isLoading: false }`
![image](https://user-images.githubusercontent.com/12215513/191675378-735d35b1-396b-44b5-a23c-483cd0ccfed2.png)

2. Comment the line of `componentDidUpdate`, refresh demo page, in console, it shows `{ count: { value: 10 }, isLoading: false }`
![image](https://user-images.githubusercontent.com/12215513/191675658-9c4d4ab2-41f0-4462-8110-8c13d8291ee2.png)

**Expected behavior**

Whether or not there is a `componentDidUpdate` event, the console should be `{ count: { value: 10 }, isLoading: false }`

**Comment by JoviDeCroock** [comment]
Just took a quick look at the issue and it looks like the following is happening:

- componentDidMount gets invoked and initiates a render.
- we push a componentDidUpdate to the _renderCallbacks
- componentDidMount gets invoked and updates state
- the above setState call pushes to the _renderCallbacks queue
- render completes and the renderCallbacks get consumed before the next render is initiated making the setState callback called with a stale state as that one completes on the next invocation

**Comment by zjhch123** [comment]
Thank you @JoviDeCroock for your quick action!
