### ISSUE TITLE
The difference between 'compat-alias-package' and 'compat' package inside preact main repo

### ISSUE THREAD

**Issue by ymchun** [preactjs/preact#3745]
- [ ] Check if updating to the latest Preact version resolves the issue

**Background**
We are developing a web component sdk using [`react-to-webcomponent`](https://github.com/bitovi/react-to-webcomponent). The sdk original use react & react-dom but we alias react using preact in our Vue application according to this [doc](https://preactjs.com/guide/v10/getting-started#aliasing-in-node).

**Describe the bug**
When aliasing react using the following alias in `package.json`
```
"react": "npm:@preact/compat",
"react-dom": "npm:@preact/compat",
```
the error prompt out
```
Module not found: Error: Package path ./client is not exported from package [my project path]/node_modules/react-dom (see exports field in [my project path]/node_modules/react-dom/package.json)
```

it works when using the following alias
```
"react": "link:node_modules/preact/compat",
"react-dom": "link:node_modules/preact/compat",
```

Seems [compat in main repo](https://github.com/preactjs/preact/tree/master/compat) has `client.js` exported but none in [compat-alias-package](https://github.com/preactjs/compat-alias-package)

**Comment by ymchun** [comment]
added reproduce repo: https://github.com/ymchun/preact-reproduce

**Comment by developit** [comment]
Thanks for the report! Just opened a [PR with the fix](https://github.com/preactjs/compat-alias-package/pull/8).
