### ISSUE TITLE
Preact doesn't preserve the DOM nodes of a keyed list when there are multiple DOM node children

### ISSUE THREAD

**Issue by luisherranz** [preactjs/preact#3766]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

@darerodz discovered in our experiments that Preact recreates the DOM nodes of a keyed list (instead of preserving them) if the component with the key has multiple DOM node children.

It's easier to see than to explain, so here is a video:

https://user-images.githubusercontent.com/3305402/195852098-ddba5424-86fd-4b86-be12-7ffa5f0cfca5.mp4

I've used a text node (`{''}`) in the example because it's the simplest, but it happens with any node. For example:

```js
const User = ({ name, surname }) => {
  return (
    <>
      <span>Name: {name}</span>
      <span>Surname: {surname}</span>
    </>
  );
};
```

**To Reproduce**

- [Stackblitz with reproduction in Preact](https://stackblitz.com/edit/vitejs-vite-ujssbv?file=src%2Fmain.jsx)

1. Create a list
2. Create a component to encapsulate the items
3. Add the key in that component
4. If the component has multiple children, the DOM nodes are not preserved

**Expected behavior**

Preact should preserve the DOM nodes.

_For reference, this is the exact same code using React: [Stackblitz with React](https://stackblitz.com/edit/vitejs-vite-b5dcvx?file=src%2Fmain.jsx)_

**Comment by ekwoka** [comment]
This, I believe is a conflict with the fragment.

I'm not sure that it's really expected to work with fragments like this, since it is not going to be able to actually attach the key to the child.

**Comment by luisherranz** [comment]
Thanks for fixing this, @JoviDeCroock!
