### ISSUE TITLE
Uncaught (in promise) TypeError: usestate is not a function

### ISSUE THREAD

**Issue by njavilas2015** [preactjs/preact#3770]
Good afternoon, I am creating a project from scratch and I encounter this difficulty. I send screenshots, I have discovered that with react if it works the problem is with preact I would like to understand what I am doing wrong or if it is possible that it is a bug

![image](https://user-images.githubusercontent.com/47610140/196052990-4b79a7dc-7d68-4497-a40d-7fd4ade3cd2f.png)
![image](https://user-images.githubusercontent.com/47610140/196053016-7b39f845-4d73-4010-bad3-95e7a787154c.png)
![image](https://user-images.githubusercontent.com/47610140/196053108-1b9fb15b-09a3-4870-9be1-278f0a4874d0.png)

my code

```tsx

import { JSX } from "preact"
import { useState } from "preact/hooks"
import { Words } from "game-sdk/dist/types"
import { T } from "game-sdk"

import ItemWord from '@/components/vzsflfowrjsvidh'

const App = (): JSX.Element => {

  const [newItem, setNewItem] = useState<Partial<Words.ModelAttributes>>()

  const handleArticles = async (id: string, value: T.Words.articles) => {
    if (id === 'new') {
      setNewItem({ ...newItem, articles: value })
    }
  }

  const handlePresentSimple = async (id: string, value: T.Words.simplePresent) => {
    if (id === 'new') {
      setNewItem({ ...newItem, simplePresent: value })
    }
  }

  return (
    <ItemWord
      id="new"
      edit={true}
      onArticles={handleArticles}
      onPresentSimple={handlePresentSimple}
      visible={false}
    />
  )
}

export default App
```

**Comment by developit** [comment]
This error is almost always because hooks are being called conditionally or out-of-order. How is `App` in your screenshot being rendered?  Are you ever "invoking" a function component, like `App()`?

It could also be that loadable (I assume `loadable-components`) is using React due to incorrect aliases.

**Comment by marvinhagemeister** [comment]
Closing because we haven't heard back from OP.
