### ISSUE TITLE
useId spews out identical ids

### ISSUE THREAD

**Issue by AlexIII** [preactjs/preact#3772]
preact  10.11.2

preact-compat 3.19.0 

```javascript
const C1 = () => {
  const id = useId();
  return <h2> {id} </h2>;
};

const App = () => {
  return (
    <>
      <h1> TEST </h1>
      <div>
        <C1 />
      </div>
      <div>
        <C1 />
      </div>
    </>
  );
};
```
![image](https://user-images.githubusercontent.com/10047074/197187368-bdfa1979-22cd-4d0d-8044-fe588dba6dab.png)

https://codesandbox.io/s/friendly-moon-9xlcfs?file=/src/index.js

**Comment by marvinhagemeister** [comment]
Can confirm that this is a bug.

FYI: The `preact-compat` package is only for Preact 8.x versions. It's not needed with Preact 10.x

**Comment by SvizelPritula** [comment]
Hello! This may be a stupid question, but why does `useId` use hashes to generate ids? Wouldn't it be enough to use a single global variable that monotonically counts up? Is this becouse of SSR?

**Comment by developit** [comment]
It is because of SSR, yes. On the client, it could be a monotonic counter.

**Comment by AlexIII** [comment]
I've found yet another suspicious thing about preact's implementation of `useId()`

Consider the following code

```javascript
const C1 = () => {
  const id = useId();
  return <h2> C1 = {id} </h2>;
};
const C2 = () => {
  const id = useId();
  return <h2> C2 = {id} </h2>;
};

const App = () => {
  const [v, setV] = useState(false);
  return (
    <>
      <h1> TEST </h1>
      <div>{!v ? <C1 /> : <C2 />}</div>
      <div>
        <C1 />
      </div>
      <button onClick={() => setV((v) => !v)}>switch</button>
    </>
  );
};
```

https://codesandbox.io/s/fervent-hopper-33n4ul?file=/src/index.js

![image](https://user-images.githubusercontent.com/10047074/197758666-957d901f-f7b8-4025-b4f0-d82108dcb04c.png)

![image](https://user-images.githubusercontent.com/10047074/197758628-e0e7ab30-b4c3-46fb-bbf0-211097af689a.png)

On top of the previous problem, when I press the button, which causes C1 to be replaced with C2, the id stays the same. This can lead to all sorts of problems. It is also inconsistent with the reference implementation of react.

https://codesandbox.io/s/zen-volhard-lfkryj?file=/src/App.js

![image](https://user-images.githubusercontent.com/10047074/197759558-d7344932-94be-4653-a26c-4a10cce23b0c.png)

**Comment by SvizelPritula** [comment]
Another potential issue:

```
import { render } from "preact";
import { useId } from "preact/hooks";

function App() {
  const id = useId();
  return <div id={id}>{id}</div>;
}

function mount(component) {
  let root = document.createElement("div");
  document.getElementById("root").appendChild(root);
  render(component, root);
}

mount(<App />);
mount(<App />);
```

results in:

```
<body>
  <div id="root">
    <div>
      <div id="P481">P481</div>
    </div>
    <div>
      <div id="P481">P481</div>
    </div>
  </div>
</body>
```

See: https://codesandbox.io/s/preact-useid-multiple-y0qbwq?file=/src/index.js

**Comment by marvinhagemeister** [comment]
@AlexIII This is a fantastic test case, thanks for sharing! Added it to #3773 and was happy to see, that the approach chosen there already addresses this scenario.

@SvizelPritula Good catch! That's a tricky one if we take SSR into account. Made a first draft for a fix in #3773 for it, but feel like it needs a bit more thought.

**Comment by marvinhagemeister** [comment]
> Hello! This may be a stupid question, but why does `useId` use hashes to generate ids? Wouldn't it be enough to use a single global variable that monotonically counts up? Is this becouse of SSR?

Not a stupid question at all! I think the hashing was part of earlier explorations. I can't find a reason to keep it anymore.

**Comment by AlexIII** [comment]
Btw, react treats the last example (multi-root app) as a special case that requires some user attention. (`identifierPrefix` [in the doc](https://reactjs.org/docs/react-dom-client.html) ).

**Comment by teetotum** [comment]
> Btw, react treats the last example (multi-root app) as a special case that requires some user attention. (`identifierPrefix` [in the doc](https://reactjs.org/docs/react-dom-client.html) ).

The relevant link into the current react documentation is https://react.dev/reference/react/useId#specifying-a-shared-prefix-for-all-generated-ids
