### ISSUE TITLE
preactCompat: npm.reversehttp.com/preact broken export 

### ISSUE THREAD

**Issue by grefl** [preactjs/preact#3789]
## Problem

In order to use native esm imports it was recommend by #2719 to use npm.reversehttp.com.

Specifically this import.

```javascript
    import { html, render, preactCompat as React } from 'https://npm.reversehttp.com/preact,preact/compat,htm/preact';
```

However, now preactCompat is undefined. 

So now, it is necessary to import each preact export individually.  Example:
```javascript
import { useState, useEffect } from 'https://npm.reversehttp.com/preact,preact/compat,htm/preact';
```

## Solution

Not sure if it's great idea to use npm.reversehttp.com since it seems unreliable. Is there a new version that broke this? Maybe unpkg.com is better choice?

**Comment by marvinhagemeister** [comment]
Looks like something changed with `npm.reversehttp.com` It seems to merge all exports at the top level rather than keeping them separate like before. Maybe it's not using the browser bundle's anymore. Not sure, but is definitely a change within their site not in Preact.
