### ISSUE TITLE
Issue with onBlur, onClick and re-rendering events order on mobile browsers

### ISSUE THREAD

**Issue by nicolaturcato** [preactjs/preact#3792]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I have an issue started with v11.10.0 happening on input elements.
This happens **only** on mobile browsers.
I have an input field and a button. I'm setting a value into react state on the onBlur event of the input, and I expect a re-rendering and the onClick events should read the proper value from the state.
After upgrading to version v11.10.0 the order is different: it sets the value into state on the onBlur event, then the onClick happens reading an old value from state, and finally it re-renders.

**To Reproduce**
To reproduce it in sandbox please click icon to "open in new window", open the inspector, toggle "device toolbar" and use a real phone (eg: iPhone SE). Then look at the order in console comparing to desktop.
https://codesandbox.io/s/wizardly-violet-jznxlb

1. Type something into the input field
2. Click button

**Expected behavior**
The events should be in the following order:
1. onBlur (set the value into state)
2. re-rendering (because of change in react state)
3. onClick (reading value from state)

**Requirements**
Mobile browser

**Comment by marvinhagemeister** [comment]
@nicolaturcato I'm unable to reproduce the issue on my end. Tried with:

- Chrome on macOS
- Chrome on Windows
- Firefox on macOS
- Safari on macOS
- Chrome on Android
- Firefox on Android
- Safari on iOS

Can you share more details about which device you're testing on?

**Comment by nicolaturcato** [comment]
Hi @marvinhagemeister ,
sorry for answering late and for providing a wrong test case.
I just updated it: https://codesandbox.io/s/wizardly-violet-jznxlb and can finally reproduce the error in sandbox aswell.

Basically the issue happens when I'm setting the value into react state and then reading the value on the onClick event from state.

Desktop works fine, events order is as I expect it:
1. onBlur (set the value into state)
2. re-rendering (because of change in react state)
3. onClick (reading value from state)

But events order in mobile is different. The onClick event happens before the re-rendering, therefore the value it reads is wrong.
This is what happens on mobile:
1. onBlur (set the value into state)
3. onClick (reading value from state)
2. re-rendering (because of change in react state)

To reproduce it in sandbox please click icon to "open in new window", open the inspector, toggle "device toolbar" and use a real phone (eg: iPhone SE). Then look at the order in console comparing to desktop.

I adapted the ticket description accordingly.

**Comment by rschristian** [comment]
> To reproduce it in sandbox please click icon to "open in new window", open the inspector, toggle "device toolbar" and use a real phone (eg: iPhone SE). Then look at the order in console comparing to desktop.

Are you able to reproduce on an actual device, or only in your browser's emulation mode?

I am able to reproduce with your steps, though that's not "a real phone" by any means; there are some odd bugs that pop up in that simulation across browsers that aren't indicative of issues on the actual devices they're simulating.

I'm also unable to reproduce on a real device.

**Comment by nicolaturcato** [comment]
Hi @rschristian ,
yes I'm able to reproduce it on my iPhone 11 connected to my mac and with console open to see logs.

**Comment by nicolaturcato** [comment]
Hi again @rschristian ,
I just double-checked this via iPhone 11 connected to mac and using Safari browser on mobile.
Running test test on https://jznxlb.csb.app/ this is the order of the logs I get:

[Log] 2. Rendering...
[Log] 1. onBlur
[Log] 3. onClick
[Log] Input value is:  – ""
[Log] 2. Rendering...

as you can see re-rendering appears at the end and input value is empty.
To test the issue you have to type something into input field and directly click the button.

**Comment by marvinhagemeister** [comment]
Can confirm the issue.

Chrome:
<img width="207" alt="Screenshot 2023-02-14 at 14 27 18" src="https://user-images.githubusercontent.com/1062408/218752350-2ad2d6b7-393e-45d6-938e-b67bcede09b9.png">

Safari macOS:
<img width="169" alt="Screenshot 2023-02-14 at 14 27 33" src="https://user-images.githubusercontent.com/1062408/218752406-83888482-ef17-4635-9297-ef5fe1105d47.png">

Safari iOS:
<img width="164" alt="Screenshot 2023-02-14 at 14 27 13" src="https://user-images.githubusercontent.com/1062408/218752435-00c36cf7-f597-4402-ad2e-1a153351fe6f.png">

**Comment by developit** [comment]
This is due to our use of setTimeout for render debouncing. I'm not sure the swap setup @andrewiggins came up with would fix this particular issue either, unfortunately.

**Comment by marvinhagemeister** [comment]
@nicolaturcato we switched back to the Promise based scheduling we had previously in recent Preact versions. Does the issue still exist?

**Comment by EhsanTaba** [comment]
I will attempt to integrate async/await sugar syntax on Promise for this. setTimeout()/setInterval() and defer  @developit, feel free to reach out to me. For those that are unfamiliar with debounce, throttle, and performance, check out: https://web.archive.org/web/20180324022838/http://demo.nimius.net/debounce_throttle/

**Comment by EhsanTaba** [comment]
> @nicolaturcato we switched back to the Promise based scheduling we had previously in recent Preact versions. Does the issue still exist?

Can anyone confirm this issue still exists?

**Comment by rschristian** [comment]
Looks like it indeed was corrected.

Safari iOS:
![image](https://github.com/preactjs/preact/assets/33403762/b21cc6ea-7aea-4cf7-acae-890aa7270a31)
