### ISSUE TITLE
Uncaught TypeError: _client.default.hydrateRoot is not a function

### ISSUE THREAD

**Issue by tommyboylab** [preactjs/preact#3793]
- ✅  Check if updating to the latest Preact version resolves the issue

**Describe the bug**

Trying to run a Preact compiled NextJs 13 application leads to the above error. 
Compiling to normal React issue is not present.

Note: Issue is present after migrating to new AppDirectory with Server/Client components.

**To Reproduce**
- Build a small NextJS 13 application that compiles to Preact on build (will try and reproduce in sandbox)
- Open the application to render infinite loading page 
- Issue is present in the console

Current using this config to compile on build
```
  webpack: (config, { dev, isServer }) => {
      if (!dev && !isServer) {
          config.resolve.alias = {
              ...config.resolve.alias,
              "react/jsx-runtime.js": "preact/compat/jsx-runtime",
              react: "preact/compat",
              "react-dom/test-utils": "preact/test-utils",
              "react-dom": "preact/compat",
          };
      }
      return config;
      },
```

Error
```
Uncaught TypeError: _client.default.hydrateRoot is not a function
    at 17-abb3538cc97ee8f6.js:1:4791
    at exports.startTransition (17-abb3538cc97ee8f6.js:17:6648)
    at exports.hydrate (17-abb3538cc97ee8f6.js:1:4755)
    at 17-abb3538cc97ee8f6.js:1:8087
    at hydrate (17-abb3538cc97ee8f6.js:1:3363)
    at exports.appBootstrap (17-abb3538cc97ee8f6.js:1:3856)
    at 7917 (17-abb3538cc97ee8f6.js:1:7978)
    at __webpack_require__ (webpack-88aa3b0aa30a04e9.js:1:525)
    at __webpack_exec__ (main-app-f7991bdf5a7d528d.js:1:467)
    at main-app-f7991bdf5a7d528d.js:1:567
```

**Expected behavior**
Application should compile successfully and run without hitting the type error, allow application to run.

**Comment by kirkas** [comment]
I've also experienced this exact issue with similar a setup (NextJS 13 + AppDirectory + webpack alias config)

**Comment by milvasic** [comment]
Any update on this? I'm another one that's experiencing this issue.

**Comment by doo-gl** [comment]
Similar, it looks like when React moved to version 18 the function `hydrate` was renamed to `hydrateRoot`
See docs: https://beta.reactjs.org/reference/react-dom/client/hydrateRoot#hydrateroot

Whereas preact is still exporting only the `hydrate` function: https://github.com/preactjs/preact/blob/958311a0400c74b18b38dfb96b334e752b3c79ef/compat/src/index.js#L224

Part of the fix here would be to export the hydrate function a second time with the name `hydrateRoot`

I did try by editing preact in my node modules folder and found that it then fails on an error similar to "TypeError: Cannot add property __k, object is not extensible" so I assume there is more going on behind the scenes than just renaming a function

**Comment by rschristian** [comment]
`react-dom/client` was added to compat in #3506
