### ISSUE TITLE
Uncaught DOMException when having `<!DOCTYPE html>` and setting the `parentDom` to `document` when rendering

### ISSUE THREAD

**Issue by rojvv** [preactjs/preact#3794]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
If we have `<!DOCTYPE html>` in our HTML document where we use Preact, and try to render or hydrate a component in the `document`, we get an Uncaught DOMException error, and the component does not render/hydrate. Although, it'll be fine if we remove `<!DOCTYPE html>`. This is very a strange behavior.

**To Reproduce**

```html
<!DOCTYPE html>
<html>
  <body>
  </body>
</html>
<script type="module">
  import { h, Component, render } from 'https://unpkg.com/preact?module';

  const app = h('html', null, h('body', null, h('h1', null, 'Hello World!')));

  render(app, document);
</script>
```

1. Open the above HTML in your browser.
2. You will face the error.
3. Try removing the first line, `<!DOCTYPE html>`.
4. See how the error is gone.

**Expected behavior**
Should act just fine :)

**Comment by marvinhagemeister** [comment]
That is the correct behavior and not a bug as the `document` is owned by the browser.

The second argument passed to render is a DOM node that's expected to be fully owned by Preact. When Preact detects that there are existing nodes there that doesn't match the virtual tree that it was given, we'll try to insert nodes before that. One of those nodes in the doctype and inserting nodes before that is not allowed like the error states.

Even in theory, rendering into the `document` itself is a very brittle approach as you're relying on the frameworks logic to not blow away nodes that are not present in the virtual tree, like for example the `<script>` tag in this scenario. It's not worth it fighting the way HTML works.

Instead, create a container element inside `<body>` that is exclusively owned by Preact. That's the recommended approach.

```diff
  <!DOCTYPE html>
  <html>
    <body>
+    <div id="app"></div>
+    <script type="module">
+      import { h, Component, render } from 'https://unpkg.com/preact?module';
+
+      const app = h('h1', null, 'Hello World!');
+
+      render(app, document.getElementById("app"));
+    </script>
    </body>
  </html>
-  <script type="module">
-    import { h, Component, render } from 'https://unpkg.com/preact?module';
-
-    const app = h('html', null, h('body', null, h('h1', null, 'Hello World!')));
-
-    render(app, document);
-  </script>
```

**Comment by roj1512** [comment]
@marvinhagemeister What about this:

- I want to SSR.
- And then hydrate in the browser to the `body`.
- Rerender the head?

Rendering in the `document` is a common thing. It works with React DOM. React DOM Server will even include the `<!DOCTYPE html>`.

**Comment by marvinhagemeister** [comment]
> Rendering in the `document` is a common practice. It works with React DOM. React DOM Server will even include the `<!DOCTYPE html>`.

You don't get this error in React because it aggressively removes any nodes not matching the virtual tree. In this case it drops the doctype node completely which makes the HTML invalid.

The common and recommended approach to doing SSR in both React and Preact is to stitch the document manually. Nodes supposed to be included in the `<head>` section are usually generated via [react-helmet](https://github.com/nfl/react-helmet), [react-head](https://github.com/tizmagik/react-head) or something custom.

```js
const html = `<!DOCTYPE html>
<html>
<head>
  ${headNodes}
</head>
<body>
  <div id="app>${app}</div>
  <script type="module">
    // ...app code + hydration here
  </script>
</body>
</html>
`

**Comment by roj1512** [comment]
I know about this way of rendering the head, but what if we wanted to use a state in the head?

**Comment by marvinhagemeister** [comment]
Can you share more about your use case why you need state in the `<head>` portion of the document?

**Comment by marvinhagemeister** [comment]
> Everything does that nowadays.

That doesn't match my experience, but I'm curious to learn more. Can you share some links to projects which do that in the way you're describing?

**Comment by roj1512** [comment]
Remix Run

https://github.com/remix-run/remix/blob/973cd68528c8c58679a5b2d974ae8cefde0db455/integration/helpers/cf-template/app/entry.client.tsx#L4

**Comment by roj1512** [comment]
Ultra

This even supports both React and Preact, but for the Preact support it does not use preact-render-to-string because of this issue, instead it uses ReactDOMServer with preact/compat.

https://github.com/exhibitionist-digital/ultra/blob/main/examples/with-react-router/client.tsx#L6

**Comment by roj1512** [comment]
@marvinhagemeister Can you please reopen this?

**Comment by roj1512** [comment]
@marvinhagemeister @JoviDeCroock @andrewiggins 

Since you're not reopening this, should I open a new issue?

**Comment by developit** [comment]
Shouldn't this be rendering into `document.documentElement`? 

I'd like to support this in Preact, since Remix is already relying on it.

**Comment by roj1512** [comment]
React seems serious about supporting this. Here's a recent related bugfix:
https://github.com/facebook/react/pull/26129

**Comment by rojvv** [comment]
Thank you!
