### ISSUE TITLE
translate="no" becomes translate="yes"

### ISSUE THREAD

**Issue by ColCh** [preactjs/preact#3799]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

**To Reproduce**

https://codesandbox.io/s/blissful-hertz-lyyv45?file=/src/index.js

1. render `<b translate="no">translate="no" attribute</b>`
2. but you got `<b translate="yes">translate="no" attribute</b>`

**Expected behavior**

should have "no" value

**Comment by DanielHeath** [comment]
I just checked, and the provided typescript bindings appear appear to be incorrect here - they should tell you that it can be set to `true` or `false`, not a string.

**Comment by ColCh** [comment]
Seems that translate=false works :)
