### ISSUE TITLE
TypeScript 4.9 breaks jsx.d.ts (version 4.8 works fine)

### ISSUE THREAD

**Issue by danielweck** [preactjs/preact#3808]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

Preact version `10.11.3`

`export interface HTMLAttributes<RefType extends EventTarget = EventTarget> extends ClassAttributes<RefType>`

With TypeScript 4.8.4, no errors.

With TypeScript 4.9.3: 

```
node_modules/preact/src/jsx.d.ts:671:19
error TS2430
Interface 'HTMLAttributes<RefType>' incorrectly extends interface 'ClassAttributes<RefType>'.
Types of property 'default' are incompatible.
Type 'boolean | SignalLike<boolean> | undefined' is not assignable to type 'boolean | undefined'.
Type 'SignalLike<boolean>' is not assignable to type 'boolean | undefined'.
```

...that's weird because:

`default?: boolean | SignalLike<boolean>;`

...which is not overriden from:

```
export interface ClassAttributes<T> extends Attributes {
	ref?: Ref<T>;
}

export interface Attributes {
	key?: Key;
	jsx?: boolean;
}
```

https://github.com/preactjs/preact/blob/4a37c998833dafa42bcdb5250128d76ee3307414/src/jsx.d.ts#L671-L672

https://github.com/preactjs/preact/blob/4a37c998833dafa42bcdb5250128d76ee3307414/src/index.d.ts#L55-L62

**To Reproduce**

* TypeScript compiler `tsc` (command line) with a TSConfig that checks all types imported by my project.
* Visual Studio Code to switch between the IDE's own TypeScript version (currently `4.8.4`) and my project's own version (`4.9.3` in my `package.json`).

**Expected behavior**

I am not sure why `default` fails specifically, when there are other `SignalLike<>` properties in `HTMLAttributes` ... I guess maybe `default` is considered a reserved keyword with special significance in TS `4.9`? Perhaps a regression bug in TypeScript, but I can't find any clue in their bug tracker: https://github.com/microsoft/TypeScript/issues

**Comment by danielweck** [comment]
Scrap that! I am able to repro with TypeScript `4.7.4`, `4.8.4` and `4.9.3` ... let me close this issue and start again!

**Comment by danielweck** [comment]
By the way, my workaround is to set `skipLibCheck` to `true` in the `compilerOptions` section of `tsconfig.json` ... not great, but I don't have time to troubleshoot this further :)

**Comment by tigrr** [comment]
I have this issue with Preact 10.11.3 too. Maybe it's worth reopening?

**Comment by kmxz** [comment]
I have this build-breaking issue too, and it can be reproduced with TypeScript 4.7/4.8.

All `10.11.x` Preact versions are affected, but `10.10.x` versions are fine.

**Comment by brookback** [comment]
I have a similar issue where my components' prop types break in subtle ways because of `preact.JSX.SingalLike` is sprinkled across all props in `HTMLAttributes` in `jsx.d.ts`.

**Comment by srsudar** [comment]
I also see this, but only in `10.11.x`.

**Comment by srsudar** [comment]
I believe I was wrong in my previous comment about the version. Opened this issue to try and get some help:

https://github.com/preactjs/preact/issues/3934
