### ISSUE TITLE
@babel/plugin-transform-react-jsx-source warning appears regardless of configuration

### ISSUE THREAD

**Issue by imidom** [preactjs/preact#3818]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Throwing an error within a Preact application with `preact/debug` enabled always logs the following warning in the dev console:

```
Add @babel/plugin-transform-react-jsx-source to get a more detailed component stack. Note that you should not add it to production builds of your App for bundle size reasons.
```

Adding `@babel/plugin-transform-react-jsx-source` to my babel configuration does not stop the warning.

This warning is logged from [here](https://github.com/preactjs/preact/blob/master/debug/src/component-stack.js#L92-L94) in `component-stack.js`. https://github.com/preactjs/preact/blob/d4089df1263faab9b980a3493a4c7e986f254f8e/debug/src/component-stack.js#L90-L95

Looking at that file, I don't believe that `hasBabelPlugin` is ever set to `true` before this warning gets logged. Unfortunately, I don't know how to detect the presence or absence of a babel plugin, otherwise I'd suggest a patch!

**To Reproduce**

(I could not reproduce this in the provided codesandbox environment, maybe because it's using `react-error-overlay`?)

Example repo: https://github.com/imidom/preact-warning-example

1. Create a new Preact application using the latest version of `preact-cli`: `npx preact-cli create default lol2` (or following instructions for a webpack - babel build)
2. Put an undefined variable into `<App />` like the following:
   ```
   ...
   <Header />
	{eekAnUndefinedVariableThatWillCauseAnException}
   <Router>
   ...
   ```
3. Run the application: `npm run dev`
4. Load the application with your dev console open
![image](https://user-images.githubusercontent.com/8891864/205338376-a17480a8-5cb1-4869-9efc-639419b1a8e8.png)

**Expected behavior**
The error is logged without an accompanying warning about a missing babel plugin if the babel plugin has, in fact, been loaded. Though I was not able to see any difference in output with the plugin installed or removed.

**Comment by rschristian** [comment]
Sorry this sat for so long.

Unfortunately it's not possible for us to correct the message for Preact-CLI users, due to the way CLI renders to the root element. While we definitely recommend migrating off of Preact-CLI, we certainly understand that's not always possible, so if the warning continues to bother anyone, best option would be to patch it.

For those who don't use Preact-CLI, you can disregard this, we should have a fix.
