### ISSUE TITLE
Component.setState() causes re-render even if the value(s) don't change

### ISSUE THREAD

**Issue by rejhgadellaa** [preactjs/preact#3821]
- [X] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

I was under the impression that `setState()` should only cause a re-render if the value of the state actually changes. So if `state.x` is `'y'`, and i call `setState({ x: 'y' });`, I expect no render to happen.

**To Reproduce**

This logs `'render!'` every time you click the button, even though the value of `state.x` remains `'y'`

```javascript
class Comp extends Component {

  constructor(props) {
    super(props);
    this.state = { x: 'y' };
  }

  render() {
    console.log('render!');
    return <button onClick={ e => this.setState({ x: 'y' }) }>Click!</button>;
  }

}
```

The functional version behaves as expected: `'render!'` is only logged once (on mount):

```javascript
function Func(props) {

  const [ x, setX ] = useState('y');

  console.log('render!');

  return (
    <button onClick={ e => setX('y') }>Click!</button>
  );
}
```

I had a quick look at `component.js > setState()`, and as far as I can tell, there isn't any value comparison happening there:
https://github.com/preactjs/preact/blob/master/src/component.js#L27

**Expected behavior**

I expected `setState()` to do some form of value comparison like `Object.is()` on the values being set before scheduling a re-render.

**Comment by JoviDeCroock** [comment]
Using fresh objects is never going to be `is` or `===` equal, following screenshot confirms that
![Object.is({ x: 'y' }, { x: 'y' }) returning false](https://user-images.githubusercontent.com/17125876/216547978-5dc7f6ee-a8c9-46a0-98d9-3b2298347a60.png)

This is because we are creating a new identity for the object, it's safer to render 😅

**Comment by marvinhagemeister** [comment]
@leadq Can you file a new issue for that?
