### ISSUE TITLE
Optimized attribute updates when using Signals for non-string values

### ISSUE THREAD

**Issue by acutmore** [preactjs/preact#3822]
**Describe the feature you'd love to see**
When using a Signal in place of text Preact optimizes this to a granular update.
Request: support for the same optimization for other attributes, e.g. `disabled`

```js
function App() {
  const count = useSignal(0);
  const inc = () => count.value++;
  const dec = () => count.value--;
  const incrementDisabled = useComputed(() => count > 1);
  const decrementDisabled = useComputed(() => count < 1);

  console.count("rendering App()"); // we always re-render

  // `disabled={incrementDisabled}`  not supported, not able to directly bind disabled to the signal.
  return (<>
    <span>{count}</span>
    <button onClick={inc} disabled={incrementDisabled.value}>+1</button>
    <button onClick={dec} disabled={decrementDisabled.value}>-1</button>
  </>);
}
```

[repl](https://preactjs.com/repl?code=aW1wb3J0IHugcmVuZGVyLCBGcmFnbWVudCB9IGZyb20gJ3ByZWFjdCc7CmltcG9ydCB7IHVzZVNpZ25hbCwgdXNlQ29tcHV0ZWQgfSBmcm9tICJAcHJlYWN0L3NpZ25hbHMiOwoKZnVuY3Rpb24gQXBwKCkgewoJY29uc3QgY291bnQgPSB1c2VTaWduYWwoMCk7CiAgY29uc3QgaW5jID0gKCkgPT4gY291bnQudmFsdWUrKzsKICBjb25zdCBkZWMgPSAoKSA9PiBjb3VudC52YWx1ZS0tOwogIGNvbnN0IGluY3JlbWVudERpc2FibGVkID0gdXNlQ29tcHV0ZWQoKCkgPT4gY291bnQgPiAxKTsKICBjb25zdCBkZWNyZW1lbnREaXNhYmxlZCA9IHVzZUNvbXB1dGVkKCgpID0%2BIGNvdW50IDwgMSk7CgogIGNvbnNvbGUuY291bnQoInJlbmRlcmluZyBBcHAoKSIpOwoKICByZXR1cm4gKDw%2BCiAgICA8c3Bhbj57Y291bnR9PC9zcGFuPgoJCTxidXR0b24gb25DbGljaz17aW5jfSBkaXNhYmxlZD17aW5jcmVtZW50RGlzYWJsZWQudmFsdWV9PisxPC9idXR0b24%2BCgkJPGJ1dHRvbiBvbkNsaWNrPXtkZWN9IGRpc2FibGVkPXtkZWNyZW1lbnREaXNhYmxlZC52YWx1ZX0%2BLTE8L2J1dHRvbj4KCTwvPik7Cn0KCnJlbmRlcig8QXBwIC8%2BLCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXBwJykpOwo%3D)

Right now passing a signal to `disabled` results in disabled always being truthy.

[repl](https://preactjs.com/repl?code=aW1wb3J0IHugcmVuZGVyLCBGcmFnbWVudCB9IGZyb20gJ3ByZWFjdCc7CmltcG9ydCB7IHVzZVNpZ25hbCwgdXNlQ29tcHV0ZWQgfSBmcm9tICJAcHJlYWN0L3NpZ25hbHMiOwoKZnVuY3Rpb24gQXBwKCkgewoJY29uc3QgY291bnQgPSB1c2VTaWduYWwoMCk7CiAgY29uc3QgaW5jID0gKCkgPT4gY291bnQudmFsdWUrKzsKICBjb25zdCBkZWMgPSAoKSA9PiBjb3VudC52YWx1ZS0tOwogIGNvbnN0IGluY3JlbWVudERpc2FibGVkID0gdXNlQ29tcHV0ZWQoKCkgPT4gY291bnQgPiAxKTsKICBjb25zdCBkZWNyZW1lbnREaXNhYmxlZCA9IHVzZUNvbXB1dGVkKCgpID0%2BIGNvdW50IDwgMSk7CgogIGNvbnNvbGUuY291bnQoInJlbmRlcmluZyBBcHAoKSIpOwoKICByZXR1cm4gKDw%2BCiAgICA8c3Bhbj57Y291bnR9PC9zcGFuPgoJCTxidXR0b24gb25DbGljaz17aW5jfSBkaXNhYmxlZD17aW5jcmVtZW50RGlzYWJsZWR9PisxPC9idXR0b24%2BCgkJPGJ1dHRvbiBvbkNsaWNrPXtkZWN9IGRpc2FibGVkPXtkZWNyZW1lbnREaXNhYmxlZH0%2BLTE8L2J1dHRvbj4KCTwvPik7Cn0KCnJlbmRlcig8QXBwIC8%2BLCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXBwJykpOwo%3D)

**Additional context (optional)**

Rough workaround (not production ready) is to wrap up the native component to limit scope of where the signal is read.

```js
function X(Type, {children, ...props}) {
  for (const k in props) {
    const v = props[k];
    if (isSignal(v)) {
      props[k] = v.value; // unwrap & subscribe to signal
    }
  }
  return <Type {...props}>{children}</Type>;
}
X.button = X.bind(null, "button");

// ...

<X.button disabled={signal} />
```

[repl](https://preactjs.com/repl?code=aW1wb3J0IHugcmVuZGVyLCBGcmFnbWVudCB9IGZyb20gJ3ByZWFjdCc7CmltcG9ydCB7IHVzZVNpZ25hbCwgdXNlQ29tcHV0ZWQsIFNpZ25hbCwgc2lnbmFsLCBjcmVhdGVTaWduYWwgfSBmcm9tICJAcHJlYWN0L3NpZ25hbHMiOwoKZnVuY3Rpb24gaXNTaWduYWwodikgewogICByZXR1cm4gdiBpbnN0YW5jZW9mIFNpZ25hbDsKfQoKZnVuY3Rpb24gWChUeXBlLCB7Y2hpbGRyZW4sIC4uLnByb3BzfSkgewogIGZvciAobGV0IGsgaW4gcHJvcHMpIHsKICAgIGNvbnN0IHYgPSBwcm9wc1trXTsKICAgIGlmIChpc1NpZ25hbCh2KSkgewogICAgICBwcm9wc1trXSA9IHYudmFsdWU7CgkJfQoJfQogIGNvbnNvbGUuY291bnQoYHJlbmRlcmluZyAke1R5cGV9YCk7CiAgcmV0dXJuIDxUeXBlIHsuLi5wcm9wc30%2Be2NoaWxkcmVufTwvVHlwZT47Cn0KWC5idXR0b24gPSBYLmJpbmQobnVsbCwgImJ1dHRvbiIpOwoKZnVuY3Rpb24gQXBwKCkgewoJY29uc3QgY291bnQgPSB1c2VTaWduYWwoMCk7CiAgY29uc3QgaW5jID0gKCkgPT4gY291bnQudmFsdWUrKzsKICBjb25zdCBkZWMgPSAoKSA9PiBjb3VudC52YWx1ZS0tOwogIGNvbnN0IGluY3JlbWVudERpc2FibGVkID0gdXNlQ29tcHV0ZWQoKCkgPT4gY291bnQgPiAxKTsKICBjb25zdCBkZWNyZW1lbnREaXNhYmxlZCA9IHVzZUNvbXB1dGVkKCgpID0%2BIGNvdW50IDwgMSk7CgogIGNvbnNvbGUuY291bnQoInJlbmRlcmluZyBBcHAoKSIpOwoKICByZXR1cm4gKDw%2BCiAgICA8c3Bhbj57Y291bnR9PC9zcGFuPgoJCTxYLmJ1dHRvbiBUeXBlPSJidXR0b24iIG9uQ2xpY2s9e2luY30gZGlzYWJsZWQ9e2luY3JlbWVudERpc2FibGVkfT4rMTwvWC5idXR0b24%2BCgkgIDxYLmJ1dHRvbiBUeXBlPSJidXR0b24iIG9uQ2xpY2s9e2RlY30gZGlzYWJsZWQ9e2RlY3JlbWVudERpc2FibGVkfT4tMTwvWC5idXR0b24%2BCgk8Lz4pOwp9CgpyZW5kZXIoPEFwcCAvPiwgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2FwcCcpKTsK)

related: #3300

**Comment by JoviDeCroock** [comment]
Something might be wrong with our REPL but it works as expected when using the correct bindings as seen [here](https://codesandbox.io/s/upbeat-euclid-k02hdf?file=/src/index.js) basically the difference is

```
  const incrementDisabled = useComputed(() => count.value > 1);
  const decrementDisabled = useComputed(() => count.value < 1);
```

and

```
      <button onClick={inc} disabled={incrementDisabled}>
        +1
      </button>
      <button onClick={dec} disabled={decrementDisabled}>
        -1
      </button>
```

**Comment by acutmore** [comment]
Fantastic! Should I raise an issue specifically for the REPL bug?
