### ISSUE TITLE
Consider adopt millionjs's Deltas idea

### ISSUE THREAD

**Issue by hackwaly** [preactjs/preact#3826]
**Describe the feature you'd love to see**
It avoid run diff algorithm when rendering huge list. I'd love to see preact to get equivalent feature.

**Additional context (optional)**
https://millionjs.org/docs/react/use-list

**Comment by developit** [comment]
This can be accomplished without an API change. It is a standard head/tail optimization in other diffing algorithms. I've prototyped it in Preact at some point.
