### ISSUE TITLE
Infinite loop when using Headless UI Radio Group with Preact

### ISSUE THREAD

**Issue by azdanov** [preactjs/preact#3827]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I was trying to use https://headlessui.com/react/radio-group#basic-example and was hoping that preact/compat would help, but I think it causes an infinite loop.

**To Reproduce**

Preact: https://codesandbox.io/s/preact-headless-ui-radiogroup-2cl9rk?file=/src/index.js
React: https://codesandbox.io/s/react-headless-ui-radiogroup-tcdco9?file=/src/App.js

I had to kill the service worker in Chrome task manager because it is stuck at 99.9 load in Preact example.

Using the simple example from https://headlessui.com/react/radio-group#basic-example

**Expected behavior**
The Preact example is in an infinite loop. I was hoping preact/compat would solve such issues between library interop.

**Comment by rathbone1200cc** [comment]
I see the same with Preact 10.13.2 (current latest) in a deno project.  The problem seems specific to use of the `RadioGroup.Option`.  Any use of this element causes the infinite loop.

**Comment by stevenhales** [comment]
I am also seeing the same. Peculiar.
