### ISSUE TITLE
A React renderer without React 18+ API support is being used with React 18+.

### ISSUE THREAD

**Issue by stitch-05** [preactjs/preact#3841]
**Describe the bug**
When I call [recoil's](https://recoiljs.org/) `useRecoilState()` I get the following error (however the function seems to be working correctly):

`A React renderer without React 18+ API support is being used with React 18+.`

I don't get any error when I use recoil with React. Perhaps I need to setup more/different paths in `tsconfig.json`?

**To Reproduce**

[Clone the repo](https://github.com/stitch-05/wpa-playground) and `npm install && npm run dev`. The problem is [here](https://github.com/stitch-05/wpa-playground/blob/07ec3d42b9a0db676b60191cb05cf87aa0446cc9/src/routes/Profile.tsx#L13).

Quick [Codesandbox](https://codesandbox.io/s/cool-dawn-sjyeur?file=/components/counter.js) code I made, runs with an error related to a renderer so I assume it's the same issue.

**Comment by rschristian** [comment]
I don't believe it's anything for you to fix, no.

Offending function in Recoil can be found here: https://github.com/facebookexperimental/Recoil/blob/f1d2969e0c2dac25877d051829b18cd6addbd0c9/packages/recoil/core/Recoil_ReactMode.js#L35-L74
