### ISSUE TITLE
[Question] How can I run Playwright’s test inside a preact project?

### ISSUE THREAD

**Issue by chrisha22** [preactjs/preact#3843]
I found this plugin https://www.npmjs.com/package/@preact/playwright-ct?activeTab=readme, but there is not enough documentation to test it, and when I try to run `yarn run test-ct`, the below error shows up.

any help is appreciated.

```
[vite]: Rollup failed to resolve import "react" from "playwright/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
Error: [vite]: Rollup failed to resolve import "react" from "playwright/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

is there any other framework I could use on preact for e2e, test automation, etc, testing?

**Comment by chrisha22** [comment]
@andrewiggins @developit could you guys give any direction on this please?

Thanks in advance!

**Comment by rschristian** [comment]
It looks like that package was published with a typo in the repo reference. You can find [the repository here](https://github.com/preactjs/playwright-ct#preact-playwright-component-testing), but while it does have a ReadMe with some instruction, I'm not sure if it's ready for use.

You might need to add an alias for Preact, if you don't already?

**Comment by chrisha22** [comment]
@rschristian , yes I will have to, seeing this issue right now.
[{
	"resource": "/Users/chris22/Documents/project/src/App.spec.tsx",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module '@preact/playwright-ct' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 29,
	"endLineNumber": 1,
	"endColumn": 52
}]

**Comment by rschristian** [comment]
That looks to be the standard TS warning? You can add a ignore comment (`// @ts-ignore`) on the line above your import if need be.

Alternativly, you can try setting `"moduleResolution": "NodeNext"` in your `tsconfig.json` as the library itself does here: https://github.com/preactjs/playwright-ct/blob/main/tsconfig.json#L4

Not 100% sure of the second suggestion, I'm rather unfamiliar with newer TS stuff.

**Comment by chrisha22** [comment]
@rschristian `"moduleResolution": "NodeNext"`, solved the warning

**Comment by chrisha22** [comment]
After running `yarn run test-ct `, I am still seeing this error about `Rollup failed to resolve import "react" from "playwright/index.ts`
https://github.com/preactjs/preact/issues/3843#issue-1512136905

**Comment by JoviDeCroock** [comment]
Hey, I quickly updated our dependencies and ran the tests which seemed to work. Any additional info or reproduction you can give here? 😅 

In my test I did
`playwright test -c playwright-ct.config.ts` with the following config

```js
import { devices, PlaywrightTestConfig } from "@preact/playwright-ct;

const config: PlaywrightTestConfig = {
  timeout: 10000,
  use: {
    ctPort: 3100,
  },
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },
  ],
};

export default config;

```

**Comment by chrisha22** [comment]
@JoviDeCroock I'll make use your config and try to run tests again, maybe this config helps. Thanks

**Comment by chrisha22** [comment]
Hey, It worked!, thanks guys, I appreciate your help!!

**Comment by JoviDeCroock** [comment]
@chrisha22 thanks for checking, made a PR to update our readme and will try to publish that so the instructions are on npm
