### ISSUE TITLE
ErrorBoundary couldn't work as well as we expect.

### ISSUE THREAD

**Issue by lwsys** [preactjs/preact#3850]
- [ x ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
ErrorBoundary couldn't work as well as we expect.

**To Reproduce**

When I use vite initialize a preact project, I just add a ErrorBoundary blow on App Component, and I cause a error but preact not catch it.

If possible, please provide a CodeSandbox/Codepen that demonstrates the issue. You can use the following template: https://codesandbox.io/s/elegant-shockley-xu2y3l?file=/routes/index.js:85-98
or a github demo [ErrorBoundary couldn't work as well as we expect.](https://github.com/lwsys/preact-error-boundary)

1. Go to render panel
2. Click on button
3. See console and find a uncatch error.

**Expected behavior**
What should have happened when following the steps above?
Catch the error.

**Comment by JoviDeCroock** [comment]
Error boundaries aren't meant to work for event-handlers as those aren't really part of the VDOM tree.

**Comment by lwsys** [comment]
Thank for you reply.
