### ISSUE TITLE
The input element is not controlled

### ISSUE THREAD

**Issue by NicolasKeita** [preactjs/preact#3851]
### Discussed in https://github.com/preactjs/preact/discussions/3848

<div type='discussions-op-text'>

<sup>Originally posted by **NicolasKeita** January  4, 2023</sup>
Hi I am moving my thread from discussion to Issue.

```
const App = () => {
	const input = '50'

	return (
		<div>
			<input value={input} />
		</div>
	)
}
```

**is not supposed to change the displayed value if I don't rerender.**

Preact is making the input component **uncontrolled** which is not specified in the preact documentation because it is probably a **unwanted** bug :boom: on preact part.

If you don't know what I mean by uncontrolled components : https://preactjs.com/guide/v8/forms/#controlled--uncontrolled-components

I can temporally use the DOM value (instead of the prop called "value") with useRef to do the work.

```

console.log(`rerender somehow then check value : ${myRef.current.value}`)
...
<input value={input} ref={myRef} />

```

**Comment by JoviDeCroock** [comment]
We don't have synthetic events i.e. in the dom components are always uncontrolled. There are ways around it, [this might give some insights](https://www.jovidecroock.com/blog/controlled-inputs)
