### ISSUE TITLE
Add support for ShadowDOM outside of Web Components.

### ISSUE THREAD

**Issue by MicahZoltu** [preactjs/preact#3865]
**Describe the feature you'd love to see**
Use a normal Preact component (with all of the usual syntax/features) but be able to apply a `<style>` to it that is constrained to just that component.

**Additional context (optional)**
Preact supports the creation of [Web Components ](https://preactjs.com/guide/v10/web-components), which provide the ability to constrain styles to a single component, but building a Web Component is quite different from building a regular preact component as you need to register it and do some magic to get component properties to correctly apply to the Web Component.

**Alternatives**
Better documentation around Web Components and improved TypeScript support may mitigate this need somewhat.  Unfortunately, the current docs are fairly sparse and if you naively follow them you end up struggling with TypeScript (the docs are all in JS with no hints on how to make things work in TS) and any complex properties require special care (setters and such) that isn't well described in the Guide.

While improved documentation around Web Components would certainly help, it would be preferable if one could just do
```jsx
<div shadow><style>...</style>shadow styled text</div>
```
in their component and get style containment without needing to go learn a complex system for creating web components.

**Comment by marvinhagemeister** [comment]
Out of curiosity: Are you more interested in web components in itself or is the scoping/constraining of styles to a particular part of the DOM the thing you're interested in?

**Comment by MicahZoltu** [comment]
Scoping styles is my primary interest.  If I could *easily* solve that with Web Components (without needing to learn a new complicated thing with its own set of constraints and edge cases) then that would be an acceptable solution to me.

I ended up building this to try to solve the problem, though I suspect it has a ton of bugs and problems that I will suffer through at some point in the future:
```ts
import { render, createElement, ComponentChildren, Fragment } from 'preact'

export function Shadow({ children }: { children: ComponentChildren }) {
	return createElement('span', {
		ref: host => {
			if (host == null) return
			const shadowRoot = host.shadowRoot || host.attachShadow({mode: 'open'})
			Array.isArray(children)
				? render(Fragment({ children }), shadowRoot)
				: render(children, shadowRoot)
		}
	})
}
```

**Comment by hbroer** [comment]
Just my opinion: Someone can archive kind of scoping easily and without magic by using css modules. And in case someone want a independent slim web component he/she can just write one outside of (p)react and use it whereever he/she want. That's  a great way to build a reuseable styled set of simple components for a company/organisation. You may be able to create shadow dom inside of your (p)react app, but how should your bundler know that the css now is just ment to be in that scope and adding styles inline there and everything outside is then handeled differently. Also you can't use normal components inside a Shadow component then. In that case the styles have to be duplicated, and again bundler does not know. It is rly only my opinion but it is complicated and not intuitive to work with. But I may be worng and just don't know what you rly want to achieve.

**Comment by MicahZoltu** [comment]
I don't use a bundler, so CSS modules aren't really a viable option, and it means I don't need to worry about teaching my bundler how to scope CSS.

> Also you can't use normal components inside a Shadow component then.

Why not?  I am able to use preact components inside the above Shadow component without much trouble.  It does mean they can't pull in external styles, but they can still receive local styles

**Comment by rschristian** [comment]
I think this is better addressed with the new [`@scope`](https://developer.mozilla.org/en-US/docs/Web/CSS/@scope) rule or in userland, supporting it ourselves seems quite niche at best.

**Comment by MicahZoltu** [comment]
Yes, @scope looks like a good solution for my use case.  I wasn't aware of it until now, so thanks for the link!
