### ISSUE TITLE
Support Shadow DOM in createPortal()

### ISSUE THREAD

**Issue by meyfa** [preactjs/preact#3869]
**Describe the feature you'd love to see**
I'd love to use `createPortal()` with a `ShadowRoot` as container. This is indeed possible in React:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cb261099d9a316fb628efc7801a9d0f25451cd67/types/react-dom/index.d.ts#L28

`createPortal()` accepts `Element | DocumentFragment`, and ShadowRoot inherits from DocumentFragment.
In Preact it's not possible, at least not when using TypeScript:

https://github.com/preactjs/preact/blob/2cafedee2ddf7c73795e887ef1970df4be2bca90/compat/src/index.d.ts#L75-L78

**Additional context (optional)**
From looking at the `createPortal()` implementation, I think this may already work at runtime, but the types are too restrictive. I did try casting the container argument to `any`, and no error was thrown, and the content was rendered as expected.

**Comment by ApurvaBasule** [comment]
@marvinhagemeister i would like to work on this issue.

**Comment by lightningspirit** [comment]
Anyone that is struggling with this issue, meanwhile there's no native support for shadow root in `createPortal`, I was able to achieve a Portal that renders a Shadow DOM adding `react-shadow` as dependency:
```tsx
import { h } from 'preact';
import { createPortal } from 'preact/compat';
import root from 'react-shadow';

interface ShadowPortalProps {
  children: preact.ComponentChildren;
}

const ShadowPortal = ({ children }: ShadowPortalProps) => {
  return createPortal(
    <root.div>
      {children}
    </root.div>,
    document.body
  );
};

export default ShadowPortal
```
