### ISSUE TITLE
Component with shouldComponentUpdate won't get re-rendered when its parent component is updated at the same time

### ISSUE THREAD

**Issue by kmxz** [preactjs/preact#3883]
Reproduced with Preact 10.11.3.

**Describe the bug**

For a component with `shouldComponentUpdate` (for example, a `PureComponent`), calling `setState` with a new state value does not cause it to re-render, if the parent component is updated at the same time.

**To Reproduce**

https://codepen.io/kmxz/pen/bGjzvbR

**Expected behavior**

In the example above, the new `state.text` value "Child-NEW" should be rendered, instead of the stale `state.text` value "child-old".

Rendering the exact same demo code using *React* gives the correct behavior (https://codepen.io/kmxz/pen/rNrPJEq).

**Comment by JoviDeCroock** [comment]
Hey, thank you for the accurate reproduction this was an error in how we deal with [strict equality](https://gist.github.com/JoviDeCroock/bec5f2ce93544d2e6070ef8e0036e4e8) and we have a fix lined up in #3884
