### ISSUE TITLE
Images with width=100% don't client side render correctly

### ISSUE THREAD

**Issue by jpnelson** [preactjs/preact#3887]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When client side rendering an image with width: 100%, the resulting image has a width of zero.

I think the issue is here specifically: https://github.com/preactjs/preact/blob/c483d9606b1ae62468ca07b4e27d478108249b81/src/diff/props.js#L121

It seems as though Preact tries to set `img.width = '100%'` and only tries to do `img.setAttribute('width', '100%')` if that fails. The issue is that `img.width = '100%'` does not cause an exception, but it does coerce the string to an integer and ultimately sets the image width to zero. `img.width` when accessed as as property is meant to be only an integer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width

**To Reproduce**
https://codesandbox.io/s/preact-images-csr-only-lrpkbp?file=/src/App.js

Load the page. Expected: the sandbox has an image with width=100%. Actual: the image is not visible since it has width=0

**Comment by JoviDeCroock** [comment]
This is live in 10.12.1
