### ISSUE TITLE
using <></> fragments without importing Fragment?

### ISSUE THREAD

**Issue by srsudar** [preactjs/preact#3901]
My sincere apologies if this is covered elsewhere, I'm having trouble googling it.

I'm aware that preact supports `<Fragment>`s, and that they can be used like so:

```
import { h, Fragment } from 'preact';
...
<Fragment>...</Fragment>
```

I have a pragma set up so that I can use `<></>` instead of `<Fragment></Fragment>`. However, when I do this, I still need to manually import `Fragment` from preact or else I get an error. This is a bit of a footgun for newcomers in the codebase, and it confuses my linter, which thinks that `Fragment` is unused.

Is this a configuration that allows people to still use `<></>` and that does not require importing `Fragment`? Or a preact lint rule I'm missing that enforces it?

**Comment by marvinhagemeister** [comment]
Yes this works and from your description it sounds like it's a configuration issue in the stack you're using. Can you share more about that?

**Comment by developit** [comment]
Using fragments without importing `Fragment` is only possible if you use the "automatic" JSX runtime:

https://babeljs.io/docs/en/babel-preset-react#react-automatic-runtime

https://www.typescriptlang.org/tsconfig#:~:text=For%20example%20if%20you%20wanted%20to%20use%20%22jsxImportSource%22%3A%20%22preact%22%2C%20you%20need%20a%20tsconfig%20like%3A

**Comment by srsudar** [comment]
Hmm, interesting... I'm going to poke around a bit and try and figure it out. Will report back.

**Comment by marvinhagemeister** [comment]
Closing as we haven't heard back, so we're assuming the "automatic" JSX runtime worked for the user.

**Comment by srsudar** [comment]
I wound up getting stuck trying to figure out our byzantine build progress. Didn't get it working yet but have enough to go on, and I'm happy with this closed. Thanks!
