### ISSUE TITLE
Question regarding Preact approach to hydration 

### ISSUE THREAD

**Issue by s-ve** [preactjs/preact#3917]
Hello, our team is considering implementing a custom C# server-side pre-renderer for our current react application. However, we are hesitant due to the statement in [React's documentation](https://beta.reactjs.org/reference/react-dom/hydrate) that `hydrate` expects the content to strictly match the content generated by `react-dom/server`. This seems to suggest that React may implement additional "magic" in `react-dom/server` that our custom C# pre-renderer may not be able to keep up with (e.g. additional DOM metadata using HTML comments or attributes).

We'd like to know if Preact is taking a similar approach to hydration as React, or if we can expect a relatively naive pre-rendering custom implementation to continue working with future versions of Preact. 

Thank you!

Note : I apologize if this is not the appropriate place for this question and would be happy to post elsewhere if needed.

**Comment by JoviDeCroock** [comment]
Hey,

We don't inject additional metadata, the only thing we ask (and no we don't throw errors for this) is that the HTML structure you produce on the server matches the one on the client. If you want to see how we exactly do render to a HTML string, you can find the code [here](https://github.com/preactjs/preact-render-to-string/blob/master/src/index.js).

Our `hydrate` will bail if it sees a difference and revert to client-side rendering which is slower.

Currently we are working on a streaming renderer which does inject additional metadata but the core Preact algo does not expect anything, it will look at your VDOM and the DOM it produces and it will have resemble what your server sent back.

**Comment by s-ve** [comment]
It's great to hear that preact doesn't plan to require additional metadata for the hydration to work. Thanks a lot for your quick and detailed response!
