### ISSUE TITLE
react-test-renderer compatibility issue

### ISSUE THREAD

**Issue by abhicoo** [preactjs/preact#3923]
Hi, 

We have and existing react app in which we are using react-test-renderer for testing.
I am following the doc https://preactjs.com/guide/v10/switching-to-preact to keep compatibility with react but while running test-cases getting below error

Objects are not valid as a React child (found: object with keys {type, props, key, ref, __k, __, __b, __e, __d, __c, __h, constructor, __v, __source, __self}). If you meant to render a collection of children, use an array instead.

**Comment by marvinhagemeister** [comment]
The react-test-renderer relies on very specific React internals and therefore doesn't work with Preact. Supporting that means to basically having to copy React 1:1 including all their internals at which point you should use React in the first place.

Instead, to test Preact apps most folks use [preact-testing-library](https://github.com/testing-library/preact-testing-library). It's very widespread and ensures that developers test their components actual behaviours vs their implementation details.
