### ISSUE TITLE
Dynamically import SVGs

### ISSUE THREAD

**Issue by wmonecke** [preactjs/preact#3924]
**Describe the feature you'd love to see**
It would be pretty cool to be able to do render svg icons like this `<Icon name='spinner' />` if I had a `spinner.svg` in my assets folder.

My current approach for something like this is to dynamically import the SVGs at runtime via a hook:

```javascript
import { FunctionComponent } from 'preact';
import { useEffect, useRef, useState } from 'preact/hooks';

type Props = {
  name: string;
};

export const useDynamicSVGImport = ({ name }: Props) => {
  const ImportedIconRef = useRef<
    FunctionComponent<SVGElement> | undefined
  >();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error>();

  useEffect(() => {
    setLoading(true);

    const importIcon = async (): Promise<void> => {
      try {
        const imported = await import(`../../assets/icons/${name}.svg`).then(
          module => module.default,
        );

        // logs: /src/assets/icons/spinner.svg if I pass name = spinner
        console.log('imported', imported); 

        ImportedIconRef.current = imported;
        
      } catch (err) {
        console.log(err);

        setError(err);
      } finally {
        setLoading(false);
      }
    };

    importIcon();
  }, [name]);

  return {
    loading,
    error,
    SvgIcon: ImportedIconRef.current,
  };
};
```

How would I extract the svg from the path `/src/assets/icons/spinner.svg`  so I can use it in my `Icon` component?

EDIT: I know I can pass this to an `<img src={path} />` tag but then I am unable to change the SVG props like fill color.

**Comment by rschristian** [comment]
This is more of a build tooling issue, what are you using?

**Comment by wmonecke** [comment]
@rschristian I am using vite + preact!

**Comment by rschristian** [comment]
You're probably looking for [`vite-svg-loader`](https://github.com/jpkleemans/vite-svg-loader#readme) or [`vite-plugin-svgr`](https://github.com/pd4d10/vite-plugin-svgr#readme) then. Unrelated to Preact really.

**Comment by wmonecke** [comment]
[vite-svg-loader](https://github.com/jpkleemans/vite-svg-loader#readme) is for Vue and [vite-plugin-svgr](https://github.com/pd4d10/vite-plugin-svgr#readme) doesnt really let you do dynamic imports. That's the issue I saw when I viewed those projects before opening this issue.

I would like to set currentColor dynamically - that is the issue I have. I can of course hard code it in the .svg but I need the icons to be able to change colors.

**Comment by rschristian** [comment]
> [vite-svg-loader](https://github.com/jpkleemans/vite-svg-loader#readme) is for Vue

Whoops, totally right. I missed that.

> I would like to set currentColor dynamically

`currentColor`, in case you were unaware, _is_ dynamic. See: https://stackblitz.com/edit/vitejs-vite-japz9b?file=src/assets/preact.svg
