### ISSUE TITLE
typescript complains with SignalLike as property boolean on default

### ISSUE THREAD

**Issue by srsudar** [preactjs/preact#3934]
- [x] Check if updating to the latest Preact version resolves the issue (it does not)

**Describe the bug**

I'm getting some confusing type errors about a `default` attribute of type `Type 'boolean | SignalLike<boolean>' is not assignable to type 'boolean'.`. I can't figure it out, and it seems similar to the issue described here:

https://github.com/preactjs/preact/issues/3808

Hoping for some assistance.

**To Reproduce**

Unfortunately I can't get the codesandbox to work, but I have created a sample repo here:

https://github.com/srsudar/preact-problems

1. Clone the repo
2. run `npm install`
3. run `npx tsc --project ./tsconfig.json`
4. observe the following type error:

```
src/components/buttons.tsx:36:6 - error TS2322: Type '{ children: never[]; href?: string | (string & SignalLike<string>); accept?: string | SignalLike<string>; acceptCharset?: string | SignalLike<string>; ... 383 more ...; 'aria-valuetext'?: Signalish<...>; }' is not assignable to type 'IntrinsicAttributes & Omit<UnstyledButtonProps, "ref"> & { ref?: Ref<HTMLButtonElement>; } & Readonly<Attributes & { ...; }>'.
  Type '{ children: never[]; href?: string | (string & SignalLike<string>); accept?: string | SignalLike<string>; acceptCharset?: string | SignalLike<string>; ... 383 more ...; 'aria-valuetext'?: Signalish<...>; }' is not assignable to type 'Readonly<Attributes & { children?: ComponentChildren; ref?: Ref<any>; }>'.
    Types of property 'default' are incompatible.
      Type 'boolean | SignalLike<boolean>' is not assignable to type 'boolean'.
        Type 'SignalLike<boolean>' is not assignable to type 'boolean'.

36     <UnstyledButton
```

**Expected behavior**

As far as I can tell, this should be a legal type. I don't see anywhere that I might be redefining `default`.

Somehow it looks like `SignalLike<boolean>` isn't correctly being coerced to a `boolean`? Or a type definition somewhere needs to also accept a `SignalLike<T>`?

I've struggled to google this, so apologies if I'm missing something obvious. I originally said on [this issue](https://github.com/preactjs/preact/issues/3808) that it appeared to be tied to a preact version, but I'm not sure that's actually the case. It might instead be tied to the `forwardRef` generic types [introduced](https://github.com/preactjs/preact/releases/tag/10.5.14) in `10.5.14`? This is at least when I began seeing the issue.

I'd welcome any pointers! I need `flushSync()`, which was introduced in `10.5.14`, but I'm hesitant of punting on getting the types right.

**Comment by srsudar** [comment]
Well that is amazing sleuthing, thank you! Sounds like it's safe for a `@ts-expect-error` for now.

Can I ask how you figured that out? I spent a lot of time trying to track down definitions and failed. I'm wondering if there are some handy `tsc` commands of which I'm oblivious or something.

**Comment by marvinhagemeister** [comment]
I right clicked on the `default` property name in our typings to see where it was referenced and two vscode showed me two instances instead of only one. The first one is from `preact-router` and the second one is the actual one from preact itself.

<img width="1003" alt="Screenshot 2023-03-16 at 14 21 32" src="https://user-images.githubusercontent.com/1062408/225630022-48fb7b72-3888-491e-ba4c-0624fad45695.png">

**Comment by srsudar** [comment]
Wow, I need to get better at this. Would have saved me so much time. VSCode's is way better than what I get out of Webstorm, though I'm usually in vim. I'd be happy to take a stab at fixing it if you had any ideas on direction. Way above my normal level of typescript ability.

**Comment by marvinhagemeister** [comment]
My assumption would be that the fix is probably to drop the definitions for `default` in `preact-router`. It's the same type as in `preact` itself so that should be fine.

**Comment by srsudar** [comment]
Ah, I thought it was something in preact given your comment that it's a bug in the preact typings.

Giving it a go here. We shall see:

https://github.com/preactjs/preact-router/pull/440

**Comment by rschristian** [comment]
Should we just remove the namespace merging instead? It's only there to support using HTML elements as router children, right? How often does that come up?

We have the same issue in `preact-iso` too, fwiw. I can mirror a change over there.

**Comment by rschristian** [comment]
> My assumption would be that the fix is probably to drop the definitions for default in preact-router. It's the same type as in preact itself so that should be fine.

Took a look today, and this doesn't seem right. Users will no longer be able to use `<Home default />` for routes. I think we'll need an `Omit` or something here in Preact's types, but I'm no TS wizard.

**Comment by srsudar** [comment]
Amazing, thank you!

**Comment by marcushultman** [comment]
I get the same error when I forward the `className` property of my interface that extends `JSX.HTMLAttributes<HTMLButtonElement>` to a function that takes `string | undefined`:
```
Argument of type 'string' is not assignable to parameter of type 'TemplateStringsArray'.  Overload 2 of 2, '(...tokens: Token[]): string', gave the following error.
    Argument of type 'string | SignalLike<string | undefined> | undefined' is not assignable to parameter of type 'Token'.
```
The function is a third-party lib ([twind](https://esm.sh/twind@0.16.19)), so it's not easy to change the function.

**Comment by rschristian** [comment]
I think you'll need to resort to `// @ts-ignore` or patching types in that case, I don't know of any better options.
