### ISSUE TITLE
preact/compat not working Node.js

### ISSUE THREAD

**Issue by krutoo** [preactjs/preact#3951]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Trying to render to string in Node.js throws:
```
Error: renderToString() error: missing "preact-render-to-string" dependency.
```

**To Reproduce**

Repo with minimum of code: https://github.com/krutoo/try-preact-compat

1. Clone repo
2. Install deps via `npm i`
3. Run `npm run dev`

**Expected behavior**
Because of `preact-render-to-string` in list of deps there should be no errors here

## P.S.

I changed `node_modules/preact/compat/server.js`

like this:
```
/* eslint-disable */
var renderToString;
try {
	const mod = require('preact-render-to-string');

        // safe access to props
	renderToString = mod?.default || mod?.renderToString || mod;
} catch (error) {
        // log original error
	throw Error(
		'renderToString() error: missing "preact-render-to-string" dependency.' + error
	);
}

module.exports = {
	renderToString: renderToString,
	renderToStaticMarkup: renderToString
};
```

and it is workking until fisrt incoming request to express server

after that it crashes with an error
```
TypeError: (0 , server_1.renderToStaticMarkup) is not a function
```

**Comment by marvinhagemeister** [comment]
This looks like the same issue as https://github.com/preactjs/preact-render-to-string/issues/290 .

Until that is fixed you can downgrade to `preact-render-to-string` version `5.2.6` as a workaround.

**Comment by krutoo** [comment]
@marvinhagemeister Thank you so much

Can you tell why this package is not automatically installed in dependencies?

**Comment by krutoo** [comment]
> > Can you tell why this package is not automatically installed in dependencies?
> 
> Not everyone needs it. So it's not installed by default.

@marvinhagemeister is it possible to make this a peer dependency?

**Comment by rschristian** [comment]
Maybe we could add & mark it as an optional peer dep, though I don't know if all tools follow that spec (`peerDependenciesMeta`).
