### ISSUE TITLE
Component re-renders indefinitely when changing state on render

### ISSUE THREAD

**Issue by jayrobin** [preactjs/preact#3959]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When changing state on render Preact will re-render indefinitely rather than throwing a "Too many re-renders" error.

**To Reproduce**

[codesandbox](https://codesandbox.io/s/flamboyant-ben-c2ulj1?file=/index.js)

```js
import { render } from 'preact';
import { useState } from 'preact/hooks';

let rerenderCount = 0;
function App() {
  const [, setValue] = useState({});
  console.log('rendering', rerenderCount);
  rerenderCount++;

  if (rerenderCount < 50) {
    setValue({});
  }

  return (
    <div>Counter: {value}</div>
  );
}

render(<App />, window.root);
```

**Expected behavior**

Logs `rendering 0` to `rendering 24`, then throws "Too many re-renders" error ([similar to React](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=301) - [thrown here](https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberHooks.js#L703-L708))

**Actual behavior**

Logs `rendering 0` to `rendering 49`. If you remove the `rerenderCount < 50` conditional, it will run indefinitely and crash the browser.

**Comment by rschristian** [comment]
When using `preact/debug`, which most Preact users will use in dev, #4349 addresses this.

React does seem to also detect infinite loops in prod too so I think we'll keep this open for the moment to better gauge whether we need a check/limit in `preact/compat` (or `preact` itself, I suppose)

**Comment by JoviDeCroock** [comment]
We do already have a check in place that it doesn't infinitely render but I reckon that maybe it still pushes to the `_component` queue and hence can still loop https://github.com/preactjs/preact/blob/main/src/diff/index.js#L224

**Comment by JoviDeCroock** [comment]
This is fixed in latest
