### ISSUE TITLE
useState/useEffect hooks management

### ISSUE THREAD

**Issue by UnrealEngineer** [preactjs/preact#3961]
Hello, there!
I'm new to Preact and I don't know is this related to the `preact`, `preact-cli` or `preact-router` but I hope maybe somebody could give me a hint where to dig :) 

When I'm working in the `dev` environment, all `useState` and `useEffect` hooks work as expected. Switching between the routes re-initiate the state of the components and `useEffect` hooks doing their work (fetch API, read/write Local Storage, etc.).
But when I'm working with a bundled app (`serve -s build`) the behavior is different.

1. Open "Home" page -> OK;
2. Change path to `/player/123` in the address bar -> OK;
3. Click on browser's "Go back"/"Go forward" buttons -> 
3.1. `useState` values have previous values;
3.2. `useEffect` hooks with `fetch` don't trigger anymore;
3.3. `useEffect` hooks with `setTimeout` have not been cleaned up on unmount;
3.4. `useEffect` hooks with Local Storage access don't update its items with the new values, e.g. there is no possibility to update timestamp in the Local Storage on the component mount. It has the initial value (when the page was opened at the first time).

Basically the whole node tree looks like a snapshot of its last state.

Please let me know what is going on here, what I'm doing wrong ;P
Thanks.

```jsx
import { Route, Router } from 'preact-router';

import Home from 'routes/home';
import Player from 'routes/player';

function App() {
  return (
    <div class="w-screen h-screen overflow-hidden font-normal font-noto">
      <Router>
        <Route path="/" component={Home} default />
        <Route path="/player/:id" component={Player} />
      </Router>
    </div>
  );
}

export default App;
```

```jsx
import Store from 'context/Store';
import Player, { PlayerProps } from 'components/Player';

type PlayerPageProps = PlayerProps;

function PlayerPage({ id }: PlayerPageProps) {
  return (
    <Store>
      <Player id={id} />
    </Store>
  );
}

export default PlayerPage;
```

```jsx
import { useState, useEffect } from 'preact/hooks';

import useGetSpot from 'hooks/useGetSpot';
import { loadSpotFonts } from 'utils/loadFonts';

import Debugger from 'components/Debugger';
import PlayerSlides from './PlayerSlides';

export type PlayerProps = {
  id: string;
};

function Player({ id }: PlayerProps) {
  const [spot, setSpot] = useState();
  
  useGetSpot(id, setSpot);

  useEffect(() => {
    if (spot) loadSpotFonts(spot);
  }, [spot]);


  if (!spot?.items?.length) return null;

  return (
    <div class="w-full h-full">
      <PlayerSlides items={spot.items} />
      <Debugger />
    </div>
  );
}

export default Player;
```

**Comment by rschristian** [comment]
Sorry for the long time without a response, but I cannot reproduce from what I pieced together.

We can reopen this in the chance you're still having some issue, but we'd need a minimal reproduction in some form.
