### ISSUE TITLE
Messed up tables with rowSpan/colSpan

### ISSUE THREAD

**Issue by Yukicanis** [preactjs/preact#3969]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When rendering a table that uses a lot of rowSpan/colSpan, the table gets messed up after changes.
This used to work in Preact 8.

**To Reproduce**

Example: https://codepen.io/yukicanis/pen/LYgGRdJ
Clicking the table alternates between two different tables.

1. Click the table two times.
2. The table does not revert to the original table.

**Expected behavior**
The table should revert to the original table.

**Comment by marvinhagemeister** [comment]
Took a quick look at this and the issue is caused by setting `rowspan="0"` instead of removing it.
