### ISSUE TITLE
iframe is reloaded when siblings before it in a list are removed

### ISSUE THREAD

**Issue by sicknarlo** [preactjs/preact#3973]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Seems similar to [this previously resolved bug](https://github.com/preactjs/preact/issues/2350)

Basically if you have a list of nodes with one that renders an iframe anywhere besides the first position, if all of the elements before it are removed the iframe is reloaded on the next render.

**To Reproduce**

https://codesandbox.io/s/jolly-sinoussi-n92mru?file=/src/test.js:320-331

1. Go to https://codesandbox.io/s/jolly-sinoussi-n92mru?file=/src/test.js:320-331
2. Click on "Toggle" -- this will remove the test elements from the dom
3. See the iframe reload

**Expected behavior**
The iframe should not reload

**Comment by InfiniteXyy** [comment]
Seems when iframe is inside a children props, this issue will happen again in `10.16.0`
https://codesandbox.io/s/flamboyant-voice-tg646l?file=/src/test.js
