### ISSUE TITLE
Unexpected behaviour with eventListeners (preact component and react wrapper)

### ISSUE THREAD

**Issue by RoseannePeeters** [preactjs/preact#3978]
- [x] Check if updating to the latest Preact version resolves the issue
It is the latest version

**Describe the bug**
I am trying to solve this [issue](https://github.com/missive/emoji-mart/issues/819) in a project that uses preact component and wraps it with a react wrapper. It is an emoji picker, it has a property in which the developer can define handleClickOutside (outside of the picker). To handle this they use an eventListener attached to the document, to unregister this event and register it they use componentWillUnmount and componentWillMount. The event seems to be properly removing from the `<html>` tag but the functionality seems to be bugged within react synthetic events or preact. The behaviour goes from the document element to a button on the page. This is the button to open the emoji-picker, but since the handleClickOutside is on there, it briefly sets the state to true and then instantly false, so it is not rerendered.

**To Reproduce**
Install @emoji-mart/react and emoji-mart dependencies.
See reproduction in codesandbox.
https://codesandbox.io/s/strange-zeh-20z3tz?file=/src/App.js

1. Click the button to open the picker (eventListener is added to `<html>`)
2. Click outside the picker (It closes, eventListener is removed from `<html>`)
3. Try to open the picker again. It doesn't. 
4. I have put a print statement inside the emoji-mart/Picker.tsx  source code that says "I am running", when clicking on the button.
5. Oddly enough it prints, so the eventListener from the document has been passed to the button????

**Expected behavior**
eventListener should be removed and the behaviour should not be there anymore.

**Comment by marvinhagemeister** [comment]
Thanks for opening an issue. I'm not sure I understand the relation to Preact with this issue. The linked codesandbox doesn't seem to use Preact at all. I can't find it in `package.json` or anywhere else in the dependency tree for that matter.

Given that the emojipicker is written for React and that the codesandbox shows that it doesn't work with React, I'd assume that there is simply a bug in the emoji picker and the way they attach their events. Most likely they don't remove one properly or the event bubbling triggers both events or something.

**Comment by rschristian** [comment]
@marvinhagemeister

Took a brief look earlier: [the base picker is Preact](https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart/src/components/Picker/Picker.tsx), then given a [React wrapper](https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart-react/react.tsx).

It looks like they inline Preact into `emoji-mart`, hence why you don't see it in the tree.

**Comment by RoseannePeeters** [comment]
> Thanks for opening an issue. I'm not sure I understand the relation to Preact with this issue. The linked codesandbox doesn't seem to use Preact at all. I can't find it in `package.json` or anywhere else in the dependency tree for that matter.
> 
> Given that the emojipicker is written for React and that the codesandbox shows that it doesn't work with React, I'd assume that there is simply a bug in the emoji picker and the way they attach their events. Most likely they don't remove one properly or the event bubbling triggers both events or something.

As @rschristian had mentioned correctly above, [the component (picker) ](https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart/src/components/Picker/Picker.tsx)itself is preact, but the [@emoij-mart/react ](https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart-react/react.tsx)is the react wrapper for it. 

Info for your query: The eventListener is added on componentWillMount and componentWillUnmount. In these respective functions they handle document.removeEventListener() and document.addEventListener . I have debugged and visually seen in devtools that the eventListener is added to the `<html>` tag, and is also successfully removed. However the behaviour jumps from it to the button as in my print statement, which can be tested in codesandbox.

I strongly suggest this would either be a bug in preact or react, since I don't see anything that is moving the behaviour between elements inside the emoji-mart code

**Comment by developit** [comment]
This is due to the way React's synthetic event system works. To fix it, I would recommend calling `e.stopPropagation()` in your `handleEmojiClick()` function instead of `e.preventDefault()`:

```diff
  function handleEmojiClick(e) {
-   e.preventDefault();
+   e.stopPropagation();
    setEmojiPickerShown(!emojiPickerShown);
  }
```

With the above change, you can see your codesandbox working here:
https://codesandbox.io/s/elated-ace-mxo6bd?file=/src/App.js:341-366

**Comment by RoseannePeeters** [comment]
> This is due to the way React's synthetic event system works. To fix it, I would recommend calling `e.stopPropagation()` in your `handleEmojiClick()` function instead of `e.preventDefault()`:
> 
> ```diff
>   function handleEmojiClick(e) {
> -   e.preventDefault();
> +   e.stopPropagation();
>     setEmojiPickerShown(!emojiPickerShown);
>   }
> ```
> 
> With the above change, you can see your codesandbox working here:
> https://codesandbox.io/s/elated-ace-mxo6bd?file=/src/App.js:341-366

Thanks for your response, I had already found this fix to work but I wanted to fix the bug so that e.stopPropogation was not needed. I thought it had to be a bug in either preact or react. You mentioned this is because of react synthetic events. But how exactly does the behaviour from one object get passed to the other? The picker element is not even being rendered anymore when the behaviour is there. Could you link me or provide me some more info on how this behaviour is still there and gets passed to the other element? Would love to learn more about this.

Thanks in advance,
Kind regards,

**Comment by thatguyjono94** [comment]
@RoseannePeeters a little bit late but I was looking at this myself when using the emoji picker earlier today. I've basically concluded that it's not a bug (or a react/preact/emoji-mart issue) but rather expected js behavior in regards to how events work.

Here's why:

Events in javascript "bubble" meaning once fired it goes back up the DOM tree, and any event listeners on nodes further up the tree will also be notified of the same event (in this case it is a click event). So when you click on the button that shows the emoji picker, what happens is that it fires a "click" event which in turn will eventually bubble up to the `document.addEventListener()` function that emoji-mart Picker component has registered on it's mount hook.

So here's how I visualise it in order of execution:

1) User clicks button to show the emoji picker (click event gets fired)
2) Emoji picker is shown (rendered in the virtual DOM) + global click listener gets registered by the emoji library
3) Original click event continues to "bubble" up the DOM till it reaches the global event listener
4) EmojiPicker is hidden again from a seState call

I hope this makes sense, but it's a common js gotcha when dynamically setting global event listeners from an original event.

Here's a vanilla js example from SO showing the same problem:

https://stackoverflow.com/questions/27037272/addeventlistener-fires-automatically-upon-assignment
