### ISSUE TITLE
Cannot find package 'react' imported from /Users/vayne/wmqj/animal-friends/node_modules/.pnpm/swiper

### ISSUE THREAD

**Issue by vaynevayne** [preactjs/preact#3983]
"pnpm": {
    "overrides": {
      "react": "pnpm:@preact/compat@latest",
      "react-dom": "pnpm:@preact/compat@latest"
    }
  },
  
  overrides is not work

**Comment by rschristian** [comment]
Use the normal Node aliases, PNPM should support it:

```json
{
  "dependencies": {
    "react": "npm:@preact/compat",
    "react-dom": "npm:@preact/compat",
  }
}
```

https://preactjs.com/guide/v10/getting-started#aliasing-in-node
