### ISSUE TITLE
Relative import path "preact" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by hemedani** [preactjs/preact#3992]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
get an error when using version `10.13.2` with deno
error is this 
```shell
error: Relative import path "preact" not prefixed with / or ./ or ../
    at https://esm.sh/stable/preact@10.13.2/deno/hooks.js:2:25
```

**Comment by rschristian** [comment]
Not a Deno user, but you'll likely need an import map: https://deno.com/manual@v1.33.0/basics/import_maps

**Comment by marvinhagemeister** [comment]
Yeah you either need an import map like @rschristian said, or you can prefix imports with `npm:` in deno to load npm modules. The latter is very new in deno.

**Comment by JoviDeCroock** [comment]
I don't think this is a Preact problem compared both releases and there's not a difference from our side. Mind confirming whether this relates to the import maps?

**Comment by JoviDeCroock** [comment]
Closing for now, feel free to re-open if there's anything we can do to help you.

**Comment by hemedani** [comment]
thanks, it's completely fine
