### ISSUE TITLE
[regression] Preact 10.14.0 breaks selection offset on controlled text inputs

### ISSUE THREAD

**Issue by birtles** [preactjs/preact#4004]
- [ ] Check if updating to the latest Preact version resolves the issue __(it does not)__

**Describe the bug**

After upgrading to Preact 10.14.0, for controlled text inputs, the selection is reset in certain cases.

**To Reproduce**

1. Go to https://codesandbox.io/s/crazy-field-ng230t
2. Click on the text input box (after waiting for it to render)
3. Type "abc"
4. Move the cursor between "a" and "b"
5. Press Backspace

**Expected behavior**
What should have happened when following the steps above?

The "a" should be deleted leaving "bc" but with the text selection in _front_ of "bc".

**Actual behavior**

"a" is deleted leaving "bc" but the cursor is moved to _after_ "bc".

Tested with Firefox and Chrome on Windows. This did not happen with 10.13.2.

**Comment by marvinhagemeister** [comment]
Tracked down the source of this issue to this PR https://github.com/preactjs/preact/pull/3926 . I cannot reproduce the error without compat.

cc @andrewiggins

**Comment by developit** [comment]
@marvinhagemeister waiting one tick actually seems reasonable here.
