### ISSUE TITLE
Missing types for Dispatch and Context in the React namespace

### ISSUE THREAD

**Issue by Scott-Fischer** [preactjs/preact#4027]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I've recently started working with a 3rd party library which was designed for react. In their types they use `React.Context` and `React.Dispatch`. In my TS config, I'm aliasing react types to `preact/compat`. But I noticed these specific types were missing from the exported React namespace and it ultimately ends up throwing during my build.

If I go in and patch the preact types, this ends up fixing the problem entirely. A type for Preact.Context already exists but just isn't being exported in the `React` namespace (only ContextType is which doesn't match the name react uses). I didn't see one for Dispatch so that one had to be copied from the react type.

```ts
type Dispatch<A> = (value: A) => void;
export import Context = preact.Context;
```

So I was wondering if there was a specific reason why these two types are not exported under the React namespace. If it was just an oversight, I'd be happy to open up a PR to apply my patch upstream.

**Comment by rschristian** [comment]
I don't think there's any specific reason, no. PRs are definitely welcome!
