### ISSUE TITLE
Suspense in final bundle when not used

### ISSUE THREAD

**Issue by jedlikowski** [preactjs/preact#4029]
**Describe the bug**
Hello, I'm building a widget which will be loaded by clients on their websites from our CDN. To have the best performance possible, I'm trying to reduce my bundle size as much as I can. It's a CRA project with some config overrides via react-app-rewired to reduce bundle size. I'm using source map explorer to visualise the bundle. In this graph I noticed the suspense-related code from `preact` is making it into the final bundle even though I'm not using `lazy` nor `Suspense` at all (I rolled a custom solution for dynamic import based on useEffect, which is enough for my needs). Is Suspense used or imported internally by some other feature?

Here is the bundle visualization:
![image](https://github.com/preactjs/preact/assets/9341608/744e0ea3-a39e-408e-9372-68affc333939)

And here are all my imports from `preact` and `preact/compat`:
```typescript
import { 
  render,
  Fragment, 
  type FunctionComponent,   
  type JSX, 
  type ComponentChild, 
  createContext
} from "preact";

import { 
  useState, 
  useMemo, 
  useCallback, 
  useEffect, 
  useRef, 
  createPortal, 
  useLayoutEffect,
  useReducer,
  type Reducer,
  useContext,
} from "preact/compat";
```

Could anyone explain why would this be the case? Or is the graph wrong? It's generated based on source map.

**Comment by JoviDeCroock** [comment]
Preact X the current version
