### ISSUE TITLE
Signal for style attribute as object

### ISSUE THREAD

**Issue by Grafikart** [preactjs/preact#4034]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I'm creating a style object using computed but when it is set on an element, it's not being applied. 
If the style is a string signal it works.

**To Reproduce**
A simple code sandbox : https://codesandbox.io/s/preact-style-issue-5nw6q8?file=/src/index.js

```jsx
function App() {
  const count = signal(0);
  const increment = () => count.value++;

  // Style is not working with object style
  const style = computed(() => ({
    color: count.value % 2 ? "red" : "blue"
  }));

  // But it works for string
  const styleString = computed(
    () => `color: ${count.value % 2 ? "red" : "blue"}`
  );

  return (
    <div style={{ margin: 20 }}>
      <p style={style}>{count}</p>
      <p style={styleString}>{count}</p>
      <button onClick={increment}>Increment</button>
    </div>
  );
}
```

**Expected behavior**
I would expect style to be updated when signal is used.

**Comment by rschristian** [comment]
Can track this issue in the signals repo: https://github.com/preactjs/signals/issues/255

**Comment by Grafikart** [comment]
Thanks, closing this issue, sorry I wasn't aware of the other repo
