### ISSUE TITLE
Error regarding `undefined __H`

### ISSUE THREAD

**Issue by DenizUgur** [preactjs/preact#4035]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

It started with a problem from vitest-dev/vitest#3502. But I think the initial problem regarding `vitest` is now gone. However, now I'm getting the following error when running my tests. The same code works in a non-test environment so I have no clue what might be wrong here.

```console
TypeError: Cannot read properties of undefined (reading '__H')
```

**To Reproduce**
I have a [repo](https://github.com/DenizUgur/vitest-repro) to test this problem. You just need to run `npm test` to see the problem.

**Expected behavior**
Well the second test `should render Fail but fails` should pass

**Comment by rschristian** [comment]
Usually means you're loading multiple copies of Preact at once, which will break hooks. Might be that `usehook-ts` module you have, it doesn't seem to support Node ESM.

**Comment by DenizUgur** [comment]
What can be done to add ESM support for that package? Or any other workarounds?

**Comment by rschristian** [comment]
Add `package.json#exports`, and fix the ESM build output to adhere to Node's semantics: needs file extensions on the imports and  also need to decide on `.cjs`/`.mjs`, depending on the package type.

I'm not positive it's that module, but from what I know of Vitest, that'd make sense.

**Comment by DenizUgur** [comment]
I have also tried another package [react-use](https://github.com/streamich/react-use/blob/master/package.json) which now generates another error (below). I figured since that's a more popular package they would have done that. Also I have other packages in my main project such as [Fuse.js](https://github.com/krisk/Fuse/blob/master/package.json) that doesn't do `package.json#exports`, so maybe this is related to another issue?

I'm just not sure if this is related to Preact or Vitest

```console
Cannot read properties of null (reading 'useRef')
```

**Comment by rschristian** [comment]
>Also I have other packages in my main project such as [Fuse.js](https://github.com/krisk/Fuse/blob/master/package.json) that doesn't do `package.json#exports`, so maybe this is related to another issue?

The issue is specifically with modules that rely on (p)react. If you first load Preact ESM's build, then its CJS as the requiring module has no valid ESM build in Node, then you wind up with two copies of Preact.

**Comment by DenizUgur** [comment]
I assume this is all happening because vitest doesn't support aliasing. Probably the issue has to be solved on that side. However, if you have any possible solution for the reproduction repo I gave that would be fantastic.
