### ISSUE TITLE
iframe is reloaded, when it's a children props in WrapperComponent, and some siblings before children is removed

### ISSUE THREAD

**Issue by InfiniteXyy** [preactjs/preact#4074]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Nearly the same as https://github.com/preactjs/preact/issues/2350

But this issue only happends in v10.16.0, works well in 10.15.1

The difference from the old issue is that, I pass this `iframe` element with children props into another `WrapperComponent`
And if there is any node removed before the `children`, the `iframe`, which is inside the `children` will get reloaded 

**To Reproduce**

https://codesandbox.io/s/festive-dust-qyr2lc?file=/src/index.js

1. Go to 'https://codesandbox.io/s/festive-dust-qyr2lc?file=/src/index.js'
2. Click on Button 'Focus on me'
3. The iframe is getting reloaded when release the button

**Expected behavior**
The iframe shouldn't get reloaded

**Comment by nmain** [comment]
`preact` is keeping the same `<iframe>` element when updating here, but it's removing it from the document and then reinserting it.  In the case of `<iframe>`s, that means the frame does a full reload.
