### ISSUE TITLE
Support SignalLike for real

### ISSUE THREAD

**Issue by artalar** [preactjs/preact#4078]
I found that the signal public interface (`SignalLike`) is not actually used at runtime, but only for types. Under the hood, `@preact/signals` patches the runtime and does all the subscription and invalidation mechanics by itself based on its internal knowledge.

It would be **awesome** to support a signal version of React's `useSyncExternalStore` hook as a general interface for other state manager adapters.

It would also be helpful to pass the ID of the element to help other state managers handle SSR.

```ts
export interface SignalLike<T> {
  peek(id: string): T;
  subscribe(fn: (value: T) => void, id: string): () => void;
}
```

**Comment by rschristian** [comment]
Can be addressed in user land, as `@preact/signals` shows. Best left for there I think, with the size constraints core has, it's unlikely to be implemented here in the near future.
