### ISSUE TITLE
Empty result of lazy component doubles next node

### ISSUE THREAD

**Issue by aleksandrjet** [preactjs/preact#4079]
I found a bug with empty result of lazy component. I could't fix it and opened [pr](https://github.com/preactjs/preact/pull/4075) with fallen test.

Perhaps this is not so easy to fix. Maybe add a notice to the documentation, that lazy component requires something to return (not null or empty fragment)?

**Comment by JoviDeCroock** [comment]
Hmm, yeah this would be indeed quite hard to fix as it seems a general issue with having no matching DOM for a given VNode during a suspended hydration, basically we want to match some kind of DOM to the suspended node while hydration is ongoing
