### ISSUE TITLE
IntrinsicAttributes.key should be of type string, not any

### ISSUE THREAD

**Issue by Lesik** [preactjs/preact#4080]
**Describe the feature you'd love to see**
I propose that in the next Preact version where we can make breaking changes, the `key` property of `IntrinsicAttributes` should be of type `string`, not `any`:

```diff
export namespace JSXInternal {
	// snip
	export interface IntrinsicAttributes {
-		key?: any;
+		key?: string;
	}
}
```

**Additional context (optional)**
While it is difficult to _prove_ that the `key` prop passed to a React component should be of type string (because React is written in JavaScript), and React will not throw when passed something else, I do believe that the spirit and intent of it is definitely to only get passed a string. See [React docs](https://legacy.reactjs.org/docs/lists-and-keys.html#keys):

> The best way to pick a key **is to use a string** that uniquely identifies a list item among its siblings.

In fact, you could argue it's dangerous to pass anything but a string, since for example passing an object will auto-stringify it into `"[object Object]"`, making it so that all iterations of your `map` have the same key, which can lead to unintended consequences.

**Comment by marvinhagemeister** [comment]
Preact doesn't stringify the `key` prop like React does, so objects won't be cast to `"[object Object]"`. That's only a problem in React. Preact doesn't care what the value of `key` is.

**Comment by Lesik** [comment]
@marvinhagemeister Interesting! I'm assuming Preact will use `Object.is` to compare the `key`s between renders to determine changes then?

**Comment by marvinhagemeister** [comment]
No, we don't use `Object.is`. We use a loose equality check. See https://github.com/preactjs/preact/blob/cd73eab77d08a033099c1456112768f90e2e822a/src/diff/children.js#L326
