### ISSUE TITLE
_jsxFileName included in the bundle with sourcemaps disabled

### ISSUE THREAD

**Issue by horprogs** [preactjs/preact#4081]
Hi! Thanks for preact!
I have an unusual case:

I have a nodejs app (`nestjs`) where I build my preact app using `build` method from `vite`.

It looks like this:

```
import { build } from 'vite'

build({
      root: '/Users/user/Documents/project/',
      build: {
        sourcemap: false,
        minify: false,
        outDir: `./dist.temp/lib`,
        lib: {
          formats: ['umd'],
          entry: '/Users/user/Documents/project/src/lib.tsx',
          fileName: () => `lib.js`,
          name: 'lib',
        },
      },
    })
```

In my preact app I just render a simple component:

```
const Component = () => {
  return (
    <div>Test</div>
  )
}

export default Component
```

```
import { render } from 'preact'
import Component from './Component'

render(<Component />, document.getElementById('app'))
```

As a result I'm getting my build with hardcoded `_jsxFileName` paths.

Interestingly, if I put this build method to a separate js and just call this file from cmd like `node build.js` it builds fine, without these paths.

I assume there is something wrong with my setup, but I'd be really grateful to have some thoughts where to look to understand why this is happening.

<img width="681" alt="image" src="https://github.com/preactjs/preact/assets/14051960/a8c4b50a-29da-4202-8a8e-a1621e221325">

**Comment by rschristian** [comment]
> Interestingly, if I put this build method to a separate js and just call this file from cmd like node build.js it builds fine, without these paths.

I don't quite know what this means; how else are you running your build script? If you're calling it from Nest itself, that's probably where you're running into issues; it might be injecting those inline sourcemaps itself.

Regardless, this looks to be an issue with Vite or other tooling that you're using, not with Preact itself.

**Comment by marvinhagemeister** [comment]
@horprogs What does your vite setup look like? Are you using the Preact preset or something else? Have you customized JSX transpilation?

**Comment by horprogs** [comment]
> What does your vite setup look like? Are you using the Preact preset or something else? Have you customized JSX transpilation?

The config is pretty simple.

```
import { defineConfig } from 'vite'
import preact from '@preact/preset-vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    preact(),
  ],
})
```

> I don't quite know what this means; how else are you running your build script? If you're calling it from Nest itself, that's probably where you're running into issues; it might be injecting those inline sourcemaps itself. I don't think Vite will create what you're seeing there.

In the 1st case I use nestjs, meaning I call `build` from `vite` when nestjs endpoint is called (sourcemaps added here).
In the 2nd case I created a file named `build.js` where I call `build` and just run it manually from a command line, like `node build.js` (in this case everything is fine).

It seems you are right and nestjs adds these paths somehow, will investigate further.

**Comment by rschristian** [comment]
[This might be relevant?](https://github.com/nestjs/nest/issues/4644#issuecomment-616992927)

**Comment by horprogs** [comment]
Thanks for checking! Not sure, I don't use monorepo and webpack. I just don't understand why (and what) adds these paths if sourcemaps are disabled and considering that I build preact app in another folder (not where nestjs app running). A bit weird

**Comment by marvinhagemeister** [comment]
Those paths are not added by source mapping, but by the JSX transform that's used. In this case it's using the `react-jsxdev` transform. That's usually done either in a babel pass, TypeScript itself or inside esbuild.

**Comment by horprogs** [comment]
I figured out that if I build my nestjs app for production and run a preact app build in this mode those paths are not being added. This is already something. Probably some context where nestjs app running has some impact. Anyways, thanks guys for useful ideas, this is not a question for preact eventually.
