### ISSUE TITLE
Keep parts of the DOM when hydrating

### ISSUE THREAD

**Issue by matthewmueller** [preactjs/preact#4082]
**Describe the feature you'd love to see**
Hey Preact team! This is more of a question than a feature request.

I'm wondering if there's a way to ignore over certain elements when hydrating or keep certain sections that have been rendered by SSR? 

**Additional context (optional)**

I'm working on a Svelte-like language over at https://github.com/livebud/duo that compiles to Preact components. (Thank you for your hard work on such an awesome lib!!)

There's certain complex objects I'd like to use to render HTML on the server side, but aren't serializable (at least not to JSON) on the client. Functions are the main use case. 

Since I won't be using them on the client, it's essentially static data, so I was wondering if there's some way to mark a certain section as ignored.

I tried the following but to no avail:

```html
<html>
  <head>
    <title>Hello</title>
  </head>
  <body>
    <div id="app">
      <div class="flash">Some static message</div>
      <h2>Hi!</h2>
    </div>
    <script type="module">
      import { hydrate, h, Component } from 'https://esm.run/preact?dev'
      class Ignore extends Component {
        shouldComponentUpdate() {
          return false
        }
        render() {
          return h('h1', {}, 'Big')
        }
      }
      const App = () => h('div', { id: 'app' }, [
        h(Ignore, {}, []),
        h('h2', {}, 'Hello!')
      ])
      hydrate(h(App, {}, []), document.body, document.firstChild)
    </script>
  </body>
</html>
```

Thanks for your help!!

**Comment by JoviDeCroock** [comment]
You could do something along the lines of the following

```js
      class IgnoreHydration extends Component {
        shouldComponentUpdate() {
          return false
        }
        render() {
          return <span dangerouslySetInnerHTML={{ __html: "" }} />
        }
      }
```

Been a while since I tried that but 😅

**Comment by matthewmueller** [comment]
Thanks for your response! This clears out what's in ignored, rather than ignoring it.

**Comment by marvinhagemeister** [comment]
Your intention sounds similar to how I've added support for passing server rendered HTML as children to Preact components in [Fresh](https://fresh.deno.dev/). The basic idea is that you add HTML comments as markers around the server rendered bits and when you encounter them in the client just before hydration you can parse the HTML to a vnode tree and stitch the whole thing together. Once you have the full combined vnode tree you can kick off hydration and the HTML nodes will be preserved as they are now part of the vnode tree.

**Comment by matthewmueller** [comment]
Hey Marvin, I didn't realize you contribute to [Fresh](https://fresh.deno.dev/). That's awesome!

I believe this solution would work great. Thanks for sharing!
