### ISSUE TITLE
Update AriaRole type to WAI-ARIA 1.2

### ISSUE THREAD

**Issue by webschik** [preactjs/preact#4098]
Hello,

I have a problem with [AriaRole](https://github.com/preactjs/preact/blob/main/src/jsx.d.ts#L1591) type.
It includes a list of all [WAI-ARIA 1.1 role definitions](https://www.w3.org/TR/wai-aria-1.1/#role_definitions) which makes it impossible to use a `meter` role for the HTML element without workarounds like type casting.

Is it possible to update `AriaRole` and use a list of roles from [WAI-ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/#role_definitions)?

**Comment by rschristian** [comment]
Thanks for providing the docs, really helped ensuring all were added.

Looks like we were missing a few 1.1 roles too

**Comment by webschik** [comment]
Thanks for fixing this so fast!
