### ISSUE TITLE
_component property is missing in preact 10

### ISSUE THREAD

**Issue by holmsshiva** [preactjs/preact#4103]
We are upgrading preact 8.5.2 to preact 10.16.0. What we have have found that in preact 8 I have the _component property in refs when I was creating a ref but it’s not present in preact 10.

based on this property I was reading the class component instance method but now in preact 10 our code is breaking.

you can reproduce the issue by creating a class component and in child class component declare any method and in parent component create a refs for child component and from parent component try running the child instance method

Can we know the reason why _component property is not available in preact 10 and what is the work around for this.

**Comment by JoviDeCroock** [comment]
It still exists however I personally strongly discourage using that 😅 https://github.com/preactjs/preact/blob/main/mangle.json#L56

**Comment by holmsshiva** [comment]
@JoviDeCroock Thank you for checking. 
Please find the ScreenShot of ref value incase of Preact 8 and Preact 10

<img width="297" alt="Screenshot 2023-08-17 at 12 40 13 PM" src="https://github.com/preactjs/preact/assets/10777453/f3193e72-2ec4-4da6-af70-6136e5935826">
<img width="296" alt="Screenshot 2023-08-17 at 12 54 08 PM" src="https://github.com/preactjs/preact/assets/10777453/25682a24-cace-42cd-a7b5-ab06de986d28">

**Comment by marvinhagemeister** [comment]
My details are a bit fuzzy on the 8.x code base since I last touched it 5 years ago. Iirc components were implemented completely differently back then. Instead of being a proper element in the tree I think we used to bind them to a DOM node and have a linked list of components on the `_component` property. With 10.x where we support Fragments and other nodes that approach makes no sense anymore.

Can you share more about the particular use case? What were you using the `_component` property for?

**Comment by holmsshiva** [comment]
@marvinhagemeister we were using _component to access the instance method / variables of the child class component

**Comment by marvinhagemeister** [comment]
@holmsshiva I'm not sure I follow. The ref _itself_ is already the component instance you're looking for. Made a codesandbox that shows how to call a method of a child component https://codesandbox.io/s/vigorous-kalam-cxngzk?file=/src/index.mjs

**Comment by holmsshiva** [comment]
Hi @marvinhagemeister Thank you for your time.
I have created a sample sandbox project https://codesandbox.io/s/brave-joana-mlnfym?file=/src/index.js .

How this can be handled without changing the code structure etc

**Comment by rschristian** [comment]
You were missing `.current` on your ref. You'll need this to access its current value, see [our docs on refs](https://preactjs.com/guide/v10/refs#createref) for more info.

Here's an example, albeit with all of that unrelated `unistore` store stuff cut out: https://stackblitz.com/edit/vitejs-vite-byrzpr?file=src%2Fmain.jsx

**Comment by holmsshiva** [comment]
@rschristian  Please try to use the codesandbox link to check why its not working I am accessing using .current property.

**Comment by rschristian** [comment]
> @rschristian Please try to use the codesandbox link to check why its not working I am accessing using .current property.

Apologies, maybe I copy/pasted poorly, one sec.

**Comment by JoviDeCroock** [comment]
The reason why it's working in the stackblitz and not in your codesandbox @holmsshiva is the `connect` HOC, i.e. it means you are having the `this` reference on your HOC rather than on your component so for example this ` this.incrementRef.current.__t.__c.incrementNew();` would work but I agree that it's not ideal 😅

**Comment by rschristian** [comment]
Whoops, thanks for catching that. Clearly wasn't paying attention.

Might be worth adding that this pattern really isn't idiomatic (p)react anyhow -- lifting that state up into the parent, using the context API, etc., is generally preferred to messing around with refs like this.

**Comment by JoviDeCroock** [comment]
Going to close this as solved, feel free to keep discussing or re-open if something else pops up
