### ISSUE TITLE
Namespace 'React' has no exported member 'HTMLProps'

### ISSUE THREAD

**Issue by jschuler** [preactjs/preact#4114]
**Describe the bug**
I have a react/typescript project that I am migrating to preact+preact/compat.

Many of our existing library components extend `React.HTMLProps`, for example:
```
import * as React from 'react';
export interface BadgeProps extends React.HTMLProps<HTMLSpanElement> {
  isRead: boolean;
}
```

After aliasing react to use preact/compat, it complains that `Namespace 'React' has no exported member 'HTMLProps'`.

Workaround for me is to update the component file
```
import { JSX } from 'preact';

export interface BadgeProps extends JSX.HTMLAttributes<HTMLSpanElement> {
  ...
}
```

**Expected behavior**
What should have happened when following the steps above?

I would have expected HTMLProps to exist in preact/compat so that I don't have to change hundreds of component files.

**Comment by rschristian** [comment]
> I would have expected HTMLProps to exist in preact/compat so that I don't have to change hundreds of component files.

You can patch the types yourself in the meantime, no need to batch renaming:

```ts
// global.d.ts
import * as preact from 'preact';

declare module 'react' {
  export interface HTMLProps<T> extends preact.JSX.HTMLAttributes<T> {}
}

```

**Comment by ynwd** [comment]
Similar problem for [https://floating-ui.com/docs/react-examples](https://floating-ui.com/docs/react-examples)
[https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx:401-432](https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx:401-432)

`React.SetStateAction`


<img width="503" alt="Screenshot 2023-09-13 at 00 43 04" src="https://github.com/preactjs/preact/assets/10122431/2ffe69a5-c147-48cb-bc34-fb611aa4a991">

**Comment by rschristian** [comment]
Please open a new issue (or PR, if you're willing) for that.

It's impossible to track issues listed as replies to already closed issues.
