### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'context')

### ISSUE THREAD

**Issue by tangyuer** [preactjs/preact#4118]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

**To Reproduce**

If possible, please provide a CodeSandbox/Codepen that demonstrates the issue. You can use the following template: https://codesandbox.io/s/preact-x-preact-cli-3-starter-vj285y2rn3

3. See error

**Expected behavior**
What should have happened when following the steps above?
在preact + react-jsonschema-form的使用中，在‘ui:widget’的自定义组件中使用antd的任何一个组件，都会报错“Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'context')”
![image](https://github.com/preactjs/preact/assets/50434656/188ec040-766c-45cc-a5f5-bc95e51d1117)

**Comment by JoviDeCroock** [comment]
I am closing this issue as it's not following the template, does not provide a reproduction nor does it tell us what's happening.
