### ISSUE TITLE
In extremely minimal test: Uncaught TypeError: Cannot read properties of undefined (reading '__H')

### ISSUE THREAD

**Issue by Clonkex** [preactjs/preact#4120]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I get the error `Uncaught TypeError: Cannot read properties of undefined (reading '__H')`.

**To reproduce**
Steps to reproduce the behaviour:

1. Go to https://jsfiddle.net/8m9d6ay1/1/
2. Click on 'Run'
3. See error

**Expected behaviour**
No error.

The error doesn't come up when [testing in codesandbox](https://codesandbox.io/s/vigorous-glade-k3s2lc?file=/index.js) but I'm not even slightly familiar with bundlers/transpilers/whatever so I have no idea what the difference is.

What am I doing wrong to be failing with such a basic test?

**Comment by Clonkex** [comment]
Ok I figured it out, finally. It'd be great if there was more detailed documentation about this (since [the tutorial](https://preactjs.com/tutorial/01-vdom) doesn't actually mention it, although [the HTM page does](https://github.com/developit/htm)) but whatever.

So instead of doing this:

```
render(Test(), document.body);
```

I should have been doing this:

```
render(html`<${Test}/>`, document.body);
```

...or this:

```
render(html`<${Test}><${Test}/>`, document.body);
```

Corrected and working fiddle: https://jsfiddle.net/3zm2swtg/

**Comment by rschristian** [comment]
We do mention this in the API docs, for what it's worth: 

> The first argument must be a valid Virtual DOM Element, which represents either a component or an element. When passing a Component, it's important to let Preact do the instantiation rather than invoking your component directly, which will break in unexpected ways:
>```jsx
>const App = () => <div>foo</div>;
>
>// DON'T: Invoking components directly breaks hooks and update ordering:
>render(App(), rootElement); // ERROR
>render(App, rootElement); // ERROR
>
>// DO: Passing components using h() or JSX allows Preact to render correctly:
>render(h(App), rootElement); // success
>render(<App />, rootElement); // success
>```

https://preactjs.com/guide/v10/api-reference#render

**Comment by Clonkex** [comment]
Aha, I read that section but I must have missed that part (or read it before fully understanding how Preact works in general and then didn't re-read later). Thanks!

**Comment by rschristian** [comment]
No worries, I do agree that it's something that's probably worth adding to the tutorial page; even if you did skim that page, I'd bet most users don't.

I made a note of it on our docs repo, I'll (hopefully) get around to that later.
