### ISSUE TITLE
Suspense changes order of elements

### ISSUE THREAD

**Issue by valentin-huebner** [preactjs/preact#4122]
**Describe the bug**
Using the lazy/Suspense sometimes changes the order of elements.

**To Reproduce**
https://codesandbox.io/s/crazy-taussig-hvc9yx?file=/src/index.js

Wait 1 second. After the lazy component has loaded, it is in second position.

**Comment by JoviDeCroock** [comment]
This seems related to using the `preact` render method as opposed to using the one exported from `preact/compat`.
