### ISSUE TITLE
Preact onClick events working with delay in iOS webview on iPhones 

### ISSUE THREAD

**Issue by VishalGulati** [preactjs/preact#4145]
**Click events working with delay in latest iOS webview applications running on PREACT version 10.13.1**
I have created a application in preact that runs in webview inside native mobile applications. The click events of my code are not working correctly os iPhones however, working fine on all android devices. I tested the behaviour in 3 different iOS versions 16.5.1, 16.6.1 and iOS 16.7 but didn't work on any. 

My code is simple preact click event handler on a `div`.

```
const ProfileComponent = ({ clickEventHandler, title }) => {
    return <div onClick={clickEventHandler && clickEventHandler}>
      <span class="userAvatar" />
      <p>{title}</p>
    </div>
}
```

When I click on the div, nothing happens,.
Now I click on another clickable item in my app which gives an alert, instead of the alert, I get to see the opoup which gets openened by the function clickEventHandler which should have been called by the first click itself.

**Expected behavior**
The code is working fine on all android devices and should work well on iOS devices too.

**Comment by JoviDeCroock** [comment]
Have you tried a more recent version of Preact? Also `onClick={clickEventHandler && clickEventHandler}` should return `true` to the onClick, does that actually work? 😅

**Comment by VishalGulati** [comment]
@JoviDeCroock - its a valid statement, &&  just returns whatever is on the right side if the left operant is truthy. So am expecting clickEventHandler to be executed on click and it works fine on all browser and even in webview inside native android apps, but not in iOS native apps' webview.

**Comment by VishalGulati** [comment]
@JoviDeCroock - also I tried simplifying the code by just having clickEventHandler associated with onClick but it still doesn't work.

updated code: 
```
const ProfileComponent = ({ clickEventHandler = () => {}, title }) => {
    return <div onClick={clickEventHandler}>
      <span class="userAvatar" />
      <p>{title}</p>
    </div>
}
```

**Comment by VishalGulati** [comment]
I have tesed y app on another iOS version 16.4.1 and it worked fine. The issue seems to be with iOS >= 16.5.1. I am stuck what could be wrong here with the webkit with these versions.
@JoviDeCroock @developit @marvinhagemeister @andrewiggins  - could you please share your inputs on this.

**Comment by JoviDeCroock** [comment]
Sorry, but tagging folks to get a reply when we already answered is a bit disrespectful. This is not our job

Have you tried a newer preact version? As I asked in the first reply... that being said I will take a look at the webkit changelog next week.

**Comment by VishalGulati** [comment]
@JoviDeCroock i am really sorry but did not intend to disrespect you. I tagged folks thinking you might be busy and having spent hours on this, I have run out of thoughts hence seeking inputs. I apologise again and appreciate you taking time to respond.

**Comment by andrewiggins** [comment]
Definitely appears like an issue with webkit webviews and not Preact. It sounds like you are trying to launch an alert by clicking on a div? Do you need to allow Webkit webviews to do this? https://stackoverflow.com/questions/26898941/ios-wkwebview-not-showing-javascript-alert-dialog

Does anything indicate this is an issue with Preact and not something to do with Webkit or webviews? For example, try a very minimal repro in raw JS. If that doesn't work it won't work in Preact either.

For more general help, you can also try asking in our Slack (https://chat.preactjs.com). Others there may have experience with Webviews on iOS

**Comment by rschristian** [comment]
> I have tesed y app on another iOS version 16.4.1 and it worked fine. The issue seems to be with iOS >= 16.5.1.

Alerts have always been a bit rough across all browsers, it wouldn't surprise me if this was a quirk in a newer iOS version. Can you test other behaviors in your `clickEventHandler`? Make it turn an element blue or something.

It'd be helpful to determine whether this was a legitimate issue with click handlers or just the behavior inside the handler.

**Comment by VishalGulati** [comment]
@rschristian @andrewiggins - alert is also a popup not the native alert of device. Sorry I should have specified it beforehand.

**Comment by rschristian** [comment]
Sounds like this was solved: https://preact.slack.com/archives/C3NMBSJKH/p1696095531562349?thread_ts=1696048377.550129&cid=C3NMBSJKH

Let us know if you continue to have issues and we can look at reopening
