### ISSUE TITLE
Injected elements getting reordered/pushed to end of wrapping html element

### ISSUE THREAD

**Issue by nikse** [preactjs/preact#4150]
**Describe the bug**

On 10.6+ re-rendering a memoized array of components is pushing all injected html to the end of the wrapping html/re-ordering the children. The bug also happens if the component is a class component using an sCU, and will happen regardless of the sCU returning true or false.

Sort of similar to [#4135](https://github.com/preactjs/preact/issues/4123), but kind of different.

**To Reproduce**

Here's an example https://codesandbox.io/s/cool-field-sjz648. It's only happening w/ these exact circumstances, i.e. a component rendering a memoized mapped array of components. Using a static array of components or rendering a raw html tag instead of a component in the map/loop does not bug.

**Expected behavior**

The component should re-render without re-ordering the children

**Comment by nikse** [comment]
Hm, so this did not happen before 10.6, which is why I'm reporting it as a bug

**Comment by rschristian** [comment]
You were relying upon chance behavior there, not anything intentional (as far as I know), which may indeed change in a minor/patch. There's not many guarantees that can be made when it comes to running around Preact/VDOM and inserting elements into the DOM yourself.

**Comment by JoviDeCroock** [comment]
Going to close this as solved, feel free to keep discussing or re-open if something else pops up
