### ISSUE TITLE
[preact/compat] use-sync-external-store shim incompatibility

### ISSUE THREAD

**Issue by michal-swiderski** [preactjs/preact#4155]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Webpack server build with `target: node` breaks when `use-sync-external-store` is imported by e.g. the app's dependency (swr for example). Both `react` and `react-dom` are aliased to `preact/compat` in webpack config.

**To Reproduce**

1. Clone https://github.com/michal-swiderski/preact-sync-external-store-shim-issue
2. `npm i`
3. `npm start`

I get: `TypeError: Cannot read properties of undefined (reading '__H')`

**Expected behavior**
The app should execute successfully.

**Comment by rschristian** [comment]
Not an issue with `use-synx-external-store`, you're simply loading multiple copies of Preact at once.

When using `target: "node"`, you need to make sure you're keeping Preact external, else, there will be multiple copies loaded at once:

```diff
const path = require("path");

module.exports = {
  mode: "development",
  entry: "./index.jsx",
  output: {
    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
  // breaks on target=node
  target: "node",
+ externals: {
+   preact: "preact"
+ }
  resolve: {
    alias: {
      react: "preact/compat",
      "react-dom": "preact/compat"
    },
  },
  module: {
    rules: [
      {
        test: /\.(jsx?)$/,
        use: "babel-loader",
      },
    ],
  },
};
```

You'll then need to correct your library target (probably to `commonjs2`) else Webpack will expect `preact` to be a global, i.e., `module.exports = preact`, which is no good. Switching this to `commonjs2` gets us `module.exports = require("preact")`, which is exactly what we want:

```diff
const path = require("path");

module.exports = {
  mode: "development",
  entry: "./index.jsx",
  output: {
    path: path.resolve(__dirname, "dist"),
    clean: true,
+   libraryTarget: "commonjs2",
  },
  // breaks on target=node
  target: "node",
  externals: {
    preact: "preact"
  }
  resolve: {
    alias: {
      react: "preact/compat",
      "react-dom": "preact/compat"
    },
  },
  module: {
    rules: [
      {
        test: /\.(jsx?)$/,
        use: "babel-loader",
      },
    ],
  },
};
```

**Comment by JoviDeCroock** [comment]
Going to close this as solved, feel free to keep discussing or re-open if something else pops up
