### ISSUE TITLE
<iframe> reloads its contents after removing one of its previous siblings when used with react-slate

### ISSUE THREAD

**Issue by hpneo** [preactjs/preact#4156]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

In a web application with slate, slate-react and Preact, if I have a node before an iframe and then I remove that node, the iframe will be reloaded. This seem to be caused by a complete re-render of the Slate's editor's content.

This behavior is not present in Preact 10.15.1 and before, and it looks like it was introduced in 10.16.0 and keep happening after that version.

**To Reproduce**

1. Go to https://stackblitz.com/edit/create-preact-starter-iza5ww?file=src%2Findex.jsx
2. Open result in another tab
3. Try to delete the second node (the paragraph with the text "Delete this line to see the iframe reload"). Or press Enter after or before the paragraph to create a new one and delete the newly created node.
4. The iframe will refresh.

**Note:** Compare with https://stackblitz.com/edit/create-preact-starter-i9u6lv?file=src%2Findex.jsx, where the same code uses Preact 10.15.1 and doesn't result in a iframe refresh. Also, [it doesn't happen in React](https://stackblitz.com/edit/stackblitz-starters-4s5n2h?file=src%2FApp.tsx).

**Expected behavior**
The iframe shouldn't refresh if I update its previous siblings.

**Comment by JoviDeCroock** [comment]
It's a bit hard to narrow this down due to slate being used, any chance of a smaller example? 😅 I'm sorry I tried around a bit to reproduce it to i.e. functional wrappers etc but all of that seemed to work

**Comment by hpneo** [comment]
@JoviDeCroock I couldn't replicate it either 😞. Seems to be working due to a specific slate or slate-react action. If it's worth, I forked the original sandbox and tried to replicate the issue with just Preact, but without success: https://stackblitz.com/edit/create-preact-starter-r7oeap?file=src%2Findex.jsx

**Comment by hpneo** [comment]
By following react-slate's implementation, I managed to replicate it: https://stackblitz.com/edit/create-preact-starter-r7oeap?file=src%2Findex.jsx

It looks like the issue is when using a memoized component. Even if the comparison function returns `true`, the element is re-rendered.

**Comment by JoviDeCroock** [comment]
Thank you so muchf for taking the time to replicate this issue. I will take a look at it, the likely cause here would be the reorderChildren function which is used to ensure proper ordering for components that bail like memoization. This way we avoid the risk of components with children props that shifted ordering from inaccurately reflecting in the DOM.
