### ISSUE TITLE
`currentComponent` not set when testing Preact hooks using ESM

### ISSUE THREAD

**Issue by Cipscis** [preactjs/preact#4176]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

I have been trying to set up a Jest test suite for a personal project which uses TypeScript, ESM module syntax, and Preact. I would like to test custom Preact hooks using `@testing-library/preact-hooks`.

I've run into errors when attempting to run tests on Preact hooks. I have set up a simple test suite that uses Preact's `useState` hook, which can be run via `npm test`. When running this test suite, it fails with the following error:

> `TypeError: Cannot read properties of undefined (reading '__H')`

**To Reproduce**

1. Clone my minimal reproducible example repo from [https://github.com/Cipscis/preact-hooks-jest-ts-esm-repro](https://github.com/Cipscis/preact-hooks-jest-ts-esm-repro)
2. Run `npm install`
3. Run `npm test`
4. See error in console

**Expected behavior**

The example test should pass with no errors.

---

I've found several other issues which report the same error message. For example, [this issue from July 2022](https://github.com/preactjs/preact/issues/3635) links to several others. From my reading, it seems that this issue may be related to using ESM, though it's not clear to me what steps I could take to resolve the issue.

In the main repo where I'm trying to add this test suite, I encounter the same error during my tests but the same custom hooks work correctly in the browser without this error. Which makes me suspect the issue may be related somehow to using `@testing-library/preact-hooks`, but the stack trace for the error only leads me into `~/node_modules/preacts/hooks/src/index.js`.

If it makes a difference, I have had to tell Jest to use the 'node' exports to allow importing from Preact within my test suite. I was advised to do this in an issue I raised on the Jest repo: [[Bug]: Unable to use ESM and TypeScript alongside a JSDOM environnment](https://github.com/jestjs/jest/issues/14652)

**Comment by Cipscis** [comment]
I've been able to resolve this by using `@testing-library/preact` instead of `@testing-library/preact-hooks`. From my reading, it sounds like `@testing-library/preact-hooks` is only intended to be used with older versions of Preact. Perhaps the [testing documentation](https://preactjs.com/guide/v10/preact-testing-library/) for the latest version of Preact should be updated to reflect this? It currently uses `import { renderHook, act } from '@testing-library/preact-hooks';` in its example.

**Comment by JoviDeCroock** [comment]
Resolved by the above docs PR, thank you for that callout!

**Comment by Cipscis** [comment]
That's great to hear, thanks very much :)
