### ISSUE TITLE
Regression in 10.18.2 when used with preact-custom-element

### ISSUE THREAD

**Issue by kizu** [preactjs/preact#4195]
- [x] Check if updating to the latest Preact version resolves the issue

I have noticed that using the 10.18.2 did break using the hooks with `preact-custom-element`.

**To Reproduce**

1. Go to https://codepen.io/kizu/pen/jOdyMyv
2. There is nothing rendered and an error in the console.

```
catch-error.js:39 Uncaught TypeError: Cannot read properties of undefined (reading '__H')
    at l (index.js:137:19)
    at B (index.js:165:20)
    at k (index.js:154:9)
    at W.Test [as constructor] (jOdyMyv?authentication_hash=XBAGRnEDLWKr:32:18)
    at W.fe [as render] (index.js:570:14)
    at R (index.js:212:14)
    at ee (children.js:145:3)
    at R (index.js:234:4)
    at ee (children.js:145:3)
    at R (index.js:234:4)
```

**Expected behavior**

There should be a “success” string rendered.

Updating the URL for `https://esm.sh/preact@10.18.1/hooks` fixes it.

**Comment by JoviDeCroock** [comment]
I checked `codepen` and it is importing both Preact 10.18.1 as well as Preact 10.18.2 in the bundles, the 10.18.1 coming from `preact-custom-element` and the 10.18.2 coming from `htm`, when I use this code with i.e. codesandbox it works flawlessly https://codesandbox.io/s/eloquent-shadow-kjvkn3?file=/src/index.js
