### ISSUE TITLE
Contexts with the same name interfere with each other

### ISSUE THREAD

**Issue by kbkmn** [preactjs/preact#4204]
Preact 10.18.2

If you create two contexts with same name, it messes with values they propagate. More specifically child context will override parent one

Minimal project
https://stackblitz.com/edit/create-preact-starter-kyjmxt?file=src%2Findex.jsx

Create context, create hook for its value, create exactly the same context with another hook and some other value. In index.jsx put both of contexts as parents for receiving component. In receiving component try to get value of higher order context. You will get value for lower one

Expected behavior
Both contexts should independently propagate their values to the receiving component without interfering with each other.

**Comment by JoviDeCroock** [comment]
This is a bug in [Prefresh](https://github.com/preactjs/prefresh) not in Preact, you can disable this by doing `prefreshEnabled: false` in the vite plugin
