### ISSUE TITLE
Add `x_google_ignoreList` (Ignore-listing code) support to sourcemaps

### ISSUE THREAD

**Issue by 0xdevalias** [preactjs/preact#4225]
Introduce the `x_google_ignoreList` extension in the sourcemaps generated by this project. This will facilitate a more streamlined debugging experience in Chrome (and other supporting browsers) by automatically filtering out framework and dependency code.

## Benefit

Implementing `x_google_ignoreList` in the sourcemaps will align this project with modern web development practices, offering a more focused and efficient debugging experience for developers using Chrome DevTools. This change will particularly benefit those who regularly engage in debugging complex applications with numerous dependencies.

## Background Context

- https://developer.chrome.com/blog/devtools-modern-web-debugging/#just-my-code
  - > The ignore-listing is enabled by populating an extra `x_google_ignoreList` field in the source map that Angular generates when compiling the project. The Chrome DevTools team encourages other framework authors to implement a similar change. Refer to the [Case Study: Better Angular Debugging with DevTools](https://developer.chrome.com/blog/devtools-better-angular-debugging/) post for more details.
- https://developer.chrome.com/blog/devtools-better-angular-debugging/#ignore-listing-code
  - > **Ignore-listing code**
    > When debugging applications using Chrome DevTools, authors generally only want to see just their code, not that of the framework underneath or some dependency tucked away in the node_modules folder.
    > 
    > To achieve this, the DevTools team has introduced an extension to [source maps](https://developer.chrome.com/blog/sourcemaps/), called `x_google_ignoreList`. This extension is used to identify third-party sources such as framework code or bundler-generated code. When a framework uses this extension, authors now automatically avoid code that they don't want to see or step through without having to manually configure this beforehand.
    > 
    > The `x_google_ignoreList` source map extension is supported by Chrome DevTools starting with Chrome 106.
- https://developer.chrome.com/articles/x-google-ignore-list/
  - > The ignoreList source map extension
    > 
    > Improve debugging experience in Chrome DevTools with the `ignoreList` source map extension.

> - https://developer.chrome.com/blog/new-in-devtools-120/#ignore-list-spec
>   - > The [source maps specification](https://sourcemaps.info/spec.html) has [adopted](https://github.com/tc39/source-map-spec/pull/19) the `ignoreList` field instead of `x_google_ignoreList` and DevTools now supports the new name with a fallback for the old one. Frameworks and bundlers can now use the new field name.
> 
> _Originally posted by @0xdevalias in https://github.com/facebook/react/issues/27774#issuecomment-1836969520_

## See Also

- https://github.com/facebook/react/issues/27774
- https://github.com/markerikson/react-prod-sourcemaps/issues/19
- https://github.com/vercel/next.js/issues/41370
  - https://github.com/vercel/next.js/discussions/41371
- https://github.com/vuejs/rfcs/discussions/607
- https://github.com/sveltejs/svelte/issues/9740
- https://github.com/angular/angular-cli/pull/23545
- https://nuxt.com/blog/v3-3#better-logging-in-browser-devtools
  - https://github.com/nuxt/nuxt/pull/19243
- https://vitejs.dev/config/server-options.html#server-sourcemapignorelist
  - https://github.com/vitejs/vite/pull/12174
  - https://github.com/vitejs/vite/pull/12633
  - https://github.com/vitejs/vite/pull/12694
- https://rollupjs.org/configuration-options/#output-sourcemapignorelist
  - https://github.com/rollup/rollup/issues/4847
  - https://github.com/rollup/rollup/pull/4846
  - https://github.com/rollup/rollup/pull/4848
  - https://github.com/rollup/rollup/pull/4926

**Comment by 0xdevalias** [comment]
> This doesn't look relevant to Preact? If I'm understanding correctly, that is something that needs to be configured in build tooling, not in libraries used.

@rschristian My understanding was that when the framework (in this case Preact), distributes itself as a minimised bundle, this is something that should be enabled/used/included within it's sourcemaps.

I believe that would then flow on to 'downstream' web app code as well (though don't quote me on that).

**Comment by 0xdevalias** [comment]
> that a **framework** or build tool has marked as to ignore

@rschristian Do you not consider preact a framework?

**Comment by rschristian** [comment]
> And Angular? Framework or 'UI library'? As they added support:

Take a look at where they added that change, it's in the _Webpack config_.

Angular is a framework as they have very specific underlying tooling -- you have to write Angular apps with Angular CLI (a Webpack-based tool, though I think that's changing?). This ties Angular to its framework rather tightly, compared to (say) React & Next, Vue and Nuxt, Svelte and SvelteKit, etc.

> I've generally seen React/etc referred to colloquially as a framework as well; so I wouldn't be so quick to dismiss the relevance on semantic differences.

I'm not dismissing this due to "emantic differences but due to actual intention. This is meant to be implemented in another layer of your tooling, a layer which UI libraries do not control.

> I'm not deeply familiar with microbundle and whether it allows passing through flags to rollup, or if it's something that would need to be enabled as part of their defaults.

We maintain Microbundle.

**Comment by 0xdevalias** [comment]
> I'm not dismissing this due to semantic differences but due to actual intention.

Fair enough.

> This is meant to be implemented in another layer of your tooling, a layer which UI libraries do not control.

I'm still not sure that that is correct. At the layer of preact, I believe it should mark itself to be ignored, so that shows in it's sourcemaps, so that then flows on to the sourcemaps of downstream projects that consume it's sourcemaps.

I may be wrong; and it seems that even if i'm not I'm unlikely to convince you otherwise, so I'll drop the point.

> We maintain Microbundle

Fair enough. Well you may or may not find this issue relevant there then, since it's a bundler:

- https://github.com/developit/microbundle/issues/1066

**Comment by rschristian** [comment]
> At the layer of preact, I believe it should mark itself to be ignored, so that shows in it's sourcemaps, so that then flows on to the sourcemaps of downstream projects that consume it's sourcemaps.

Again, your [Angular link](https://github.com/victorporof/angular-cli/blob/7c74fd12cd6454f4a7e1c3eedd165ecf9974a414/packages/angular_devkit/build_angular/src/webpack/plugins/devtools-ignore-plugin.ts#L56-L60) is a great example here in usage:

```js
for (const [index, path] of map.sources.entries()) {
    if (path.includes('/node_modules/') || path.startsWith('webpack/')) {
        ignoreList.push(index);
    }
}
```

As shown, this is happening in a Webpack plugin, during the user's app build. This isn't something that needs to flow on downstream, the consumer/framework can handle this perfectly well on their own.

Now, a good point of implementation could be [`create-preact`](https://github.com/preactjs/create-preact), though it looks like Vite (which `create-preact` uses) might already implement this?

**Comment by 0xdevalias** [comment]
> Now, a good point of implementation could be [create-preact](https://github.com/preactjs/create-preact), though it looks like Vite (which create-preact uses) might already implement this?

This is the relevant link on the vite docs, but that's seemingly for the dev server:

- https://vitejs.dev/config/server-options.html#server-sourcemapignorelist
  - > `server.sourcemapIgnoreList` is the equivalent of [`build.rollupOptions.output.sourcemapIgnoreList`](https://rollupjs.org/configuration-options/#output-sourcemapignorelist) for the dev server.
  - > By default, it excludes all paths containing node_modules. You can pass false to disable this behavior, or, for full control, a function that takes the source path and sourcemap path and returns whether to ignore the source path.
  - > Note: [`server.sourcemapIgnoreList`](https://vitejs.dev/config/server-options.html#server-sourcemapignorelist) and [`build.rollupOptions.output.sourcemapIgnoreList`](https://rollupjs.org/configuration-options/#output-sourcemapignorelist) need to be set independently. `server.sourcemapIgnoreList` is a server only config and doesn't get its default value from the defined rollup options.

Looking at vite's `rollup.config.ts`, both `envConfig` and `clientConfig` seem to set `sourcemapIgnoreList` to `true`:

- https://github.com/vitejs/vite/blob/main/packages/vite/rollup.config.ts#L19-L56

Looking at `rollup`'s docs for `output.sourcemapIgnoreList`, it seems this is a predicate for what to add to the ignore list, and can either be a boolean (that presumably globally enables/disables it), or a function returning a boolean:

- https://rollupjs.org/configuration-options/#output-sourcemapignorelist

So from that, it would seem that `create-preact` should already benefit from it, via the default specified in `vite` (which is the same sort of default that I thought/still think would make sense to set in `microbundle; but at this stage I'm just accepting that I am potentially wrong and don't know what i'm talking about)

**Comment by 0xdevalias** [comment]
> How about a case where the end-app isn't bundled/transpiled/etc, and thus has no chance to mark `x_google_ignoreList` for it's own dependencies; but is loading `preact` from a CDN. In that case, if `preact` directly set `x_google_ignoreList` in it's own sourcemap files, it would be correctly ignored listed; but since it doesn't, the end app can't benefit from that. Right?

Rather than just throwing this out there as a question, I decided to test it. Creating a tiny test file that loads `preact` from `https://unpkg.com/preact@latest/dist/preact.min.js`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Preact App</title>
  <script src="https://unpkg.com/preact@latest/dist/preact.min.js"></script>
</head>
<body>
  <div id="app"></div>
  <script>
    const { h, render, Component } = preact;

    class App extends Component {
      render() {
        return h('h1', null, 'Hello from Preact!');
      }
    }

    render(h(App), document.getElementById('app'));
  </script>
</body>
</html>
```

Looking at the 'Sources' tab, under 'Authored' -> 'unpkg.com', we can see that `preact@latest/src` is still shown, even when "Hide ignore-listed sourced" is ticked:

![image](https://github.com/preactjs/preact/assets/753891/5a77d1d9-212a-42b3-b6f4-9ba9d966efb7)

Now if I edit that source to add a `debugger` statement in the render:

```diff
      class App extends Component {
        render() {
+         debugger;

          return h('h1', null, 'Hello from Preact!');
        }
      }
// ..snip..
```

We see that the full call stack is shown in the debugger, including all of the `preact` internals that aren't really relevant to my end-user app code:

![image](https://github.com/preactjs/preact/assets/753891/7b01d432-ace2-450f-913d-8ee1e9baa105)

Now I can work around this by manually configuring the ignore list in my Chrome DevTools and adding a rule such as this:

```
^https://unpkg\.com/preact@latest/src/a
```

Which will 'dim' the `preact@latest/src` entry on the Sources tab when "Hide ignore-listed sourced" is disabled:

![image](https://github.com/preactjs/preact/assets/753891/94f29d5a-3851-456a-8223-e768eedc686f)

And it won't show at all when "Hide ignore-listed sourced" is ticked:

![image](https://github.com/preactjs/preact/assets/753891/a41553a2-690c-42d4-aed9-14272efe03a3)

Now, repeating the `debugger` test from above with my manually added ignore rule, we can see that there is a new unchecked "show ignore-listed frames" checkbox, and all of the `preact` internals are no longer shown by default in the debugger call stack:

![image](https://github.com/preactjs/preact/assets/753891/acfed50c-47c6-49f3-9884-37c831a2e5de)

And then if I want to see the `preact` internals in this call stack for whatever reason, I can tick the "show ignore-listed frames" checkbox, and they will be visible to me (but dimmed to show that they're generally ignored):

![image](https://github.com/preactjs/preact/assets/753891/cc601c77-89cb-48cd-b05c-6385cbbaac9b)

Now while every developer who uses preact could go and manually configure those ignore rules in their individual DevTools each and every time, that's a lot of cumulative manual effort, which to my understanding, is why the `x_google_ignoreList` convention was added to sourcemaps, which allows 'frameworks' (in the general colloquial use of the term), or just 'libraries' in general, to emit this in their library sourcemaps, and have it automagically configured with no manual effort required for any downstream developers. At least, that is my understanding, which has been reinforced by the test I just did above.

As I said earlier, if you still choose not to implement this here, that's fair enough; but I don't believe the reasoning you originally based that decision on holds true.
