### ISSUE TITLE
Incorporate preact to NEXTJS.

### ISSUE THREAD

**Issue by chiddekel** [preactjs/preact#4233]
Now on modern fronted solutions the best choice is NEXTjs.
Is any plan to incorporate preactjs in to NEXTJS by preactjs developers?

**Comment by rschristian** [comment]
[`next-plugin-preact`](https://github.com/preactjs/next-plugin-preact) used to exist for this purpose, but constant breakages on Next's side, as well as differing views on the best path forward for users, made this impossible to keep up with and unlikely to see future updates.

If you're still on Next v12 it should work for the most part though.

**Comment by marvinhagemeister** [comment]
Yup, there are no plans to support nextjs at the moment. With them being composed of many react core devs now nextjs has been relying on more and more internal react APIs. Supporting that would basically mean copying every decision of React at which point it makes more sense to go with React directly.

**Comment by chiddekel** [comment]
So better just using preach for react modules.
