### ISSUE TITLE
preact+react-modal,Uncaught TypeError: Cannot read properties of null (reading '__H')

### ISSUE THREAD

**Issue by AprilLastCherry** [preactjs/preact#4260]
I used preact and react-modal to implement a Modal. A child component of Reacts-Modal is implemented by preact, and using hooks in a child component prompts an error

This is the scene I prepared for the reenactment
https://codesandbox.io/p/github/AprilLastCherry/preact-demo/draft/purple-wildflower?file=%2Fsrc%2FApp.tsx%3A7%2C17&workspaceId=25022dc6-b7f9-4ebb-a0bd-889cc7cc7de8

1. An error message is displayed when Modal is opened

I don't understand how it works and hope to solve this problem, or react-modal and preact together is not a good solution，so what implementation should I use

**Comment by JoviDeCroock** [comment]
That codesandbox can't be accessed but that hooks warning is most likely due to duplicate Preact versions as many issues can be found before with `__H`

**Comment by AprilLastCherry** [comment]
Sorry, the example is not working properly. I'm not sure if it has to do with the use of preact or the configuration of rollup.

The code is as follows.

index.js
```javascript
import { render } from "preact";
import { useState } from "preact/hooks";
import Modal from "react-modal";
import Content from "./App";

Modal.setAppElement("#root");

const App = () => {
  const [modalIsOpen, setIsOpen] = useState(false);

  return (
    <>
      <button
        onClick={() => {
          setIsOpen(true);
        }}
      >
        Open Modal
      </button>

      <Modal isOpen={modalIsOpen}>
        <Content />
      </Modal>
    </>
  );
};

render(<App />, document.getElementById("root"));
```
child.js
```javascript
import { useState } from "preact/hooks";

const Content = () => {
  // get an error when use hooks 
  const [count, setCount] = useState(0);

  return <div />;
};

export default Content;
```
rollup.config.js
```javascript
import typescript from "rollup-plugin-typescript2";
import scss from "rollup-plugin-scss";
import clear from "rollup-plugin-clear";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import { babel } from "@rollup/plugin-babel";
import replace from "@rollup/plugin-replace";
import { terser } from "rollup-plugin-terser";
import serve from "rollup-plugin-serve";
import livereload from "rollup-plugin-livereload";
import htmlTemplate from "rollup-plugin-generate-html-template";
import postcss from "rollup-plugin-postcss";
import alias from "@rollup/plugin-alias";

export default {
  input: ["./src/index.tsx"],
  output: {
    file: "dist/main.js",
    format: "cjs",
  },
  plugins: [
    alias({
      entries: [
        { find: "react", replacement: "preact/compat" },
        { find: "react-dom/test-utils", replacement: "preact/test-utils" },
        { find: "react-dom", replacement: "preact/compat" },
        { find: "react/jsx-runtime", replacement: "preact/jsx-runtime" },
      ],
    }),
    typescript(), // 会自动读取sconfig.json配置文件
    postcss({
      extensions: [".css"], // 将scss解析成css
      extract: true,
      modules: true,
    }),
    clear({
      targets: ["dist"],
    }),
    replace({
      preventAssignment: true,
      "process.env.NODE_ENV": JSON.stringify("production"), // 否则会报：process is not defined的错
    }),
    nodeResolve({}),
    commonjs(),
    babel(), // 会自动读取babel的配置文件
    terser(),
    serve("dist"),
    livereload("src"), // 当src目录中的文件发生变化时，刷新页面
    htmlTemplate({
      template: "public/index.html",
      target: "dist/index.html",
    }),
  ],
  external: [
    {
      includeDependencies: true,
    },
  ], // 项目中引用的第三方库
};
```

**Comment by JoviDeCroock** [comment]
The reproduction still doesn't work though...

**Comment by AprilLastCherry** [comment]
codesandbox is still not accessible?

**Comment by AprilLastCherry** [comment]
> The reproduction still doesn't work though...

https://codesandbox.io/p/github/AprilLastCherry/preact-demo/draft/purple-wildflower?file=%2Frollup.config.js%3A14%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrjykeeh00073b6gom5czz5n%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrjykeeg00033b6g170ij6kz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrjykeeg00053b6gjlq4onci%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrjykeeg00063b6gjegcnl7n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrjykeeg00033b6g170ij6kz%2522%253A%257B%2522id%2522%253A%2522clrjykeeg00033b6g170ij6kz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrjz35fr00023b6hbs0imaj1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Frollup.config.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrjz35fr00023b6hbs0imaj1%2522%257D%252C%2522clrjykeeg00063b6gjegcnl7n%2522%253A%257B%2522id%2522%253A%2522clrjykeeg00063b6gjegcnl7n%2522%252C%2522activeTabId%2522%253A%2522clrjyknz300553b6g5hjc2ewq%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A10001%252C%2522id%2522%253A%2522clrjyknz300553b6g5hjc2ewq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrjykeeg00053b6gjlq4onci%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrjykeeg00043b6g46et8mt2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrjykeeg00053b6gjlq4onci%2522%252C%2522activeTabId%2522%253A%2522clrjykeeg00043b6g46et8mt2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
try this link

**Comment by JoviDeCroock** [comment]
... still unable to access

**Comment by AprilLastCherry** [comment]
> The reproduction still doesn't work though...
this demo code
https://github.com/AprilLastCherry/preact-demo.git

**Comment by AprilLastCherry** [comment]
> ... still unable to access

I'm sorry, but I don't know how to open the codesandbox permission. I thought I had already opened it.
I was so stupid, cry.

**Comment by JoviDeCroock** [comment]
No problem at all, will check it out later

**Comment by AprilLastCherry** [comment]
I solved the development problem by replacing functional components with class components，Although the underlying principle is still not clear, it can be developed.I plan figure out the principle later.
