### ISSUE TITLE
Island architecture with partial hydration

### ISSUE THREAD

**Issue by mvestnik** [preactjs/preact#4261]
Hi! 
I have a server on Go that gives me ready-made HTML with all the data I need. 

 In HTML I have this element:

![1.png](https://github.com/preactjs/preact/assets/150515091/717eb05a-10d0-4307-bac3-a351e7136cc2)

Component in tsx:

![2.png](https://github.com/preactjs/preact/assets/150515091/d23dd05b-1338-4332-8c0d-b02d1cb0d8ec)

Next, I plug in the hydration test middleware from the creator of Preact. 

Html and component are the same in structure, but still HTML is rerender. 

![3.png](https://github.com/preactjs/preact/assets/150515091/bd3c3c0d-029a-4e02-8a24-14338c90fd21)

I have three questions. 
1. What am I doing wrong? How can I avoid rerender again? 
2. Is island architecture even possible with Preact (when in static html one or few elements are connected by selector to a Preact component)? 
3. Is progressive hydration possible (e.g. by event)? 

Thanks

**Comment by rschristian** [comment]
> Next, I plug in the hydration test middleware from the creator of Preact.

You need to provide this, it's unclear what you're referring to.

> Is island architecture even possible with Preact

There are numerous island frameworks that support Preact, so yes. This is very possible.

**Comment by mvestnik** [comment]
- "You need to provide this, it's unclear what you're referring to".

I use this gist code for logging hydrate process:
https://gist.github.com/developit/90d94b2b92c8a2f466f2f44bca5d1cec

But it is possible to achieve this effect without islands framework and by simply connecting the component to the html element by selector?

 I can hydrate ONE element on a page and not the entire DOM, right?

**Comment by mvestnik** [comment]
I figured it out, I apologize. Turns out spaces and tabs are important too.
