### ISSUE TITLE
When the value of setState remains unchanged, the state-driven controlled component, such as <input/>, seems to no longer be under the influence of the state.

### ISSUE THREAD

**Issue by kriastans** [preactjs/preact#4267]
- [x] Check if updating to the latest Preact version resolves the issue

# Describe the bug
When the value of setState remains unchanged, the state-driven controlled component, such as `<input/>`, seems to no longer be under the influence of the state.

# To Reproduce

https://stackblitz.com/edit/create-preact-starter-lcgsrs?file=src%2Findex.jsx,index.html

The intention of this input field is to prohibit users from entering any non-numeric characters. It works as expected in React, but in Preact, it appears to turn the input into an uncontrolled component when the value of the state remains unchanged.

# Steps to reproduce the behavior:

1. Input 123, should see 123 displayed in `<input/>`
2. Keydown "d", should see 123 displayed in `<input/>`, but saw 123d displayed in `<input/>`
3. Keydown "f", should see 123 displayed in `<input/>`, but saw 123df displayed in `<input/>`
4. Keydown "1", should see 1231 displayed in `<input/>`

**Comment by JoviDeCroock** [comment]
This is a known issue in Preact as we don't have real controlled components, an alternative for this can be to store the state in an object or like [this PR](https://www.jovidecroock.com/blog/controlled-inputs) restore the value back when no change happens.
