### ISSUE TITLE
preact/compat's SetStateAction is different from React's SetStateAction

### ISSUE THREAD

**Issue by tobycm** [preactjs/preact#4285]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

preact/compat's [SetStateAction](https://github.com/preactjs/preact/blob/main/hooks/src/index.d.ts#L5) is different from React's [SetStateAction](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/ts5.0/index.d.ts#L1727)

**Expected behavior**
It should be the same, unless the internal mechanics are different (unlikely because the transpiled JS works fine).

**Comment by rschristian** [comment]
Can you clarify what the actual problem is? A type being different shouldn't be an issue on its own.

**Comment by tobycm** [comment]
The type checking throws an error when it shouldn't because the transpiled code works fine.

**Comment by rschristian** [comment]
But can you give an actual example of this? That's what I'm asking for.

There's many ways in which your code could work just fine while not adhering to correct types.

**Comment by tobycm** [comment]
Example:

React: https://codesandbox.io/p/devbox/condescending-wilbur-9gf73z

Preact: https://codesandbox.io/p/devbox/k4mvdw
