### ISSUE TITLE
When I attempt to extend HTMLAttributes every intrinsic element becomes of type any

### ISSUE THREAD

**Issue by Zequez** [preactjs/preact#4301]
This is the type declaration I'm using:

```js
import { JSXInternal as JSXI } from 'preact/src/jsx';

declare module 'preact/src/jsx' {
  namespace JSXInternal {
    interface HTMLAttributes<T> extends JSXI.HTMLAttributes<T> {
      class?: any;
    }
  }
}
```

Essentially what I want to do is to extend the HTMLAttributes in order to be able to pass any type to the "class" attribute so I can then process it on the options.vnode hook; however when I use this declaration every element becomes of type any.

There was a long discussion a couple of years ago with something similar, but it was for extending IntrinsicElement not HTMLAttributes, and that thread is how I arrived to the current shape of the declaration file.

**Comment by rschristian** [comment]
I believe this is what you want instead:

```ts
interface MyCustomProps {
  class?: any;
}

declare module 'preact' {
  namespace JSX {
    interface IntrinsicAttributes extends MyCustomProps {}
  }
  interface Attributes extends MyCustomProps {}
}

export {};
```

**Comment by JoviDeCroock** [comment]
Closing as answered
