### ISSUE TITLE
Current plan for event types?

### ISSUE THREAD

**Issue by tjcrowder** [preactjs/preact#4309]
What's the current plan for the type information for events?

[The documentation](https://preactjs.com/guide/v10/typescript/#typing-events) only mentions class components, and shows using DOM event types like `MouseEvent`, which aren't as useful as they might be because `currentTarget`'s type is `EventTarget`. (You can control the type of `this` via a `this` parameter declaration [even in function components, provided you don't use an arrow function], but not the type of `currentTarget`.)

But in #2301 it looks like `TargetedEvent` and its subtypes are the way forward, not least because they let you declare the type for `currentTarget`. (Those are currently in the JSX namespace, though #2706 suggests that may change.)

Is `TargetedEvent` the plan then?

If so, would a documentation PR covering that be welcome (at some point)?

**Comment by rschristian** [comment]
I don't know if there's any plan per se, but indeed, `TargetedEvent` seems to work pretty well, though it should be inferred automatically and not required to be explicitly set these days.

All docs PRs are greatly appreciated, [preact-www](https://github.com/preactjs/preact-www) is the docs repo with the [typescript doc residing here](https://github.com/preactjs/preact-www/blob/master/content/en/guide/v10/typescript.md).

**Comment by tjcrowder** [comment]
@rschristian Thanks! Wow, this is embarrassing, how did I fail to catch the inference provided for inline handlers?! (I almost never write them, but it was the obvious thing to check.) That really answers the question about what the current thinking on event types is, sorry for poor research. I'll check out the docs repo and see how/whether I can help there.

**Comment by rschristian** [comment]
Oh, no worries!

The types being correctly inferred is a quite recent development as of the start of this year I believe -- anything older (which is the vast majority of the 10.x.x release line) won't work in the same fashion.
