### ISSUE TITLE
onFocusIn and onFocusOut events incorrectly set

### ISSUE THREAD

**Issue by objerke** [preactjs/preact#4314]
**Describe the bug**
The changing in casing of the `onfocusin` and `onfocusout` attributes to `onFocusIn` and `onFocusOut` in [4307](https://github.com/preactjs/preact/pull/4307), introduced in [10.19.7](https://github.com/preactjs/preact/releases/tag/10.19.7),  breaks those types of event listeners.

**To Reproduce**
1. Go to https://stackblitz.com/edit/vitejs-vite-8tupqq?file=src%2Fmain.tsx
2. Click on the top input field, then click on the next input field
3. See that the top most component does not change from "No focus" to "Has focus". The `focusin` event listener is never triggered.

Inspecting the element using dev tools, the `onFocusIn` attrbute creates an event listener for the non standard `FocusIn` event instead of `focusin`.
![image](https://github.com/preactjs/preact/assets/8665943/a157a4f4-fa30-4b4f-9086-ef17b4b0c77b)

**Expected behavior**
The same behavior of setting `onFocusIn` as the previous `onfocusin`, meaning event listeners for the `focusin`
since the latter has been removed from the declaration file.

![image](https://github.com/preactjs/preact/assets/8665943/8070afab-9fd7-4fb6-a251-cc88df7d83a2)

**Comment by JoviDeCroock** [comment]
Heh, I did not think this would be a thing but `'focusin' in document.createElement('div')` evaluates to `false` hence why this started failing. 😅

**Comment by objerke** [comment]
The DOM is wonderful at times 😉 

Here is a failing test that can be added to `events.test.js`

```
it('should support camel-case focus event names', () => {
	render(<div onFocusIn={() => {}} onFocusOut={() => {}} />, scratch);

	expect(proto.addEventListener)
		.to.have.been.calledTwice.and.to.have.been.calledWith('focusin')
		.and.calledWith('focusout');
});
```

**Comment by rschristian** [comment]
Looks like the property exists in WebKit but not Chrome or FF, do we just need to give them a little push? I've had to do that in the past for FF a couple times.

**Comment by objerke** [comment]
@JoviDeCroock Amazing pace of fixing this and [4221](https://github.com/preactjs/preact/issues/4221)! 💯 🥳
