### ISSUE TITLE
Cannot read properties of undefined (reading '__m')

### ISSUE THREAD

**Issue by joshua7v** [preactjs/preact#4326]
**Describe the bug**

call `useId` will throw an error `Cannot read properties of undefined (reading '__m')` similar to #4277
the environment is with Astro, probably related, but the error throws from preact

**To Reproduce**

1. open the stackblitz link from Astro's Preact example https://github.com/withastro/astro/tree/latest/examples/framework-preact
2. navigate to a component such as src/components/message.tsx
3. add `import { useId } from 'preact/hooks';` and call `useId()` within component
4. look at the console or page preview to see the error

<img width="1920" alt="Snipaste_2024-03-26_10-48-27" src="https://github.com/preactjs/preact/assets/4159858/1a700c48-b8a2-4442-9b6c-5cafdedff013">

**Expected behavior**

useId is pretty useful, it should work

**Comment by rschristian** [comment]
This is an issue in `preact-ssr-prepass`, which the Astro integration uses.

There's already [an open issue there](https://github.com/preactjs/preact-ssr-prepass/issues/60) you can track, but I should have a fix together shortly. Looks it just fell out of sync a bit with RTS (which Astro might be able to switch to now?)

**Comment by marvinhagemeister** [comment]
Yeah the functionality provided by `preact-ssr-prepass` is directly provided by `preact-render-to-string` these days. Switching to the latter is recommended.

**Comment by rschristian** [comment]
Already switching them over: https://github.com/withastro/astro/pull/11464
