### ISSUE TITLE
`hydrate` doesn't replace attributes at root replaced node

### ISSUE THREAD

**Issue by crutchcorn** [preactjs/preact#4328]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

With an HTML pre-hydrated value like this:

```html
<div id="app">
    <ul style="color: red">
        <li>Non-hydrated, should be red</li>
    </ul>
</div>
```

Hydrating with an `ul` of different `style` attributes, like so:

```tsx
import { hydrate } from 'preact';

function App() {
  return (
    <ul style={{ color: 'blue' }}>
      <li>Hydrated, should be blue</li>
    </ul>
  );
}

hydrate(<App />, document.getElementById('app'));
```

Does not replace the color from the SSR with the color from the client.

**To Reproduce**

https://stackblitz.com/edit/vitejs-vite-eckx3s

1. Run app with JS enabled
2. See error

**Expected behavior**
What should have happened when following the steps above?

Ideally, the root should be like so after hydrations:

```html
<div id="app">
  <ul style="color: blue">
      <li>Hydrated, should be blue</li>
  </ul>
</div>
```

**Comment by crutchcorn** [comment]
Interesting, this behavior appears to be intentional according to the tests:

https://github.com/preactjs/preact/blob/main/test/browser/hydrate.test.js#L195-L220

Can someone help me provide context for understanding _why_ and how to solve this issue in our app?

**Comment by rschristian** [comment]
This looks to be the correct behavior.

Hydration differs from a standard render in that it's essentially just hooking up event handlers, "hydrating" the static HTML and making it interactive. As a result, this is a bit faster, but it will not alter elements or their attributes, as that's not hydration.

Generally, your server-rendered HTML should match what will be rendered on the client, but if it can't for some reason and you still want SSR'd HTML, you could just call `render()` on the client instead.

**Comment by crutchcorn** [comment]
Understood. I'll see if I'm able to make a PR upstream to allow us to opt-into `render` instead of `hydrate`

**Comment by rschristian** [comment]
Additionally, you may want to try moving your client-side logic into a `useEffect` or simply skip rendering that specific component on the server.
