### ISSUE TITLE
Render mui cache inside shadow dom leaves style sheets in head and content unstyled 

### ISSUE THREAD

**Issue by codeHul** [preactjs/preact#4338]
I am using Material ui in my web-component created with Preact. The. issue I've been running into is that I'm having trouble targeting the shadow dom when following Material's guide on how to move the style sheets inside the shadow dom. 

**To Reproduce**

To reproduce I set up a project from scratch using Vite and preact and then I installed Material ui on top of it. Besides my App files I added a Material Slider. In my main file I followed Material ui's guide regarding styling in shadow dom, https://mui.com/material-ui/customization/shadow-dom/ .

1. Go to https://stackblitz.com/edit/create-preact-starter-zcd2qh?file=src%2Fmain.jsx,src%2FSliderSizes.jsx
2. Wait for the project to load and observe
3. If you inspect the page you will se the Material ui tags correctly rendered inside the Shadow dom but the style sheets remain in the document head
4. Uncomment the ReactDOM.createRoot code in main.jsx and the style sheets are moved inside the shadow dom.

**Expected behavior**
The style sheets should be moved inside shadow dom so that the styling is applied on the slider tags.

**Comment by rschristian** [comment]
Your example is missing `import { render } from 'preact'`, though I wouldn't recommend calling both `register` & `render`, that seems like it'll cause issues.
