### ISSUE TITLE
Runtime error when using an external react module

### ISSUE THREAD

**Issue by lokeb** [preactjs/preact#4353]
Hi. I have a strange problem. The browser throws an error when the external module calls useState as follows:
```code
Uncaught TypeError: Cannot read properties of undefined (reading '__H')
    at h (hooks.module.js:1:161)
    at y (hooks.module.js:1:297)
    at p (hooks.module.js:1:261)
    at async-storage.js:248:36
    at k.Main [as constructor] (main.js:11:30)
    at k.B [as render] (preact.module.js:1:8957)
    at O (preact.module.js:1:6465)
    at $ (preact.module.js:1:1774)
    at O (preact.module.js:1:6603)
    at D (preact.module.js:1:9016)
```
The module is linked externally using npm link. When I copy the external module inside the project, then there is no such problem. When using this same approach with a React project, the application works fine. The external module, a react effect which is a single file is as follows:

```js
import { useState, useEffect } from 'react'

\\the browser throws an error when useState is called:

return () => {
    //line 248:
    const [_, setUpdate] = useState(null)
}
 ```

The only difference in using externally and internally is as follows:
```js
//externally
import storage from 'async-storage'
//internally
import storage from './async-storage'
```

webpack:
```js
resolve: {
    alias: {
      'react': 'preact/compat',
      'react-dom/test-utils': 'preact/test-utils',
      'react-dom': 'preact/compat'
    }
  },
  module: {
    rules: [
      {
        test: /\.m?js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
            plugins: [
              ['@babel/plugin-transform-class-properties'],
              ["@babel/plugin-transform-react-jsx"],
              ["babel-plugin-wildcard"]
            ]
          }
        }
      },
```
There isn't any chance of multiple copies of preact because I am not using any other modules that use preact.

**Comment by rschristian** [comment]
> The module is linked externally using npm link. When I copy the external module inside the project, then there is no such problem. 

Don't use `npm link`, it's very broken in regards to symlinks. Use something like [`yalc`](https://npm.im/yalc) instead.

> There isn't any chance of multiple copies of preact because I am not using any other modules that use preact.

This isn't quite how it works.

What's happening is your lib is pulling a copy of Preact through the symlink and your local application also has one, ergo, two copies.

**Comment by rschristian** [comment]
React's internals might be a bit more forgiving here? Not entirely sure to be honest, I don't work with React much.

You could also be running up against the dual-package hazard potentially, as React still doesn't ship ESM. Depends on how you're building your package.

**Comment by marvinhagemeister** [comment]
Yeah it's 99% an issue with the build tooling used. The error occurs when there are multiple Preact versions used.

**Comment by rschristian** [comment]
Going to close this on out as it's hopefully been addressed.

Feel free to reply if you're still having issues and we can take a look.
