### ISSUE TITLE
render() with popover doesn't work

### ISSUE THREAD

**Issue by codedread** [preactjs/preact#4380]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
As per [this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover) the `popover` attribute is available in all browser. However, I get a complaint with Preact 10.21.0: `render(<div popover>foo</div)`:

"Popover not assignable to type htmlattributes htmldivelement"

**To Reproduce**

See the above snippet. Also this [react bug](https://github.com/facebook/react/issues/27479).

**Comment by rschristian** [comment]
Just a type error or an actual functional issue?

#4378 addresses the types

**Comment by codedread** [comment]
Yes, I think it's just a type error. Functionality it seems to work.
