### ISSUE TITLE
False positive on render loop detection

### ISSUE THREAD

**Issue by alexander-entin** [preactjs/preact#4381]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
"Too many re-renders" error shows and the app stops when there is no real issue.

**To Reproduce**
https://stackblitz.com/edit/vitejs-vite-kuwua3?file=src%2Fmain.tsx

1. Click the button 25 times
2. See error

**Expected behavior**
No error, counter == 25

**Comment by howlowck** [comment]
RL example of hitting this issue (more common than hitting the same button 25 times) is when there is any controlled text input. After typing 25 characters in the input box, *boom* error, and the input becomes uncontrolled. Please push a new patch version with #4382 fix. 🙏
