### ISSUE TITLE
Rendering just gets slower over time

### ISSUE THREAD

**Issue by SuperDisk** [preactjs/preact#4383]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
It seems that as time goes on and things get rendered repeatedly, performance just slows down to the point where rendering takes much, much longer than it did at the start. I experienced this in one of my projects, and when I switched to React, the performance issue went away, which implies it's Preact-specific.

**To Reproduce**

https://codesandbox.io/p/devbox/preact-bug-cr5gfc?file=%2Fsrc%2FApp.tsx%3A21%2C1

Press <kbd>Re-render 1000 times</kbd> to do some re-rendering. At first it's quite fast, and then slowly but surely it bogs down to the point where it's taking a massive amount of time to increment the counter.

I can reproduce the bug in Firefox `124.0.2 (64-bit)`, but not on Chromium `Version 124.0.6367.155 (Official Build) snap (64-bit)`

**Expected behavior**
Performance should remain at the same level as when the app starts up. This seems like a pretty severe issue to me.

**Comment by JoviDeCroock** [comment]
Hmm, that's odd! Mind trying something like

```
import { options } from 'preact'

options.debounceRendering = queueMicrotask
```

Also try that with requestIdleCallback and setTimeout.

**Comment by SuperDisk** [comment]
Just tried it, the same problem still seems to occur using `setInterval`, `requestIdleCallback`, and `setTimeout`.

**Comment by JoviDeCroock** [comment]
For me it works correctly on both FF and Chrome 😅

**Comment by SuperDisk** [comment]
> EDIT: you didn't do what is in the code-snippet though 😅

What do you mean? I put that code snippet in and tried all the variations. Then I removed the snippet, so that's why it's not there when you click the link.

**Comment by SuperDisk** [comment]
I just tried that as well-- it does seem to speed things up a bit, but by the time it reaches 1000 it's definitely slowing down.

**Comment by JoviDeCroock** [comment]
Could you do a memory dump because for me there's no more leak with that disabled

**Comment by ritschwumm** [comment]
if i understand the code correctly, then every click on the button creates a new `setTimeout` "loop" and this loop never ends - so i'd expect it to become slower with each click on the button due to the increasing amount of active setTimeouts..

**Comment by JoviDeCroock** [comment]
This is correct yes! I didn't look at the new code, the first version made sense as it just called setCount 1000 times 😅

**Comment by SuperDisk** [comment]
https://github.com/preactjs/preact/assets/1688837/63990188-9844-48b1-b894-15380deea189

You can see it starts extremely fast, but by the time it reaches 1000 it's crawling.

**Comment by SuperDisk** [comment]
Aha, I disabled Preact Devtools and it seems the memory leak goes away. My bad for not mentioning I had that enabled, I forgot about it :(

Curious what's causing it there though.

**Comment by JoviDeCroock** [comment]
Both prefresh as well as the dev-tools hold onto VNodes, we are probably running into some scenario where we fail to cut the link of i.e. `_parent`/`_children` and it cant' be gc'ed.

**Comment by JoviDeCroock** [comment]
CC @marvinhagemeister just so you're aware of this

**Comment by JoviDeCroock** [comment]
Will close out this issue now as we're aware of this issue in prefresh/devtools but those are also just for development
