### ISSUE TITLE
one more time on the Ukraine banner

### ISSUE THREAD

**Issue by bkerin** [preactjs/preact#4388]
I want to better and more calmly say why I find these banners so objectionable.

I have strong opinions on the conflict in Ukraine, but more generally the banner presumes to speak for the entire community on a matter where unanimity is inconceivable.  This would be objectionable if it said the opposite.  I notice your project predates the recent acute phase of the conflict.  Did you check if all your devs really do stand with Ukraine?  How about all your issue reporters?

If the banner said "Many of the devs stand with Ukraine" I'd cheerfully use your software, but since I almost always end up at least submitting issues for libraries I use I won't use I won't start with preact or any of it's dependencies.  I'm not willing to have any contributions that I end up making used for political purposes.

**Comment by bkerin** [comment]
Btw I notice yarn appears to have taken down these banners

**Comment by JoviDeCroock** [comment]
Let me start out by saying this from my own point of view, if you think war-crimes and other atrocities are political then that's something I would encourage you to reconsider. I realise that banners like these can come across as conveying a progressive agenda, however what I as a person stand most with is showing that human suffering shouldn't be taken lightly.

If a simple banner reminding people about the atrocities a country has to go through offends them to the point of not wanting to interact with the repository then I am really happy that you don't want to use this tech and I would even ask you to check where this is coming from.

I also want to take this opportunity to warn you that next time you post one of these repeated issues I will give you a timeout of interacting with any of the repositories I am a part of.
