### ISSUE TITLE
preact@10.20.2 application is broken on old user agents

### ISSUE THREAD

**Issue by adrian-wozniak** [preactjs/preact#4415]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Change https://github.com/preactjs/preact/pull/4318 caused that application is not rendered correctly on old user agents. Some of the components blink until they are finally rendered some of them are not rendered at all.

It turned out that [`isConnected` API is not widely available](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected#browser_compatibility) and old user agents are no longer capable of rendering preact app properly.

**To Reproduce**

One of the user agents I faced that problem is `Opera/9.80 (Linux mips; ce-html/1.0) Presto/2.12.407 Version/12.50 HbbTV/1.3.1 (; Humax; fvp4000t; UKTFAE 1.03.54; 1.0.0; wired) ce-html/1.0 FVC/1.0 (Humax; fvp4000t;)`. `isConnected` property is `undefined`.

**Expected behavior**
Application should be rendered properly.

**Comment by JoviDeCroock** [comment]
It's [available in 95%](https://caniuse.com/?search=isConnected) - however Preact X has to support IE11 so we have to find a solution for that. Thank you for reporting

**Comment by adrian-wozniak** [comment]
@JoviDeCroock you are right, 95% definitely means "widely" 😅. I meant that it is not supported by all actively used user agents :). Anyway, thanks for handling that!
