### ISSUE TITLE
useEffect never called

### ISSUE THREAD

**Issue by trusktr** [preactjs/preact#4417]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

I have this code:

```js
/** @jsx h */
import { h, render } from 'preact';
import { useEffect } from 'preact/hooks';

function Container(props) {
  return <div style="width: 100%; height: 100%;">{props.children}</div>;
}

const App = () => {
  console.log('App');

  useEffect(() => {
    console.log('EFFECT !!!!!!!!!!!');
  }, []);

  return <Container></Container>;
};

render(<App />, document.body);
```

The hook is never called, the `EFFECT` log never happens.

**Expected behavior**

Isn't the effect supposed to run once?

Also the DOM content in the `<body>` is just `<undefined>`. 

**To Reproduce**

https://stackblitz.com/edit/preact-starter-template-jzkt7e?file=App.jsx

(Heads up, this is a fork of the stackblitz that is the number one result for "stackblitz preact" on Google)

**Comment by trusktr** [comment]
Don't know why that one doesn't work (it is the top result in Google for "stackblitz preact"). This one works though:

https://stackblitz.com/edit/create-preact-starter-kak5bf?file=src%2Findex.jsx

**Comment by rschristian** [comment]
Looks like a fairly buggered up example, with the empty HTML document and all.

StackBlitz has a Preact app on the front page under the 'FrontEnd' tab, and we have one we provide here for issues: https://stackblitz.com/edit/create-preact-starter

Closing, as it's not an issue.
