### ISSUE TITLE
JSX prop works incorrectly on Custom Element, Preact fails to detect JS property setter

### ISSUE THREAD

**Issue by trusktr** [preactjs/preact#4418]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

[Preact docs](https://preactjs.com/guide/v10/web-components/#properties-and-attributes) say the following:

> When a Custom Element defines a [setter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) for a given property, Preact detects its existence and will use the setter instead of an attribute.

However, I have Custom Elements with setters and Preact calls `setAttribute` instead of setting the JS properties as described.

**To Reproduce**

https://stackblitz.com/edit/create-preact-starter-ydvaru?file=src%2Findex.jsx

In this example, the `console.assert`s statements in the `useEffect` show that the JS property setter exists but that the attribute still gets set instead of the JS property.

The `debugger` statement in `getMountPoint`: it will pause on `toString` of the value passed into `mount-point={}`. When the devtools debugger is paused, we can see that the value gets passed into `setAttribute`.

**Expected behavior**

We expect the value to be passed to the JS property because the setter exists, as described in the Preact documentation.

**Comment by rschristian** [comment]
Can you please provide a _minimal_ reproduction? It's much easier to help you if you cut everything down to the bare minimum.

If you're defining a custom element, do it in the reproduction please. Don't libs from elsewhere.

**Comment by trusktr** [comment]
Sure, here's a simplified example. Basically same steps. I added `console.assert`s with descriptions inside the `useEffect`.

https://stackblitz.com/edit/create-preact-starter-ydvaru?file=src%2Findex.jsx

**Comment by rschristian** [comment]
This is working as intended.

`mount-point` and `mountPoint` are not the same thing; we don't try to coerce/guess prop names. If the label cannot be found on the DOM element, we set it as an attribute. You need to use `<custom-element mountPoint={...}></custom-element>`.

If you wanted to contribute a note on casing/naming, you could do so [here](https://github.com/preactjs/preact-www/tree/master/content/en/guide/v10/web-components.md)

**Comment by trusktr** [comment]
Ah, I see. Thanks! Yeah that note will be useful.

**Comment by trusktr** [comment]
What are your thoughts on the wording here in this PR:

- https://github.com/preactjs/preact-www/pull/1156

I'm not sure if you'd the part 

> like other other JSX compilers or runtimes may

That sentence could just be something like the following if mentioning other libs/frameworks/tools is not desirable:

> Preact maps camelCase JSX property names to the JS properties of the custom elements, not dash-case.
