### ISSUE TITLE
Type inference of Omit type not working, CSSProperties in preact/compat

### ISSUE THREAD

**Issue by MTtankkeo** [preactjs/preact#4427]
```ts
import { CSSProperties } from "preact/compat";

interface ExampleProperties extends Omit<CSSProperties, "display"> {
    // ... skip propertys

    [key: string]: any;
}
```
This issue is not present in react, In the code above, the auto-completion function of Sample Properties (which seems to be a type inference problem) is not working.

Of course, if you don't use Omit, type inference of the CSSProperties is working.

**Comment by rschristian** [comment]
This is a TypeScript "issue" (technically working as intended, "limitation" might be a better word), not a Preact issue. See: https://github.com/microsoft/TypeScript/issues/49656

You can use something like this instead:

```ts
type MyOmit<T, K extends PropertyKey> = { [P in keyof T as Exclude<P, K>]: T[P] }

interface ExampleProperties extends MyOmit<CSSProperties, 'display'> {
    [key: string]: any;
}
```

**Comment by MTtankkeo** [comment]
thanks, and that has helped me a lot.

**Comment by rschristian** [comment]
Oh, and as I forgot to link it, here's a StackOverflow post that I swiped that impl from with a bit more context: https://stackoverflow.com/a/76616671/8963648
