### ISSUE TITLE
Aliasing in node refers to the old @preact/compat

### ISSUE THREAD

**Issue by vergilfromadyen** [preactjs/preact#4445]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
The documentation says [aliasing in node](https://preactjs.com/guide/v10/getting-started/#aliasing-in-node) should define dependencies as:
```json
{
  "dependencies": {
    "react": "npm:@preact/compat",
    "react-dom": "npm:@preact/compat",
  }
}
```

However, [`@preact/compat`'s last release was in 2022](https://www.npmjs.com/package/@preact/compat?activeTab=versions) and the logic cannot be easily replaced by referring to [`preact-compat`](https://github.com/preactjs/preact/blob/main/compat/package.json#L2) because [its last release was in 2019](https://www.npmjs.com/package/preact-compat?activeTab=versions).

I'm not sure if this is the correct place to open this issue or in [compat-alias-package](https://github.com/preactjs/compat-alias-package) but it seems like `compat-alias-package` could "just" re-export `preact/compat`.

For context: I am working on a Preact *library* (as in, it is consumed by applications and is not by itself an application) and I'd like to make use of tanstack-query but this ties my hands somewhat.

Can you advise if this is in fact an issue?

**Expected behavior**
There is a npm package (not a subpath) to refer to

**Comment by JoviDeCroock** [comment]
It does just re-export Preact/compat 😅 https://github.com/preactjs/compat-alias-package/blob/main/index.mjs#L1-L2 we need this to correctly alias in node for i.e. when no bundler is used.

**Comment by vergilfromadyen** [comment]
Ah, nevermind then, I wasn't paying attention :)

Thanks for the quick reply!
