### ISSUE TITLE
Failed to execute insertBefore DOMException happens on rendering list of items

### ISSUE THREAD

**Issue by ycharniauski** [preactjs/preact#4447]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

DOMException happens on rendering list of items.
<img width="954" alt="image" src="https://github.com/user-attachments/assets/29b0700d-fb92-4d6f-ba29-558b25df3d41">

**To Reproduce**

To reproduce the issue we need reorder list of items and in the same time item component should render another component. Bug happens only if items have keys.

Here is a [demo](https://preactjs.com/repl?code=aW1wb3J0IHsgcmVuZGVyIH0gZnJvbSAncHJlYWN0JzsKaW1wb3J0IHsgdXNlU3RhdGUsIHVzZUVmZmVjdCwgdXNlQ2FsbGJhY2ssIHVzZU1lbW8gfSBmcm9tICdwcmVhY3QvaG9va3MnOwoKY29uc3QgSXRlbUEgPSAoeyB0ZXh0IH0pID0%2BIDxkaXY%2BQToge3RleHR9PC9kaXY%2BCmNvbnN0IEl0ZW1CID0gKHsgdGV4dCB9KSA9PiA8ZGl2PkI6IHt0ZXh0fTwvZGl2PgoKY29uc3QgSXRlbSA9ICh7IHRleHQgfSkgPT4gKAogIE1hdGgucmFuZG9tKCkgPCAwLjUgPyA8SXRlbUIgdGV4dD17dGV4dH0gLz4gOiA8SXRlbUEgdGV4dD17dGV4dH0gLz4KKQoKY29uc3QgaXRlbXMgPSBbCiAgeyBpZDogMSwgdGV4dDogIkxlYXJuIEphdmFTY3JpcHQiLCBkb25lOiBmYWxzZSB9LAogIHsgaWQ6IDIsIHRleHQ6ICJMZWFybiBQcmVhY3QiLCBkb25lOiBmYWxzZSB9LAogIHsgaWQ6IDMsIHRleHQ6ICJQbGF5IGFyb3VuZCBpbiBKU0ZpZGRsZSIsIGRvbmU6IHRydWUgfSwKICB7IGlkOiA0LCB0ZXh0OiAiQnVpbGQgc29tZXRoaW5nIGF3ZXNvbWUiLCBkb25lOiB0cnVlIH0sCl0KCmZ1bmN0aW9uIENvdW50ZXIoKSB7Cgljb25zdCBbY291bnQsIHNldENvdW50XSA9IHVzZVN0YXRlKDApOwoJY29uc3Qgc29ydGVkID0gaXRlbXMuc29ydCgoKSA9PiBNYXRoLnJhbmRvbSgpIC0gMC41KQoKCXJldHVybiAoCgkJPGRpdiBjbGFzcz0iY291bnRlci1jb250YWluZXIiPgoJCQk8YnV0dG9uIG9uQ2xpY2s9eygpID0%2BIHNldENvdW50KGNvdW50ICsgMSl9PlJlZnJlc2gge2NvdW50fTwvYnV0dG9uPgoJCQk8dWw%2Be3NvcnRlZC5tYXAoaXRlbSA9PiA8SXRlbSBrZXk9e2l0ZW0uaWR9IHRleHQ9e2l0ZW0udGV4dH0gLz4pfTwvdWw%2BCgkJPC9kaXY%2BCgkpOwp9CgpyZW5kZXIoPENvdW50ZXIgLz4sIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhcHAnKSk7Cg%3D%3D)

Seems issue happens when `__k` pointer becomes `null`
![image](https://github.com/user-attachments/assets/aa31e79c-4e91-4fa2-ae46-d54747b1b4d5)

**Expected behavior**

**Comment by JoviDeCroock** [comment]
I tried to reproduce this by logging in the Array from the demo and the component that gets rendered and came to this test which does not fail...

```
	it.only('test', () => {
		const ItemA = ({ text }) => <div>A: {text}</div>
		const ItemB = ({ text }) => <div>B: {text}</div>

		const Item = ({ text, type }) => {
			return type === 'B' ? <ItemB text={text} /> : <ItemA text={text} />
		}

		let set;
		class App extends Component {
			constructor(props) {
				super(props);
				this.state = { items: a, mapping: mappingA };
				set = (items, mapping) => {
					this.setState({ items, mapping });
				}
			}

			render() {
				return (
							<ul>
							{this.state.items.map((key, i) => (
								<Item key={key} type={this.state.mapping[i]} text={key} />
							))}
						</ul>
				)
			}
		}

		const a = ['3', '2', '4', '1'];
		const mappingA= ['A', 'B', 'B', 'B']
		const b = ['3', '2', '1', '4'];
		const mappingB = ['B', 'A', 'B', 'A']
		const c = ['4', '2', '1', '3'];
		const mappingC = ['A', 'B', 'B', 'A']

		render(<App items={a} mapping={mappingA} />, scratch);
		expect(scratch.innerHTML).to.equal('<ul><div>A: 3</div><div>B: 2</div><div>B: 4</div><div>B: 1</div></ul>');

		set(b, mappingB);
		rerender();
		expect(scratch.innerHTML).to.equal('<ul><div>B: 3</div><div>A: 2</div><div>B: 1</div><div>A: 4</div></ul>');

		set(c, mappingC);
		rerender();
		expect(scratch.innerHTML).to.equal('<ul><div>A: 4</div><div>B: 2</div><div>B: 1</div><div>A: 3</div></ul>');
	})
```
