### ISSUE TITLE
preact cannot be installed from git remote url

### ISSUE THREAD

**Issue by hzy** [preactjs/preact#4474]
- [x] Check if updating to the latest Preact version resolves the issue (Checked, the issue still reproduce)

**Describe the bug**
When I try to install preact from git (e.g. `npm install git+https://github.com/preactjs/preact.git#10.23.0`), the installation fails.

It is likely that `npm-merge-driver-install` in prepare scripts caused the failure

**To Reproduce**

1. create a empty project with a package.json file like below:
    ```
    {
      "dependencies": {
        "preact": "git+https://github.com/preactjs/preact.git#10.23.0"
      }
    }
    ```
2. run `npm install`
3. install will FAIL, the log below seems to be the key reason of failure
    ```
    $ ......
    $ npm error npm-merge-driver-install: Current working directory is not using git or git is not installed, skipping install.
    $ ......
    ```

**Expected behavior**
install should succeed.

**Comment by JoviDeCroock** [comment]
It's pretty rare for these to work, I acknowledge that there's an issue there with the install but still you would need to run `build`/... for this to work correctly. An easier way around this would be to use the `tar` files included in specific releases https://github.com/preactjs/preact/releases/tag/10.23.2

**Comment by rschristian** [comment]
> but still you would need to run `build`/... for this to work correctly

`build` is part of our `prepare` script; assuming it completed, the user wouldn't need to do anything else.

+1 for using releases though, it saves time and and Git dependencies with NPM has some security concerns last I checked.
