### ISSUE TITLE
Hooks broken in pure browser aka "no build tools route"

### ISSUE THREAD

**Issue by psydvl** [preactjs/preact#4477]
- [x] Check if updating to the latest Preact version **NOT** resolves the issue 

**Describe the bug**
preact/hooks.useState (or any other hook) broken if used as is

**To Reproduce**

https://periwinkle-tabby-lasagna.glitch.me
https://glitch.com/edit/#!/periwinkle-tabby-lasagna

1. copy and paste to browser url
    ```html
    data:text/html,<script type="module">
    import { useState } from "https://esm.sh/preact/hooks";
    const [foo, setFoo] = useState(0);
    </script>
    ```
2. Open console
    Firefox: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>
    Chrome-based:  <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>
3. See error:
    Firefox
    ```
    Uncaught TypeError: r is undefined
        Preact 4
            l
            I
            B
            <anonymous>
    index.js:148:2
    ```
    Chrome-based
    ```
    Uncaught TypeError: Cannot read properties of undefined (reading '__H')
        at l (index.js:148:19)
        at I (index.js:181:20)
        at B (index.js:168:9)
        at (index):21:29
    ```

**Expected behavior**
No error, since this hooks mentioned in https://preactjs.com/guide/v10/no-build-workflows/#preact-with-hooks-signals-and-htm
No-Build Workflows -> Recipes and Common Patterns -> Preact with Hooks, Signals, and HTM

**Comment by JoviDeCroock** [comment]
Context here https://github.com/preactjs/preact/issues/2564#issuecomment-636316811

**Comment by JoviDeCroock** [comment]
Oh.... You aren't using the hook in a component... That can't work 😅
