### ISSUE TITLE
Module `"preact/compat"` has no exported member `ElementRef`

### ISSUE THREAD

**Issue by PratikDev** [preactjs/preact#4481]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
The `ElementRef` type is not available yet

**To Reproduce**
Check [this](https://stackblitz.com/edit/create-preact-starter-bt5jpo?file=src%2Findex.jsx) Stackblitz demo where i'm importing the `ElementRef` from `preact`. In the same line `render` is also imported. If you hover over `render` you'll see the type definition of it. But that's not the case for `ElementRef`. It doesn't show any type definition (idk why Stackblitz isn't showing any error there. but vscode does)

1. Run `npm init preact elementRefDemo`
2. Check `Typescript` when asked
3. Try importing `ElementRef` in `src/index.ts` from `preact` or `preact/compact`

**Expected behavior**
`ElementRef` should be available in `preact` or `preact/compact`

**Comment by PratikDev** [comment]
I'm mainly integrating [shadcn](https://ui.shadcn.com/) and finding ts issues in the shadcn provided components. i'll try to keep adding all the issues i find in this comment

`KeyboardEvent` is also not available.

**Comment by rschristian** [comment]
I'm fairly certain `KeyboardEvent` is part of TS's DOM typings, it's not something we'd supply? You might have misconfiguration your `tsconfig.json` if it's not available.

**Comment by PratikDev** [comment]
Isn't it like we'll re-export most of the unavailable types from react?

**Comment by rschristian** [comment]
We don't re-export anything from React, no. We do not rely on React's types for our own.

It just makes little sense to me at this moment why React provides a `KeyboardEvent` type, it seemingly matches the standard DOM type. [See](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABACwIZgCYBsCmAnAChwDccwoAuRAaRwE8AjOVPDAUVPIEpEBvAKERDEJMlAB0Aa3r8AvkA)

**Comment by PratikDev** [comment]
maybe i'm too noob in TS world. but when u say re-export, do u mean to re-export from TS directly?

**Comment by rschristian** [comment]
Yes, assuming I'm not missing something, I believe that's all we'd do.

I'm admittedly not a big TS user myself though.

**Comment by PratikDev** [comment]
u said react provides their own `KeyboardEvent`. it's still unclear to me why they had to do it? and even if they do, why can't we just directly use this `KeyboardEvent` without importing from anywhere? so that the one from TS gets used (i tried. it throws error).

**Comment by rschristian** [comment]
> u said react provides their own KeyboardEvent. it's still unclear to me why they had to do it?

No clue, feel free to look through the blame: [source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2255)

> why can't we just directly use this KeyboardEvent without importing from anywhere?

You absolutely can (and should) in user code, if it fits your needs. Won't work for libs though if they expect to pull that type from React.

**Comment by rschristian** [comment]
Do you happen to have an example of a module that relies on the `ElementRef` type? We'd supply it from `preact/compat`, rather than `preact` itself, but I'd like to test that our implementation is correct.

**Comment by PratikDev** [comment]
yes. as mentioned in my first comment, I was trying to use [shadcn](https://ui.shadcn.com/) with `preact`. And many components in shadcn like [Select](https://ui.shadcn.com/docs/components/select) and [Sheet](https://ui.shadcn.com/docs/components/sheet) do use `ElementRef`

**Comment by rschristian** [comment]
Thanks, was just looking for a specific component.

**Comment by rschristian** [comment]
I took a look at this tonight, but looks like it might rely on #4113, which I'm not sure we can address.

Open to PRs, if anyone's got them though.
