### ISSUE TITLE
Performance issue in findMatchingIndex after upgrade to 10.23.2

### ISSUE THREAD

**Issue by grizopul-tibco** [preactjs/preact#4482]
This is only an issue in 10.23.2, downgrading to 10.23.1 makes the issue disappear.

**Describe the bug**
Under some circumstances, involving (many)keyed children, skewedIndex becomes really large, causing the loop in findMatchingIndex to take a lot of time. 

**To Reproduce**

1. Go to https://stackblitz.com/edit/freezing-preact
2. Click on any item in the list and drag up and down towards the top
3. The ui freezes and takes a lot of time to update

**Expected behavior**
When downgrading to 10.23.2, the ui is responsive no matter how you drag the item.

**Comment by JoviDeCroock** [comment]
I'm assuming that the shifting forward change is not completely accurate 😅 we might need to perform a [tweak here](https://github.com/preactjs/preact/pull/4472/files#diff-0880f02a2230660b9b02c49e965966e94d52e06b66026ef716ca33dc31123722R320) I probably won't have time for this in the coming weeks

**Comment by FishOrBear** [comment]
@JoviDeCroock Why don't you hurry up and release it, I'm already having an endless loop in the test environment

**Comment by JoviDeCroock** [comment]
@FishOrBear excuse me? I am doing this in my spare time already... this is not my job, hope you realise that this kind of attitude is the whole issue with oss lately

**Comment by FishOrBear** [comment]
@JoviDeCroock I'm sorry, but I don't mean to press,I'm not a native English speaker, so the content of the translation may be a bit straightforward

**Comment by marvinhagemeister** [comment]
@FishOrBear The problem is not being straightforward, the problem is that your past message comes off as being pretty entitled and disrespectful. On top of that the endless loop is very likely a problem with your code, not a bug in Preact. This makes your previous comment even more out of line.
