### ISSUE TITLE
When hydrating, an `insertBefore` DOM manipulation can happen

### ISSUE THREAD

**Issue by ccouzens** [preactjs/preact#4498]
- [ ] Check if updating to the latest Preact version resolves the issue

- reproduced on a branch up to date with main

**Describe the bug**

When hydrating, empty strings cause calls to update the DOM. Either `insertBefore` or `appendChild` depending on the location of the empty string.

**To Reproduce**

Test cases:

bd21b804c806098a914b711a0aa7972f70bb25cd

```tsx
	it('should skip empty strings before elements', () => {
		scratch.innerHTML = '<p><span></span></p>';
		hydrate(
			<p>
				{''}
				<span></span>
			</p>,
			scratch
		);
		expect(scratch.innerHTML).to.equal('<p><span></span></p>');
		expect(getLog()).to.deep.equal([]);
	});

	it('should skip empty strings after elements', () => {
		scratch.innerHTML = '<p><span></span></p>';
		hydrate(
			<p>
				<span></span>
				{''}
			</p>,
			scratch
		);
		expect(scratch.innerHTML).to.equal('<p><span></span></p>');
		expect(getLog()).to.deep.equal([]);
	});
```

[CI run](https://github.com/ccouzens/preact/actions/runs/10871546798/job/30165506372):

```
FAILED TESTS:
  hydrate()
    ✖ should skip empty strings before elements
      Chrome Headless 128.0.0.0 (Linux x86_64)
    AssertionError: expected [ '<p>.insertBefore(#text, <span>)' ] to deeply equal []

      + expected - actual

      -[
      -  "<p>.insertBefore(#text, <span>)"
      -]
      +[]
      
    at Context.<anonymous> (test/browser/hydrate.test.js:495:28)



    ✖ should skip empty strings after elements
      Chrome Headless 128.0.0.0 (Linux x86_64)
    AssertionError: expected [ '<p>.appendChild(#text)' ] to deeply equal []

      + expected - actual

      -[
      -  "<p>.appendChild(#text)"
      -]
      +[]
      
    at Context.<anonymous> (test/browser/hydrate.test.js:508:28)
```

**Expected behavior**
What should have happened when following the steps above?

I would expect the behaviour of empty strings to match the behaviour of `null`s. Neither is outputted when rendering HTML to string. Nulls are not inserted into the DOM when hydrating and it is my expectation that neither are empty strings.

**Comment by ccouzens** [comment]
I'm happy to look into this further.

I can see the call to `insertBefore` happening here https://github.com/preactjs/preact/blob/main/src/diff/children.js/#L343

One solution would be to check for the empty string case within the parent `if`. However I suspect it would be better to treat `null` and `""` the same throughout the codebase.

**Comment by JoviDeCroock** [comment]
We have a similar tradeoff for splitting up text nodes, i.e. if you have `<p>hello {name}</p>` we'll split it up into two text nodes. The thing is we could start special casing this stuff, however it starts creating inconsistency between purely client trees and hydrated trees which might pose some risk. If we start consistently ignoring text-nodes without a textual value, I think we could fix this. We'd mainly have to create a new branch in diffElementNodes where when there is no vnode.type and the vnode.props would result in an empty text node we skip.

**Comment by ccouzens** [comment]
> I think it's also good because adding that text-node sets us up for faster mutations in the future.

OK. In this instance it's very easy for me to do `|| null` in my application code in instances where I'm not expecting the string to be replaced by a non-empty string.

I'll treat it as an application bug on my end rather than a preact bug.

Thanks,
Chris
