### ISSUE TITLE
useStateRef hook request

### ISSUE THREAD

**Issue by pejman-hkh** [preactjs/preact#4504]
**Describe the feature you'd love to see**

In my opinion, we can add a hook to PReact called useStateRef, where the diffing operation only happens inside the ref, and we skip the diffing process for the rest of the components.

In the following example, during setState and render, the diffing operation only occurs on the div where the ref is set, and the rest of the components are ignored:
```jsx
const [state,setState, ref] = useStateRef();

const handler = () => {
	setState(state+1)	
}

return <Layout>
	<div ref={ref}>
		{state}
	</div>
	<button onClick={handler}></button>
</Layout>
```

I’m not sure if this is feasible or not, but it seems like a good idea.

**Comment by JoviDeCroock** [comment]
This is already how Preact signals work, a primitive like this doesn't feel like a great hook case to me, it's better implemented in user-land with a signal/observable pattern.

**Comment by pejman-hkh** [comment]
Thank you for your response.
Could you explain how I can implement signals in Preact at the user level?

**Comment by JoviDeCroock** [comment]
Signals you don't need to implement as we did already, see link of previous message. The thing I mean is that you can implement your hook in a similar way; where you update the text node directly in reaction to the event.

**Comment by pejman-hkh** [comment]
I don't know how to implement it with signals.
If you could provide an example, that would be helpful.
I currently don't have enough time to explore and implement it, but maybe I can work on it later.

**Comment by JoviDeCroock** [comment]
Again; with signals this is done for you, just use signals 😅 you can read the blog post https://preactjs.com/blog/introducing-signals/ so installing preact/signals and leveraging useSignal/... for that state

**Comment by pejman-hkh** [comment]
This is amazing.
Thank you!

**Comment by rschristian** [comment]
Just to add: our REPL has a few signals examples that you can play around with, such as [`counter-signals`](https://preactjs.com/repl?example=counter-signals) & [`todo-signals`](https://preactjs.com/repl?example=todo-signals). Insert a `console.log('rerendering');` into the component and see how your UI can update without component rerenders.
