### ISSUE TITLE
Types for synthetic events using compat?

### ISSUE THREAD

**Issue by jose-torres-marin** [preactjs/preact#4510]
Aliasing react and react-dom to preact/compat and then doing:
`import { MouseEvent } from 'react'`

Typescript complains:
`Namespace 'React' has no exported member 'MouseEvent'.ts(2694)`

I can see MouseEvent doesn't exist in [the index file](https://github.com/preactjs/preact/blob/3fe5d6b00fa6a7d0a1af83f2ea8822a7f82cdd6c/compat/src/index.d.ts#L635).

Could anyone clarify the proper way to type a mouse event using preact/compat?

**Comment by jose-torres-marin** [comment]
Using `import { JSX } from "preact"` and then `JSX.TargetedMouseEvent`

**Comment by rschristian** [comment]
I think we can & should re-export these from compat so that this works. As such, going to reopen.
