### ISSUE TITLE
Zustand v5 compatibility and the React's useSyncExternalStore

### ISSUE THREAD

**Issue by meglio** [preactjs/preact#4537]
I asked zustand if they are compatibly with preact:

https://github.com/pmndrs/zustand/discussions/2758

The answer is:

> Zustand v5 uses `useSyncExternalStore` from 'react', so it depends on Preact's compatibility with React's uSES.

So my question is, could you please clarity regarding the preact compatibility with the React's `useSyncExternalStore`.

**Comment by rschristian** [comment]
We provide a uSES impl from compat: https://github.com/preactjs/preact/blob/4181cba60c339245175df8e2609567a0f501da42/compat/src/index.js#L170

You could try running Zustand's test suite w/ Preact aliased in if you wanted to, but if it's just a question of whether we support uSES, then yes.

**Comment by meglio** [comment]
Is it a possibility that you create a pure preact version of the library?

**Comment by rschristian** [comment]
I don't think we'd maintain that as a first-party thing, no. Certainly feel free to write it yourself if you feel it's useful.

Is there any part that doesn't work with `preact/compat`?

**Comment by meglio** [comment]
> Is there any part that doesn't work with preact/compat?

We don't use `preact/compat` in our project because it blows its size -- while we switched from react to preact specificly to reduce the dependency size and speed things up. IMO using `preact/compat` discards most of the reasons to switch from react to preact in the first place.

**Comment by rschristian** [comment]
Sorry, but I think you're mistaken -- Preact with compat is ≈10kb w/ gzip, React is 58kb... that's a 48kb difference yet.

If you're seeing different numbers then you've misconfigured something.

**Comment by meglio** [comment]
> Preact with compat is ≈10kb w/ gzip, React is 58kb... that's a 48kb difference yet.

Thanks I'll explore further.

**Comment by rschristian** [comment]
For your reference:

`preact` + `preact/hooks` + `preact/compat`: [9.35kb](https://bundlejs.com/?q=preact%2Cpreact%2Fhooks%2Cpreact%2Fcompat&treeshake=%5B*%5D%2C%5B*%5D%2C%5B*%5D)
`react` + `react-dom/client`: [58.1kb](https://bundlejs.com/?q=react%2Creact-dom%2Fclient&treeshake=%5B*%5D%2C%5B*%5D)

**Comment by windmaomao273** [comment]
just curious why need `zustand` if we have `signal`. I'm new to `preact`, but seems `signal` is created for that purpose.

**Comment by meglio** [comment]
Yes I've been experimenting with signals, good so far, the only thing is, by looking at the source code, it seemed overengineered.
