### ISSUE TITLE
`useContext` throws an exception if used inside of `useEffect`

### ISSUE THREAD

**Issue by al6x** [preactjs/preact#4540]
**Describe the bug**

When `useContext` used inside of `useEffect` exception thrown `TypeError: Cannot read properties of null (reading 'context')`

**To Reproduce**

[playground](https://preactjs.com/repl?code=aW1wb3J0IHsgcmVuZGVyLCBjcmVhdGVDb250ZXh0IH0gZnJvbSAncHJlYWN0JwppbXBvcnQgeyB1c2VFZmZlY3QsIHVzZUNvbnRleHQgfSBmcm9tICdwcmVhY3QvaG9va3MnCgpleHBvcnQgY29uc3QgQ3R4ID0gY3JlYXRlQ29udGV4dCh7IG5hbWU6ICdBbGV4JyB9KQoKZXhwb3J0IGZ1bmN0aW9uIEhpKCl7CiAgdXNlRWZmZWN0KCgpID0%2BIHsKICAgIGNvbnNvbGUubG9nKHVzZUNvbnRleHQoQ3R4KS5uYW1lKSAvLyBFcnJvciAKICB9LCBbXSkKCiAgcmV0dXJuIDxkaXY%2BSGkge3VzZUNvbnRleHQoQ3R4KS5uYW1lfTwvZGl2Pgp9CgpyZW5kZXIoPEhpLz4sIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhcHAnKSkK)

```
import { render, createContext } from 'preact'
import { useEffect, useContext } from 'preact/hooks'

export const Ctx = createContext({ name: 'Alex' })

export function Hi(){
  useEffect(() => {
    console.log(useContext(Ctx).name) // Error 
  }, [])

  return <div>Hi {useContext(Ctx).name}</div>
}

render(<Hi/>, document.getElementById('app'))

```

**Expected behavior**

It should work.

**Comment by JoviDeCroock** [comment]
This has always been the case, you can only call hooks in the function body, not inside other hooks.
