### ISSUE TITLE
HMR Not Working in Next.js with Preact

### ISSUE THREAD

**Issue by itMovieKing** [preactjs/preact#4542]
Description: I’m experiencing an issue where hot reloading is not functioning as expected when using Next.js and Preact in my project. After making changes to my components, the browser does not update automatically. This issue forces me to refresh manually to see any updates.

Environment:

Next.js version: ^12.3.4
Preact version: ^10.19.5

Steps to Reproduce:

Initialize a Next.js project with the specified package versions.
Configure the project to replace React with Preact.
Make a small change in any component file (e.g., modify text or styles).
Observe that the changes are not reflected automatically in the browser.
Expected Behavior: After making a change, the component should update in the browser without requiring a manual refresh.

Actual Behavior: Changes do not appear until the page is manually refreshed.

Additional Details:

I can see the hot update request in the Network tab of DevTools, and the request includes the correct updated content. However, the changes are still not applied in the browser until a manual refresh is triggered.

Attempted Solutions:

Restarted the development server to see if the issue persists.
Cleared the .next cache folder and re-ran the development server.
Additional Context: This issue only occurs when Preact is used as a React substitute. With standard React, hot reloading works as expected.

Questions:

Is there any known workaround to restore hot reloading functionality with this setup?
Are there specific configurations or dependencies required to enable hot reloading for Next.js with Preact?

github: https://github.com/itMovieKing/test_hmr

**Comment by JoviDeCroock** [comment]
This is expected, we removed support for Next.JS after they started diverging more and more. There's a lot of internals that are React only and we've reached out about these but never received replies.

**Comment by itMovieKing** [comment]
> This is expected, we removed support for Next.JS after they started diverging more and more. There's a lot of internals that are React only and we've reached out about these but never received replies.
> 
> You can always try and see if https://github.com/preactjs/next-plugin-preact/tree/master/packages/next-plugin-preact still works for you but there's no real official support left. I also realise that the package does not reflect that anymore 😅

Here’s an updated reply acknowledging that `next-plugin-preact` resolved your issue:

---

Thank you for the clarification and for suggesting `next-plugin-preact`! After trying it, I can confirm that it resolved the hot reloading issue in my setup. I appreciate the recommendation!

As a follow-up, I’d like to know:
1. Do you anticipate any future efforts to support Next.js compatibility directly, or do you foresee this as a long-term separation due to the architectural changes?
2. Are there other recommended tools or frameworks you’d suggest for projects with similar requirements to Next.js if full Preact compatibility isn’t feasible in the future?

Thanks again for your insights and the guidance!

**Comment by JoviDeCroock** [comment]
> Do you anticipate any future efforts to support Next.js compatibility directly, or do you foresee this as a long-term separation due to the architectural changes?

I do not think the Next team is interested in it nor can we keep spending effort in supporting it.

> Are there other recommended tools or frameworks you’d suggest for projects with similar requirements to Next.js if full Preact compatibility isn’t feasible in the future?

I've always suggested using `vite`/`vike`, you can also check out `create-preact` https://github.com/preactjs/create-preact.

Vite works well out of the box, vike can be used for SSR and for SSG you can look at create-preact which has great prerender support.
