### ISSUE TITLE
Fragment induced memory leak if not keyed and state change triggered by context

### ISSUE THREAD

**Issue by glenveegee** [preactjs/preact#4558]
- [ X ] Check if updating to the latest Preact version resolves the issue
 It does not resolve the issue

**Describe the bug**
When a parent component undergoes state transitions due to context changes, and it returns a fragment which bounds two or more child components that are themselves modified by changes in different parts of the context (so keying the fragment makes no sense), memory will leak and the heap will ultimately fill up and throw an error

**To Reproduce**

Instructions on how to reproduce and a demonstration of the memory leak are available in the following repo: https://github.com/glenveegee/preact_fragment_memleak

Steps to reproduce the behaviour:

- Install the node dependencies after downloading the repo
- Starts the dev server (hosted at http://localhost:5173/)
- Open the developer console to use the memory profiling tools
- Profile memory to obtain a non-leaky memory profile 
- Visit http://localhost:5173/leaky and perform the memory profiling again
- Compare and contrast memory profiles

**Expected behavior**

- Manual garbage collection should return heap memory to "normal" levels.
- Profiling heap memory without manual garbage collection should show automatic, periodic garbage collection back to "normal" levels

**Comment by JoviDeCroock** [comment]
@glenveegee this is probably only present in development and is an issue with prefresh https://github.com/preactjs/prefresh/issues/558 - you can try to disable prefresh in vite to reproduce that

**Comment by glenveegee** [comment]
Thanks @JoviDeCroock. Running with vite HMR disabled had no effect, but running with `NODE_ENV='production'` seems to confirm that this memory leak is specific to the dev environment

**Comment by JoviDeCroock** [comment]
https://github.com/preactjs/prefresh/issues/558 should have you covered as well

**Comment by rschristian** [comment]
> Running with vite HMR disabled had no effect

How'd you disable HMR? Like this?

```js
// vite.config.js
export default defineConfig({
  plugins: [preact({ prefreshEnabled: false )]
});
```

If so, and you still saw issues, we may have a problem elsewhere yet?

**Comment by glenveegee** [comment]
Yes that's what I did to disable it

**Comment by glenveegee** [comment]
@rschristian `prefreshEnabled: false` in the Preact config worked although I confess this is the first time I've encountered that option. Search on the Preact docs site and google returned irrelevant results so perhaps some indexed docs on the option would help with visibility in search engines.

![Screenshot 2024-11-19 at 09 26 15](https://github.com/user-attachments/assets/d47c512f-96d5-4226-9348-0e59144451db)

**Comment by rschristian** [comment]
We don't document `@preact/preset-vite` at all on the docs site, you can find all its info in [its readme](https://github.com/preactjs/preset-vite) though.

**Comment by glenveegee** [comment]
That explains it. Thanks @rschristian

**Comment by rschristian** [comment]
And thanks for confirming that works, Jovi's fix to prefresh should be all that's needed then.
