### ISSUE TITLE
BUG: REACT HOOK FORM preact MAX INPUT

### ISSUE THREAD

**Issue by VigilioYonatan** [preactjs/preact#4565]
// error register react hook form have the type register max like number and preact input have a string. 
```tsx
import { useForm } from "react-hook-form";

export function App() {
    const { register } = useForm<{ name: string }>();
    return (
        <>
            <input type="text" {...register("name")} max="" /> // error 
        </>
    );
}

```

**Comment by JoviDeCroock** [comment]
Hey,

We have an issue template, I don't really fully understand what you are expecting to happen or what I have to do reproduce it. Could you please follow the template.
