### ISSUE TITLE
BUG: REACT HOOK FORM register type max input is a number ERROR

### ISSUE THREAD

**Issue by VigilioYonatan** [preactjs/preact#4566]
- [x ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
React hook form method register have a type max input like number and input preact is Signalish<string | undefined> .
```tsx
import { useForm } from "react-hook-form";

export function App() {
    const { register } = useForm<{ name: string }>();
    return (
        <>
            <input type="text" {...register("name")} />
        </>
    );
}

```

**To Reproduce**
https://codesandbox.io/p/sandbox/error-input-react-hook-form-y8rprh

1. example but no show error, but in vite js it happen
2. npm init vite@latest app
3. choose preact typescript and install dependencies.
4. install react hook form  

SOLUTION
**Expected behavior**
the solution is that  min and max add number 
		min?: Signalish<string | undefined|number>;
	MAX?: Signalish<string | undefined|number>;

**Comment by rschristian** [comment]
I don't think your sandbox is public, mind making it so?

**Comment by VigilioYonatan** [comment]
> ~I don't think your sandbox is public, mind making it so?~
> 
> Edit: Nevermind, no need.

yes, it no neccesary,  solution is add number in min and max type in input or react      hook form add string min and max. React hook form is the library most used in react.

**Comment by rschristian** [comment]
Maintainers would generally prefer you leave that determination _up to them_. The number of times we've been told a reproduction isn't necessary when it very much was... 😄
