### ISSUE TITLE
TS error for h() function overload match when element properties do not include global attribute

### ISSUE THREAD

**Issue by nbalatsk-oracle** [preactjs/preact#4577]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
The issue is related to type updates in [PR 4546](https://github.com/preactjs/preact/pull/4546). It is not reproducible with Preact 10.24.3.

The h() function definitions still use HTMLAttribute instead of AllHTMLAttributes. Since the HTMLAttribute interface is now limited to global attributes/properties, the h() function overload match fails when given properties do not contain global attributes.

![Screenshot 2024-11-27 at 3 08 18 PM](https://github.com/user-attachments/assets/6cb23644-f6d1-4fb1-83ef-9dd73ff11d9d)

**To Reproduce**
You can use this [example in Typescript playground](https://www.typescriptlang.org/play/?ts=5.4.5#code/JYWwDg9gTgLgBAbzgCzgXzgMyhEcBEYUApgIYDGM+A3AFC3kQB2AzvDMWwMrEA2xlOAF44ACgCUwgHyJacOI1bwIYGCwCCUKKQCewuAG058xHABupXgFdiALgIXrxAIz4ANHF6kARn3v4ANUsbV3Q3Y3kkRxt-aOIAJndPHz8CIKdEsOMAXTp5RTY4FRhgZhZ9Yo0tXQA6EFIwUVFi0qZJIRkECLgSGCsoJhRRbvl8FuZ3EdM4+3GmGriskxM5mq9fXm7xPPRt4wL4IhVykS7lplIQOwIQHQA5S+J8YzQd3v7B5FF8Fj4BKg8RzALA8cxYe1etGIAA9ILBTBxuH9BJDaEA) to see the issue.

1. Use the following code in Typescript playground 
```const testSelect = () => {
  const optsArray = [
    { value: "value1", label: "Value1" },
    { value: "value2", label: "Value2" },
  ];
  const options = optsArray.map((option) => {
    return h(
      "option",
      { value: option.value },
      option.label
    );
  });
  const props = {
    name: "myName"
  };
  return h("select", props, options);
};
export { testSelect };
```
2. See errors for 'option' and 'select':
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'ComponentType<{ value: string; }>'.(2769)
index.d.ts(278, 17): The last overload is declared here.
```

**Expected behavior**
The correct overload for HTMLElement should be found.

**Comment by JoviDeCroock** [comment]
I reckon it's this extends here https://github.com/preactjs/preact/blob/main/src/index.d.ts#L249 😅

**Comment by rschristian** [comment]
I don't believe React's types pull anything like `AllHTMLAttributes`? IIUC, it should be resolving to that `keyof InstrinsicElements` overload and pulling the correct element types from that.

I only spent a few minutes earlier but we do appear to diverge from their `createElement` types a bit, I'd hazard a guess something isn't right in ours.
