### ISSUE TITLE
types: `EventHandler` returning (seemingly) incorrect type

### ISSUE THREAD

**Issue by rschristian** [preactjs/preact#4581]
- [X] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Found this trying to help [Hypothesis upgrade their frontend-shared repo](https://github.com/hypothesis/frontend-shared/pull/1803).

#4538 seems to be the cause of a regression in the following type, resulting in the following error:

```
Property 'call' does not exist on type 'GenericEventHandler<HTMLInputElement>'.
  Property 'call' does not exist on type 'EventHandlerObject<TargetedEvent<HTMLInputElement, Event>>'.
```

Not really sure what that type change is even doing, need more time to investigate but wanted to get this opened.

**To Reproduce**

[TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCwDRwFIGUAacC+cAZlBCHAERhQCmAhgMYwUDcAUG0QK4B2TwEHnADCyGgwDWAIwgAPABRJBoujwDmNAgC5MuAHQBJHmC4wAEgBUAsgBkAgjBhRgU0zQDOAHku2jJmACiADY0IDQ8MAB8AJSIHHDEvPyCKKoAJiEq6jTysQhsCQnKyKoaAPx6DHRBQbnsCfjxcLQwXFBCnsDGpnDFpTQAvAglPBk0WRqEAPSRbI1sQA)

```ts
import { JSX } from "preact";

function Checkbox({ onChange }: JSX.HTMLAttributes<HTMLInputElement>) {

  function handleChange(this: void, event: JSX.TargetedEvent<HTMLInputElement>) {
    onChange?.call(this, event);
           // ^ Error here
  }

  return <input onChange={handleChange} />
}
```

**Expected behavior**

Shouldn't be any error

**Comment by JoviDeCroock** [comment]
Hmm, the whole bivariancehack situation is concerning already. I wonder whether we can get away with a similar fix to https://github.com/preactjs/preact/pull/4547

**Comment by lilnasy** [comment]
I think the error really is expected. Starting with the latest version, Checkbox can be passed something other than a function.

For example, with this usage:
```tsx
class Form {
    handleEvent(event: Event) {
        ....
    }
    
    render() {
        return <Checkbox onChange={this}/>
    }
}
```

The userland fix would be something like this:
```tsx
import type { JSX } from "preact";

function Checkbox({ onChange }: JSX.HTMLAttributes<HTMLInputElement>) {
    function handleChange(this: void, event: JSX.TargetedEvent<HTMLInputElement>) {
        // onChange?.call(this, event);
        onChange && "handleEvent" in onChange
            ? onChange.handleEvent(event)
            : onChange.call(this, event)
    }
    return <input onChange={handleChange} />
}
```

Although, I expect this to be a widely used pattern, so maybe there should be something to make migration easier. That could be a helper type so that Checkbox can say, "I am actually different from an input element because I accept a narrower type for event handlers":

```tsx
import type { JSX } from "preact";

type FunctionOnly<Element extends EventTarget> = {
    [Key in keyof JSX.HTMLAttributes<Element>]:
        Exclude<JSX.HTMLAttributes<Element>[Key], JSX.EventHandlerObject<JSX.TargetedEvent>>
}

function Checkbox({ onChange }: FunctionOnly<HTMLInputElement>) {
    function handleChange(this: void, event: JSX.TargetedEvent<HTMLInputElement>) {
        onChange?.call(this, event);
    }
    return <input onChange={handleChange} />
}
```
