### ISSUE TITLE
Latest preact version breaks @radix-ui/react-switch and application

### ISSUE THREAD

**Issue by ndt080** [preactjs/preact#4590]
preact@^10.25.0 (it has also been checked on 10.25.1)

**Describe the bug**
When trying to create a component, the page freezes. There is no memory leak in devtools, but the rendering process does not continue

Everything works fine on version 10.24.3

**Comment by JoviDeCroock** [comment]
Hey,

Mind adding a reproduction as the issue template demands?

**Comment by ndt080** [comment]
@JoviDeCroock Hi, I tried to reproduce the problem in StackBlitz with pure Switch usage and I failed. I have a really large and complex application. After updating to 10.25.0/10.25.1, my application began to freeze at the time of rendering the UI. Experimentally, commenting on the components, I found that the hang causes @radix-ui/switch.  Asynchronous operations, memoization, fragments, or suspense may be affected. I need a little more time to reproduce the problem in a clean environment.

**Comment by JoviDeCroock** [comment]
@ndt080 you can also try running a `git bisect` yourself to see which change broke it.

**Comment by ndt080** [comment]
As it turned out, the problem was not with @radix-ui/*. I wrapped all dynamic component inserts in Suspense and the problem was resolved.

```
function SomeComponent({ ButtonComponent }) {
return <div><Suspense fallback={null}><ButtonComponent /></Suspense ></div>
}
```

I think, this issue can be closed
