### ISSUE TITLE
`onToggle` types do not use `ToggleEvent`

### ISSUE THREAD

**Issue by lucacasonato** [preactjs/preact#4614]
The types for `onToggle`, for example in `<div popover onToggle={fn} />`, are typed as `JSX.GenericEventHandler<HTMLDivElement> | undefined` rather than `JSX.ToggleEventHandler<HTMLDivElement> | undefined`. This is important, because `ToggleEvent` has a `newState` and `oldState` field that `Event` does not.

**Comment by rschristian** [comment]
Unfortunately `ToggleEvent` is newer than our minimum supported TS version, not sure we can land this in the near future.

**Comment by JoviDeCroock** [comment]
Released in 10.25.4

**Comment by lucacasonato** [comment]
Thanks!
