### ISSUE TITLE
Preact failed to render webcomponent (Failed to execute 'createElementNS')

### ISSUE THREAD

**Issue by Akiyamka** [preactjs/preact#4622]
- [x] Check if updating to the latest Preact version resolves the issue
preact@10.25.3

**Describe the bug**
Attempt to use `@honatas/multi-select-webcomponent` package broke preact render 

**To Reproduce**
```jsx
import MultiselectWebcomponent from '@honatas/multi-select-webcomponent';

window.customElements.define('multi-select', MultiselectWebcomponent);

export function MultiSelectInput<T>({
  options,
}) {
  return (
    <multi-select
      id="planetIds"
      class="border"
      selecteditem="badge bg-primary pt-1 m-1"
      dropdown="border"
      dropdownitem="p-1"
      selectallbutton="btn btn-sm btn-light"
      selectallbuttonspan="bi-check2-all text-success"
      clearbutton="btn btn-sm btn-light"
      clearbuttonspan="bi-x-circle text-danger"
    >
      {options.value.map((option) => (
        <option value={option.value}>{option.label}</option>
      ))}
    </multi-select>
  );
}

```
Error:
```js
Uncaught NotSupportedError: Failed to execute 'createElementNS' on 'Document': The result must not have attributes
```
Error point to next line in preact source code
https://github.com/preactjs/preact/blob/main/src/diff/index.js#L436

**Expected behavior**
Preact able to render custom tags

**Comment by JoviDeCroock** [comment]
I think this bug has been introduced in https://github.com/preactjs/preact/pull/4364 we should call the non namespace equivalent here.

**Comment by rschristian** [comment]
Quick search seems to hint this is an issue with the lib, rather than us: https://github.com/Honatas/multi-select-webcomponent/issues/1

**Comment by Akiyamka** [comment]
@rschristian thank you for investigation, you right, it's not preact issue
