### ISSUE TITLE
Rendering and Events Order Mixed Up

### ISSUE THREAD

**Issue by whamtet** [preactjs/preact#470]
I've created a [Codepen](http://codepen.io/whamtet/pen/bBZjBq?editors=0010) to demonstrate an annoying bug,

To reproduce create a link on each line and replace the links with radio buttons after clicking.  The original onclick event that triggers the change incorrectly triggers a second onclick on the radio button.  To be correct the first onclick should finish before the radio buttons are rendered.

Suggestions?  I can submit a pull request if you can hint where it might be going wrong.

**Comment by mkautzmann** [comment]
You can fix the behavior by preventing the click event from bubbling.

Try changing your `advanceState` function to be like this:

```javascript
advanceState(e) {
  e.stopPropagation();
  this.setState({step: 2, radio: 1});
}
```

**Comment by whamtet** [comment]
Thanks

**Comment by developit** [comment]
Interesting. It seems like this is also caused by preact using capturing phase for click events.

**Comment by developit** [comment]
Update: I think this issue is now tracking a potential switch back to bubbling for all events, rather than selectively using capturing phase for whitelisted event types.

**Comment by MrGuiMan** [comment]
Hi @developit , just encountered this issue as well, are there been any any development since January ? Thanks !

**Comment by developit** [comment]
Still pondering my original reply about going back to bubbling-for-everything.  It would be nice for filesize and fix this issue, though it would make certain uses of event delegation fail (like delegated `onfocus`).

**Comment by marvinhagemeister** [comment]
We removed any special handling of events that may have been in Preact a long time ago. Today we're simply reusing the DOM's event system and from the looks of it this issue is no longer present with that :tada:
