### ISSUE TITLE
Documentation request for beginners

### ISSUE THREAD

**Issue by amitguptagwl** [preactjs/preact#483]
No doubt preact and surprisingly small. But I'm not able to follow the documentation much given on main site. It looks like the people who have already worked with reactjs and looking for small library can easily switch to preact. I couldn't even find much tutorials on google. 

So what would be right way for the beginner who doesn't have basic knowledge of setting up babel, webpack etc.? Do we have documentation/API library? Do I need to learn reactjs first?

I started with a codepen example. But it looks like that the example given on [type of component](https://preactjs.com/guide/types-of-components) are also broken. When I click on "Run in REPL", nothing is displayed. I'm checking in chrome browser on Ubuntu machine.

**Comment by developit** [comment]
Hi there @amitguptagwl! You're right, the documentation for people who haven't worked with Virtual DOM Components previously is a little lacking.  We have the [Getting Started](https://preactjs.com/guide/getting-started) guide, but it intentionally skips over any sort of Babel/Webpack setup.  This is done because Preact doesn't require any of that, rather it's just commonplace these days.  However, it'd be nice to have a "zero to sixty" type tutorial, taking you from a `<script>` tag all the way to a small app.

The codepen examples probably the best place to start right now since that allows you to code productively without getting tangled up in tooling and setup.  As for the Run In REPL issue you noted - those examples don't really do much that you could see visually - they render `<a></a>`, which is invisible and has no attributes 🐙

**Comment by robertknight** [comment]
>  However, it'd be nice to have a "zero to sixty" type tutorial, taking you from a <script> tag all the way to a small app.

👍 for a starting-from-zero example with minimal tooling. I worked through the [Vue.js Getting Started guide](https://vuejs.org/v2/guide/) a couple of weeks ago and the documentation is really, really good. The lack of tooling required especially stands it in stark contrast to eg. Angular 2.

> Do I need to learn reactjs first?

I think the answer to this is basically yes, but only the fundamentals. You don't need to learn every nook and cranny of React, but working through their [Getting Started guide](https://facebook.github.io/react/docs/hello-world.html) to understand the rationale and the basic principles is I think a prerequisite before you can make use of Preact.

**Comment by amitguptagwl** [comment]
I also created some tutorial for my tool [stubmatic](https://github.com/NaturalIntelligence/Stubmatic). And most of the people (at least in my direct contact) are satisfied with that. I would be more than happy to create documentation for preact as well. But I need to learn it first.

**Comment by amitguptagwl** [comment]
@developit As per my understanding with Link example, props hold properties passed to the component or  attributes passed to element. And this example should work

HTML
`<span id="tg" text="preact">amit</span>`

JS

```
class BigLetters extends Component {
	render(props) {
		return <h1>{ props.text.toUpperCase() }</h1>;
	}
}

render(<BigLetters />, document.getElementById('tg'));
```

But here props has only an empty array with name children.

**Comment by developit** [comment]
@amitguptagwl - ah, so attributes are actually never read from the DOM - only written.  In Preact (and any other React-like library), `props` are only properties passed to a Component. If you render a DOM component (any JSX tag with a lowercase name), you're passing `props` into the DOM as `attributes` - a one-way operation only.

So, here's how you'd pass `text` to your BigLetters component using Preact:

First, your HTML is just a root into which elements will get rendered. It doesn't hold any state.

HTML:

```html
<span id="tg"></span>
```

JS:

```js
class BigLetters extends Component {
	render(props) {
		return <h1>{ props.text.toUpperCase() }</h1>;
	}
}

render(<BigLetters text="preact">amit</BigLetters>, document.getElementById('tg'));
                   // ▲ we move our props and children here
```

**Comment by amitguptagwl** [comment]
Thanks @developit , Let me try that. I'm actually trying to convert a [custom element](http://plnkr.co/edit/90caBkgtenglziQje0Hj?p=preview) in preact that I initially created in riotjs. But due to some issue of rendering I decided to explore other react frameworks.

**Comment by developit** [comment]
Ah yes, that's definitely more geared towards preact-custom-element. If you're working in an environment where HTML is the source of application structure/composition, you'll want that library in order to blend Preact's JSX/VDOM world with that of the DOM :)

**Comment by amitguptagwl** [comment]
After 20 mins of try I found that `registerCustomElement(Icons, "ta");` doesn't work. But `registerCustomElement(Icons, "t-a");` works.

**Comment by developit** [comment]
ahh, yes. That's actually enforced by the [Custom Elements specification](http://w3c.github.io/webcomponents/spec/custom/#prod-potentialcustomelementname). I've submitted a PR to preact-custom-element to make a note of that in the readme.

**Comment by marvinhagemeister** [comment]
We've added a [Getting Started](https://preactjs.com/guide/v10/getting-started) guide and a [Tutorial](https://preactjs.com/guide/v10/tutorial) page on our new site :tada:
