### ISSUE TITLE
Callback of `setState` is called at not expected time.

### ISSUE THREAD

**Issue by windyGex** [preactjs/preact#556]
See the following code: 

```js
class A extends React.Component {
  componentWillMount() {
    this.setState({
        a: 'a'
    }, () => {
      console.log('setState');
    })
  }
  render() {
    return <B></B>
  }
}

class B extends React.Component{
  render() {
    return <div>B</div>;
  }
  componentDidMount() {
    console.log('didMount');
  }
}


ReactDOM.render(<A/>, mountNode);
```

**Preact** will log:

```
setState
didMount
```

**React** will log:

```
didMount
setState
```

I'm not sure if this is a bug？It will be error when access domNode of child component in callback.

**Comment by developit** [comment]
Preact folds pre-mount `setState()` calls into the initial render by design. I hadn't thought of the callback issue though, that's cumbersome.

**Comment by windyGex** [comment]
What's your opinion？ @robertknight

**Comment by robertknight** [comment]
I can confirm this happens in Preact 10: https://codesandbox.io/s/lp5xyqq4vz

**Comment by edimitchel** [comment]
@developit And now, callback is no more called !
https://codesandbox.io/s/556-nop2h

**Comment by JoviDeCroock** [comment]
Hey @edimitchel, I can confirm that it works in `componentDidMount` and not in `componentWillMount`. I'll try to look into this later, for the time being you could use didMount instead .

**Comment by edimitchel** [comment]
> Hey @edimitchel, I can confirm that it works in `componentDidMount` and not in `componentWillMount`. I'll try to look into this later, for the time being you could use didMount instead.

I used on `componentDidMount` on my personal project and this not working. Actually, you're right, on the demo, it works like expected. But for now, on my project, it doesn't.

**Comment by JoviDeCroock** [comment]
@edimitchel it seems to work here: https://codesandbox.io/s/556-wlfp4

**Comment by edimitchel** [comment]
@JoviDeCroock Yes, I changed the `Will` by `Did`.

**Comment by JoviDeCroock** [comment]
> I execute another setState inside the callback (yes, I know, legacy code..), and the callback of this isn't called

I was talking about this part

**Comment by edimitchel** [comment]
Sorry, I thought it was the same codesandbox url.
Can you see the issue here : https://codesandbox.io/s/556-glj62
The state doesn't change on the second callback.

**Comment by JoviDeCroock** [comment]
Oh, the state doesn't seem to be updated in the callback but it is in the render, will try to look into it soon.

**Comment by edimitchel** [comment]
I have to create an issue for that ? @JoviDeCroock

**Comment by JoviDeCroock** [comment]
It would be nice to have these separate since this one revolves around `componentWillMount` and no callbacks at all.

**Comment by robertknight** [comment]
Given that `componentWillMount` is [deprecated in React](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount), I wonder if it is still worth trying to fix this?

**Comment by planttheidea** [comment]
@robertknight `componentWillMount` has been deprecated, but only the unprefixed versions. `UNSAFE_componentWillMount` [will continue to work going forward](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path).

**Comment by ForsakenHarmony** [comment]
They're saying "Only the new “UNSAFE_” lifecycle names will work from this point forward.", not "The new “UNSAFE_” lifecycle names will work from this point forward."

Which doesn't say they're maintaining it long term

Also "these lifecycles will be more likely to have bugs in future versions of React, especially once async rendering is enabled."

**Comment by planttheidea** [comment]
@ForsakenHarmony I suppose it depends on your definition of long-term. The non-prefixed versions will be deprecated after version 16, however "UNSAFE_" will still work and be maintained throughout version 17. No guarantees for version 18 and beyond, however that is a distant future. Should we dismiss the use-case because one day, years down the line, the API may be gone entirely?
