### ISSUE TITLE
Suggestion: Include Neutrino as a way to get started.

### ISSUE THREAD

**Issue by payerahmed** [preactjs/preact#710]
There's a community supported [neutrino preset](https://www.npmjs.com/package/neutrino-preset-preact) out there for Preact.
This is one of the quickest way to get started with the library. Consider adding it to the documentation.

The basic getting started steps are:
```bash
yarn add --dev neutrino neutrino-preset-preact
yarn add preact preact-compat

mkdir src && touch src/index.js src/App.js
```

App.js  
```jsx
import { Component } from 'preact'

class App extends Component {
  render () {
    return (
      <h1>Hello World!</h1>
    )
  }
}

export default App
```

index.js  
```jsx
import { render } from 'preact'
import App from './App'

let root
function init () {
  root = render(<App />, document.getElementById('root'), root)
}

init()

if (module.hot) module.hot.accept('./App', init)
```
package.json
```json
...
  "scripts": {
    "start": "neutrino start",
    "build": "neutrino build"
  },
  "neutrino": {
    "use": [
      "neutrino-preset-preact"
    ]
  }
```

## npm start
and you're good to go with hot reloading and all.

**Comment by developit** [comment]
That seems like a reasonable alternative for those not using [preact-cli](https://github.com/developit/preact-cli/).  Not sure where it fits in the existing documentation, likely needs to be slotted in somewhere new (which is good, we need to change up the information architecture quite a bit)

**Comment by fa7ad** [comment]
@developit hey, author of the preset here. Let me know if you need some changes to the preset.

I'm thinking of creating a one step tool (a la create-react-app), that uses neutrino to bootstrap the app :smile: 
I think that will massively simplify the process of creating and using a preact app further.

**Comment by eliperelman** [comment]
Hey, just found this thread, author of Neutrino here. We have a scaffolder in the works for Neutrino that will work with all our projects types, and that will include preact as well. This is slated to ship with Neutrino v8.

My suggestion would be to hold off on documenting using Neutrino and preact in this manner until we ship that, which should occur within the next 3 weeks.
