### ISSUE TITLE
Compatibility issue with react-textfit

### ISSUE THREAD

**Issue by plusCubed** [preactjs/preact#763]
I first brought this up in Slack. I'm filing here to keep track. Here are the relevant bits from that:

- Me: The [react-textfit](https://github.com/malte-wessel/react-textfit) library doesn't work with preact/preact-compat, as the text just gets stuck at 100px size. I looked over the code but I don't understand enough about preact to debug this - maybe it's something to do with [timing](https://github.com/malte-wessel/react-textfit/blob/master/src/Textfit.js#L127)?
- Jason: if you resize your browser window, does it update with the right size?
- Me: No, if the window gets too small it changes to 1px, but otherwise stays at 100px
- Jason: weird... yeah that series call you pointed too seems odd. just not sure why it would be preact-specific  
- Jason: Here's a [gist of react-textfit via preact-cli](https://gist.github.com/developit/b1c78c1ebcb4b9d81bbfb9d64b2414ae)
- Jason: By deferring setState callbacks I was able to visualize the issue, but I don't see where things are going wrong in the code
- Jason: its like fontSize isn't taking effect

**Comment by eligao** [comment]
Hi, I've encountered exactly the same problem, is there any workaround?

**Comment by eligao** [comment]
OK I figured out a workaround, just use forceUpdate() instead of callbacks in setState() in react-textfit.
https://github.com/eligao/react-textfit/commit/1a602d29201e193f4710cdd1feda60acd184812b

**Comment by marvinhagemeister** [comment]
Just tried the linked gist in the latest Preact version and the issue is not present anymore :tada:
