### ISSUE TITLE
Flow check cause error

### ISSUE THREAD

**Issue by jakubzaba** [preactjs/preact#770]
I got this error when I check Flow
```
Error: node_modules/preact/dist/preact.js.flow:3
  3: import { createElement as h, cloneElement, Component, render } from 'react';
                                                           ^^^^^^ Named import from module `react`. This module has no named export called `render`.
```
I can ignore it with `<PROJECT_ROOT>/node_modules/preact/.*` in `.flowconfig` or do you have any other suggestions how to fix it?

**Comment by developit** [comment]
Looks like we need to update the definitions.

**Comment by marvinhagemeister** [comment]
We removed support for flow in `master` as the typings were unmaintained and nobody took up the torch to update them. For now contributing definitions to `flow-typed` is much more future proof :+1:
