### ISSUE TITLE
Errors in flow type

### ISSUE THREAD

**Issue by DimitryDushkin** [preactjs/preact#781]
Problem is in https://github.com/developit/preact/blob/master/src/preact.js.flow#L3 
Flow produces error:
```
Error: node_modules/preact/dist/preact.js.flow:3
  3: import { createElement as h, cloneElement, Component, render } from 'react';
                                                           ^^^^^^ Named import from module `react`. This module has no named export called `render`.

Error: node_modules/preact/src/preact.js.flow:3
  3: import { createElement as h, cloneElement, Component, render } from 'react';
                                                           ^^^^^^ Named import from module `react`. This module has no named export called `render`.
```

Which is fair error report, because react do not have `render` export, but `react-dom` does. I think `import { render } from 'react-dom';` will fix it.

**Comment by DimitryDushkin** [comment]
Made PR https://github.com/developit/preact/pull/782

**Comment by marvinhagemeister** [comment]
We removed the flowtype definitions in `master` because they were unmaintained and we don't have any experience with flow in our team. Any definitions for preact should be contributed to `flow-typed` :+1:
