### ISSUE TITLE
Rendering into SSR-generated DOM causes weird behaviour with empty (null) components

### ISSUE THREAD

**Issue by eweilow** [preactjs/preact#811]
I have encountered an issue, specifically first encountered with `react-router`, when I do server-side rendering. For example - the following `<App/>` has different behaviours on initial render into the SSR-generated DOM, depending on the current window.pathname:
```javascript
import { h, Component } from "preact";
import { Route } from "react-router-dom";
import { Home, Test } from "./components"; //Your standard route components

export default class App extends Component {
  render(){
    return (
      <div class="app">
        <Route exact path="/" component={Home}/>
        <Route exact path="/test" component={Test}/>
      </div>
    );
  }
}
```

If the path is `/`, only a text node is appended to `.app` in place of the second `<Route/>`.
If the path is `/test`, the entire tree under the second `<Route/>` is re-rendered and an empty text node is inserted in place of the first `<Route/>`.

### Replication
I've replicated the issue [in a codepen](https://codepen.io/eweilow/pen/gxGOMo). I would expect the behaviour to be what is shown in `5)` and `6)` - no calls to `Element.prototype`.

### My workaround
The workaround I've implemented in my SSR code is the following concept: 
```javascript
function serialize(element) {
  let serializedHTML = "";
  /*
    other code
  */
  if(element.nodeType === 3) {
    const nodeText = escape(element.nodeValue);
    if(nodeText.length === 0) {
      serializedHTML += "<!--SSR-EMPTY-TEXT-->";
    } else {
      serializedHTML += nodeText;
    }
  }
  /*
    handle other nodeTypes
  */
  return serializedString;
}
```

Before rendering the app on the client, I run the following:
```javascript
function applyTextNodeFix(rootNode) {
  if(rootNode.nodeType === 8) {
    if(rootNode.data === "SSR-EMPTY-TEXT") {
      const emptyTextNode = document.createTextNode("");
      emptyTextNode.__preactattr_ = true;
      rootNode.parentNode.replaceChild(emptyTextNode, rootNode);
    }
  }
  for(let child of rootNode.childNodes) {
    applyTextNodeFix(child);
  }
}
applyTextNodeFix(document.body);
```
Running the above results in no changes to the DOM being made on initial render, since the empty text nodes are already inserted and available to be diffed against.

If possible, I'd like to help out with a more permanent solution!

**Comment by developit** [comment]
Hiya - this is likely the same underlying issue as #809. I think we could work around it in SSR by emitting a Comment instead of a Text node.

**Comment by eweilow** [comment]
Yeah, when looking at that issue again it does look like the same thing!
I'm thinking that a comment would be less likely to break real applications of zero-width space, but perhaps either mode could be exposed via options? 

I've tested an implementation of the comment method and from what I can tell, it would entail adding an if clause before [these lines](https://github.com/developit/preact/blob/master/src/vdom/diff.js#L74-L89) in `diff.js`:
This is what I've added, which reduces the amount of dom operations to a single call to `replaceChild` in each box in my codepen example: 
```javascript
if(dom && dom.nodeType === 8 && dom.data === SSR_EMPTY_KEY) {
	let replaceWith = document.createTextNode('');
	dom.parentNode.replaceChild(replaceWith, dom);
	out = replaceWith;
}
```

In `preact-render-to-string` we'd change [these lines](https://github.com/developit/preact-render-to-string/blob/master/src/index.js#L61-L63) in `index.js` to:
```javascript
if (vnode==null || vnode===false) {
	return `<!--${SSR_EMPTY_KEY}-->`;
}
```

**Comment by JoviDeCroock** [comment]
This is fixed in Preact X
