### ISSUE TITLE
Async components and async rendering

### ISSUE THREAD

**Issue by 3axap4eHko** [preactjs/preact#862]
# Some definitions
Async component is usual component that render method returns promise of component instead of component. It will be useful for SSR to await some async operation like db query or http request.
# Implementation
Just insert at 
https://github.com/developit/preact/blob/master/src/h.js#L15
``` javascript
let children=EMPTY_CHILDREN, isPromised=false, lastSimple, child, simple, i;
```
https://github.com/developit/preact/blob/master/src/h.js#L48
``` javascript
isPromised = isPromised || child instanceof Promise;
```
https://github.com/developit/preact/blob/master/src/h.js#L58
``` javascript
if (isPromised) {
    return Promise
        .all(children)
	.then(children => {
	    p.children = children;
	    return p;
	});
}
```
It does not affect existing functionality and render pipeline. It just handle a case when a component render method returns promise.

Also you can find an example with changes here https://github.com/3axap4eHko/preact-async-example to be sure that it works properly

**Comment by 3axap4eHko** [comment]
To async render on server side just change lines
https://github.com/developit/preact-render-to-string/blob/master/src/index.js#L52
``` javascript
async function renderToString(vnode, context, opts, inner, isSvgMode) {
```
it should be async function
https://github.com/developit/preact-render-to-string/blob/master/src/index.js#L92
``` javascript
rendered = await c.render(c.props, c.state, c.context);
```
await component rendering
https://github.com/developit/preact-render-to-string/blob/master/src/index.js#L187
``` javascript
pieces = await Promise.all(pieces);
```

**Comment by developit** [comment]
What triggers a re-render for new children in this setup?

**Comment by SergeS** [comment]
Your case seems to solve your problem, when you are only doing server-side rendering using preact (So no re-renders are needed). On client side I cannot imagine many cases, where this concept is useful (Expect prototyping maybe)
- There are some placeholders, when data are loading
- It is good idea to separate functional part (Including data loading) from rendering part - that means no Promise may end in component at all
- What happen if there is concurrency issue occurs (For example: second Promise will finish before first Promise)

Even on server-side it is good idea to gather data first, and then render your template

**Comment by 3axap4eHko** [comment]
@developit there are no rerender.

@SergeS Let me help to improve your imagination =) Imagine you are developing an application with services. Does not matter with SSR or SPA. Once you change URL you trigger a route that renders a component. This component triggers a service and at the moment of rendering this component still didn't receive any data from service but it must render something. At this case, you have to handle the situation when you don't have a data for component manually like an if condition in the render method.

``` js
class ServiceComponent extends Component {
  componentWillMount() {
    service().then(data => this.setState({ data }));
  }
  render() {
    const {data} = this.state;
    if(!data) {
      return null;
    } 
    return <div>{data.username}<img src={data.avatar} /></div>;
  }
}
```
