### ISSUE TITLE
React tool box compatability

### ISSUE THREAD

**Issue by ralphsmith80** [preactjs/preact#864]
Checkout the issue there for more details. 
react-toolbox/react-toolbox#1676

Is the [`React.cloneElement`](https://github.com/react-toolbox/react-toolbox/blob/dev/components/menu/Menu.js#L199) logic suppose to work with `preact`?

Checkout the Menu case [here](https://preact-compat-example.surge.sh/).

**Comment by marvinhagemeister** [comment]
Tried a few things out, but I'm unable to reproduce the issue with `10.0.0-rc.1` anymore :tada:
