### ISSUE TITLE
preact-transition-group we still need it???  update v2

### ISSUE THREAD

**Issue by simonjoom** [preactjs/preact#878]
I use the version of react-transition-group in v2 , and compiled from source with preact

 "react-transition-group": path.resolve(__dirname, './temp/react-transition-group-master/src/'), 

 i did not found any issue to use it with preact, 
i watched your code preact-transition-group  who is from first stable v1 of react-transition-group,

i don't see the interest to keep it ... who is not updated 
I work with material-ui who use react-transition-group api v2 all works as expected with preact (touch ripple work)
So i deleted the preact-transition-group of my deps .. 

Simo

**Comment by developit** [comment]
Hi - I wasn't aware of the v2 release! I think it requires preact-compat, right?

**Comment by simonjoom** [comment]
hello, material-ui is working on the v2 release, 
yes i use preact-compat and it's fully working (no need to add a preact-transition-group)

**Comment by developit** [comment]
Nice.
