### ISSUE TITLE
handle user input on SSR content before preact is loaded

### ISSUE THREAD

**Issue by borisirota** [preactjs/preact#922]
Hi

Sometimes, when serving SSR content, the user can enter data before `preact` is loaded (slow connection, big `js` bundle, etc.). Then when `preact` bootstraps, it wipes out that state.

Related issues in the `react` repo: [4293](https://github.com/facebook/react/issues/4293) and [2585](https://github.com/facebook/react/issues/2585).

[react-safe-universal-inputs](https://github.com/chrisblossom/react-safe-universal-inputs) seems like a workaround for `react` but it doesn't work in `preact`.

In addition, I created a HOC as a wrapper for the relevant inputs, which sets id's and then on client side, tries to access the input and its value (with `document.getElementById`) on constructor, componentWillMount and componentDidMount lifecycle events, but without success.

The relevant inputs isn't available at the mentioned lifecycle events - seems like `preact` removes the SSR inputs before calling the events.

I used the technique mentioned [here](https://jsfiddle.net/developit/2vgozmvc/) (watch for DOM updates) and I don't understand why while hydrating these inputs (and other elements) are being replaced and not just updated (same content served from server is being rendered on client). I digged into the relevant issues in this repo and I'm rendering preact on client side after serving SSR content as recommended:
```js
render(<App />, window.document.body, window.document.body.lastElementChild)
```

Any suggestions how to address this use case ?

Thanks for a great lib !!

**Comment by marvinhagemeister** [comment]
Thanks for the warm words🥰 The time between when the HTML is served to the client and the js has booted up is frequent issue with any framework. Some talks refer to it as the "uncanny valley".

Wondering if we could look at reusing the `dom`'s value on hydration

**Comment by developit** [comment]
This is fixed now that Preact X has a dedicated `hydrate()` codepath. Dirtied DOM values (input value, checked, etc) are never modified during hydration, and can be inspected using a ref of lifecycle callback. They are only re-synced to the Virtual DOM on the second render (setState/forceUpdate).

Example of resynced input:

```js
function Input({ ref, ...props }) {
  const key = 'checked' in props ? 'checked' : 'value';
  return <input {...props} ref={c => {
    if (c && c[key] != props[key]) {
      setTimeout(() => {
        c.dispatchEvent(new Event('input'));
        c.dispatchEvent(new Event('change'));
      });
    }
  }} />;
}
```
