### ISSUE TITLE
Integration with Parcel and Unistore

### ISSUE THREAD

**Issue by hwclass** [preactjs/preact#959]
Hey folks,

I have started working on some [starter repo](https://github.com/hwclass/parcel-preact-unistore-starter) containing Preact and Unistore bundled with Parcel. Here is the repo. Do we need to add that into the 'Examples" part of the readme file? 

BTW, I am open completely for suggestions regarding the example repo..

Thanks..

**Comment by developit** [comment]
Sure! Send a PR and we'll add it.

**Comment by JoviDeCroock** [comment]
Since this is for another repo (docs/unistore) let's close this.
