### ISSUE TITLE
Firefox validation triggers on input component render

### ISSUE THREAD

**Issue by sandgraham** [preactjs/preact#972]
Hi, I noticed that on Firefox, any form inputs that are `required` are immediately validated. This results in the inputs having a red error outline on page load. I ran into this on `Preact v8.1.0` and `Firefox v58.0b10`.

It looks like React recently fixed this: https://github.com/facebook/react/issues/8395. The issue seems well documented in the thread. I might be able to poke around this weekend to offer assistance, but I just wanted to bring this up.

Thanks!

**Comment by developit** [comment]
Sorry for the late reply - this is interesting! I'd be happy to discuss if you want to jump on [Slack](https://preact-slack.now.sh).

**Comment by Rafi993** [comment]
Does this bug still exist. If so I would be willing to help.

**Comment by sandgraham** [comment]
I don't think this is still an issue. I tested the behavior out on the latest Firefox Developer Edition 71.0b12 (64-bit) and `input` does not validate until the form is submitted.

Here is a sandbox to verify: https://codesandbox.io/s/kind-firefly-6fbcx

**Comment by JoviDeCroock** [comment]
Great to hear that and thank you for digging up this issue @Rafi993 will close this now
