### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by reznord** [preactjs/preact#995]
Right now we are listing all the `Demos`, `Libraries & Add-ons` in the README itself.

It would be better to move them to wiki and create separate pages for each.

Any thoughts? @developit @lukeed

**Comment by lukeed** [comment]
I think there'd be higher visibility (and better searching) on the Preact site.

**Comment by developit** [comment]
Agreed, probably best to just consolidate them on the preact site and leave Preact's readme as a separate (shorter) thing.

**Comment by gedw99** [comment]
No. Leave it in the readme too.
This first thing I do when I hit a git repo of something new is hit the demos to see it .  !

**Comment by marvinhagemeister** [comment]
Fixed with #2232
